### ISSUE TITLE
Go formatter doesn't work after `go mod init` is called

### ISSUE THREAD

**Issue by pgemmich** [zed-industries/zed#10143]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Go formatter works fine before `go mod init` has been called. Steps to reproduce:
1. Create go file.
2. Specify language overrides in `settings.json` as follows
```
  "language_overrides": {
    "Go": {
      "format_on_save": {
        "external": {
          "command": "goimports",
          "arguments": []
        }
      }
    },
  },
```
3. Perform formatting on file, it works fine.
4. Run `go mod init`.
5. Formatter doesn't work

### Environment

Zed: v0.129.1 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```
2024-04-04T01:50:58+02:00 [ERROR] crates/terminal_view/src/terminal_view.rs:285: error upgrading view
2024-04-04T01:51:14+02:00 [WARN] timed out waiting for formatting
2024-04-04T01:53:11+02:00 [ERROR] Cancelled LSP request task for "textDocument/documentHighlight" id 230 which took over 120s
2024-04-04T01:53:11+02:00 [WARN] Generic lsp request to gopls failed: LSP request timeout
2024-04-04T01:53:11+02:00 [ERROR] crates/editor/src/editor.rs:3792: LSP request timeout
2024-04-04T01:53:11+02:00 [ERROR] Cancelled LSP request task for "textDocument/codeAction" id 231 which took over 120s
2024-04-04T01:53:11+02:00 [WARN] Generic lsp request to gopls failed: LSP request timeout
2024-04-04T01:53:11+02:00 [ERROR] crates/editor/src/editor.rs:3745: LSP request timeout
2024-04-04T01:53:20+02:00 [WARN] timed out waiting for formatting
```

**Comment by Moshyfawn** [comment]
#8460 may have the setup information for you.

**Comment by mrnugget** [comment]
I found the problem. 

By default we start up `gopls`, the Go language server, and by default in Go files we use the `organizeImports` code action that it offers to fix imports after formatting the code. Meaning that out of the box, when you open a Go project in Zed, and hit save in a file, Zed

1. Runs `organizeImports` via `gopls` to fix any imports
2. Formats the file with `gopls`

With your configuration, what happens is this:

1. Runs `organizeImports` via `gopls` to fix any imports
2. Formats the file with `goimports`

The problem is that after adding a `go.mod` file, `gopls` seems to go into a funky state: diagnostics stop working, autocomplete stops working, and when we call `organizeImports` it times out.

The "fix" is to either:

1. Restart `gopls` with `editor: restart language server`
2. Restart Zed completely (to restart `gopls`)
3. Disable `code_actions_on_format`: 
```json
  "languages": {
    "Go": {
      "code_actions_on_format": {},
      "format_on_save": {
        "external": {
          "command": "goimports",
          "arguments": []
        }
      }
    },
```


I'm going to close the ticket because I don't see what we can do here. The problem seems to be with `gopls` getting into this state. Other language servers, such as rust-analyzer, do handle changes to `Cargo.toml` better, for example. But to be fair to `gopls`, I do think changing/adding a fundamental file such as `go.mod` is a case where one could say "please restart".

**Comment by pgemmich** [comment]
@mrnugget Thanks a lot, it solved the problem!
