### ISSUE TITLE
Selecting an autocomplete item should not lose placeholder tabs

### ISSUE THREAD

**Issue by marwan-at-work** [zed-industries/zed#10185]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It's common to call a function and tab through its parameters because each param has its own tab-placeholder. 

However, if we end up choosing an autocomplete item from the list within param1, we lose the ability to tab into param2. 

See the below screen recording for demonstration.

### Environment

Zed: v0.129.2 (Zed)
OS: macOS 14.3.0
Memory: 96 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/16294261/9b31fd2e-d2b4-4e22-98cf-ef0ff0b87d9e

**Comment by mrnugget** [comment]
Here's more to reproduce:

1. Create the following `main.go` file:
```go
package main

import "fmt"

type Animal struct {
	Name string
}

func myFunctionWithArguments(a *Animal, numA, numB int) {
	fmt.Printf("animal: %+v, foo: %d", a.Name, numA+numB)
}

func main() {
	horse := &Animal{Name: "Horse"}

	//
}
```
2. Create a new line to call `myFunctionWithArguments`:
![screenshot-2024-05-13-10 06 02@2x](https://github.com/zed-industries/zed/assets/1185253/5e273444-f99a-42e7-a5ad-d83f4955a4a3)
3. Hit `tab` to accept suggestion
![screenshot-2024-05-13-10 06 21@2x](https://github.com/zed-industries/zed/assets/1185253/8b30461c-e3fa-49bb-bdfd-31562acb3f2a)
4. Type `hor` to get `horse` as suggestion:
![screenshot-2024-05-13-10 06 36@2x](https://github.com/zed-industries/zed/assets/1185253/0465ff79-f403-447c-9ad7-3e5006f11bdd)
5. Accept suggestion with `tab`
6. Try to hit `tab` to go to next parameter — does not work

in Vim mode, you now have to hit `Esc` and then go back in insert mode again and then hit tab.

**Comment by mrnugget** [comment]
It's definitely a Go thing. It works in Rust

https://github.com/zed-industries/zed/assets/1185253/0567f5d9-79fa-495a-b099-7012b195fac0

**Comment by mrnugget** [comment]
Okay, more information:

1. `gopls` sends even single-word-no-tab-stops completions as snippets. `insertTextFormat = 2`: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertTextFormat
2. We then parse the snippet, which is just a single word, and fall to the default case of adding the end-of-the-word as the tab stop: https://github.com/zed-industries/zed/blob/b625846d0e86dc2f47635c9c2a75a743a87940e4/crates/snippet/src/snippet.rs#L27-L30
3. In combination that results in Zed accepting snippet for function-call, pushing it on stack, then accepting "snippet" for first parameter and pushing it on stack, when then `tab` is hit, the snippet on top of the stack is not the function call, but the identifier, and since we're already at the end of it, nothing happens.
4. In Vim mode, when hitting `Esc` it basically triggers a "dismiss menus & completions" logic, which pops the current snippet off the stack. So when you then go back in insert mode, only the correct snippet is still left.
