### ISSUE TITLE
Window decoration not being draw in wayland

### ISSUE THREAD

**Issue by XDeme1** [zed-industries/zed#10346]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it
After #10227 Wayland windows were not being drawn at all.
After #10343 Wayland window are being draw but decorations are not being draw.

### Environment

Zed: v1.0.0 (Zed Dev bfd9bb8a7cbb59880179e481e0a9e92ad1c89617)
OS: Linux 1.0.0
Memory: 15.5 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot_20240409_225549](https://github.com/zed-industries/zed/assets/66138117/5b9e1997-29c9-43d9-8002-54e970eb7f84)

**Comment by XDeme1** [comment]
This might not be related to window decorations but, some clicks, and actions don't work.
Sometimes after trying to Alt+F4 the window multiple times, this logs starts appearing:
![Screenshot_20240410_105814](https://github.com/zed-industries/zed/assets/66138117/b629d781-338f-4fc2-bd37-3bb1e52df053)

**Comment by mikayla-maki** [comment]
> This might not be related to window decorations but, some clicks, actions, and keyboard shortcuts don't work.
Sometimes after trying to Alt+F4 the window multiple times, this logs starts appearing:

This should be fixed now.

**Comment by LightTreasure** [comment]
I got the Window decorations working in Wayland, but it seems like I'm reverting an intentional change. Zed's code is specifically asking the Wayland compositor(aka server) to not draw window decorations, instead specifying that Zed will handle window decorations itself(client). 

Here's the git diff:

`
--- a/crates/gpui/src/platform/linux/wayland/window.rs
+++ b/crates/gpui/src/platform/linux/wayland/window.rs
@@ -202,7 +202,7 @@ impl WaylandWindow {
                 decoration_manager.get_toplevel_decoration(&toplevel, &globals.qh, surface.id());

             // Request client side decorations if possible
-            decoration.set_mode(zxdg_toplevel_decoration_v1::Mode::ClientSide);
+            decoration.set_mode(zxdg_toplevel_decoration_v1::Mode::ServerSide);
         }
`

**Comment by bsneed** [comment]
I downloaded the latest from git and this still seems to be an issue.  I see line 249 still refers to `ClientSide`.

**Comment by monzeromer-lab** [comment]
I still get this issue somehow
