### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by akoufa** [zed-industries/zed#10467]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello and kudos for the great work. I would like to request if possible to add Kotlin support.

**Comment by JosephTLyons** [comment]
Hey @akoufa,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/extensions/issues/138

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
