### ISSUE TITLE
collapse option to the search 

### ISSUE THREAD

**Issue by JustFrederik** [zed-industries/zed#10612]
### Check for existing issues

- [X] Completed

### Describe the feature

- [x] add a replace to the search project similar to the vscode version.
- [ ] add a collapse option to the search

**Comment by bennetbo** [comment]
Hey, from my understanding the first bullet point is already implemented:
Pressing toggle replace:
![image](https://github.com/zed-industries/zed/assets/53836821/e66297d6-c607-47bd-a463-c6a063583dc3)

Shows this:
![image](https://github.com/zed-industries/zed/assets/53836821/544bba53-19c0-478f-a1a6-fc021ca7860b)

**Comment by JustFrederik** [comment]
sorry that im dumb ;D

**Comment by JosephTLyons** [comment]
Hey @JustFrederik, can you give a bit more detail on what you want with the collapse option? Is the want to be able to collapse each excerpt?

**Comment by JustFrederik** [comment]
@JosephTLyons each file

**Comment by JosephTLyons** [comment]
Ok awesome. There's actually an issue for this already here:

- https://github.com/zed-industries/zed/issues/10228

Since your first bullet point already exists in Zed and since there's already an issue for the second, I'm going to close this out to keep things tidy. Please upvote 👍 the other issue!
