### ISSUE TITLE
column indicator changes when entering vim's visual mode

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#10728]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When pressing `v` or `V` the column number in the status line is increased by 1.

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
I'm going to close this as WONTFIX.  This happens because in normal mode your cursor is (under the hood) "before" the highlighted character, but in visual mode, the end of your selection is "after" the highlighted character. Vim uses the character itself for the position, but zed uses the gaps between the characters.

Is there a reason you need the number to match?

**Comment by hferreiro** [comment]
No reason, I just noticed the column number was wrong, or, at least different from what vim reports.
