### ISSUE TITLE
vim-commentary doesn't work

### ISSUE THREAD

**Issue by silvenon** [zed-industries/zed#10775]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I was unable to figure out way, but `gcc` acts as if I typed in `cc`, same goes for `gc` in visual mode, `g` just gets ignored and it treats it as `c`. And regular commenting via Cmd+/ works in that file, so it's not like Zed doesn't know which comments to use for that file 🤔

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by baldwindavid** [comment]
I'm guessing this expectation was due to the mention of vim-commentary in the docs on the marketing site... https://zed.dev/docs/vim

I'm not quite sure where those docs are hosted and whether that is an old or new reference. At any rate, `g c` and `g c c` are not in the Stable Release. However, they did just happen to have been added in the vim default keybindings for the latest Preview Release so they'll get into Stable next Wednesday.

If you want them now simply add these keybinding to your keymap...

```json
{
  "context": "Editor && vim_mode == normal",
  "bindings": {
    "g c c": "editor::ToggleComments"
  }
},
{
  "context": "Editor && vim_mode == visual",
  "bindings": {
    "g c": "editor::ToggleComments"
  }
},
```

`Cmd+/` works because there is already a default mapping for that shortcut to `editor::ToggleComments`.

**Comment by silvenon** [comment]
> I'm guessing this expectation was due to the mention of vim-commentary in the docs on the marketing site... https://zed.dev/docs/vim

Exactly 😅

> However, they did just happen to have been added in the vim default keybindings for the latest Preview Release so they'll get into Stable next Wednesday.

Great, thank you! And thanks for the tip on how to add those bindings in the meantime. ❤️
