### ISSUE TITLE
wrong crate name of auto generated rust test task 

### ISSUE THREAD

**Issue by sunliang711** [zed-industries/zed#10915]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

rust's crate name's format is underscore style, eg: folder named my-crate will be renamed to my_crate, while the auto generated rust test task's name use my-crate instead of my_crate.

so, the generated task should be fixed from "cargo test -p my-crate test_some_function --nocapture" to "cargo test -p my_crate test_some_function --nocapture"

<img width="551" alt="image" src="https://github.com/zed-industries/zed/assets/16303258/183408cb-9c93-42f3-8f5e-0ef7c1a55e16">

### Environment

Zed: v0.132.2 (Zed Preview)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: x86_64

**Comment by SomeoneToIgnore** [comment]
Can you elaborate why would the hyphen crate name be wrong?

Here's a sample `cargo new` project with hyphens and the test
![image](https://github.com/zed-industries/zed/assets/2690773/6987ce10-8063-4d45-abd7-8e2a957c5336)
it works for hyphened crate name both with Zed tasks 
![image](https://github.com/zed-industries/zed/assets/2690773/512c35bd-569c-4047-a6a4-8a7fd36cb7f7)
and the direct `cargo` invocations in the terminal
![image](https://github.com/zed-industries/zed/assets/2690773/e975de92-4b00-47c9-a9ee-4e5557033a65)

There's been an issue with the way we retrieved those package names (incorrectly in case there's been an override in Cargo.toml): https://github.com/zed-industries/zed/issues/10925 but it's fixed in https://github.com/zed-industries/zed/pull/10929 and as you can see in the PR, we are barely getting the human-readable package name out of the `cargo pkgid` command, which also returns hyphens.

**Comment by SomeoneToIgnore** [comment]
Thinking of this more, `cargo pkgid` provides the hyphened names and `cargo ... -p` commands work with these, so I will close this, as https://github.com/zed-industries/zed/pull/10929 should have fixed all related issues.

Please comment, if there's something that is not working for you still after that fix.

**Comment by sunliang711** [comment]
Great, it's working now, thank you for your hard working !
