### ISSUE TITLE
File not found in search if not tracked by git and never opened before

### ISSUE THREAD

**Issue by aarroisi** [zed-industries/zed#10981]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I opened "search project files" menu (with cmd + P), I've never been able to search files that are:
- not tracked by git (usually .env files), and
- never opened before

If the files are tracked by git, it searches just fine. If the untracked files have been opened before, it also searches just fine.

### Environment

Zed: v0.132.2 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-04-25 at 17 54 49](https://github.com/zed-industries/zed/assets/34854015/7fd3991c-5c95-46d2-80db-bcf202e4bfc0)
Searching .env, never opened before, not checked into git. File starts with ".". --> Not found

![Screenshot 2024-04-25 at 17 55 00](https://github.com/zed-industries/zed/assets/34854015/4e2916bd-9480-4f8f-8b74-c23cd7832110)
Searching erl_crash.dump, never opened before, not checked into git. --> Not found

![Screenshot 2024-04-25 at 17 55 14](https://github.com/zed-industries/zed/assets/34854015/ef266e23-6441-402c-8b9d-f67330c75d14)
Searching .formatter.exs, never opened before, checked into git. File starts with ".". --> Found

![Screenshot 2024-04-25 at 17 58 05](https://github.com/zed-industries/zed/assets/34854015/acddcbc6-897e-47d2-8e2e-98e409c74074)
Searching .env, opened before, not checked into git. File starts with ".". --> Found

**Comment by JosephTLyons** [comment]
Hey @aarroisi, I think this is because Zed's file finder doesn't include anything that is in the `.gitignore` file. However, the file finder does include files that have been recently opened, as you have noticed. Some users are wanting the ability to include files that are excluded via the `.gitignore`

- https://github.com/zed-industries/zed/issues/4599
- https://github.com/zed-industries/zed/issues/4745

Do either of these issues cover what you are wanting here?

**Comment by aarroisi** [comment]
Yes, that's exactly what I meant, sorry for not searching thoroughly enough to notice there are duplicates.
