### ISSUE TITLE
JavaScript Debug Terminal

### ISSUE THREAD

**Issue by skhaz** [zed-industries/zed#11096]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed is amazing; sometimes, however, I need to open VSCode to debug a TypeScript project. In VSCode, there is a terminal called 'JavaScript Debug Terminal,' where if I set some breakpoints and run my project, the IDE will stop at those breakpoints. It would be incredible if Zed had this feature as well.

**Comment by SomeoneToIgnore** [comment]
We have https://github.com/zed-industries/zed/issues/5307 and https://github.com/zed-industries/zed/issues/5065 so I will close this as a duplicate, while it's a bit less generic and oriented on JS.

**Comment by szszoke** [comment]
@SomeoneToIgnore I would argue that this is not a duplicate issue and the currently available functionality doesn't address the use case well.

The way the debugger terminal works is that VS Code debugger automatically attaches to any running node processes.

This is especially useful when something is running in watch mode, and the node process is constantly restarted due to changed files.

Having a debugger automatically attach to the running node process is really convenient in this case because it's essentially watch mode fog the debugger.

They do this is by providing extra parameters to node via environment variables, including a preload script which is used to talk to VS Code.

**Comment by SomeoneToIgnore** [comment]
Great, but both yours and the OP lack the VSCode links and/or videos about the key points of this approach: as a mere Rust dev, I lack the knowledge of all this even on the "how to start it" level.

I presume you speak of https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach which leaves me wondering why no one posted that link before instead of all these words above.

Also, the place to argue seems wrong: it's an issue had been closed for 418 days, after all: I would create a feature request in https://github.com/zed-industries/zed/discussions

**Comment by szszoke** [comment]
You are correct. I was speaking of the auto attach feature that you linked.

Sorry for not posting any links.

I didn't want to create yet another issue for the same thing so I wrote here instead but I will start a discussion about this.

Edit:

I started a discussion.
https://github.com/zed-industries/zed/discussions/33148
