### ISSUE TITLE
Почему Zed, а не V? 

### ISSUE THREAD

**Issue by kuzbassPlayer** [zed-industries/zed#11291]
### Check for existing issues

- [X] Completed

### Describe the feature

Почему Zed, а не V? Не лучше ли было бы назваться ZOV🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺, чтобы никого не обижать? 

### If applicable, add mockups / screenshots to help present your vision of the feature

Не лучше ли было бы назваться ZOV🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺, чтобы никого не обижать?

**Comment by mrnugget** [comment]
Hey! Locking this, since it's against our code of conduct. See this as a warning.

Our code of conduct (which you can find here: https://zed.dev/docs/code-of-conduct) includes under `Examples of unacceptable behavior` the following:

```
* Trolling, insulting or derogatory comments, and personal or political attacks
```

And while I don't speak Russian, Google Translate tells me that this issue here is a combination of a few things that are called out as unacceptable.
