### ISSUE TITLE
Support for Codeium

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#11623]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to see support for https://codeium.com/ (a free coding copilot)

**Comment by JosephTLyons** [comment]
Hey @krstp,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4726

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Comment by krstp** [comment]
Thanks @JosephTLyons , I was sure I have seen this issue and tried to find it but for whatever reason Codeium search did not deliver. Upvoted. Thanks.

**Comment by insign** [comment]
Vote here https://codeium.canny.io/feature-requests/p/zed-integration
