### ISSUE TITLE
Support for WebP files

### ISSUE THREAD

**Issue by jsarnowski-un7** [zed-industries/zed#11863]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, there's no preview for `.webp` files in Zed.

### If applicable, add mockups / screenshots to help present your vision of the feature

[example.zip](https://github.com/zed-industries/zed/files/15323204/example.zip)

**Comment by bbb651** [comment]
It seems `img` element is broken for webp in general, it does correctly [opens an image preview editor](https://github.com/zed-industries/zed/blob/main/crates/image_viewer/src/image_viewer.rs#L42) but the image (taken from [here](https://www.gstatic.com/webp/gallery3/1_webp_ll.webp)) doesn't display inside it:
![image](https://github.com/zed-industries/zed/assets/53972231/16373a9e-2938-46e9-8d64-863412cb94da)
With this error:
```
[ERROR util] crates/gpui/src/elements/img.rs:345: Image(Unsupported(UnsupportedError { format: Exact(WebP), kind: GenericFeature("VP8L") }))
```
that comes from [`image`](https://github.com/image-rs/image/blob/1207aca6af0c808e00857fa2bf14fff3ccdee6ff/src/error.rs#L55-L61), it's odd because afaict the `webp` feature should be enabled by default, I'll look into it more later

**Comment by notpeter** [comment]
I believe this has been fixed.  I can open webp and ico in zed now.

<img width="464" alt="Screenshot 2024-08-27 at 17 02 22" src="https://github.com/user-attachments/assets/7ab35eaa-b538-403a-b6cb-b03b140a3bbc">

If you are still running into trouble, please comment and I'm happy to reopen.
