### ISSUE TITLE
error: failed to run custom build command for `openssl-sys v0.9.93`

### ISSUE THREAD

**Issue by sangelxyz** [zed-industries/zed#11953]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed Fails to compile with the latest release, a previous release 1-2 weeks ago built fine so it's a fairly recent change? I'm using Fedora40.

Installing the following modules fixes it for Fedora.
dnf install perl-File-Compare
dnf install perl-File-Copy

### Environment

Fedora 40

**Comment by yodatak** [comment]
I just made a pr to the script repo to fix it I find it

**Comment by yodatak** [comment]
https://github.com/zed-industries/zed/pull/11868

**Comment by mgroenb** [comment]
I'm running into the same issue on Ubuntu 22.04.4 LTS:
``` 
running cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"

  --- stderr
  thread 'main' panicked at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:

  Error building OpenSSL dependencies:
      Command: cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
      Failed to execute: No such file or directory (os error 2)
```

**Comment by sangelxyz** [comment]
> I'm running into the same issue on Ubuntu 22.04.4 LTS:
> 
> ```
> running cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
> 
>   --- stderr
>   thread 'main' panicked at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:
> 
>   Error building OpenSSL dependencies:
>       Command: cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
>       Failed to execute: No such file or directory (os error 2)
> ```

export RUST_BACKTRACE=1
and build again, it should show some more information on where it's failing.

**Comment by mgroenb** [comment]
> > I'm running into the same issue on Ubuntu 22.04.4 LTS:
> > ```
> > running cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
> > 
> >   --- stderr
> >   thread 'main' panicked at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:
> > 
> >   Error building OpenSSL dependencies:
> >       Command: cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
> >       Failed to execute: No such file or directory (os error 2)
> > ```
> 
> export RUST_BACKTRACE=1 and build again, it should show some more information on where it's failing.

Thanks for the suggestion @sangelxyz. Here's the trace:
``` 
Created include/openssl/configuration.h

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL.md file first)      ***
  ***                                                                ***
  **********************************************************************
  running cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"

  --- stderr
  thread 'main' panicked at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:

  Error building OpenSSL dependencies:
      Command: cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
      Failed to execute: No such file or directory (os error 2)



  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
     2: <openssl_src::Build>::run_command
     3: <openssl_src::Build>::build
     4: build_script_main::find_vendored::get_openssl
     5: build_script_main::find_openssl
     6: build_script_main::main
     7: <fn() as core::ops::function::FnOnce<()>>::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sangelxyz** [comment]
> > > I'm running into the same issue on Ubuntu 22.04.4 LTS:
> > > ```
> > > running cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
> > > 
> > >   --- stderr
> > >   thread 'main' panicked at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:
> > > 
> > >   Error building OpenSSL dependencies:
> > >       Command: cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
> > >       Failed to execute: No such file or directory (os error 2)
> > > ```
> > 
> > 
> > export RUST_BACKTRACE=1 and build again, it should show some more information on where it's failing.
> 
> Thanks for the suggestion @sangelxyz. Here's the trace:
> 
> ```
> The following warnings were emitted during compilation:
> 
> warning: openssl-sys@0.9.93: Compiler version doesn't include clang or GCC: "cc" "--version"
> 
> error: failed to run custom build command for `openssl-sys v0.9.93`
> note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
> 
> Caused by:
>   process didn't exit successfully: `/home/<user>/repos/zed/target/debug/build/openssl-sys-8dd39609500af006/build-script-main` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
>   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
>   cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
>   OPENSSL_NO_VENDOR unset
>   cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
>   CC_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
>   CC_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_CC
>   HOST_CC = None
>   cargo:rerun-if-env-changed=CC
>   CC = None
>   cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
>   cargo:warning=Compiler version doesn't include clang or GCC: "cc" "--version"
>   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
>   CRATE_CC_NO_DEFAULTS = None
>   DEBUG = Some("true")
>   CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
>   cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
>   CFLAGS_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
>   CFLAGS_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_CFLAGS
>   HOST_CFLAGS = None
>   cargo:rerun-if-env-changed=CFLAGS
>   CFLAGS = None
>   cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
>   AR_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
>   AR_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_AR
>   HOST_AR = None
>   cargo:rerun-if-env-changed=AR
>   AR = None
>   cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-linux-gnu
>   ARFLAGS_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_linux_gnu
>   ARFLAGS_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_ARFLAGS
>   HOST_ARFLAGS = None
>   cargo:rerun-if-env-changed=ARFLAGS
>   ARFLAGS = None
>   cargo:rerun-if-env-changed=RANLIB_x86_64-unknown-linux-gnu
>   RANLIB_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=RANLIB_x86_64_unknown_linux_gnu
>   RANLIB_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_RANLIB
>   HOST_RANLIB = None
>   cargo:rerun-if-env-changed=RANLIB
>   RANLIB = None
>   cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64-unknown-linux-gnu
>   RANLIBFLAGS_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64_unknown_linux_gnu
>   RANLIBFLAGS_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_RANLIBFLAGS
>   HOST_RANLIBFLAGS = None
>   cargo:rerun-if-env-changed=RANLIBFLAGS
>   RANLIBFLAGS = None
>   running cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="cc" RANLIB="ranlib" "perl" "./Configure" "--prefix=/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64"
>   Configuring OpenSSL version 3.2.1 for target linux-x86_64
>   Using os-specific seed configuration
>   Created configdata.pm
>   Running configdata.pm
>   Created Makefile.in
>   Created Makefile
>   Created include/openssl/configuration.h
> 
>   **********************************************************************
>   ***                                                                ***
>   ***   OpenSSL has been successfully configured                     ***
>   ***                                                                ***
>   ***   If you encounter a problem while building, please open an    ***
>   ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
>   ***   and include the output from the following command:           ***
>   ***                                                                ***
>   ***       perl configdata.pm --dump                                ***
>   ***                                                                ***
>   ***   (If you are new to OpenSSL, you might want to consult the    ***
>   ***   'Troubleshooting' section in the INSTALL.md file first)      ***
>   ***                                                                ***
>   **********************************************************************
>   running cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
> 
>   --- stderr
>   thread 'main' panicked at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:
> 
> 
> 
>   Error building OpenSSL dependencies:
>       Command: cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"
>       Failed to execute: No such file or directory (os error 2)
> 
>   stack backtrace:
>      0: rust_begin_unwind
>                at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
>      1: core::panicking::panic_fmt
>                at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
>      2: <openssl_src::Build>::run_command
>      3: <openssl_src::Build>::build
>      4: build_script_main::find_vendored::get_openssl
>      5: build_script_main::find_openssl
>      6: build_script_main::main
>      7: <fn() as core::ops::function::FnOnce<()>>::call_once
>   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> warning: build failed, waiting for other jobs to finish...
> ```

It seems to be failing on building
running cd "/home/<user>/repos/zed/target/debug/build/openssl-sys-41424193214078f9/out/openssl-build/build/src" && "make" "depend"

you could try
sudo apt-get install openssl openssl-dev

follow by cargo clean

I had a look in where OpenSSL dependency come from it appears the http crate added it with isahc which is similar to reqwest but uses CURL/OpenSSL which no Rustls feature.

**Comment by mgroenb** [comment]
> sudo apt-get install openssl openssl-dev libssl-dev

Thanks for digging into this. Unfortunately, that didn't work. I already have `openssl` and `libssl-dev` installed. The package manager cannot find `openssl-dev` and what I gather from [this](https://stackoverflow.com/a/65990851) is that `libssl-dev` is the Ubuntu version of `openssl-dev`. Running a `cargo clean` and then trying again produces the same result.

**Comment by sangelxyz** [comment]
> > sudo apt-get install openssl openssl-dev libssl-dev
> 
> Thanks for digging into this. Unfortunately, that didn't work. I already have `openssl` and `libssl-dev` installed. The package manager cannot find `openssl-dev` and what I gather from [this](https://stackoverflow.com/a/65990851) is that `libssl-dev` is the Ubuntu version of `openssl-dev`. Running a `cargo clean` and then trying again produces the same result.
> 
> Just for reference:
> 
> ```
> ~/repos/zed main ❯ sudo apt-get install openssl libssl-dev
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> libssl-dev is already the newest version (3.0.2-0ubuntu1.15).
> openssl is already the newest version (3.0.2-0ubuntu1.15).
> openssl set to manually installed.
> 0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
> 
> ~/repos/zed main ❯ sudo apt-get install openssl-dev
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package openssl-dev
> 
> ~/repos/zed main ❯ cargo clean
>      Removed 7032 files, 1.4GiB total
> ```
> 
> And then the same error occurs when I run `cargo run`.

Some more info that may help, this is from the open-ssl crate

# Debian and Ubuntu
$ sudo apt-get install pkg-config libssl-dev

there is more information on 
https://docs.rs/openssl/latest/openssl/

including how to point to an existing install using the env variable OPENSSL_DIR
export OPENSSL_DIR="/usr/local/ssl

**Comment by Etbelo** [comment]
I had the same Issue, try installing `sudo apt install make`. Then Zed compiled perfectly.

**Comment by yodatak** [comment]
> > I had the same Issue on Ubuntu 24.04, try installing `sudo apt install make`. Then Zed compiled perfectly for me.
> 
> This actually fixed my issue, had not realized make was missing! 🤦 Probably a good idea to add to the dependancies section.
> 
> https://github.com/zed-industries/zed/blob/main/script/linux#L25
> 
> ```
> make
> ```

I already done in PR https://github.com/zed-industries/zed/pull/11868
We just have to merge it :)

**Comment by yodatak** [comment]
And for ubuntu debian https://github.com/zed-industries/zed/pull/12257

**Comment by SymphonyNineth** [comment]
I'm having the same issue now on Fedora 40 and none of the steps above helped.
I have  perl-File-Copy and  perl-File-Compare installed as well as whole bunch of openssl packages

- apr-util-openssl.x86_64                              1.6.3-16.fc40                       @anaconda                       
- openssl.x86_64                                       1:3.2.1-2.fc40                      @fedora                         
- openssl-devel.x86_64                                 1:3.2.1-2.fc40                      @fedora                         
- openssl-libs.x86_64                                  1:3.2.1-2.fc40                      @anaconda                       
- rust-openssl+default-devel.noarch                    0.10.64-2.fc40                      @updates                        
- rust-openssl-devel.noarch                            0.10.64-2.fc40                      @updates                        
- rust-openssl-macros+default-devel.noarch             0.1.1-3.fc40                        @fedora                         
- rust-openssl-macros-devel.noarch                     0.1.1-3.fc40                        @fedora                         
- rust-openssl-sys+default-devel.noarch                0.9.102-1.fc40                      @updates                        
- rust-openssl-sys-devel.noarch                        0.9.102-1.fc40                      @updates                        
- rust-sev+openssl-devel.noarch                        1.2.1-2.fc40                        @fedora                         
- xmlsec1-openssl.x86_64                               1:1.2.37-7.fc40                     @anaconda  


What's interesting is that i have already built the IDE successfully once several days ago, but after pulling latest changes i'm seeing the same issue.

`error: failed to run custom build command for `openssl-sys v0.9.93`

Caused by:
  process didn't exit successfully: `/home/user/zed/target/release/build/openssl-sys-0acaa6385adf63f3/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
  AR_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
  AR_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-linux-gnu
  ARFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_linux_gnu
  ARFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rerun-if-env-changed=RANLIB_x86_64-unknown-linux-gnu
  RANLIB_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=RANLIB_x86_64_unknown_linux_gnu
  RANLIB_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_RANLIB
  HOST_RANLIB = None
  cargo:rerun-if-env-changed=RANLIB
  RANLIB = None
  cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64-unknown-linux-gnu
  RANLIBFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64_unknown_linux_gnu
  RANLIBFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_RANLIBFLAGS
  HOST_RANLIBFLAGS = None
  cargo:rerun-if-env-changed=RANLIBFLAGS
  RANLIBFLAGS = None
  running cd "/home/user/zed/target/release/build/openssl-sys-df465ffaf83aee3e/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="cc" RANLIB="ranlib" "perl" "./Configure" "--prefix=/home/user/zed/target/release/build/openssl-sys-df465ffaf83aee3e/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64"

  --- stderr
  Can't locate lib.pm in @INC (you may need to install the lib module) (@INC entries checked: /usr/local/lib64/perl5/5.38 /usr/local/share/perl5/5.38 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./Configure line 16.
  BEGIN failed--compilation aborted at ./Configure line 16.
  thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:



  Error configuring OpenSSL build:
      Command: cd "/home/user/zed/target/release/build/openssl-sys-df465ffaf83aee3e/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="cc" RANLIB="ranlib" "perl" "./Configure" "--prefix=/home/user/zed/target/release/build/openssl-sys-df465ffaf83aee3e/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64"
      Exit status: exit status: 2


      
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
`

Is anyone else still facing the issue or i'm alone here?)

**Comment by SymphonyNineth** [comment]
> **[SymphonyNineth](/SymphonyNineth) ** commented
I fixed it by running `cargo update`

**Comment by mgroenb** [comment]
> I had the same Issue on Ubuntu 24.04, try installing `sudo apt install make`. Then Zed compiled perfectly for me.

I hadn't realized `make` wasn't installed. This fixed it for me. Thanks!

**Comment by OvercastWarmth** [comment]
> I'm having the same issue now on Fedora 40 and none of the steps above helped. I have perl-File-Copy and perl-File-Compare installed as well as whole bunch of openssl packages
>
> ...
>
> Is anyone else still facing the issue or i'm alone here?)

We are having this issue as well, `cargo update` did not fix it for us. Neither did installing any of the packages mentioned above, as they all were already installed.

**Comment by SymphonyNineth** [comment]
> > I'm having the same issue now on Fedora 40 and none of the steps above helped. I have perl-File-Copy and perl-File-Compare installed as well as whole bunch of openssl packages
> > ...
> > Is anyone else still facing the issue or i'm alone here?)
> 
> We are having this issue as well, `cargo update` did not fix it for us. Neither did installing any of the packages mentioned above, as they all were already installed.

Have you tried reinstalling the dependencies for linux? They have added some more in the past few days

**Comment by brunoro** [comment]
I just encountered the same error here (Fedora Atomic 40). I solved it by installing a couple of additional dependencies: `perl-Module-Build` and `perl-local-lib`.

**Comment by ConradIrwin** [comment]
@brunoro could you add those to `./script/linux` on those platforms too please

**Comment by notpeter** [comment]
I think I've improved `script/linux` to cover all these cases.
If you run into additional regressions or platform issues, please open a clean issue and I'm happy to troubleshoot.

Thanks for reporting!
