### ISSUE TITLE
"This buffer contains unsaved edits" dialogue in Search project files.

### ISSUE THREAD

**Issue by kakserpom** [zed-industries/zed#12029]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1) Use 'Search project files' to find some string that occurs in an open file.
2) Edit that open file in its own tab.
3) Try to close the search tab and see "This buffer contains unsaved edits" 

It's a bit annoying.

### Environment

Zed: v0.135.2 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hmm, I'm actually not able to reproduce this one, @kakserpom.  If I:

- Search for a string in project search
- Open the source file and edit it (and dont save it)
- I'm still able to close the project search that had the search result

Zed is supposed to allow you to close files with unsaved changes, so long as that file is open somewhere else (a different pane, etc).

Maybe I misunderstood though - would you be able to upload a small screen capture showing what you are running into?

**Comment by kakserpom** [comment]
![zed](https://github.com/zed-industries/zed/assets/175350/19e580ee-b5bc-4408-a0b7-2b7606c23023)

**Comment by kakserpom** [comment]
@JosephTLyons

**Comment by afterwind-io** [comment]
@JosephTLyons 
Same here. I just figured out why it is hard to reproduce. First open a search tab(by context menu `Find in folder`, or issue command `workspace: search` etc.), then search anything. The tricky thing here is the results **must across multiple files**.   Then, modify any content which also appears in the search result, and you will notice the modified indicator shows up in the title of the search tab. Now close the search tab, and here it goes.

The problem is, the search tab should be a special tab which should never trigger an unsaved state, maybe it is limited by the design or something else?

**Comment by SomeoneToIgnore** [comment]
> the search tab should be a special tab which should never trigger an unsaved state

This is wrong, as search/diagnostics/etc. tabs are multibuffers that allow edits — so the user may have searched for something, then edited at least one of the excerpts inside the search results that are not open anywhere else but the search results multibuffer.

The real invariant should be: any item being closed, should only prompt for saving items that have no file yet or the items that are not present in the other tabs opened in the current window.

The former requirement comes from the Zed's modal limitations: unsaved item without a file opens a system prompt for finding a place to save the file, and that conflicts (and does not appear properly) with "Do you want to save N files" prompt that may also appear.

The latter requirement was actually fixed by me (fixing this issue too, presumably) in the branch: https://github.com/zed-industries/zed/compare/main...kb/rework-save-prompts
The problem with it, that I could not make any tests to work for some reason. Anybody is welcome to pick it up if interested, or I might return back to it some weeks later when the time permits.

**Comment by neunato** [comment]
Reproduction steps:
1. create two files with contents "AAA"
2. search project for "AAA"
3. open one of the files and edit it, without closing
4. close the project search tab

https://github.com/user-attachments/assets/cf276b4e-dea9-4dbd-a3bb-ee14c7161f16

This only happens when results from two or more files are shown (unsaved files seem to work fine)

**Comment by giiyms** [comment]
I think I am getting this error.
After doing a project search, but without editing anything. When I want to close the window, I receive the warning popup. Any way to turn this off?

![Image](https://github.com/user-attachments/assets/30a48b74-ab75-49b3-af61-d01c6b469ff6)
