### ISSUE TITLE
support for Typst language

### ISSUE THREAD

**Issue by gabrielalexandrelopes** [zed-industries/zed#12088]
### Check for existing issues

- [X] Completed

### Describe the feature

Support for the Typst language (to replace LaTeX): https://github.com/typst/typst, with instant preview, like in the VSCode plugin: https://marketplace.visualstudio.com/items?itemName=mgt19937.typst-preview

The Typst compiler is written in rust, so it could be a nice integration.

**Comment by bbb651** [comment]
There's already an [extension](https://github.com/WeetHet/typst.zed) which should already be available in Zed (which uses [tinymist](https://github.com/Myriad-Dreamin/tinymist), which seems more active and with more features than [typst-lsp](https://github.com/nvarner/typst-lsp)). I previously tried to make one based on typst-lsp before extensions had lsp support: #9152 but it's a lot worse than WeetHet's one. Pdf preview is quite hard to do, I had a discussion on possible ways to implement it [here](https://discord.com/channels/869392257814519848/873293828805771284/1216507733755559957) (the vscode extension uses [pdf.js](https://github.com/mozilla/pdf.js) but Zed currently doesn't have for support webviews), to summarize it:

- macOS: https://developer.apple.com/documentation/pdfkit
- windows: https://learn.microsoft.com/en-us/windows/win32/api/windows.data.pdf.interop/
- linux: it's complicated, [libpoppler](https://poppler.freedesktop.org/) seems to be the best option, we can either:

  - Invoke one of the `pdfto*` binaries it ships with
  - Use `libloading` to dynamically load it and use an unsafe api
  - Use `poppler-rs` and have poppler as a hard dependency


But I just found out that typst has png and svg support which would be a lot easier to implement (doesn't replace the need for pdf support, but is a good workaround). The issue is that extensions currently can't really run code other than tree-sitter grammars/lsp, and this would need a custom view, so it's blocked on more extension support: #5269

**Comment by gabrielalexandrelopes** [comment]
Thank you for your answer! Indeed using a web view would make this extension very easy to implement using e.g. https://github.com/Myriad-Dreamin/typst.ts.

The PNG idea is good, I tried `typst watch test.typ test.png` which compiles on save, but unfortunately the PNG does not update in zed (https://github.com/zed-industries/zed/issues/11529)

**Comment by bbb651** [comment]
If/when webviews are implemented I don't even think typst.ts is necessary, we can just run the normal typst binary in watch mode and have pdf implemented with webviews separately. I'll try to work on implementing refreshing in image views, I completely overthought it with the custom view thing, I forgot you can just... view pngs 😅

**Comment by WeetHet** [comment]
Hi! I'm the author of the typst extension. Honestly, I'm not using it right now, as there isn't a way to monitor typing events from the extension and zed doesn't have autosave on delay. I thing that, until one of those features (hopefully, input monitoring) lands in zed for extensions, you are better of using neovim with tinymist and the [typst-preview](https://github.com/chomosuke/typst-preview.nvim) plugin

**Comment by jvoisin** [comment]
For PDF preview on Linux, spawning the PDF reader is usually enough, as most of them are automatically refreshing their output if the opened file is changed. Please don't bundle a PDF reader in Zed :)

**Comment by notpeter** [comment]
I've opened an issue for tracking the implementation of an Extension API which makes it possible to implement webviews as this would be the likely method to support an extension which provides typist-preview like functionality:

- https://github.com/zed-industries/zed/issues/21208

Thanks for reporting, please 👍 upvote and subscribe to track progress.
