### ISSUE TITLE
Running tests by UI button does not read environment variables

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#12125]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running tests by UI button does not read environment variables

### Environment

Zed: v0.136.2 (Zed Preview)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: x86_64

## By `cargo test`
<img width="1072" alt="Screenshot 2024-05-22 at 21 18 51" src="https://github.com/zed-industries/zed/assets/5475262/a6aea57b-bf95-4092-9127-a93082d665e5">

## By the UI button

<img width="1072" alt="Screenshot 2024-05-22 at 21 19 00" src="https://github.com/zed-industries/zed/assets/5475262/1ff09049-3363-4b06-8d92-4b79ca343940">

**Comment by osiewicz** [comment]
Where exactly did you set this environmental variable? When spawning tasks, we do go through your shell of choice, so in theory we should pick up any variables defined in .zshrc et al

**Comment by failable** [comment]
Hello, I set it in `.env` and have `.envrc` used by `direnv` to set the variable.

**Comment by jvanbaarsen** [comment]
I'm running into these same problems:

```
Zed: v0.142.5 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64
```

**Comment by jvanbaarsen** [comment]
The solution for me was to set the terminal in zed to the correct shell type:

```
  "terminal": {
    "shell": {
      "program": "zsh"
    }
  },
```

I had `direnv` initialised in ZSH, and not in Bash, and somehow zed decided to run tasks in bash.

**Comment by florinpatrascu** [comment]
Hi there - does the solution mentioned [above](https://github.com/zed-industries/zed/issues/12125#issuecomment-2210717951) work with tests for other frameworks i.e. Elixir? I have set up direnv using the `zsh-direnv` plugin, and have that exact Zed configuration for the "terminal". However, when running tasks for mix, I encounter errors about missing the environment variables that are otherwise configured in`.envrc`. The command executed by these tasks appears as follows: `⏵ Command: 'zsh -i -c ``mix test test/<and my test>:<line#>'` - Thank you

**Comment by mrnugget** [comment]
@florinpatrascu can you modify the command so that instead of running `mix test` it also `cd /path/to/project && mix test`? Because direnv only sets up the env variables when `cd`ing into a directory.

There's a separate issue for that: https://github.com/zed-industries/zed/issues/4977#issuecomment-2160041972

**Comment by florinpatrascu** [comment]
Thank you to both of you for the feedback and suggestions.

@jvanbaarsen:
> Does DirEnv work in your "normal" terminal?

Of course, I wouldn't be reaching out to the team here if it wasn't necessary :)

@mrnugget:

> [...] can you modify the command so that instead of running mix test it also cd /path/to/project && mix test?

I should have mentioned this earlier. I did try using: `"command": "cd $ZED_WORKTREE_ROOT && mix", ..`. This command is valid and when _expanded_, works perfectly fine in a regular terminal session. However, when I ran it from a task, I encountered the same unexpected results, which is why I was seeking assistance here.

**Comment by florinpatrascu** [comment]
ha, your PR should do it, @mrnugget. I am amoeba-level at Rust but I can understand what you're doing there :) and I can follow what you're working on :) I think it might work because of a previous test I just did. When I noticed that `cd` wasn't triggering the change dir hook in direnv, and adding an extra `cd -` wasn't working either, I tried using `direnv export zsh && mix` instead, and it _worked_! By also adding a `printenv` in the command, I could see the expected ENV vars. However, these vars weren't being passed down, to mix. The vars I see in the test are probably just the ones from the initial zed's process?! This is just my basic understanding. And more specifically, the transitions between folders before running 'mix' aren't working with the current zed version, at least for my case. HTH ¯\\_(ツ)_/¯
