### ISSUE TITLE
File svg view with image render

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12128]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to be able to have a preview of the svg file created as happens with md files.

<img width="1080" alt="Screenshot 2024-05-22 alle 15 43 00" src="https://github.com/zed-industries/zed/assets/20476002/a05cf19c-84f0-44ac-a366-822623141518">

**Comment by JosephTLyons** [comment]
Hey @Angelk90 - we enabled SVG previews at one point, but we didn't have a good plan for users who still wanted to edit the code of the SVG, so we reverted it. This issue proposes a solution so that SVGs could be both edited and previewed:

- https://github.com/zed-industries/zed/issues/10454

I think this is the same thing you are requesting (let me know if I'm wrong), so I'm going to close this in favor of the other one.

**Comment by RVFET** [comment]
> [@JosephTLyons](https://github.com/JosephTLyons) : Another problem that the svg syntax is not recognized as xml.

Apparently, this is still not resolved. I ended up using the following file association trick from [this guide](https://zed.dev/docs/configuring-zed#file-types) to get it to work.
```json
"file_types": {
  "html": ["*.html"],
  "javascriptreact": ["*.js"],
  "css": ["*.css"],
  "XML": ["*.svg"]
},
```

EDIT: Seems like language names are case-sensitive too, as in, `xml` is different than `XML`.
