### ISSUE TITLE
Syntax recognition yaml separation line

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12185]
### Check for existing issues

- [X] Completed

### Describe the feature

As you can see from the two images on vscode, the separation line `---` is highlighted differently, but not on zed.

Vscode:
<img width="770" alt="Screenshot 2024-05-23 alle 09 24 39" src="https://github.com/zed-industries/zed/assets/20476002/da4a5913-20eb-469a-9cb9-8886013a1dc5">
Zed:
<img width="765" alt="Screenshot 2024-05-23 alle 09 24 57" src="https://github.com/zed-industries/zed/assets/20476002/222e447d-c7e1-4ff6-9ae9-564d50a2e0c6">

**Comment by weirdo-adam** [comment]
I had a similar problem
，error：Source contains multiple documents; please use YAML.parseAllDocuments() at line 68, column 1:

**Comment by notpeter** [comment]
> I had a similar problem ，error：Source contains multiple documents; please use YAML.parseAllDocuments() at line 68, column 1:

@weirdo-adam This error is because `yaml-language-server` does not properly support multiple documents. See:
- https://github.com/redhat-developer/vscode-yaml/issues/995

@Angelk90 The `---` is correctly captured as `punctuation.special`
https://github.com/zed-industries/zed/blob/34ac8c2c732215c9fb93c56a0c2f1e7879d5f543/crates/languages/src/yaml/highlights.scm#L49

Theme designers are free to style that as they see fit.  If you would like a default theme where the difference is more pronounced check out "Atelier Lakeside Dark":
<img width="272" alt="Screenshot 2024-12-16 at 2 50 52" src="https://github.com/user-attachments/assets/7d110809-e88e-47be-8122-93a7fb8840d4" />

Even in One Dark there is a difference, it is just subtle.
<img width="650" alt="Screenshot 2024-12-16 at 2 51 50" src="https://github.com/user-attachments/assets/10f0a295-310a-499a-9108-d5b2cd20d35b" />

Thanks for reporting!
