### ISSUE TITLE
I'm facing this error during compile for linux:  type annotations needed for `Box<_>`

### ISSUE THREAD

**Issue by shahverd** [zed-industries/zed#12264]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
    Compiling time v0.3.28
error[E0282]: type annotations needed for `Box<_>`
  --> /home/mostafa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.28/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
```

### Environment

I don't know the alternative for `copy system specs into clipboard` on linux.

**Comment by SomeoneToIgnore** [comment]
What's your rustc version, does it match https://github.com/zed-industries/zed/blob/d5fe2c85d80288a0f50eb1c2dfb1e82f11046402/rust-toolchain.toml#L2 ?

**Comment by SomeoneToIgnore** [comment]
Also note, that you cannot compile a dependency crate, not Zed per se, so not really related to Zed.

**Comment by shahverd** [comment]
my rustc version is as above.

**Comment by SomeoneToIgnore** [comment]
Our Linux CI shows that building is possible on a daily basis, people seem to have no compliation issues related to Rust, and also my local tests on a clean VM show the same:
<img width="779" alt="Screenshot 2024-05-26 at 00 27 44" src="https://github.com/zed-industries/zed/assets/2690773/219c227c-a264-4446-8ba9-469c4e56bbca">

So, closing this optimistically as something broken with the local set-up.

I see 2 possibilities: 

* `zed` project directory has some rustc overrides or otherwise the toolchain version is not the same.
I would try running `cargo --version` to ensure things are working.

* The crate source code could've been edited or anyhow else damaged.
I would remove `/home/mostafa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.28/` and try to recompile.

Maybe, there's something else is off, but I cannot deduce that from such sparse details.

**Comment by fala13** [comment]
Had the exact same compilation issue on different project - deleting Cargo.lock solved it.

**Comment by jonmayer** [comment]
I am seeing the exact same failure with time-0.3.28 -- I'm running on stable (rustc/cargo version 1.80.0, but on ARM architecture (stable-aarch64-unknown-linux-gnu).

**Comment by jonmayer** [comment]
Ah, I see the error is being tracked in the time-rs project: https://github.com/time-rs/time/issues/696

Looks like they have a fix (as of 18 hours ago).

**Comment by BassManFH** [comment]
Same here, `cargo update` resolved the issue, although time-rs wasn't updated.

**Comment by kevin-valerio** [comment]
For other folks coming here in the future, I had this issue by doing `cargo install mydependency --locked`, removing the `--locked` made it worked :)
