### ISSUE TITLE
Certain comments are not permitted in Zed's settings.json

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12316]
### Check for existing issues

- [X] Completed

### Describe the feature

Vscode:
<img width="584" alt="Screenshot 2024-05-26 alle 14 38 47" src="https://github.com/zed-industries/zed/assets/20476002/cca5f707-2320-4349-9542-8626a88ddb29">

Zed:
<img width="357" alt="Screenshot 2024-05-26 alle 14 38 28" src="https://github.com/zed-industries/zed/assets/20476002/ba573a65-656b-481f-bad8-e177116f6327">

**Comment by maxdeviant** [comment]
What exactly is the issue here?

**Comment by osiewicz** [comment]
I'd say this works as intended; when working with JSON files, Zed marks them as `jsonc` files ([see this](https://github.com/zed-industries/zed/blob/main/crates/languages/src/json.rs#L168)), which causes JSON language server to permit comments in them. My bet is on VSC marking them as `json` instead. 
See [this section of JSON language server documentation](https://www.npmjs.com/package/vscode-json-languageserver#server-capabilities) on differences between json and jsonc.

**Comment by osiewicz** [comment]
JSONC is used quite a bit outside of VSC itself in one way or the other (hell, there's even [JSON5](https://json5.org/) which explicitly supports comments). We do support comments in Zed `settings.json` too, because we find it to be a good tradeoff.
I hear you - we should be smarter about when and how to allow comments in JSON files. My point is just that as it stands, Zed does exactly what it's asked to do and it is just a matter of configuration, which we admittedly do not expose sufficiently to the end user.

**Comment by SomeoneToIgnore** [comment]
To add on top, commenting out the entire line works due to leniency of our settings.json parser:

<img width="654" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/f02b65c1-61f9-4907-bbc2-9e258c0ab113">

So whatever comment is needed, it can be placed above or below the line, not to the right of it.

**Comment by AndydeCleyre** [comment]
I just want to note that I thought zed's json files were json, and tried to manipulate them with json-manipulating tools, but that failed since it's some other spec (but I don't know which one). For now I just removed the comments that were automatically added, so my own files are actual json.

**Comment by osiewicz** [comment]
This is fixed per https://github.com/zed-industries/zed/pull/12655/
