### ISSUE TITLE
Join/merge panes

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#12409]
### Discussed in https://github.com/zed-industries/zed/discussions/12115

<div type='discussions-op-text'>

<sup>Originally posted by **tcard** May 22, 2024</sup>
In VSCode, "View: Join Editor Group With Next Group" does the equivalent of (in Zed terms) moving all open files from a pane to the next pane and then closing the pane.

This allows you to keep working with fewer panes, while keeping all of the current open files and without having to worry about their state of save.

This is a feature I miss while using Zed.</div>

**Comment by idmyn** [comment]
I think this is especially valuable now that you can hide the tab bar - because you're not aware of how many tabs you might be closing when you run "close inactive items" - I'd love to work with panes without worrying about getting the popup asking if I want to discard unsaved changes

looks like this is also related to https://github.com/zed-industries/zed/issues/5182
