### ISSUE TITLE
Improve discoverability around closing git diffs

### ISSUE THREAD

**Issue by Morgandri1** [zed-industries/zed#12404]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello! 
When you open a git diff on a line, there isn't a [easy] way to close the diff. An 'x' button, or something similar to the close diagnostic button would be much appreciated 

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="524" alt="Screenshot 3" src="https://github.com/zed-industries/zed/assets/68765538/44dd74d7-28f8-49d7-b796-2691410f1308">

**Comment by Morgandri1** [comment]
in hindsight I guess the button should be in the current version, but 🤷

**Comment by jtlandis** [comment]
I also agree that there should be a button. After a bit of searching, I found that pressing `CMD+'` while your cursor is on the added line (in your case line 70) should close the git diff.

**Comment by Morgandri1** [comment]
Although convoluted, thank you Jason! I think this is probably a pretty good first issue?

**Comment by Moshyfawn** [comment]
There's also the `Esc` key and the `editor: toggle hunk diff` action in the command panel. I'm not sure how the team feels about a button, though.

**Comment by Morgandri1** [comment]
didn't know about the esc keybind. good to know.

imo if there's a dismiss button for the error diagnostic, there should be one here, but thats just me.

**Comment by someone13574** [comment]
Maybe you could keep showing the git gutter and have clicking that toggle it off, just like you can toggle it on by clicking the git gutter?

**Comment by Morgandri1** [comment]
Not a bad idea; Would the gutter expand or only show on the current?

**Comment by someone13574** [comment]
I’d say only show for the current code, with the same colour as when it is unexpanded.

**Comment by Morgandri1** [comment]
agreed

**Comment by Morgandri1** [comment]
So I was able to get the git gutter to stay when opened, but can't figure out how to close it. 

Would appreciate some help 
https://github.com/Morgandri1/zed

**Comment by SomeoneToIgnore** [comment]
To show the X mark in the gutter, here's a set of pointers:

* Zed is already able to combine LSP actions (lightning icon in the gutter) and tasks (triangle icon in the gutter) under the same entry, and can replace one icon with another, if tasks are mixed.
Here's how tasks' icon is added:
https://github.com/zed-industries/zed/blob/cfbf5dca7a8abe6286ca94a3a03a079f77e2869a/crates/editor/src/element.rs#L1561
we could add another X icon similar way for every added and modified hunk.

In the editor element, when we paint the gutter during `fn paint_gutter`, we have all its `layout.display_hunks` — whatever one has the hitbox is clickable ergo folded (as the code works now), otherwise it's expanded.
https://github.com/zed-industries/zed/blob/cfbf5dca7a8abe6286ca94a3a03a079f77e2869a/crates/editor/src/element.rs#L2837

We can add another icon below for every expanded hunk, similar to `test_indicators` and `indicator`:
https://github.com/zed-industries/zed/blob/cfbf5dca7a8abe6286ca94a3a03a079f77e2869a/crates/editor/src/element.rs#L2860-L2874

* Deleted hunks are harder, as those open a separate, nested editor and push down the real gutter — X mark has to be placed inside that editor's gutter instead.
For deleted hunks' editors, we now draw a fake space padded with the gutter size instead of the real gutter:
https://github.com/zed-industries/zed/blob/cfbf5dca7a8abe6286ca94a3a03a079f77e2869a/crates/editor/src/hunk_diff.rs#L323
we can add an X icon straight there and toggle the hunk folding for parent editor from there.
