### ISSUE TITLE
Windows: When "Save As" dialog is open, application will become unresponsive.

### ISSUE THREAD

**Issue by Tallone** [zed-industries/zed#12410]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I attempt to save an "untitled" file, the entire program becomes unresponsive once the dialog box opens

### Environment

Zed: v0.138.0 (Zed Dev c03600c55ecde723f721ce6cf2456dd8f674379f)
OS: Windows 10.0.22631
Memory: 31.9 GiB
Architecture: x86_64

**Comment by happytraveller-alone** [comment]
encounter same problem, attempt to save an "untitled" file, the entire program becomes unresponsive once the dialog box opens

Zed: v0.142.5 (https://github.com/zed-industries/zed/releases/tag/v0.142.5)
OS: Windows 11 22631.3737
Memory: 63.7 GiB
Architecture: x86_64

**Comment by bitfield** [comment]
I ran into a similar problem on macOS (ironically while using Zed to edit the crash diagnostics while reporting an unrelated Zed issue).

I opened a new buffer, pasted in the text, and hit Cmd-S. This opened the macOS 'save as' dialog, with the filename set to 'Untitled'. I changed this to something like `crash.dump.txt`, and hit Enter, but this had no effect: the dialog stayed open. I switched back to the buffer and hit Cmd-S again. I got another 'save as' dialog, equally unresponsive.

No matter what I did after that, although I could use Zed normally otherwise, I couldn't get rid of those 'save as' dialogs. Hitting Escape, Enter, or clicking the buttons had no effect. If I closed all Zed's other windows, I was still left with those two dialogs. I had to quit Zed and restart to get rid of them.

I haven't had any luck reproducing this so far.

**Comment by xgfone** [comment]
any progress??

**Comment by JunkuiZhang** [comment]
I'm not quit sure what you mean by "unresponsive" in this issue. It's normal for Zed to become unresponsive to input after opening the save file dialog, as the application itself won't accept input until the dialog is closed—similar to how VSCode behaves when a save dialog is open. Are you saying that the dialog itself is unresponsive, or that Zed remains unresponsive even after the dialog is closed?

**Comment by JunkuiZhang** [comment]
> My log
> 
> ```
> 2024-06-27T16:47:47+08:00 [ERROR] unable to create IShellItem: 参数错误。 (0x80070057)
> ```

@Huliiiiii 你的问题看起来不同，请问你能提供复现方式吗？

**Comment by JunkuiZhang** [comment]
> _I'm_ saying that the dialog(s) are unresponsive, while Zed still works (except that trying to 'save as' any buffer just creates yet another unresponsive dialog) but I think the Windows users are saying that Zed is unresponsive too.

Hm, my question was actually directed at the original author of this issue. Your description of the issue on macOS is quite clear—sorry for the confusion!

**Comment by Huliiiiii** [comment]
> > My log
> > ```
> > 2024-06-27T16:47:47+08:00 [ERROR] unable to create IShellItem: 参数错误。 (0x80070057)
> > ```
> 
> @Huliiiiii 你的问题看起来不同，请问你能提供复现方式吗？

再试了一次，没有出现这条报错，可能是另一个问题导致的。

**Comment by Huliiiiii** [comment]
This may be caused by IME.

1. Open Zed without workspace
2. Change to English Keybroad
3. `Save As` work fine.
3. Change to Chinese IME
4. `Save As` window and Zed freeze

**Comment by Tallone** [comment]
On Zed 0.152.3 in mac, the problem is "fixed", using Pinyin or ABC keyboard both works fine.

**Comment by Huliiiiii** [comment]
@Tallone 
Can you reopen it? This still happens on the latest version of zed on Windows.

**Comment by JunkuiZhang** [comment]
> @Tallone Can you reopen it? This still happens on the latest version of zed on Windows.

There is a #17069 for windows already.

**Comment by JunkuiZhang** [comment]
For Windows users, a temporary workaround is to enable compatibility mode for the input method. On Windows 11, you can do this by going to: Settings -> Time & Language -> Input -> Language & Region -> Click the language options for "Chinese" -> Scroll down to find Pinyin input method -> Click on the keyboard options -> General -> Scroll down and turn on compatibility.

![Screenshot 2024-09-12 131621](https://github.com/user-attachments/assets/07cb2924-3225-4042-a23b-5a166e11b690)

For more info see #17069
