### ISSUE TITLE
Keyboard shortcut to comment out not working in xml

### ISSUE THREAD

**Issue by noahfarr** [zed-industries/zed#12447]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open an XML file and press cmd + / to comment out selected lines, nothing happens.  For other file types, this is working fine for me. I've installed the XML extension to check if it helps but nothing happens. I have the VSCode keybindings enabled. 

### Environment

Zed: v0.137.3 (Zed)
OS: macOS 14.5.0
Memory: 18 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @noahfarr - I'm guessing this is because the XML extension is missing the line in the configuration file to tell it how to transform the line.  You can see examples [here](https://github.com/evrensen467/zed-sql/blob/49b27ca2787142bb83d142d593743233d15bf304/languages/sql/config.toml#L4) and [here](https://github.com/zed-industries/zed/blob/a6e0c8aca161237515a7e5cf54f15e4de75879b1/extensions/html/languages/html/config.toml#L5C1-L5C14).

A fix would need to go into the extension repo here:

https://github.com/sweetppro/zed-xml/blob/main/languages/xml/config.toml

Since this isn't code we own, I'm going to close this out. Feel free to reach out if there are any issues getting that fixed.
