### ISSUE TITLE
Vim mode search character "/"

### ISSUE THREAD

**Issue by kjvdven** [zed-industries/zed#12524]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In Vim Mode:
When I forward or back search for the "/", the search bar is triggered. 

### Environment

Zed: v0.137.5 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
@kjvdven This is by design, as I wanted to make sure that we didn't have to rebuild the entire search feature.

One thing I tried to ensure is that the behavior with enter, etc. should be the same as real vim. Are there cases where your muscle memory is not working, or are you asking for a bottom-docked search feature so it looks more vim-like?

**Comment by kjvdven** [comment]
@ConradIrwin Thanks for you answer.

Maybe I was a little soon to report, can't reproduce my issue anymore since last update. Or maybe I just was bad at typing.

But a search bar at the bottom is also a nice idea, because it doesn't produce a layout shift. 

And if I'm talking about layout shifts, i prefer, when toggling the sidebar on the right, that the sidebar overlays, instead shifting the code. But that is probably another feature request :)

**Comment by ConradIrwin** [comment]
:D makes sense!

**Comment by kraftwer1** [comment]
Agreed, having a bottom-docked search would be closer to Vim and the layout shift wouldn't happen anymore. Not only on `/`, but also for `*` and `cmd+e` and alike.
