### ISSUE TITLE
Ruby extension incorrectly detects tests

### ISSUE THREAD

**Issue by joeldrapper** [zed-industries/zed#12579]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The queries used to detect Minitest tests, RSpec example groups and RSpec specs are not sufficient to be included by default in the Ruby extension. Simply calling the method `test`, `it` or `describe` does not guarantee you are using Minitest or RSpec. Additionally, the definition of a method starting with `test_` does not guarantee the use of Minitest.

There are other test libraries for Ruby including [Sus](https://github.com/ioquatix/sus), [TLDR](https://github.com/tendersearls/tldr), and [Quickdraw](https://github.com/joeldrapper/quickdraw) that conflict with these queries.

Additionally, the commands that the runnables tasks trigger are not even correct for RSpec or Minitest. For RSpec, the command should start with `bundle exec rspec` to ensure the bundled version of RSpec is used. For minitest, this is more complicated. It’s usually `bundle exec rake` or `bundle exec rake test`. Sometimes it’s `bundle exec rails test` and sometimes (when working on a Rails gem), it’s `bin/test`.

## Steps to Reproduce
In any Ruby file, these three examples trigger runnables without correct scoping:

```ruby
def test_something
end

describe Something

test "something"
```

## Recommended solution

At minimum, the runnables should be removed by default. Perhaps they could be enabled with a configuration or by installing an `rspec` or a `minitest` extension. Alternatively, it might be possible to write more precise queries to detect the presence of the relevant Ruby gems.

I don’t know if this is possible, but the *ideal* solution would probably be to allow project-level configuration of tasks with the relevant runnable detection queries. That way, users could copy/paste e.g. the Minitest configuration into their project and update the task to execute `bundle exec rake` or `bin/test` or whatever they need.

### Environment

Zed: v0.137.6 (Zed)
OS: macOS 14.4.1
Memory: 128 GiB
Architecture: aarch64

**Comment by vitallium** [comment]
>The queries used to detect Minitest tests, RSpec example groups and RSpec specs are not sufficient to be included by default in the Ruby extension. Simply calling the method test, it or describe does not guarantee you are using Minitest or RSpec. Additionally, the definition of a method starting with test_ does not guarantee the use of Minitest.

Totally agree with that. `tree-sitter` is limited to the language syntax only. It does not know anything about used Ruby gems or testing infrastructure. Relying solely on them gives false-positive results because different framework could use the same DSL, like `context` is minitest or RSpec but their meaning could be different, for example, giving the runnables list. In my opinion, things like runnable tests should be provided by LSP since it knows about Ruby gems. [The Ruby LSP addon for `rspec`](https://github.com/st0012/ruby-lsp-rspec) does that. It provides the list of runnables via [Code Lens](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeLens_resolve). Unfortunately, Zed does not have support for Code Lens yet.

>Additionally, the commands that the runnables tasks trigger are not even correct for RSpec or Minitest. For RSpec, the command should start with bundle exec rspec to ensure the bundled version of RSpec is used. For minitest, this is more complicated. It’s usually bundle exec rake or bundle exec rake test. Sometimes it’s bundle exec rails test and sometimes (when working on a Rails gem), it’s bin/test.

 I also agree on this one too. That was another puzzle I tried to solve with minimum effort. For `rspec` tests I decided to use a binstub to ensure Zed runs `rspec` in the bundle context. Luckily, we have use local Zed tasks to override run commands that match the project configuration, for instance, to ensure the bundled `minitest` is used we can use the following local task (to create a local task list you need to create `.zed` folder with the `tasks.json` file in your project):

```json
  {
    "label": "test $zed_symbol",
    "command": "./bin/rake", // or "bundle"
    "args": ["test", "$zed_file", "--name", "\"/$zed_symbol/\""],
    "tags": ["minitest-test"]
  }
```

The important part here is the `tags` key, runnables queries assign this tag to targets. I wish to have a single tag for all possible variations and frameworks but I think that will be challenging.

>At minimum, the runnables should be removed by default. Perhaps they could be enabled with a configuration or by installing an rspec or a minitest extension. Alternatively, it might be possible to write more precise queries to detect the presence of the relevant Ruby gems.

I think that could be a good solution to provide runnables for Ruby projects, i.e., remove the bundled `tasks.json` and mention the local `tasks.json` in the documentation. @joeldrapper what do you think about that?

@joeldrapper and, of course, this is the kind of feedback I have been waiting for. Appreciate it! This is a good starting point towards improving the Ruby extension.

**Comment by vitallium** [comment]
@joeldrapper What do you think on the following approach:

1. Remove all built-in tasks for running tests and provide a single task that will output instructions on running tests for your testing framework. Here how it's look in action:

```json
[
  {
    "label": "rspec $ZED_RELATIVE_FILE:$ZED_ROW",
    "command": "echo",
    "args": [
      "'Please create a local tasks file for Zed (https://zed.dev/docs/tasks) to run tests with your command.\n'"
    ],
    "tags": ["ruby-test"]
  }
]

```

Screenshot:
![CleanShot 2024-06-10 at 17 18 04@2x](https://github.com/zed-industries/zed/assets/1894248/9206570f-54ec-4409-807a-03e0d68a7c0f)

I think that could be enough for now while Zed does not provide a way for extensions to provide context in tasks in a more efficient way, as seen in [the Go language](https://github.com/zed-industries/zed/blob/main/crates/languages/src/go.rs#L457). The message could be adjusted, of course. All in all, I don't want to rush things here, and any expert is more than welcome.

**Comment by andyw8** [comment]
Thanks for the tip about `$ZED_SYMBOL`, I've opened https://github.com/zed-industries/zed/pull/27607 to add it to the Ruby docs.
