### ISSUE TITLE
Expected installation paths on Linux, name of cli binary

### ISSUE THREAD

**Issue by jirutka** [zed-industries/zed#12585]
### Check for existing issues

- [X] Completed

### Describe the feature

If I understand it correctly, `cli` is supposed to be on PATH and used to launch the `Zed` UI from a terminal, right? However, `cli` currently expects `Zed` to be in the same directory as `cli` and named either `zed` or `Zed`. This means `cli` cannot be named `zed` (it essentially creates a fork-bomb…), which is quite unexpected.

According to [FHS](https://refspecs.linuxfoundation.org/fhs.shtml), `cli` should be installed in the `bin` directory (`/bin`, `/usr/bin` or `/usr/local/bin`) to be on PATH and `Zed` (UI) most likely in the `libexec` directory (`/usr/libexec` or `/usr/local/libexec`). `cli` is not a good name for a binary on PATH, it’s expected to be named `zed`.

I’m packaging Zed for Alpine Linux ([package](https://pkgs.alpinelinux.org/packages?name=zed), [APKBUILD](https://git.alpinelinux.org/aports/tree/testing/zed/APKBUILD)) and I had to [patch](https://git.alpinelinux.org/aports/tree/testing/zed/zed-libexec.patch) `crates/cli/src/main.rs` to make it work as expected.

**Comment by mikayla-maki** [comment]
FYI, I don't think this patch is doing what you're intending to: https://git.alpinelinux.org/aports/tree/testing/zed/initial_user_settings.patch, as it leaves the default setting intact until a user opens and saves the new ones. Better to change the settings here, so that they'll startup correctly: https://github.com/zed-industries/zed/blob/main/assets/settings/default.json
