### ISSUE TITLE
 Reveal in finder refer to mac os and on linux or other 

### ISSUE THREAD

**Issue by yodatak** [zed-industries/zed#12776]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In Linux we don't have finder we have a file explorer and in Linux when i see reveal in finder i cannot understand what it mean because it look like i must do some search and i just want to open the folder where the file is

### Environment

Linux

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Maybe Open in file explorer and stay with Finder for the mac user if its easy for mac users

**Comment by dhairyanadapara** [comment]
I have observed that the context menu contains both 'Trash' and 'Delete' options. Based on the platform, we can display only one option. 

I'm checking what the solutions are.

**Comment by someone13574** [comment]
> I have observed that the context menu contains both 'Trash' and 'Delete' options. Based on the platform, we can display only one option.
> 
> I'm checking what the solutions are.

Don't all the desktop platforms (Linux, MacOS, Windows) have both delete and trash?

**Comment by dhairyanadapara** [comment]
@someone13574 Yes all the platform supports both trash and delete but the interpretation is different in each one:
Mac:
Trash (Command + Delete) -> Soft delete
Delete (Option + Command + Delete)-> Hard delete

Windows:
Recycle Bin (Delete) -> Soft delete
Delete (Ctrl + Shift + Delete) -> Hard delete

I have used the linux but don't have exact idea.

**Comment by someone13574** [comment]
@dhairyanadapara But that’s just a keybinding change. Your first comment was about not showing options.

**Comment by dhairyanadapara** [comment]
Hey @someone13574, I realized I misunderstood the code and mistakenly suggested its removal. I've checked again, and everything works as expected. However, we should update the copy text for "Trash" and "Delete" to help users differentiate between them more easily. The confusion might have arisen because both "Delete" and "Trash" are shown. Typically, applications only display "Trash" or a soft delete option. If users want to permanently delete something, they can use the keybinding or the file explorer.
