### ISSUE TITLE
Auto Suggestion

### ISSUE THREAD

**Issue by HtetAungKhant23** [zed-industries/zed#12832]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, we use Zed in our office, but we would appreciate having trigger suggestions similar to those in VS Code.

**Comment by osiewicz** [comment]
Do you mean autocompletions like such:
![image](https://github.com/zed-industries/zed/assets/24362066/7ad8fee7-dab8-46f5-a4c3-1b83c0280dab)
if so, that's already supported. What languages are you using?

**Comment by Shin-Thant** [comment]
I think what he means is the `Cmd + I` keyboard shortcut to trigger or show snippets.

https://github.com/zed-industries/zed/assets/88672871/8a5df2ff-5d14-4018-bda5-6d5356b08cd7

As you can see in the video, I can use keyboard shortcut `Cmd + I` to get the snippets. In zed, I need to first type the first letter of the property in order to get the snippets.

May be I misunderstand the issue or I just don't know how to enable that.

**Comment by HtetAungKhant23** [comment]
This is exactly what I meant. Thank you for your in depth explanation of the problem.

**Comment by bennetbo** [comment]
You can achieve that by pressing `ctrl+esc` or by running `editor::show_completions` in the command palette. 

If you'd like to rebind it to `cmd-i`, add this into your [keymap](https://zed.dev/docs/key-bindings):

```json
  {
    "context": "Editor",
    "bindings": {
      "cmd-i": "editor::ShowCompletions"
    }
  },
```

**Comment by Shin-Thant** [comment]
@bennetbo It works. Thanks!
