### ISSUE TITLE
GitHub permalink not working

### ISSUE THREAD

**Issue by eproxus** [zed-industries/zed#13042]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a Git repository with the following `.git/config` configuration:

   ```gitconfig
   [remote "origin"]
       url = git@github.com:org/repo.git
   ```
2. Choose `editor: open permalink to line` from the command palette
3. See the following error message:
   > Failed to open permalink: failed to parse Git remote URL

The same happens with `ssh://github.com/org/repo.git`.

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

**Comment by maxdeviant** [comment]
What is the output of `git remote -v` in the repository?

**Comment by eproxus** [comment]
Hmm, it actually is:
```console
$ git remote -v
origin  github-work:org/repo.git (fetch)
origin  github-work:org/repo.git (push)
```

Which is because I have the following in my `~/.gitconfig`:

```
[url "github-work:org/"]
    insteadOf = git@github.com:org/
```

If I remove that it works (here's hoping it doesn't break anything else in my workflow, but that's my problem 😛)

If this is not something you intend to support (which I can understand, feel free to close this issue).

**Comment by donaldo-paktolus** [comment]
I have the exact same issue

**Comment by notpeter** [comment]
I believe ssh:// urls were fixed by:
- https://github.com/zed-industries/zed/pull/19924

It's not really practical for Zed to attempt to resolve a git remote which is re-written by `.gitconfig` to a fake host alias specified in `~/.ssh/config` to detect whether the end host name is github.com.

I'm happy to revisit if you have a suggested method for how this could be implemented, but for now I'm going to close it as unactionable.  Thanks for reporting.

**Comment by tashi21** [comment]
I'm also facing the same issue due to the same reason as @eproxus. @notpeter while I understand that currently it isn't supported or deemed as important, shouldn't this be implemented sometime in the future? I'm sure many people would have custom ssh configs for work repos. But if it is highly impractical for Zed to parse the ssh config to be able to resolve custom host names, what can we change in our configs to be able to get the same custom ssh config functionality AND use Zed's permalink feature?

Would it be too difficult to add a custom mapping of hostnames in the settings file for such a scenario that Zed can use to replace custom hosts with the actual underlying host? It can be a permalink specific setting, or a git related setting. Whichever results in a better and more practical implementation.

**Comment by eproxus** [comment]
I've managed to solve it by removing the SSH host alias, so from my side the issue can be closed. For what it's worth, I personally don't think it is that strange to not require an editor to be aware of this kind of host mapping hack.

**Comment by nagromLobo** [comment]
I have a very similar setup for my local vs. home github accounts and would love for this feature to work or to have some sort of config to point out that the host actually points to github if the resolution can't happen automatically
