### ISSUE TITLE
[Windows] Go to definition does not work

### ISSUE THREAD

**Issue by FlixCoder** [zed-industries/zed#13135]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I hover over a method from some crate, I correctly get a tooltip with the function's documentation. However, when I try to go to the definition (F12 or right-click), nothing happens.
It is important to note that this is part of a dependency, so the file it outside of the project.
I am talking about rust-analyzer here, so it is a Rust project.

EDIT: It actually does not matter where the file is, I cannot even go to definition in the same file.

See below for the logs, there is a successful response from the language server, but the editor cannot open the file due to some failed stat call apparently.

### Environment

Zed: v0.141.0 (Zed Dev 15d3e54ae3ac0e0e9256cdebfd41d9e38e6cb7eb)
OS: Windows 10.0.22631 (It is actually Windows 11 lol)
Memory: 30.7 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

For every try, I get the following two lines:
```
2024-06-17T12:04:51+02:00 [INFO] Took 2.2158ms to receive response to "textDocument/definition" id 4586
2024-06-17T12:04:51+02:00 [ERROR] crates\editor\src\element.rs:289: failed to stat worktree path
```

**Comment by SomeoneToIgnore** [comment]
The stat error comes from
https://github.com/zed-industries/zed/blob/0afb3abfd24c4f9851fc8a8ef37da89cb754dd41/crates/worktree/src/worktree.rs#L379

which should happen only when the file does not exist:
https://github.com/zed-industries/zed/blob/0afb3abfd24c4f9851fc8a8ef37da89cb754dd41/crates/fs/src/fs.rs#L371-L402

So I expect something odd happens when the code tries to fetch the symlink or path metadata during the FS operations.
Windows is not even in alpha now, so anything can be broken there and is worth investigating (as you were supposedly building the Windows binary from sources anyway)

**Comment by heksesang** [comment]
I think it's caused by this: https://github.com/zed-industries/zed/pull/12928/files#diff-9aed0f58926aee71638164c95da3800a90460d525d736a354c71490e333c8d88

`to_file_path()` assumes that you can just take the file path of the file URI and use it as the absolute path, but because the file URI on Windows is `file:///c:/source/myfile.rs` it ends up with the malformed `/c:/source/myfile.rs` as the absolute path used in the navigation code.

To solve this, `to_file_path()` needs to do a bit more work to ensure the file path is correct on Windows.

**Comment by AlbertMarashi** [comment]
If anyone else had this issue coming from Google, what worked for me is quitting/restarting Zed - and then I got rust properly working (Go to definition, AI predictions, error highlighting)

Not sure why a restart was required, but hope this helps someone
