### ISSUE TITLE
MacOS `cmd` shortcut is not working, and get mixed up with `ctrl`  for custom key binding

### ISSUE THREAD

**Issue by konsalex** [zed-industries/zed#13152]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have made a recording of the bug 

https://github.com/zed-industries/zed/assets/12672541/33223121-da55-4054-9f14-d2704c16dd3d

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.3.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Added in the description

**Comment by konsalex** [comment]
@notpeter from which perspective redundant? I have assigned another shortcut in `cmd-~` in MacOS and conflicts with that  🤔

**Comment by notpeter** [comment]
Sorry, there's two things going on and I think I initially misunderstood one of them.
 
The default keymap (cmd-shift-p, zed: open default keymap) contains the following bindings:
```
[
  {
    "context": "Workspace",
    "bindings": {
      "ctrl-`": "terminal_panel::ToggleFocus",
      "ctrl-~": "workspace::NewTerminal",
    }
  }
]
```

1. The behavior you are seeing at the end of your video (when you press "ctrl-shift-`" aka "ctrl-~") is the default behavior (unaffected by your keymap) of opening a new terminal window.

2. MacOS by default maps "cmd-`" and "cmd-shift-`" (aka "cmd-~") to cycle between windows of the currently open app.  This was a no-op for you because you only have a single window open, if you open a second Zed window, you'd see the window cycling.  I believe MacOS intercepts these key strokes (just like "cmd-tab" and "cmd-shift-tab" for app switching) and they cannot be disabled and don't get passed to Zed. I'd have to double check, but either we never receive the events or we ignore them because MacOS is about to change the focused window.

Let me know if I've completely missed the point or am misunderstanding your intent.

**Comment by konsalex** [comment]
@notpeter indeed my bad, missed the part that <code>shift+`</code>  is equivalent to `~`.

Now modified and worked as expected thanks for the help!
