### ISSUE TITLE
Better Assistant Panel layout

### ISSUE THREAD

**Issue by Rajveer2009** [zed-industries/zed#13321]
### Check for existing issues

- [ ] Completed

### Describe the feature

In the current Assistant Panel all the text is editable, it feels more like a text file then a menu, it should be more like the one VSCode has

### If applicable, add mockups / screenshots to help present your vision of the feature

![326621189-d36feee0-71e3-49a6-b55c-748748447e0f-1](https://github.com/zed-industries/zed/assets/93126793/0cc49cf0-27ce-483b-ba74-121b20982900)

**Comment by pointlessone** [comment]
I respectfully disagree. It is useful to have Assistant blocks editable.

LLMs get the whole conversation sent on every completion, not just the last message. This means that every message, both my and assistant's are sent on every turn. Every token costs money. So it's useful to remove unhelpful parts of the previous messages. Things like hallucinations, extra verbose explanations, ideas that turned out to lead nowhere can be removed. Useful parts can be rephrased more succinctly. This can lead to better results, while saving some money/time.

**Comment by JosephTLyons** [comment]
> I respectfully disagree. It is useful to have Assistant blocks editable.
> 
> LLMs get the whole conversation sent on every completion, not just the last message. This means that every message, both my and assistant's are sent on every turn. Every token costs money. So it's useful to remove unhelpful parts of the previous messages. Things like hallucinations, extra verbose explanations, ideas that turned out to lead nowhere can be removed. Useful parts can be rephrased more succinctly. This can lead to better results, while saving some money/time.

This has sort of been our goal with the assistant since day one - give the users control over all the text, nothing is inaccessible - so you can correct and guide the model as the conversation develops.

**Comment by JosephTLyons** [comment]
I think for now, we will close this out, because we are currently working on features that heavily lean into our current design.
