### ISSUE TITLE
Unable to save after opening the default settings file

### ISSUE THREAD

**Issue by xiaoai-669** [zed-industries/zed#13622]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**When I open the default settings file and modify a value, a pop-up window will appear when I use command + s  to save, so I can't save.**

<img width="1243" alt="image" src="https://github.com/zed-industries/zed/assets/174075254/cbcdcde5-ca88-481b-a744-9130923e1b18">

<img width="1792" alt="image" src="https://github.com/zed-industries/zed/assets/174075254/b0fc2729-c871-41a3-8f8d-9b665e444c22">

### Environment

Zed: v0.141.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GB
Architecture: x64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by maxdeviant** [comment]
This is the expected behavior.

Opening the default settings opens a new buffer with the contents of the default settings.

If you want, you can save the default settings to you `settings.json`, but it's recommended to just modify the things you want in `settings.json`, since these are overlaid on top of the defaults.

**Comment by JosephTLyons** [comment]
Just for added clarity @xiaoai-669, you should be opening `Settings > Open Settings` and placing your custom settings, that override the default settings, in there.
