### ISSUE TITLE
eslint-disable comments added on save in svelte files

### ISSUE THREAD

**Issue by unlocomqx** [zed-industries/zed#13633]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

[Simple Repro](https://github.com/unlocomqx/zed-eslint-svelte-issue)

I have a few custom eslint rules

```ts
{
	rules: {
		'no-console': ['error', { allow: ['warn', 'error'] }],
		'@typescript-eslint/no-unused-vars': 'warn',
		'no-restricted-syntax': [
			'warn',
			{
				message: "$inspect is not allowed",
				selector:
					"CallExpression[callee.name='$inspect']"
			}
		]
	},
},
```
When I have code inside a svelte file that triggers an eslint warning or error, I get an eslint-disable comment that is inserted automatically

![CleanShot 2024-06-28 at 10 52 48@2x](https://github.com/zed-industries/zed/assets/793712/cc892dbf-0bff-4700-b1d3-c6be08abb54e)

It also happens for other svelte rules, not just custom rules

![CleanShot 2024-06-28 at 10 55 22@2x](https://github.com/zed-industries/zed/assets/793712/9dd2fc13-102a-4488-b645-d5fcb90cd6a3)

### Environment

Zed: v0.141.2 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Frank-vdm** [comment]
i get this with a react/ typescript project, its super annoying, and only started happening since the last update for me

**Comment by unlocomqx** [comment]
> i get this with a react/ typescript project, its super annoying, and only started happening since the last update for me

Same.

Here's a [repro](https://github.com/unlocomqx/zed-eslint-svelte-issue)

**Comment by xiduzo** [comment]
This happened to me a while back for react projects, and it drives me nuts. I am back to vscode until this issue is solved

**Comment by unlocomqx** [comment]
This is tagged as relating to svelte. if any react guys can provide a repro, it would also be helpful to verify the issue.

**Comment by eulke** [comment]
Same with react / js project

**Comment by mrnugget** [comment]
> Same.
> 
> Here's a [repro](https://github.com/unlocomqx/zed-eslint-svelte-issue)

Thanks for that repo!

I cannot reproduce it though.

Here's what I did:

1. Clone your repo
2. Run `pnpm install` in it
3. Open the repo with Zed
4. Edit the `+page.svelte` file to remove the comments
5. Hit save.

Code is formatted.

I then edited the ESLint config to add another rule:

```diff
diff --git a/eslint.config.js b/eslint.config.js
index b5b7d9b..310e012 100644
--- a/eslint.config.js
+++ b/eslint.config.js
@@ -32,6 +32,7 @@ export default [
        },
        {
                rules: {
+                       'prefer-const': 'error',
                        'no-console': ['error', { allow: ['warn', 'error'] }],
                        '@typescript-eslint/no-unused-vars': 'warn',
                        'no-restricted-syntax': [
```

When I then hit save, ESLint fixes the `let` to `const` but inserts no comments.

https://github.com/zed-industries/zed/assets/1185253/2062fc74-0fe0-4bc5-982d-24fd02aeae19

Here's the Zed `settings.json` that I was using:

```json
{
  "languages": {
    "Svelte": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    },
    "TSX": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    },
    "Vue.js": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    },
    "JavaScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    }
  },
  "vim_mode": true
}
```

**Comment by Laurin-Notemann** [comment]
A similiar issue has occured with my tsx file, but it seemed like it occures more often when I had my settings page open as a tab. And for me it happened when I had two many line (for example two lines and I hit save, and then it adds a comment to ignore an eslint rule)

**Comment by unlocomqx** [comment]
@mrnugget I tried with these settings and the issue went away

```json
"languages": {
    "Svelte": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    }
  }
```

Can you try without that setting to see if you can reproduce it?

Thanks

**Comment by hmttrp** [comment]
I am experiencing the same issue in a Typescript project.
I noticed that this is only happening when I have `source.organizeImports` enabled. So removing the following snippet from my configuration makes the issue dissapear.
```
  "code_actions_on_format": {
    "source.organizeImports": true
  },
```

The issue is also reproducible in the [example repo](https://github.com/zed-industries/zed/issues/13633#issuecomment-2196871547) when the setting is enabled.

**Comment by eulke** [comment]
Here is my Log

```
2024-07-04T17:36:36-03:00 [INFO] Language server with id 22 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/eulke/development/mpfc-balance-frontend/app/components/OpenFinance/Totalizator/TotalAmount/index.js",
  "state": 1,
  "validationTime": 69
}
2024-07-04T17:36:36-03:00 [INFO] Language server with id 22 sent unhandled notification eslint/openDoc:
{
  "url": "https://github.com/prettier/eslint-plugin-prettier#options"
}
```

**Comment by eulke** [comment]
Is true that if comment i comment `source.organizeImports` that issue dissapear

```
  "languages": {
    "JavaScript": {
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true
          // "source.organizeImports": true
        }
      }
    }
  },
```

But i want to be able of have both things

**Comment by unlocomqx** [comment]
> So it's a language server that adds these comments then? Which language server is that? Is there a way to disable that behaviour? Or is it about the order of the code actions?

Probably the eslint ls

**Comment by mrnugget** [comment]
@grzegorzkiselev reports here https://github.com/zed-industries/zed/issues/12997#issuecomment-2228490870 that updating the eslint version fixed the issue for him. Can someone else confirm this?

**Comment by unlocomqx** [comment]
@mrnugget It still occurs on eslint 9.7.0. I updated the [repro](https://github.com/unlocomqx/zed-eslint-svelte-issue).

**Comment by grzegorzkiselev** [comment]
@mrnugget I found very interesting line in source code:

https://github.com/zed-industries/zed/blob/fa3d29087dc3b08aed5a23e7d02f282b3568917b/crates/languages/src/typescript.rs#L378

```
"disableRuleComment": {
  "enable": true,
  "location": "separateLine",
}
```

This literally contains what we want to turn off.  But the value is hardcoded, can we somehow override it?

**Comment by unlocomqx** [comment]
@grzegorzkiselev that's these code actions
![CleanShot 2024-07-15 at 21 15 25@2x](https://github.com/user-attachments/assets/b86d132b-c279-4006-8a0f-13427615645e)

**Comment by grzegorzkiselev** [comment]
@unlocomqx, I think I've found the solution! Needed in file
`~/Library/Application Support/Zed/languages/eslint/vscode-eslint-release/2.4.4/vscode-eslint/client/src/client.ts`

Find string
```
disableRuleComment: config.get<CodeActionSettings['disableRuleComment']>('codeAction.disableRuleComment', { enable: true, location: 'separateLine' as const, commentStyle: 'line' as const }),
```
and replace enable with false.

**Comment by grzegorzkiselev** [comment]
I think I found a workaround:

<img width="1136" alt="изображение" src="https://github.com/user-attachments/assets/8c1f7ce2-f07f-47c0-a5ab-73e3906b9220">

I commented out these conditions in `~/Library/Application Support/Zed/languages/eslint/vscode-eslint-release/2.4.4/vscode-eslint/server/src/eslintServer.ts`, recompiled, restarted, and so far in In my tests this solution works fine.

Side effect: The shutdown options will disappear from this menu.
<img width="451" alt="изображение" src="https://github.com/user-attachments/assets/83bca131-6239-4592-9f38-5669abd4c010">

**Comment by mrnugget** [comment]
@grzegorzkiselev what's your Zed config for that?

**Comment by grzegorzkiselev** [comment]
@mrnugget 

<img width="381" alt="изображение" src="https://github.com/user-attachments/assets/4ef3d66e-6462-463c-aeb0-a8adda24ac21">

Import helpers and fixAll.eslint work, disabling comments are not added.

**Comment by grzegorzkiselev** [comment]
@mrnugget Not exact.

We found that source.addMissingImport or source.organozeImports triggered comments. 

After I patched the eslint extension, the comments no longer triggered.

The screenshot with the config only demonstrates that the previously problematic configuration is usable with the patch from [here](https://github.com/zed-industries/zed/issues/13633#issuecomment-2229622864).

**Comment by mrnugget** [comment]
Okay, I dug into this with @ConradIrwin for the past few hours.

What we found:

- Sometimes (!) when we send `organizeImports` on save, the `eslint` language server will respond with all of the "disable ..." actions and tag them as `organizeImports`. We then execute them, because, well, it says they're `organizeImports` code actions.
- That really only happens sometimes. I cannot find a reliably way to reproduce it. Thanks to everybody here we have the repo, but even in that repository, I _sometimes_ can reproduce the issue and sometimes not, with the same config.

What we need to do:

- Figure out when this happens: is it a combination of different language servers playing together? is it a special combination of "what the code looks like" and "when it's saved"?
- Figure out whether it's safe to ignore all code actions with `commands` attached to them when running code actions on save/format (vs. manually triggered via code actions menu)

**Comment by hmttrp** [comment]
I've checked the logs and noticed that the order of kinds in the `only` property is changing. I also checked if that could cause any issues in the eslint LSP and I believe I found something.

1. Eslint LSP [only considers the first string in `params.context.only`](https://github.com/microsoft/vscode-eslint/blob/edc9685bcda26462dc52decce213167af8d2b25d/server/src/eslintServer.ts#L588) and [uses that as a `kind` in the return value](https://github.com/microsoft/vscode-eslint/blob/edc9685bcda26462dc52decce213167af8d2b25d/server/src/eslintServer.ts#L624-L637).
2. Since [`code_actions_on_format` is a HasMap](https://github.com/zed-industries/zed/blob/ef5305869f68df853ece5a2f18fd01ac52463710/crates/language/src/language_settings.rs#L120) there is no guarantee of the order that is being sent to the lsp. This could be the reason why this is only happening sometimes [since there is a specific condition when the code action is the fix all one.](https://github.com/microsoft/vscode-eslint/blob/edc9685bcda26462dc52decce213167af8d2b25d/server/src/eslintServer.ts#L589-L611)

Here is an example request that was made to the LSP which caused the issue:
```jsonc
{
  "jsonrpc": "2.0",
  "id": 140,
  "method": "textDocument/codeAction",
  "params": {
    // ...
    "context": {
      "diagnostics": [
        // ...
      ],
      "only": ["source.organizeImports", "source.fixAll.eslint"] // <-- this is the interesting part
    }
  }
}
```

And here is one (after restarting zed) that did not cause the issue:
```jsonc
{
  "jsonrpc": "2.0",
  "id": 69,
  "method": "textDocument/codeAction",
  "params": {
    // ...
    "context": {
      "diagnostics": [
        // ...
      ],
      "only": ["source.fixAll.eslint", "source.organizeImports"] // <-- notice the change in order
    }
  }
}

```

**Comment by mrnugget** [comment]
Thank you both! Very nice detective work. I'll dig in.

**Comment by mrnugget** [comment]
Just merged a fix to `main` that will go out with the next Preview release. It fixes the issue for me. We now filter the code actions we send to a server based on their capabilities. Previously we would send anything.
