### ISSUE TITLE
Keep unsaved files content saved+open when quitting Zed

### ISSUE THREAD

**Issue by himat** [zed-industries/zed#13708]
### Check for existing issues

- [X] Completed

### Describe the feature

I think Zed would be much more functional if it behaved like Sublime and VScode, where if you quit the entire app (cmd q), it won't prompt you to save unsaved files. 
Instead, it does preserve those files, and when you re open the IDE, those unsaved new files are still there!
It becomes far more useful with that.

Of course, if you press the X button on a single file tab, then it should prompt then to save or discard.

**Comment by bennetbo** [comment]
Hey, this is a duplicate of #4683 (which we are actively working on), feel free to :+1: that issue.

**Comment by git-mosis** [comment]
Hey @bennetbo - it's been a year and https://github.com/zed-industries/zed/issues/4683 is closed without the feature implemented. May we get an update? Hope this feature doesn't fall through the cracks.

**Comment by bennetbo** [comment]
@git-mosis Not sure what you mean? We persist unsaved files across restarts now.

https://github.com/user-attachments/assets/cef449f0-7d36-4d05-ada9-39e5a887da8b

**Comment by javafuns** [comment]
Using Zed 0.195.3 (mac). when quit the app, still warn me to save or  Don't save.
@bennetbo

**Comment by bennetbo** [comment]
Strange. What do your settings look like? Do you have `"restore_on_startup"` configured?

**Comment by andyzasl** [comment]
@bennetbo 
Same for me. 
Could you please share your configuration? I've tried
with 
> "restore_on_startup": "last_session","

but no difference, still warns about to save or not

**Comment by denisazevedo** [comment]
This is related: https://github.com/zed-industries/zed/issues/15098

**Comment by leonid1812** [comment]
I waited so long for Zed on Windows, so much was said about this editor. However, I am completely disappointed - even the basic functionality doesn’t work. The restore_on_startup feature is absent, there are no plugins, and it doesn’t support syntax highlighting for programming languages.

**Comment by leonid1812** [comment]
Zed 0.218.6 on Windows still does not work with the Last Session or Last Workspace options. When I work with individual files (not with a project)

**Comment by leonid1812** [comment]
<img width="1350" height="1125" alt="Image" src="https://github.com/user-attachments/assets/c4e3d2ee-7593-4fce-914d-624a28efac3e" />

<img width="1052" height="711" alt="Image" src="https://github.com/user-attachments/assets/f52236e2-6c14-4b2f-b196-5b13293f2fbe" />

<img width="1004" height="390" alt="Image" src="https://github.com/user-attachments/assets/7c4473bc-764b-4513-b0c7-cfa877560887" />

Create a new file and add text

<img width="1150" height="252" alt="Image" src="https://github.com/user-attachments/assets/e034850c-ab4f-40f0-a9d2-fe142385a605" />

I am closing the Zed editor.
Expected behavior: Zed automatically saves text in internal temporary files.
Reality: Zed asked to save a file.

<img width="1473" height="617" alt="Image" src="https://github.com/user-attachments/assets/228a483f-306e-47ba-8468-2d1e29ae8f90" />

After reopening the Zed editor, no files were restored at startup.

<img width="1321" height="470" alt="Image" src="https://github.com/user-attachments/assets/fd4a2519-4242-4fec-9600-54cb7e603286" />

**Comment by leonid1812** [comment]
<img width="951" height="304" alt="Image" src="https://github.com/user-attachments/assets/4de27073-5ce8-4924-a510-3f9d0e0919cd" />

But you are right. If you add a directory to the project, then Zed restores the session. However, I think this is a very strange and non-obvious solution.

**Comment by yeowyap** [comment]
> <img alt="Image" width="951" height="304" src="https://private-user-images.githubusercontent.com/17238147/537272028-4de27073-5ce8-4924-a510-3f9d0e0919cd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njg3Njg3ODMsIm5iZiI6MTc2ODc2ODQ4MywicGF0aCI6Ii8xNzIzODE0Ny81MzcyNzIwMjgtNGRlMjcwNzMtNWNlOC00OTI0LWE1MTAtM2Y5ZDBlMDkxOWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTE4VDIwMzQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMGU2NzIyNTgwZTg0ZDU1NGY3NDM1YWJlZTE3NTdkYzMxMTZmZTQxM2NkMDQ1MGM4ZGViODdiYTZlNWEwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C2qH3qJnhl1hxORpZL2x8WuLAsLUWm33wtA4DIecyg4">
> But you are right. If you add a directory to the project, then Zed restores the session. However, I think this is a very strange and non-obvious solution.

Agreed, this is a workaround. Longer term, it would be great to see this addressed properly by Zed.
