### ISSUE TITLE
Custom XKB layout

### ISSUE THREAD

**Issue by CaptaiNiveau** [zed-industries/zed#13700]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

> To add to the list of fallacies:
> * When processing key presses in linux, you can't assume that pressing a certain key (button with a keycode) has the same meaning everywhere. Keyboard layouts are handled by xkb, and can be reconfigured *entirely*. `Shift`+`Home` (to select everything up to the beginning of the line) can actually be achieved by pressing `Henkan`+`Space`+`E` (or any other key combination), and apps written in all UI toolkits (GTK, QT, even Electron) can handle such key presses – do not be the app that “knows better” by processing raw keycodes and breaking custom xkb layouts. Example tickets in other projects:
>   * https://github.com/davatorium/rofi/issues/485
>   * https://github.com/xkbcommon/libxkbcommon/issues/17 ← a bunch of useful info, I think
>   * https://github.com/mate-desktop/pluma/issues/17 ← this one has extremely helpful answers by @bluetech
>   * https://superuser.com/questions/801611/how-to-make-all-applications-respect-my-modified-xkb-layout
> 
> _Originally posted by @AlexDaniel in https://github.com/zed-industries/zed/issues/5395#issuecomment-1908666401_

This (locked) issue still exists and I'm running into it, using [Colemak + Extend from Dreymar](https://github.com/DreymaR/BigBagKbdTrixXKB). Specifically, the Extend layer causes some key combinations to not be picked up by zed.
Examples:
- ':' ("Shift + ;") 
- ')' ("Shift + 0")

The issue disappears for ':' (Qwerty p/P, Colemak ;/:) if I comment out the following lines from the Extend config file located at `xkb-data_xmod/xkb/symbols/extend` in the repo:
```
key <AD10> { symbols[Group1]=[Any       , Any       , Any       , Any       ,   // P
	    Delete                      , Delete                        ,   // Del
	    KP_Add                      , KP_Add                        ] , // KP_+
	 actions[Group1]=[NoAction(), NoAction(), NoAction(), NoAction(),
	    Redirect(key=<DELE>,clearmods=LevelFive), Redirect(key=<DELE>,clearmods=LevelFive),     // <DELE>
	    NoAction()                  , NoAction()                    ] ,
	 repeat=yes     };  // QWE P, Cmk ; :
```

wev produces the correct results and without the extend layer zed reads these keys correctly. Changing to default QWERTY instead of Colemak doesn't change this issue, as long as Extend is still active.

### Environment

Zed: v0.141.3 (Zed)
OS: Linux Wayland arch unknown
Memory: 58.7 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
@CaptaiNiveau Forgive me, I'm new to this -- I don't have all the original context and I've have never tried to used Colemak and it's been two two decades since I needed a custom XKB on Linux. But I want to understand the issue you're having.

Could you please edit your description so I might better understand the scope of your issue and have a good chance of being able to reproduce it? (steps to reproduce, etc).  Truly ExpainItLikeIm5 and I will  

We want to try and support Linux users and a diversity of configurations where possible, but I want to be upfront, I can make no promises. In the future please imagine the real human being reading your words (me!).  Even if you feel wronged, opening a new issue with a 1000 word block quote is coming in pretty hot. It's extremely unlikely to generate your desired response, but let's try and de-escalate a bit and take another crack at it.

**Comment by CaptaiNiveau** [comment]
Oh, no worries, this is in good faith :)

The way you configure your keyboard layout heavily depends on your DE, even if all of them actually use XKB under the hood (both X11 and all Wayland compositors I know of use it). I'm running Hyprland and the XKB config is just a few lines in its input config. If you check Dreymars repo I linked above, there's more detailed information on how to use Colemak/Extend on the most popular DEs (KDE. 

For this issue, you don't have to switch QWERTY for Colemak, just activate Extend. If you tell me which DE you're on, I can tell you how to, in case you get stuck. I spent a while optimizing my keyboard and trying to figure out how to actually make these layouts work in Linux (issues with key repeat, XWayland etc.), so I totally understand where you're coming from ^^

If you're running in an X11 session, it's a lot easier to apply this layout using the `install-dreymar-xmod.sh` command in the repo, while Wayland sessions commonly have their own config file for this. 

I'm happy to help you with whatever you're getting stuck with. It's probably easier if you tell me which DE (think KDE Plasma/Gnome/XFCE) you're using and if you're in a Wayland or X11 session (`echo $XDG_SESSION_TYPE` if you're unsure). This way, I can give you way more specific advice on how to replicate my issue. 

Btw, I'm totally happy that you're supporting Linux at all, no need to de-escalate. Thanks for open-sourcing this awesome project ^^

**Comment by fsh** [comment]
I had a similar issue to you, and I fixed mine with https://github.com/zed-industries/zed/pull/13931

Check to see if that works for you too if you're using X11. I don't have Wayland so didn't check/touch that. Incidentally, I also use Colemak and multiple groups/layers, tho I made it from scratch.

**Comment by CaptaiNiveau** [comment]
Nice, I compiled it from main (using the aur) and it seems to work properly, even from hyprland :D
I'll try some other stuff and close this issue when I'm certain that everything's fixed.

Btw, what do your layers look like? I got a Framework and want to use its QMK abilities to create even better layers - I'd love to take some inspiration ^^
If it's too off-topic, I wouldn't mind an E-Mail either.

**Comment by fsh** [comment]
Cool if it works for you now, but if you are indeed on Wayland then I doubt it's because of my patch! My fix was exclusively for X11 client. Maybe some other patch got in there.

---

Re keymap:

My keymap isn't fancy, it's bespoke out of practicality. I used the Norwegian-ish layout as the base for non-A-Z when I switched to Colemak since I generally like it better than US and I needed `æøå` as "plain keys." But in my experience there's a "problem" with it—and other Nordic/European maps: tho the symbol/punctuation placement feels great & logical for writing text, it feels insane for programming, e.g. all the Shift+<digit> or AltGr+<digit> stuff.

So step by step I kept moving stuff off of the digit row since it's many painful miles away. My home row's third layer (AltGr or RAlt) is `@{[(<>)]}~<Cómpósing Aćúté><Còmpòsing Gr̀àv̀è>`. Other symbols—`?!$+&%_=∈×^∧#≡*⋅…` + more čo̊m̧pōsin̈g chars—are on the other two rows. Now I only use the digit row for digits. The shifted version of the symbol layer tends to just have vaguely related symbols, e.g. `∈↔∉` `[↔⟦` `…↔⋯` `?↔¿` `*↔∘`. I also have another two layers (Menu or RCtrl or RWin) (+Shift) for more random stuff that is rarer (and admittedly harder to remember), mostly math-related stuff like `ℝℤℵ∩∀∎∫∇‖±∂∏∑` & fun stuff like `♠♣♥♦¦“§”«¶»✓✗™` etc.

Of course, AltGr+RWin[+Shift] gives yet two more layers... I originally set it up for Greek and stuff like that, but two modifiers side by side is beyond painful and everything without obvious mnemonics I don't recall anyway. At some point I want to clean it up and maybe try latched/locked modifiers for other alphabets (Greek or math-variants like 𝖆𝖇𝖈𝕒𝕓𝕔 etc.). More and more keyboards put the _braindead_ `Fn`-key (gods I hate it) where I want my second modifier to be, so it'd be cool if I could compress to only one modifier (+ shift) for symbol input. E.g. `AltGr+g` might be a Greek latch and `AltGr+G` a Greek lock, etc. Stuff like that would be cool, but it's been many years since I touched Xkb configs. Plus, I use these symbols like…maybe 6 times a year… So it's one of those "spend a week in a keymap rabbit hole to maybe save 1 minute of extra work per year" kind of things…
