### ISSUE TITLE
Assistant drops response and shows no output for openAI compatible API provider

### ISSUE THREAD

**Issue by AdjectiveAllison** [zed-industries/zed#13741]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm on version [v0.142.3-pre](https://github.com/zed-industries/zed/releases/tag/v0.142.3-pre) in order to take advantage of the [custom models feature](https://github.com/zed-industries/zed/assets/32017007/01057e7b-1f21-49ad-a3ad-abc5282ffaf0) released in 1.142.0-pre. 

I'm attempting to use octoAI, which can be used with openAI sdk in many languages so their api should be completely compatible. Here is the [documentation](https://octo.ai/docs/text-gen-solution/rest-api).

I set my api_url:
"api_url": "https://text.octoai.run/v1",

I then try to generate both in-line and in the chat window with a custom model set and get no response. I've talked to octoAI support and they confirmed I'm getting 200 responses from the requests zed editor send (auth correct, post structure correct, etc). Yet the GUI just hangs indefinitely. 
![image](https://github.com/zed-industries/zed/assets/20910163/a81bd449-4340-4804-bb1b-f9b8ba19aa2d)

Looking at logs, it seems the response body is dropped rather quickly with a message from sagebind. I attached the full message in the logging field below. I'm not sure if I maybe need to enable more verbose logging to see what's happening? I tried to dig through the source code of the assistant and I don't see where the issue may be happening but I'm also not very familiar with the codebase yet.

### Environment

Zed: v0.142.3 (Zed Preview)
OS: Linux Wayland arch unknown
Memory: 19.5 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

[INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early
</pre></details>

**Comment by amtoaer** [comment]
It seems that "tool_calls" field is set to null by OctoAI. However, Zed uses  `Vec` instead of `Option<Vec>` to handle it. 
<img width="1004" alt="image" src="https://github.com/zed-industries/zed/assets/32017007/d690e0de-2a3e-4ef9-846f-ea81b7d60110">
According to [OpenAI document](https://platform.openai.com/docs/api-reference/chat/create), "tool_calls" is optional:
<img width="589" alt="image" src="https://github.com/zed-industries/zed/assets/32017007/b9124f10-2515-4011-894c-2b171f9483d1">
A simple solution would be to replace "tool_calls" from `Vec` to `Option<Vec>` to fix this problem. I'm a little busy right now, so it would be kind if someone could submit a PR to fix it.

**Comment by AdjectiveAllison** [comment]
Thanks so much for the assistance @amtoaer!! I was able to open up a PR with your direction :)
