### ISSUE TITLE
Getting Started with GDScript Zed Extension and GoDot Game Engine

### ISSUE THREAD

**Issue by RustoMCSpit** [zed-industries/zed#13773]
### Check for existing issues

- [X] Completed

### Describe the feature

in godot, i can hold ctrl and click on items to find what they do. this can be done in zed but it would have to link them to their online documentation (unless zed bundled documentations inside itself)

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/zed-industries/zed/assets/134429563/d92bcf5a-f7a9-44fc-a204-630e9aa37b0b

**Comment by notpeter** [comment]
We support this already, but it is language-server dependent. For example with lua-language-server, holding cmd and hovering shows you underlined links:
<img width="760" alt="Screenshot 2024-07-10 at 10 14 45" src="https://github.com/zed-industries/zed/assets/145113/09b3f55c-76c9-4652-bf31-083ad3a1fe94">

And the "View Document" link at the bottom links to the [online lua documentation](http://www.lua.org/manual/5.4/manual.html#pdf-print).

Which language(s) are you hoping would support this?

**Comment by RustoMCSpit** [comment]
is there a tutorial on how to set this up?

**Comment by notpeter** [comment]
Zed depends on the language server for your particular programming language to provide this info. So for example the [Zed Lua Extension](https://github.com/zed-industries/zed/tree/main/extensions/lua) bundles [lua-language-server](https://github.com/LuaLS/lua-language-server) which bundles a markdown version of the Lua HTML manual. If the language server provides this, there shouldn't be any setup required for it to work in Zed.

Alternatively, you can configure a custom task that will launch an external program and pass the currently selected text to it.  Here is an example of someone doing this with so they can setup a keyboard shortcut to launch and search [Dash](https://kapeli.com/dash) (a documentation app) for whatever they've selected.
- https://github.com/zed-industries/zed/issues/13327

**Comment by RustoMCSpit** [comment]
>  If the language server provides this, there shouldn't be any setup required for it to work in Zed.

is there a way to auto-download the language servers through zed? or a list for them in zed?

**Comment by notpeter** [comment]
Most will auto downloaded when you download the appropriate extension or the first time you open a file-type which we match with a support language/language server.

There is an extension for GDScript ([grndctrl/zed-gdscript](https://github.com/grndctrl/zed-gdscript)) as well as C, C++, C#, etc. Just search extensions.

**Comment by RustoMCSpit** [comment]
> Most will auto downloaded when you download the appropriate extension or the first time you open a file-type which we match with a support language/language server.
> 
> There is an extension for GDScript ([grndctrl/zed-gdscript](https://github.com/grndctrl/zed-gdscript)) as well as C, C++, C#, etc. Just search extensions.

wait so how do i "activate" it

**Comment by notpeter** [comment]
The GDScript extension is not built or officially supported by Zed, but here are instructions for getting started with Godot in Zed.

1. Install netcat: run `brew install netcat` in a terminal
2. Open Zed.
3. Open zed extensions (cmd+shift-x)
4. Close Zed.
5. Search for GDScript, click "Install Extension"
1. [Download GoDot](https://godotengine.org/download/macos/)
2. Unzip godot.app and drag it to your /Applications folder.
3. open Godot.app and open your project (an example project is fine)
4. In Godot, Editor Menu -> Editor Settings; scroll down the left sidebar to `Text Editor -> External`
    1. Use External Editor: "✅ On"
    2. Exec path: `/Applications/Zed.app/Contents/MacOS/zed`
    3. Exec flags: `{project} {file}`
    3. Close settings to save.
5. In Godot double click on a *.gd script and Zed will launch

When GoDot is running, the GDScript extension will connect to the language server provided by the GoDot environment and give you the fancy underlines, jump to definition and hover states when you hold cmd.   

<img width="918" alt="image" src="https://github.com/user-attachments/assets/9689f5b8-95bc-4e43-a9bb-1ffd16d08281">

P.S. If Zed is already running with another workspace (or with no workspace open) spawning from Godot will fail. Just cmd+q Quit Zed and it should work again. Not sure exactly why, but I gave up because GoDot doesn't support passing arbitrary arguments (e.g. `--wait`) correctly.  Anyways, good luck!

**Comment by RustoMCSpit** [comment]
thank you!!!

**Comment by Minoqi** [comment]
this should really be added to the readme, super useful!

**Comment by grndctrl** [comment]
The first step is unnecessary I think, because the extension works with NC as well, which comes on your mac? Correct me if I'm wrong. Otherwise a good writeup, can you create a pull request to make this part of the readme?
