### ISSUE TITLE
Not accept "ollama" as assistant API key

### ISSUE THREAD

**Issue by GitHubGeek** [zed-industries/zed#13811]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Following the doc to use locally run ollama as assistant: https://zed.dev/docs/assistant-panel#using-ollama-on-macos

Zed refuses to connect to ollama as per error below:

![image](https://github.com/zed-industries/zed/assets/265551/8e236c44-2c7d-466c-b862-340f3b59885f)

### Environment

Zed: v0.142.4 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by amtoaer** [comment]
It appears that api_url is not set correctly. This error indicates that Zed is attempting to access the official OpenAI API using "ollama" as the key.
Additionally, the documentation is currently outdated and needs to be updated to reflect the current changes. Since #12902 has been merged, we can now simplify the configuration for ollama as follows:
```json
"assistant": {
    "version": "1",
    "provider": {
      "name": "ollama"
    }
}
```

**Comment by notpeter** [comment]
We've completely reworked the AI Assisting configuration flow for Ollama so it no longer requires overriding the OpenAPI endpoint so this should be fixed in the newest Zed Preview.

![Screenshot_20240815_144957](https://github.com/user-attachments/assets/ee47bf74-bd01-4c9e-8487-98a09b229643)

If you are still experiencing this with a recent build, please comment and we can reopen. Thanks.

**Comment by AnkushMalaker** [comment]
The connect button doesn't do anything for me - I suppose its because I'm not running ollama on the same device I'm using to code. I think this is a pretty common usecase where ollama provider is not localhost. A field to enter the ollama url would be nice.

**Comment by notpeter** [comment]
To use a non local endpoint you can do so via settings. Just change `api_url`. 
```
"language_models": {
  "ollama": {
    "api_url": "http://localhost:11434"
  }
}
```

If you want to increase the default (conservative; capped at 32k) max_toxens (context size) you can do that here as well:
```json
"language_models": {
  "ollama": {
    "api_url": "http://localhost:11434"
    "available_models": [
      {
        "name": "phi4",
        "display_name": "Phi4 64K",
         "max_tokens": 65536
      }
    ]
  }
}
```

**Comment by andreasteich** [comment]
Is it possible to incorporate some kind of credentials if using a remote `api_url`?
