### ISSUE TITLE
Does not autocomplete in Python when using `'` instead of `"` 

### ISSUE THREAD

**Issue by xtanion** [zed-industries/zed#13972]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In python string can be defined by either `"string"` or `'string'`
the later doesn't autocompletes in Zed as of now

### Environment

Mac OS | 14.5 (23F79)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Interesting. Single quote has `close = false` and it's been this way since it was introduce in 34351c0a51cad8f354f628d23a0dc04e4112d04b.
https://github.com/zed-industries/zed/blob/9a6f30fd950d95beba36e5c547d78f2b495dd609/crates/languages/src/python/config.toml#L7-L13

@maxbrunsfeld Was this intentional?

Related: 
- #13998

**Comment by maxbrunsfeld** [comment]
@notpeter thanks for raising that. I do *not* think it was intentional, I probably accidentally kept that from the Rust configuration (in which single ticks are often unpaired). Want to make that change to set `close` to true?

**Comment by notpeter** [comment]
This fix will be in tomorrow's Zed Preview release (v0.144.x) which will end up in Zed stable a week from Wednesday (2024-07-17). Thanks for reporting.
