### ISSUE TITLE
Disable accept completions on Enter

### ISSUE THREAD

**Issue by ghivert** [zed-industries/zed#14065]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi!

When typing some text, completions shows up and display useful documentation and functions. But when you have typed the full text you want, if the completions are still there, pressing `enter` will complete the first proposition. For people used to type quickly, completions can be too slow.
Oftentimes, you have the ability to choose between "Tab" and "Tab + Enter" to accept completions.

I have restored that behaviour by putting

```json
  {
    "context": "Editor && showing_completions",
    "bindings": {
      "enter": "editor::Newline"
    }
  }
```

In keybindings, but I think having a toggle in the settings would be a huge gain, instead of having to search across the web to understand how to disable the keybinding. 🙂

**Comment by notpeter** [comment]
You have discovered the correct way to workaround this.

The default action for `enter` in the global context is `menu::Confirm`:
https://github.com/zed-industries/zed/blob/5bb18adbe86edbe368676f9ed3131a9982522b0c/assets/keymaps/default-macos.json#L19

And so you've added binding at a more specific context which overrides this:
```json
  {
    "context": "Editor && showing_completions",
    "bindings": {
      "enter": "editor::Newline"
    }
  }
```

We generally would avoid adding a settings that alters the keymap in a way that is not visible to the user.  The existing complexity of default-macos.json + jetbrains.json + vim.json + ~/.zed/keymap.json combined with overlapping contexts is already quite a bit.

That said, there have been internal design discussion about how to improve visibility around commonly desired key remappings and the ability to pick and choose from a menu of options (e.g. instead of forcing users to adopt an entire new keymap layer (e.g. SublimeText, JetBrains, Atom, etc) or manually write a json object with context, allow choosing "make shift-shift behave like jetbrains" or in this case "use an alternate key for accepting completions".

Anyways, this is a long way of saying, we're are unlikely to implement this enhancement request and so I'm going to close. 

Thanks for reporting and documenting a work around.
