### ISSUE TITLE
Zig Extension doesn't indent when creating a block

### ISSUE THREAD

**Issue by Peeda** [zed-industries/zed#14140]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When typing a block by typing { followed by enter, the following line isn't indented when using the zig extension. This behavior isn't present in other languages with Zed. If it helps, I have path lookup set to true for zls, since without it zed couldn't install zls.

### Environment

Zed: v0.145.0 (Zed Dev 5bc3846d592dc7e9acb81f709cc7257ae594bc77)
OS: Linux Wayland fedora 40
Memory: 7.1 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[Screencast_20240711_000701.webm](https://github.com/zed-industries/zed/assets/107806301/80f2a5eb-853b-4787-a1c3-a28eed277403)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-11T00:07:29-04:00 [INFO] Initializing default prettier with plugins {}
2024-07-11T00:07:29-04:00 [INFO] starting language servers for Zig: zls
</pre></details>

**Comment by notpeter** [comment]
I think the zig [idents.scm](https://github.com/zed-industries/zed/blob/main/extensions/zig/languages/zig/indents.scm) just needs a little love here.

I tried the following and got indent working as expected.
<img width="574" alt="Screenshot 2024-07-11 at 1 33 53" src="https://github.com/zed-industries/zed/assets/145113/575a52f5-457f-4da8-86ef-aee67e4302a2">

I'll see what I can do.

**Comment by Peeda** [comment]
I've edited this file and ran the install script again but nothing seems to have changed, is there something I need to do to rebuild the extension?

**Comment by notpeter** [comment]
Yeah, you have to use `install dev extension` and navigate to the `extensions/zig` folder.
<img width="654" alt="Screenshot 2024-07-11 at 11 22 42" src="https://github.com/zed-industries/zed/assets/145113/5343e182-d885-4016-9e0d-cfb0efd4b09d">

**Comment by Peeda** [comment]
Gotcha, seems to be working for the most part now

**Comment by GildedHonour** [comment]
Where's this zig extension? How to install it? Isn't there built-in support of Zig?

**Comment by notpeter** [comment]
> Where's this zig extension? How to install it? Isn't there built-in support of Zig?

Yes. Zig support is "built in" but internally it's implemented as an extension.  You install it like a normal extension via the extensions panel (cmd+shift+x).  If you want to improve an extension (like the changes I was testing above) you just checkout the zed repo, make your changes and then click "install dev extension" in the extensions panel and point it at `zed/extensions/zig` where you made your changes.

Source code is in the main zed repo here:
- https://github.com/zed-industries/zed/tree/main/extensions/zig

I've pushed a PR which fixes the indent for all three of the examples you provided (if statement, function statement, bare block `{}`).  The bare block still does not work if it is the first character in the file, but otherwise acts as expected.  Happy to accept PRs.

This will be available in next week's Zed Preview (2024-07-14) and the following week in Zed Stable (2024-07-21).  Thanks for reporting!
