### ISSUE TITLE
Simple jupyter kernel doesn't work correctly

### ISSUE THREAD

**Issue by sigmaSd** [zed-industries/zed#14146]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have a simple jupyter kernel, that works in vscode/jupyter

In zed, repl run works the first time, then it only shows Queued

here is the do_execute override

```py
def do_execute(self, code, silent, store_history=True, user_expressions=None, allow_stdin=False):
        # Send the first JSON object to the process's standard input
        code_object = {"code": code}
        json_code = json.dumps(code_object)
        self.re.stdin.write(json_code.encode("utf-8"))
        self.re.stdin.write(b"\n")
        self.re.stdin.flush()

        # Read the first JSON object from the process's standard output
        json_result = self.re.stdout.readline().decode("utf-8")
        action_type = json.loads(json_result)

        if "Eval" in action_type:
            action = action_type["Eval"]
            self.send_response(self.iopub_socket, 'display_data', {
                'metadata': {},
                'data': {
                    action["mime_type"]: action["value"]
                }
            })

        return {'status': 'ok',
                'execution_count': self.execution_count,
                'payload': [],
                'user_expressions': {},
               }
```

I also tried the EchoKernel example from https://jupyter-client.readthedocs.io/en/latest/wrapperkernels.html and it errors as well, although with a different error, it doesn't connect at all

@rgbkrk would be great if you take a look

### Environment

Zed: v0.145.0 (Zed Nightly 07dc4050bf305882860d25957d5dd614cc2bc60b)
OS: Linux Wayland fedora 40
Memory: 7.6 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by rgbkrk** [comment]
Thanks for reporting this. I _think_ this is a case where we're waiting for a shell reply and so no other shell requests go out.

**Comment by rgbkrk** [comment]
For the moment, we're reliant on the kernelspecs having a `language` field in the kernelspec in order to detect if they can be run. For the sake of the echo kernel I've set the language to `plain text` so that I can open it on `.txt` files.

Using this kernelspec:

```json
{
  "argv": [
    "python",
    "-m",
    "/Users/kylekelley/code/src/github.com/zed-industries/echokernel/echokernel.py",
    "-f",
    "{connection_file}"
  ],
  "display_name": "Echo",
  "language": "plain text"
}
```

I was able to reproduce #14090 since I got an error launching the kernel where this error ended up in the logs rather than something visible to the user:

```
/Users/kylekelley/.pyenv/versions/3.11.7/bin/python: Error while finding module specification for '/Users/kylekelley/code/src/github.com/zed-industries/echokernel/echokernel.py' (ModuleNotFoundError: No module named '/Users/kylekelley/code/src/github'). Try using '/Users/kylekelley/code/src/github.com/zed-industries/echokernel/echokernel' instead of '/Users/kylekelley/code/src/github.com/zed-industries/echokernel/echokernel.py' as the module name.
```

After fixing up the kernelspec (using the echo kernel repo directly), I was able to reproduce this.

<img width="169" alt="image" src="https://github.com/user-attachments/assets/0d5aa094-3931-4b4c-80a9-1a1fdb616d23">

I'll see what I can figure out next!

**Comment by rgbkrk** [comment]
This bug is the same as the one I've experienced with the Ark (R) kernel, where we're stuck waiting for a `kernel_info_reply` before we can send any other shell messages. There's a bit of an architecture issue with the underlying library that I'll need to address (https://github.com/zeromq/zmq.rs/pull/194). For the time being, I'm going to timeout waiting for replies and likely just not bother waiting for them (for now).

**Comment by rgbkrk** [comment]
Ok I've opted to just not send `KernelInfoRequest` as a temporary fix. All is working well with the echo kernel. What's the kernel you were using I should also try this with @sigmaSd?

**Comment by rgbkrk** [comment]
Try this out again with your kernel on Nightly when you get a chance.

**Comment by sigmaSd** [comment]
Thanks @rgbkrk it works now, here is the kernel https://github.com/sigmaSd/IRust/blob/master/crates/irust_repl/irust_kernel/irust_kernel/kernel.py
