### ISSUE TITLE
CTRL+W closes terminal instead of removing word

### ISSUE THREAD

**Issue by keks** [zed-industries/zed#14160]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I am in the terminal and press CTRL+W, the terminal closes. I would have expected that the word before the cursor gets removed, as it does in basically every other terminal.

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 30.7 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Interesting, in https://github.com/zed-industries/zed/pull/13263 we configured it such that `ctrl-w` in terminal will not close the terminal and will send a ctrl-w keystroke.

https://github.com/zed-industries/zed/blob/489077befcc1ac4e1aa4505fa3f27f1a6528da48/assets/keymaps/default-linux.json#L252-L257

This is definitely working for someone else on Linux, because here they are requesting the opposite -- they wish ctrl-w closed the window and instead it's getting passed to the terminal: 
- https://github.com/zed-industries/zed/issues/14369

Just to be clear, your title/description have an uppercase W.  Are you typing to `ctrl-w` or `ctrl-shift-w`?

Are there any details that you can imagine that might be factors here? Alternate keyboard layout, etc?

**Comment by notpeter** [comment]
@keks Can you edit the environment (Zed version) in your description? There is no Zed 1.0.0 nor Linux 1.0.0, where did this come from?  You can get this in zed with `zed: copy system specs into clipboard` from the command palette (ctrl-shift-p).

**Comment by keks** [comment]
Hm, that is exactly what I did. I installed from my Manjaros repos, it's possible that they broke this somehow... I'll check there for now!
