### ISSUE TITLE
Settings discoverability

### ISSUE THREAD

**Issue by mhanuszh** [zed-industries/zed#14224]
### Check for existing issues

- [X] Completed

### Describe the feature

As a new user, one of the largest cause of friction is the discoverability of the settings.

Zed needs some kind of settings search. Or even better: all settings should be modifiable from the command palette.

An extremely useful QoL feature would be fuzzy searching. Here is an example as a reason for using multiple synonyms for a setting or command: microsoft/vscode#89292

**Comment by notpeter** [comment]
Yeah, there's definitely room from improvement here. Launching `zed: open default settings` from the command palette is not the most accessible thing.

You can also see our defaults in your web browser: [assets/settings/default.json](https://github.com/zed-industries/zed/blob/main/assets/settings/default.json).

Similarly the default keymap are good for discovery too: [assets/keymaps](https://github.com/zed-industries/zed/tree/main/assets/keymaps)

**Comment by notpeter** [comment]
Hi @mhanuszh, 

There has been significant internal research and prototyping around settings management, searchability and discoverability, but it has not yet been prioritized.  Since there is nothing particularly actionable in this request (e.g. if someone opened a PR with a settings search we would be very unlikely to merge it) I'm going to go ahead and close. 

Thanks for reporting!
