### ISSUE TITLE
regex replacement text fails when using an underscore immediately following a capture group

### ISSUE THREAD

**Issue by icylace** [zed-industries/zed#14298]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Create a new file (`cmd-t`).
2. Enter some text, like "foo", for example.
3. Open the search-and-replace panel (`cmd-alt-f`).
4. Toggle on searching by regular expression (`cmd-alt-x`).
5. Use `(.*)` as the search text.
6. Use `$1_` as the replacement text.
7. Execute the search-and-replace operation.

If the text was originally "foo", then the expected result is "foo_". However, the actual result is the removal of "foo".

### Environment

Zed: v0.144.2 (Zed Preview)
OS: macOS 13.6.7
Memory: 64 GiB
Architecture: x86_64

**Comment by notpeter** [comment]
You can use `${1}` instead of `$1` and it will work.

FYI we also support named capture groups too:
<img width="668" alt="Screenshot 2024-07-12 at 18 35 29" src="https://github.com/user-attachments/assets/48ce5d3f-9118-48a5-9d96-a78cd62960ce">

**Comment by 0x822a5b87** [comment]
I've encountered the same problem, the replacing behavior not as expected when using regex match groups with a **underscore** following behind the match group in the replacement string. And I'm rest assured that this error is caused by a BUG in Rust regex crate - [Underscore in replacement string treated as backspace](https://github.com/rust-lang/regex/issues/69)

The workaround you mentioned does fix the error, but I find it somewaht trivial and error-producing. For me, it took me about 2 or 3 hours to find this solution.

Is there any chance to fix it by replacing `$\d+_` with `${\d+}_` on the **Replacement Pattern** before executing the actual replacement?

For example:

```Rust
extern crate regex;

use regex::Regex;

fn main() {
    let re = Regex::new(r"\$(\d+)_").unwrap();
    let text = r"$1_ and $20_ are examples.";

    let replaced_text = re.replace_all(text, |caps: &regex::Captures| {
        let num = caps.get(1).unwrap().as_str();
        format!("${{{}}}_", num)
    });

    println!("{}", text);
    println!("{}", replaced_text);
}
```

The program will replace `$1_` with `${1}_` and replace `$20_` with `${20}_`. Here is the output message from the program:

```
$1_ and $20_ are examples.
${1}_ and ${20}_ are examples.
```

I'm not proficient in the Rust Programming Language and Regex. There may be too many tasks that I'm not taking into account, but I'm pretty sure that fixing it through this method is a significant improvement in user experience.
