### ISSUE TITLE
Zed uninstall script just like installation script (linux)

### ISSUE THREAD

**Issue by sidharthpunathil** [zed-industries/zed#14306]
### Check for existing issues

- [X] Completed

### Describe the feature

```
Note: Zed is just awesome! 
```
* Zed installation: `curl https://zed.dev/install.sh | sh`

* Was hoping there would be something to uninstall zed eg.  `curl https://zed.dev/uninstall.sh | sh`

#### Why?
* Tried to install zed from AUR and now I  have 2 zed executable

**Comment by aintnodev** [comment]
I ran the following commands to uninstall (what I've understood from [`install.sh`](https://zed.dev/install.sh)):
```sh
rm -rf $HOME/.local/zed.app
rm -rf $HOME/.local/bin/zed
rm -rf $HOME/.local/share/zed
```
As zed is now available on [Arch](https://archlinux.org/packages/extra/x86_64/zed/) so i thought it would be a good idea to just install it from there.

**Comment by aintnodev** [comment]
> I ran the following commands to uninstall (what I've understood from [`install.sh`](https://zed.dev/install.sh)):
> 
> ```shell
> rm -rf $HOME/.local/zed.app
> rm -rf $HOME/.local/bin/zed
> rm -rf $HOME/.local/share/zed
> ```
> 
> As zed is now available on [Arch](https://archlinux.org/packages/extra/x86_64/zed/) so i thought it would be a good idea to just install it from there.

Run `rm -rf $HOME/.local/share/applications/dev.zed.Zed.desktop` to remove `.desktop` file as well however as you already have an AUR package installed so you may not want to remove the `.desktop` file.

**Comment by Gambloide** [comment]
I built the Flatpak version ~24 hours before general availability of Linux builds was announced and also identified these folders which I deleted:

```
rm -rf $HOME/.var/app/dev.zed.Zed-Dev/
rm -rf $HOME/.local/share/flatpak/app/dev.zed.Zed-Dev/
```

**Comment by amithm7** [comment]
Devs don't want to merge the PR but this should work till a better solution comes:

```sh
curl https://raw.githubusercontent.com/zed-industries/zed/82ad7f2b/script/install.sh | sh -s uninstall
```

**Comment by carlosfernandezcabrero** [comment]
for remove the meny entry:
```
rm -rfv $HOME/.local/share/applications/dev.zed.Zed.desktop
```

**Comment by SomeoneToIgnore** [comment]
It's a bit ironic and borderline funny how this issue's lifespan is closing half of a year, but there was exactly one attempt to fix it and it missed the point.
Yet, so much noise here and [there](https://github.com/zed-industries/zed/discussions/14267) had been generated...

I still hope Linux skills include bash script writing, so the issue seems to be with the "point", let's clarify that:

* https://github.com/zed-industries/zed/pull/16660 was close (but seem to have missed the desktop entry at least) so that could be taken as a base
* the script has to be bundled with the Zed distro: we cannot guarantee that people update their Zed's timely and any remote script maygo out of sync with the real state due to this
* only Zed's bundling procedure has to be affected, other packaging systems know what they are doing and are capable of uninstalling themselves
* the script has to be a totally separate one, and called `uninstall.sh` or something
* and to be POSIX-compatible, as there's so many Linux flavors with odd set-ups
* it's a good idea to mention the uninstall script in the bundling script, to reduce chances of people forgetting to update that
* and please actually test that it works, otherwise it would be embarassing

**Comment by amithm7** [comment]
@SomeoneToIgnore

> https://github.com/zed-industries/zed/pull/16660 was close (but seem to have missed the desktop entry at least) so that could be taken as a base

Don't lie. It did NOT miss [desktop entry](https://github.com/zed-industries/zed/pull/16660/files#diff-08b624c4cf3301c03903fe40d86af08880f095510e2858cf6b0fb3cf2a71c770R146).

> the script has to be a totally separate one, and called uninstall.sh or something

Even if this need is for the UX, `uninstall.sh` can just call `curl https://zed.dev/install.sh | sh -s uninstall`.

---

Bloating machines with software they don't want won't do you any good in the long run.
