### ISSUE TITLE
Terminal doesn't close on ctrl+` or ctrl+w on Linux

### ISSUE THREAD

**Issue by yorunoken** [zed-industries/zed#14369]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The terminal inside of Zed doesn't close itself when I click ctrl+w or ctrl+` with the terminal focused.
I can, however, close it using middle click or click the "x" icon right next to the terminal's name

### Environment

Zed: v0.143.6 (Zed)
OS: Linux Wayland arch unknown
Memory: 15.5 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Hi, thanks for reporting.

Both of these are intentional although somewhat confusing.  We've opted to pass `ctrl-w` directly to the terminal because it's a relatively common command for emacs users (`ctrl-w` is kill region and `ctrl-x ctrl-w` is Save As.

We also have a slightly different behavior for ``ctrl-` `` than VSCode.  We use it to toggle focus between the terminal and the editor pane, but VSCode uses it to toggle focus and hide the bottom dock. If you want this behavior it's easily enough to define a custom keybind for it.

Here's an example keymap.json (`ctrl-shift-p`, `zed: open keymap`) which I think gives you the behavior I think you're expecting:

```json
[
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-w": "pane::CloseActiveItem", // Don't pass ctrl-w to terminal, let Zed handle it.
      "ctrl-`": "workspace::ToggleBottomDock" // match vscode behavior
    }
  }
]
```
  
Let me know me know if that works. Thanks

**Comment by yorunoken** [comment]
cool, thank you!

**Comment by ExplodingCabbage** [comment]
Man, this kind of sucks as a brand new user trying to explore Zed and figure out the shortcuts, because when CTRL-W doesn't work as you'd expect and you go into the right-click context menu for the terminal tab, it appears to tell you that CTRL-W *is* in fact the shortcut you need...

![image](https://github.com/user-attachments/assets/2198f7bc-5f03-4947-a8b2-5b21ce2eaf60)

... and then when you check the default keymap, the first occurrence of `ctrl-w` you find seems to confirm this:

![image](https://github.com/user-attachments/assets/a5b7ab9b-e6fd-4e7d-973e-277d9d0a68f6)

Maybe this wouldn't mislead someone with a deep understanding of how Zed's contexts work, but it was very misleading to me!

I *guess* the nuance here is that when I'm in the screenshotted menu, I'm in "pane" context but not "terminal" context, and so the usual "pane" context shortcuts apply, but when I've actually got the terminal itself focused (and not just the pane containing the terminal) I'm in "terminal" context and the terminal-specific overrides for CTRL-W and CTRL-SHIFT-W apply. Okay, fine, I guess, but I wonder if there's a way of changing this that would make this more discoverable to a new user without having to google and find this particular GitHub issue to understand what's going on.

(I don't have any good suggestions yet, or else I'd open an issue and maybe a PR proposing them. Am just noting that the status quo is a bad, confusing experience for a new user exploring the editor.)

**Comment by adsick** [comment]
@notpeter I'd argue on your
> "<kbd>ctrl-\`</kbd>": "workspace::ToggleBottomDock" // match vscode behavior

It's different: let's say that I'm editing the code and the terminal is open. I want to switch to the terminal so I press "<kbd>ctrl-\`</kbd>" as I do in VS Code. What happens is terminal disappearing. Now I need to press it again for it to appear and focus, so no, it's not a "match"

**Comment by notpeter** [comment]
@adsick If you apply the context as suggested in my comment:
```
[
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-w": "pane::CloseActiveItem", // Don't pass ctrl-w to terminal, let Zed handle it.
      "ctrl-`": "workspace::ToggleBottomDock" // match vscode behavior
    }
  }
]
```

It means that everywhere else (e.g. this is `Workspace` context) the default mapping will apply:
https://github.com/zed-industries/zed/blob/f106ea7641c585d31ff9703b270d7f39d602f8ec/assets/keymaps/default-linux.json#L545

So if your focused in the Terminal `` ctrl-` `` will trigger `workspace::ToggleBottomDock`.
And if your not in the Terminal `` ctrl-` `` will trigger `terminal_panel::ToggleFocus"`

I do not see the behavior you're describing, perhaps you pasted just that line into a different context? Opening `dev: Open Key Context View` from the command palette might help you see the current context and which keybinding is being chosen.

**Comment by adsick** [comment]
@notpeter ah, yes this is great!, I used "workspace" context without realization that I can (and should) use `Terminal`.
Thanks for making it clear.

**Comment by sshishov** [comment]
Terminal should not be closed using `ctrl-W` as it does not make sense and I have closed by mistake terminal so many times already.

In VSCode terminal is not closed when you press `ctrl-W` as terminal is closed using `ctrl-D` inside the termianal. At least it is closing it properly with `exit` and there is no process on the background.

How to not propagate `ctrl-W` to terminal as it is closing it for me every time, when I want to close the editor with commit message?

**Comment by MohammedEssehemy** [comment]
> Terminal should not be closed using `ctrl-W` as it does not make sense and I have closed by mistake terminal so many times already.
> 
> In VSCode terminal is not closed when you press `ctrl-W` as terminal is closed using `ctrl-D` inside the termianal. At least it is closing it properly with `exit` and there is no process on the background.
> 
> How to not propagate `ctrl-W` to terminal as it is closing it for me every time, when I want to close the editor with commit message?

You can simply disable this behaviour by assigning empty action to this key binding when context is terminal

```json
{
    "context": "Terminal",
    "bindings": {
      "ctrl-w": null
    }
}
```
