### ISSUE TITLE
Default Linux keybinding for forward is incorrect / non-conventional

### ISSUE THREAD

**Issue by MatthewScholefield** [zed-industries/zed#14418]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The default keybinding for `pane::GoForward` is `ctrl-alt-shift--` ([code ref](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-linux.json#L330)) but on my system this combination is impossible and instead needs to be written as `ctrl-alt-shift-_` (because shift changes the hyphen to underscore and Zed must be interpreting the shortcut like that).

Adding the following to `keymap.json` fixes the issue:
```json
[
    {
        "context": "Pane",
        "bindings": {
            "ctrl-alt-shift-_": "pane::GoForward"
        }
    }
]
```

### Environment

Zed: v0.143.7 (Zed)
OS: Linux Wayland fedora 40
Memory: 14.8 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I caused this regression in https://github.com/zed-industries/zed/pull/13946. Funnily enough a few days later I woke up in the middle of the night and out of nowhere thought "Someone is going to have a bad time on a keyboard where `_` isn't over `-`."  Thanks for reporting.

Fixed in: 
- https://github.com/zed-industries/zed/pull/14570
