### ISSUE TITLE
Delay in listing files while opening remote folders 

### ISSUE THREAD

**Issue by vinod4dev** [zed-industries/zed#14431]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

 While opening remote folders   on the  zed  tree , it does-not show folder contents immediately if folders are nested deep. Understandably this is due to network lag . It just opens the folder  without listing files ,which gives an impression that there are no files under the folder .

Some sort of indicator would be useful to suggest that folder is being opened  

### Environment

Linux -  Debian 12.6 

May be applicable to all environments

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Some sort of indicator would be useful to suggest that the folder is being opened  

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by bennetbo** [comment]
In the latest preview release we changed the way how remoting works quite significantly (https://zed.dev/docs/remote-development). We now connect via SSH directly to the remote machine, instead of going through the collab server, so latencies should be much better now. Feel free to re-open if you can still reproduce the issue
