### ISSUE TITLE
URLs in terminal is not clickable if link contains question mark

### ISSUE THREAD

**Issue by gjask** [zed-industries/zed#14500]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. open terminal in zed on linux
2. `git push remote branch` to gitlab
3. gitlab will respond with link to create new MR which terminal doesn't allow (recognize) to be clicked

### Environment

Zed: v0.143.7 (Zed)
OS: Linux Wayland fedora 40
Memory: 14.9 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![obrazek](https://github.com/user-attachments/assets/7be97a1d-4032-4457-a18d-6a134d64337f)

**Comment by notpeter** [comment]
If you hold ctrl the link should become a hyperlink.
On MacOS, cmd is the key that does this.

**Comment by gjask** [comment]
It still doesn't work not even with any of <kbd>Ctrl</kbd> keys pressed.

**Comment by gjask** [comment]
To be completely clear, some links in terminal work for me. This one doesn't.

**Comment by notpeter** [comment]
I can reproduce this issue.  Links which contain a question mark are no converted to hyper links. 

Reproduction steps: 
1. In terminal paste `echo https://www.google.com/search?q=hi` and press enter
2. Hover over the output holding ctrl (linux) or cmd (mac)
3. No Hyperlink

**Comment by bbb651** [comment]
I found the problem, the [url regex](https://github.com/zed-industries/zed/blob/1ea363b0200d3d796f38dc6ea75ac3deb188d102/crates/terminal/src/terminal.rs#L429) is perfectly fine and matches the url as intended, but the [word regex](https://github.com/zed-industries/zed/blob/1ea363b0200d3d796f38dc6ea75ac3deb188d102/crates/terminal/src/terminal.rs#L430) doesn't match `?` and `=`, and for some reason [the word regex is matched before the url](https://github.com/zed-industries/zed/blob/1ea363b0200d3d796f38dc6ea75ac3deb188d102/crates/terminal/src/terminal.rs#L844) - I went through the entire git of `word_regex` up to [this commit that introduced it](https://github.com/zed-industries/zed/commit/75d900704eb838ea2e07f90f012e4871049b398c) and I still cannot understand it's purpose, especially as it does not agree with alacrity about what a word is since double click word selection works with an entirely different logic (e.g. `:` breaks apart words, but `?` and `=` doesn't, which makes sense as `:` is often used as a delimiter).
There has been many commits adding more and more characters to make it this "url or path matcher". I think it should just be replaced with separate path and url matchers, or at least be renamed and be properly defined because "word" is not the right word (especially as paths can contain spaces, currently this is not handled at all).

**Comment by prfj** [comment]
Any feedback on this ?

This negative impacts Zed experience when working with Git push using bitbucket, gitlab and others


Example after push
```
remote:
remote: View pull request for feature/xxx => master:
remote:   https://bitbucket.org/project/repo/pull-requests/1?t=1
remote:
```

results on unclickable link

**Comment by gjask** [comment]
This issue seems to be wrongly categorized as a support issue. So maybe that is why it is not reaching devs.

**Comment by hovsater** [comment]
I can re-produce this as well, so I went ahead and updated the labels accordingly.

**Comment by notpeter** [comment]
I can no longer reproduce this and I believe it has been fixed, likely as part of:
- https://github.com/zed-industries/zed/pull/19004

Thanks for reporting!
