### ISSUE TITLE
clangd lsp version setting

### ISSUE THREAD

**Issue by MichalCiechanowski** [zed-industries/zed#14640]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Default clangd lsp seams to be set on well default, I wish to change that so my lsp will not show me errors from old standard version, because when i compile it with 
```clang++ -std=c++2b -Wall``` 
there are no errors but just with 
```clang++ -Wall```
 I get same errors that I get from lsp.

### Environment

System Version: macOS 14.5 (23F79)
Zed 0.143.7

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1912" alt="image" src="https://github.com/user-attachments/assets/1e2ff7d0-aece-484e-9521-ef6388e47919">
<img width="438" alt="image" src="https://github.com/user-attachments/assets/6c4ba61c-5c39-4c86-9d62-63bf3d783cb7">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jansol** [comment]
If you use cmake or meson or such to generate your build files you can instruct it to also generate a `compile_commands.json` that describes the compiler flags needed for each file. If that is not a sensible solution for your case, you can add a `.clangd` to the workspace root directory to define them instead: <https://clangd.llvm.org/config.html#compileflags>

**Comment by jansol** [comment]
Yes, and both the `compile_commands.json` and `.clangd` files are used to tell clangd what compiler flags your code is meant to be compiled with, so it can adjust its warnings/errors accordingly. This includes `-std=c++2b` or whatnot for setting the standard version you want to target.

If you want to set the default standard for clangd globally rather than separately for individual projects you can also put a configuration file for clangd in `~/Library/Preferences/clangd/config.yaml`: https://clangd.llvm.org/config.html#files

Alternatively you can configure zed to send the flags to clangd via `initializationOptions.fallbackFlags`: https://clangd.llvm.org/extensions#compilation-commands

**Comment by MichalCiechanowski** [comment]
ok it works thank you for help

Solution:
create file ```~/.clangd``` with this code 
``` 
CompileFlags:
  Add: [-std=c++2b, -Wall, -Wno-missing-prototypes]
```

**Comment by notpeter** [comment]
> Solution: create file `~/.clangd` with this code
> 
> ```
> CompileFlags:
>   Add: [-std=c++2b, -Wall, -Wno-missing-prototypes]
> ```

For anyone finding this in the future, you should put individual `.clangd` files inside projects and likely putting one in your home directory.  I believe clangd does not explicitly search `~/` but instead searches parent directories of your projects and uses and `.clangd` it finds (so that only works if your project dir is under your home dir).

If you want to provide user (global) clangd settings, I believe the preferred method is via `config.yaml` under:
- Windows: C:\Users\Bob\AppData\Local\clangd\config.yaml
- macOS: ~/Library/Preferences/clangd/config.yaml 
- Linux: ~/.config/clangd/config.yaml

Source: [clangd config files](https://clangd.llvm.org/config#files) docs.
