### ISSUE TITLE
Document keymap context

### ISSUE THREAD

**Issue by bersace** [zed-industries/zed#14718]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi,

Reading https://github.com/zed-industries/zed/blob/main/docs/src/key-bindings.md, I don't find a proper documentation of `"context"` query in keymaps.json. Could you document this ?

My questions:

- What is `mode` ?
- What context when no file are opens ?
- What is `Markdown` ?
- How to know the current context ?
- How to know available shortcut in a context ? Doom Emacs has a bottom drawer showing *next* shortcut.

Regards,
Étienne

**Comment by notpeter** [comment]
Yep. We could use some better documentation around context for keybindings.  Here's a non-exhaustive list of contexts used by the default bindings.

- (no context) == global shortcut
- `Workspace`
- `Pane`
- `ProjectPanel` (left files sidebar)
  - `ProjectPanel && not_editing`
- `Editor`
  - `Editor && mode == full`
    - `Editor && mode == full && inline_completion`
    - `Editor && mode == full && !jupyter`
    - `Editor && mode == full && inline_completion`
  - `Editor && !inline_completion`
  - `Editor && mode == auto_height`
  - `Editor && renaming`
  - `Editor && showing_completions`
  - `Editor && inline_completion && !showing_completions`
  - `Editor && showing_code_actions`
  - `Editor && (showing_code_actions || showing_completions)`
  - `ContextEditor > Editor`
  - `Picker > Editor`
- `BufferSearchBar`
  - `BufferSearchBar && in_replace`
  - `BufferSearchBar && !in_replace > Editor`
- `ProjectSearchBar`
  - `ProjectSearchBar > Editor`
  - `ProjectSearchBar && in_replace > Editor`
  - `ProjectSearchBar && !in_replace`
- `ProjectSearchView`
- `Dock`
- `AssistantPanel`
- `PromptLibrary`
- `Terminal`
- `OutlinePanel`
- `CollabPanel`
  - `CollabPanel && not_editing`
  - `(CollabPanel && editing) > Editor`
- `ChannelModal`
  - `ChannelModal > Picker > Editor`
- `TabSwitcher` (ctrl-tab / ctrl-shift modal)
- `FileFinder` (cmd+p modal "Search project files")
- `Markdown` (markdown preview window)
- `EmptyPane || SharedScreen`

Plus a bunch more in [vim.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/vim.json)

----

> What is mode ?

Editor `mode` can be either `full` or `auto_height`. Full is the normal editor, I believe `auto_height` is during the find in files where you can directly edit the results (in a height constrained space).

> What context when no file are opens ?

If you have no panels in focus, no files open `Workspace` or global (no context) will apply.

> What is Markdown?

Markdown preview.

> How to know the current context ?
> How to know available shortcut in a context ? Doom Emacs has a bottom drawer showing next shortcut.

This would be a useful enhancement.

**Comment by bersace** [comment]
Thanks @notpeter 

`Workspace` also applies if a panel is opened. I want `space space` to trigger `file_finder::Toggle` only if no panel.

Anyway, a documentation on this powerfull feature would be great, e.g. for community to implement #4642 .

Regards,

**Comment by bersace** [comment]
> `Workspace` also applies if a panel is opened. I want `space space` to trigger `file_finder::Toggle` only if no panel.

`EmptyPane` do the trick. Thanks !

**Comment by bersace** [comment]
A primer:

Contextes:
```
AssistantPanel
BufferSearchBar
ChannelModal
CollabPanel
ContextEditor
Dock
Editor
EmptyPane
FileFinder
Markdown
OutlinePanel
Pane
Picker
ProjectPanel
ProjectSearchBar
ProjectSearchView
PromptLibrary
TabSwitcher
Terminal
VimControl
Workspace
```

`vim_mode` values :

```
insert
normal
operator
replace
visual
waiting
```

Context operators:

- `&&`
- `!=`
- `==`
- `>`
- `()`
- `!`
- `||`

Variables:

```
auto_height
editing
full
inline_completion
in_replace
jupyter
menu
mode
not_editing
renaming
showing_code_actions
showing_completions
vim_mode
vim_operator
```

I grepped from keymaps, not Rust.

**Comment by bersace** [comment]
From grepping Rust code:

Identifiers (`key_context.add(...)`, `.key_context(...)`):

```
AssistantPanel
BufferSearchBar
ChannelModal
ChatPanel
child-1
child-2
CollabPanel
ContextEditor
copilot_suggestion
DevServerModal
Editor
EmptyPane
FileFinder
GiveFeedback
GoToLine
inline_completion
in_replace
jupyter
MarkdownPreview
menu
nested
Pane
parent
Picker
ProjectSearchBar
Prompt
PromptLibrary
renaming
SharedScreen
showing_code_actions
showing_completions
TabSwitcher
TasksModal
TextInput
```

Context Key/values (`key_context.set(...)`):

```
mode
extension
```

**Comment by neunato** [comment]
I spent the last few days configuring zed, and have found keybind configuration has some room for improvement :) A few notes:

It took a while to get over the initial confusion of what contexts actually are. do they relate to the mere presence of an element? or does it have to have focus? if one context is active does it deactivate others or do they coexist? is there some hierarchical structure to them? how do they relate to actions, given the similar prefixes? how are keybind conflicts resolved?

Here are my conclusions, please correct me if I'm wrong:
  
-  **context represents the focus location within the cascading hierarchy of graphical elements**
  
-  **the last keybind definition for a key wins**
  
-  **any action can be called from within any context, but not all actions will work from all contexts**
  
-  **when an action for a keybind cannot be applied, it falls back to the previous one**
  
-  **an immediate child of an element can be selected with `Parent > Child`**


One could compare it to the following html and css selectors:


```html
   <div class="Global">
      <div class="Workspace">
         <div class="Pane">
            <div class="BufferSearchBar">
               </div class="Editor">
                  <!-- search -->              <!-- .Workspace > .Pane > .BufferSearchBar > .Editor -->
               </div>
            </div>
            </div class="Editor">
               <!-- buffer -->                 <!-- .Workspace > .Pane > .Editor -->
            </div>
         </div>
      </div>
   </div>
```

It's possible to apply rules `Parent > Child` just like in css, but this is hard to use when the document structure is unknown. Having a non-direct child selector would probably make things easier to use too (like `Workspace > Editor`)

It's possible to specify the same context multiple times, where the last one wins. This can be useful when a command may not succeed to make it fallback to a previous one, see this example:

```jsonc
[{
   "context": "Editor && mode == full",
   "bindings": {
      "f1": "buffer_search::Deploy"          // only gets called if "buffer_search::FocusSearch" fails
   }
},{
   "context": "Editor && mode == full",
   "bindings": {
      "f1": "buffer_search::FocusSearch"     // focus if open, else look for next action
   }
}]
```

Which feels like an anti-pattern, would be nice to have a way of specifying fallback commands. This is how micro deals with it: `"Tab": "Autocomplete|IndentSelection|InsertTab"`.

--------------------

What I would like to see:
- the above explanations present in keybind documentation
- the context hierarchy documented
- the commands documented and accessible with inline completions, to provide an experience similar to settings
- a better way of specifying multiple commands for same key and context
- better organisation in the default keybinds

--------------------

A few observations:
- `Editor && mode == full` vs `Editor && mode == auto_height` actually has nothing to do with multibuffers.
From my testing, it looks like `Editor` includes everything you can type in - from menu and find panel to rename box in sidebar.
   - `mode == full` seems to include any tab (?), including search tab
   - `mode == auto_height` couldn't figure out
- `ProjectSearchView` couldn't figure out

--------------------------------------

And some additional suggestions:
- non-direct child context selector
- replace `in_replace` with a dedicated context, like `BufferSearchBarReplace", as it effectively represents the same thing - what the focused element is
- binding a chain of commands to a key

**Comment by test3211234** [comment]
Hi @neunato. You seem to know how the whole context system works, and I had multiple questions about that. Could you answer them please? Here:

https://github.com/zed-industries/zed/discussions/15401

**Comment by malssid** [comment]
> A primer:
> 
> Contextes:
> 
> ```
> AssistantPanel
> BufferSearchBar
> ChannelModal
> CollabPanel
> ContextEditor
> Dock
> Editor
> EmptyPane
> FileFinder
> Markdown
> OutlinePanel
> Pane
> Picker
> ProjectPanel
> ProjectSearchBar
> ProjectSearchView
> PromptLibrary
> TabSwitcher
> Terminal
> VimControl
> Workspace
> ```
> 
> `vim_mode` values :
> 
> ```
> insert
> normal
> operator
> replace
> visual
> waiting
> ```
> 
> Context operators:
> 
> * `&&`
> * `!=`
> * `==`
> * `>`
> * `()`
> * `!`
> * `||`
> 
> Variables:
> 
> ```
> auto_height
> editing
> full
> inline_completion
> in_replace
> jupyter
> menu
> mode
> not_editing
> renaming
> showing_code_actions
> showing_completions
> vim_mode
> vim_operator
> ```
> 
> I grepped from keymaps, not Rust.

I feel like these variables should be documented somewhere! I had to use the `editing` one here to bind a/A/r inside the ProjectPanel. If I don't use this, I can't actually type these letters in the input box.

```
  { 
    "context": "ProjectPanel && !editing",
    "bindings": { 
      "space e": "workspace::ToggleLeftDock",
      "a": "project_panel::NewFile",
      "A": "project_panel::NewDirectory",
      "r": "project_panel::Rename",
      "d": "project_panel::Delete"
    }
  }
]
```

**Comment by AurevoirXavier** [comment]
> Yep. We could use some better documentation around context for keybindings. Here's a non-exhaustive list of contexts used by the default bindings.
> 
> * (no context) == global shortcut
> * `Workspace`
> * `Pane`
> * `ProjectPanel` (left files sidebar)
>   
>   * `ProjectPanel && not_editing`
> * `Editor`
>   
>   * `Editor && mode == full`
>     
>     * `Editor && mode == full && inline_completion`
>     * `Editor && mode == full && !jupyter`
>     * `Editor && mode == full && inline_completion`
>   * `Editor && !inline_completion`
>   * `Editor && mode == auto_height`
>   * `Editor && renaming`
>   * `Editor && showing_completions`
>   * `Editor && inline_completion && !showing_completions`
>   * `Editor && showing_code_actions`
>   * `Editor && (showing_code_actions || showing_completions)`
>   * `ContextEditor > Editor`
>   * `Picker > Editor`
> * `BufferSearchBar`
>   
>   * `BufferSearchBar && in_replace`
>   * `BufferSearchBar && !in_replace > Editor`
> * `ProjectSearchBar`
>   
>   * `ProjectSearchBar > Editor`
>   * `ProjectSearchBar && in_replace > Editor`
>   * `ProjectSearchBar && !in_replace`
> * `ProjectSearchView`
> * `Dock`
> * `AssistantPanel`
> * `PromptLibrary`
> * `Terminal`
> * `OutlinePanel`
> * `CollabPanel`
>   
>   * `CollabPanel && not_editing`
>   * `(CollabPanel && editing) > Editor`
> * `ChannelModal`
>   
>   * `ChannelModal > Picker > Editor`
> * `TabSwitcher` (ctrl-tab / ctrl-shift modal)
> * `FileFinder` (cmd+p modal "Search project files")
> * `Markdown` (markdown preview window)
> * `EmptyPane || SharedScreen`
> 
> Plus a bunch more in [vim.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/vim.json)
> 
> > What is mode ?
> 
> Editor `mode` can be either `full` or `auto_height`. Full is the normal editor, I believe `auto_height` is during the find in files where you can directly edit the results (in a height constrained space).
> 
> > What context when no file are opens ?
> 
> If you have no panels in focus, no files open `Workspace` or global (no context) will apply.
> 
> > What is Markdown?
> 
> Markdown preview.
> 
> > How to know the current context ?
> > How to know available shortcut in a context ? Doom Emacs has a bottom drawer showing next shortcut.
> 
> This would be a useful enhancement.

<img width="545" alt="image" src="https://github.com/user-attachments/assets/175aa533-244a-4cb3-be7a-e291732d58a7">

Apparently, this document is outdated. `BufferSearchBar` context finally works for me.

**Comment by baptisteArno** [comment]
Yes, same for `Assistant`, I belive now it is `AssistantPanel`

**Comment by baptisteArno** [comment]
I am confused, I thought that this would work for file finder, project finder and buffer list but it's not

```json
{
    "context": "menu",
    "bindings": {
      "ctrl-j": "menu::SelectNext",
      "ctrl-k": "menu::SelectPrev"
    }
  }
```

It works if I remove context. I also tried ProjectSearchBar, BufferSearchBar etc... no context work. I often times am confused about what to insert here and what are the possibilities.

This really need a better documentation because it's most likely a deal breaker compared to the way we can configure Neovim

**Comment by leo91000** [comment]
I have setup some keybinds like this : `Editor && !AssistantPanel && (vim_mode == normal || vim_mode == visual)`

However, when I open the assitant panel, it stills uses this keyind, so the !AssistantPanel does not seems to take effect.

Is it because of cascading rules ?

Is there a way to have keyinds disabled in the assistant panel ?

**Comment by AntonEriksson978** [comment]
Would be super useful if there was a command that would show/print what context you are currently in to make it easier to create your keymaps.

**Comment by notpeter** [comment]
> Would be super useful if there was a command that would show/print what context you are currently in to make it easier to create your keymaps.

Yeah, we could certainly do better here, but I recommend you look at the existing Contexts in [default-linux.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-linux.json) or [default-macos.json]([default-linux.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-macos.json) as a reference.

Because sometimes in addition to knowing your current context (`Root > Workspace > Pane > Editor`) you may want to exclude certain context for mapping. For example :
https://github.com/zed-industries/zed/blob/b83b42b9beba389c3b77eef5f0323b68eff9ea5a/assets/keymaps/default-macos.json#L446-L452

**Comment by andrewbanchich** [comment]
> There has been discussion about building a debug window (like debug: open syntax tree view does for tree-sitter) which displays your GPUI context for keymapping or your syntax highlighting context for themes.

that would be super awesome. confusion about contexts and why some keybindings are not working / being overridden has been by far my biggest pain point in adopting Zed (although that isn't saying much - it's been wonderful with almost everything else).

**Comment by andrewbanchich** [comment]
IMO it would be ideal if we could have a command like `debug: key bindings` which shows the name of the current context, a list of all active `context` values from your custom keybindings + the default ones, and then a list of all values per unique binding / context tuple, e.g.

```json
"currentContext": "ContextC",
"activeContexts": ["ContextB", "ContextC"]
"keys": {
  "ctrl-g": {
    "activeBindings": [
      "ContextB": "bar",
      "ContextC": "baz"
    ]
  }
}
```

if the last one is the winner, then that makes it easy to figure out why it's doing `baz` instead of `bar` / how overrides work.

you can also see `ContextA` is not active at all, which helps explain issues with adding a binding under the wrong context.

**Comment by Apromixately** [comment]
I agree with Andrew. There needs to be some debuggability here. I am trying to remove the cmd-r (which toggles the right dock) with `"cmd-r": null` and adding that to Workspace and Editor did not help.

**Comment by kurtbuilds** [comment]
It'd be a huge huge win to have a way to debug keybindings. Specifically, it would have two bits of functionality:

1. See the current "context" that my cursor is in.
2. See the actions that I just took using existing editor commands / keybindings.

That would make it much easier to rebind keys to the hotkeys that I want. Right now, the context and the keybinding actions are really undiscoverable.

@Apromixately I've seen `null` not working a lot of the time, so I sometimes instead remap to an action that seems to be a no-op, while still being a command. I found `"workspace::Unfollow"` to suit this purpose - I'm not actually sure what it's intended to do.

**Comment by kurtbuilds** [comment]
One thing I'm finding surprising, it seems that `"context": "Editor",` has higher precedence than `"context": "Editor && mode == auto_height",`.

I'm trying to redo how assist/inline assist get opened and submitted, so I had a `cmd-enter` binding in `context: Editor` and overwrote it in `context: Editor && mode == auto_height` to override the value while in the inline_assist window, but that didn't actually work.

I had to move the cmd-enter binding to `context: Editor && mode == full` to eliminate the conflict.

**Comment by kurtbuilds** [comment]
Detailing another issue with key binding resolution:

I'm coming from intellij, where cmd+enter is "open code actions menu". In editor, cmd-enter creates a newline, and in the assistant, cmd-enter submits the query to the assistant. Looking at default macos keybindings, cmd-enter exists in both `Editor && mode == full` and `ContextEditor > Editor` contexts, which the commands you'd expect for this behavior, `EnterNewLine` and `assistant::Assist`, respectively.

Ok, then, I just need a custom keybinding for `Editor && mode == full` to map cmd-enter to `ToggleCodeActions`. I do that, and it works in the editor (good), but it disables any action in the Assistant. Ok, that's weird, but maybe I can fix it by adding an explicit "assistant::Assist" to `ContextEditor > Editor` back again. No, that doesn't do anything. Okay, what about the `AssistantPanel` context instead? No, that also doesn't do anything.

One short-term solution, is it possible to add debug or trace log lines when keybindings are dispatched, so that I can launch Zed with that log level, and see both the context and the command being executed?

**Comment by kurtbuilds** [comment]
> I have setup some keybinds like this : `Editor && !AssistantPanel && (vim_mode == normal || vim_mode == visual)`
> 
> However, when I open the assitant panel, it stills uses this keyind, so the !AssistantPanel does not seems to take effect.
> 
> Is it because of cascading rules ?
> 
> Is there a way to have keyinds disabled in the assistant panel ?

@leo91000 After lots of trial and error, I found that `Editor && mode == full && !(ContextEditor > Editor)` works for "only the main editor". Notably `!AssistantPanel` does not work. Quick explainer for each clause: Editor is a text entry editor (can be inline assistant, the main editor, assistant panel, maybe others). mode == full contrasts with auto_height, which implies the inline assistant, so mode == full means a full height editor (either main editor or assistant panel), and finally `!(ContextEditor > Editor)` excludes the assistant panel. I don't know why, other than a bug that `!AssistantPanel` wouldn't work just as well. I tried `!(AssistantPanel > Editor)` and that also doesn't work.

Quick summary of the rules I've discovered so far, for myself and others:
1. Precedence works based on hierarchy (so Editor beats Workspace), but doesn't appear to work on "narrowing" of any kind, so `Editor && mode == full` *does not beat* `Editor`, and `ContextEditor > Editor` *does not beat* `Editor`.
2. Precedence seems to be hardcoded for system hotkeys like `cmd-o`. I had to create a global keybinding for `cmd-o` instead of creating it at context `Workspace`.
3. `null` doesn't always clear a hotkey, neither does `zed::NoAction`. You can use another no-op action (I use `workspace::Unfollow` - which is what `escape` does) to clear a binding. This seems especially true for system hotkeys like `cmd-o` and `cmd-p`. 

Quick summary of contexts I'm using:
1. `ContextEditor > Editor` is the assistant panel. Using `AssistantPanel` is at best flakey.
2. `Editor && mode == auto_height` is the inline assistant panel.
3. `Editor && mode == full && !(ContextEditor > Editor)` should be your context for the main editor. It excludes code completion menus, the inline assistant, the assistant panel.

Lastly, it's worth noting that the internal keybindings seem to have different precedence rules. The example I described in my previous post is one example. Looking at `cmd-enter`, builtin keybindings have `EnterNewLine` for `Editor && mode == full` and `assistant::Assist` for `ContextEditor > Editor`. However, changing those commands using the same directives doesn't work for user keybindings. I instead have to use `Editor && mode == full && !(ContextEditor > Editor)`, otherwise the bindings conflict.

**Comment by injust** [comment]
The default `ctrl-shift/alt-enter` keybindings for `repl::Run/RunInPlace` use the context `Editor && jupyter && !ContextEditor`.

What's the difference between `!ContextEditor` here vs `!(ContextEditor > Editor)`?

**Comment by lcrownover** [comment]
The lack of clear documentation around contexts is the last thing keeping me from adopting Zed over Neovim for most editing sessions. I use a 99% keyboard-centric workflow and I, for the life of me, can't get some of my simple keybinding cases to work. 

Having a debug window that displays the current context would be immensely helpful, as well as documentation around precedence.

**Comment by opsnull** [comment]
@lcrownover try command "debug: open key context view"，I find it's very helpful to view UI context stack and keybinding matching.
![image](https://github.com/user-attachments/assets/141cf773-28be-4b3d-92d5-0614e70b4361)

**Comment by ConradIrwin** [comment]
Closing this now the documentation is more up-to-date and the debug view exists.

**Comment by KorigamiK** [comment]
I also want to know the meaning of `use_key_equivalents` in the keymaps file as well

**Comment by notpeter** [comment]
> I also want to know the meaning of `use_key_equivalents` in the keymaps file as well

See: https://zed.dev/docs/key-bindings#non-qwerty-keyboards

**Comment by KorigamiK** [comment]
> See: https://zed.dev/docs/key-bindings#non-qwerty-keyboards

got it, thanks!

**Comment by adsick** [comment]
https://zed.dev/docs/key-bindings#contexts doesn't provide exhaustive list of contexts, nor it doesn't link to a place where they are listed, why is this issue closed then? Am I missing something?

**Comment by notpeter** [comment]
@adsick This issue was closed because previously contexts were entirely undocumented.

Currently there is no centralized list of contexts (spread around the code base) so I can't point you at a list and it not yet possible to automatically maintain an generated enumeration of valid contexts and conditional sub-contexts.

In the meantime, the best way to discover contexts is to open `dev: key context view` and click around the app / enter keystrokes to see which mappings apply in a given context.

**Comment by bersace** [comment]
`dev: open key context view` is the best documentation you can have. Pretty neat actually.

**Comment by adsick** [comment]
> `dev: open key context view` is the best documentation you can have. Pretty neat actually.

Yes, that thing is neat
