### ISSUE TITLE
Windows Binary Download Support

### ISSUE THREAD

**Issue by TakumiBC** [zed-industries/zed#14841]
### Check for existing issues

- [X] Completed

### Describe the feature

I am wondering why even though Zed has Windows support, however there wasn't a binary version released.
I've created a workflow using GitHub Actions to automatically compile and generate a installer for Zed on Windows. https://github.com/TakumiBC/zed-windows

**Comment by jansol** [comment]
The reason is that Zed does not have (official) Windows support yet. Just some community contributions towards a port which happens to be usable to ??? degree.

**Comment by JosephTLyons** [comment]
@jansol is correct - if Zed compiles and runs on Windows, its entirely because of the community, as it hasn't been our primary focus yet. Once we make Windows our focus, we will put a large amount of time into making sure things are stable and performant, and then we will support direct downloads.  We don't want to give off the impression that Zed on Windows is stable, so users just have to compile it for now.

**Comment by JosephTLyons** [comment]
I'm going to close this out in favor of:

- https://github.com/zed-industries/zed/issues/5394

We will close that issue out once we are able to confidently say we have something stable running on Windows.

**Comment by A-bnk** [comment]
Hey guys, sorry for commenting on this closed thread. Just wanted to give you a heads up that the binary OP provided, when uploaded to virustotal.com reports that it contains two malware. I am by no means an expert in the cyberspace and I am not saying that there is a malicious intend behind OPs action I just wanted to know if it really is safe to install, or maybe its a false positive?
![image](https://github.com/user-attachments/assets/c49c6a89-1af1-4a87-9843-9e11ccd54025)

**Comment by TakumiBC** [comment]
I believe it's an error. The full compile process is open-sourced, you can also run the github actions workflow by your own if you want.
