### ISSUE TITLE
On Linux  `--version` flag doesn't return version number but path to binary

### ISSUE THREAD

**Issue by hammadmajid** [zed-industries/zed#14859]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On Arch linux (possibly other distros as well) running the command `zeditor --version` doesn't return version number as expected but path to zed binary instead (see screenshot below).

### Environment

Zed: v0.144.4 (Zed)
OS: Linux Wayland arch unknown
Memory: 7.6 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/d136238d-85ae-4667-8883-300b30d04191)

**Comment by nt8r** [comment]
This string comes from `cli/src/main.rs`:
```rust
    impl InstalledApp for App {
        fn zed_version_string(&self) -> String {
            format!(
                "Zed {}{} – {}",
                if *RELEASE_CHANNEL == "stable" {
                    "".to_string()
                } else {
                    format!(" {} ", *RELEASE_CHANNEL)
                },
                option_env!("RELEASE_VERSION").unwrap_or_default(),
                self.0.display(),
            )
        }
```

I suppose `RELEASE_VERSION` is used instead of `CARGO_PKG_VERSION` because the cli crate is versioned independently (and is on 0.1.0) but should report the version of the `zed` crate. The `RELEASE_VERSION` environment variable is only set by the `bundle-linux` script, not a normal Cargo build, and the Arch package [does a normal Cargo build](https://gitlab.archlinux.org/archlinux/packaging/packages/zed/-/blob/main/PKGBUILD?ref_type=heads#L63).

I think it would be more reasonable to have a `build.rs` for the `cli` crate inject this variable, instead of expecting an external wrapper script to do it and silently producing builds that don't know their version otherwise.

**Comment by notpeter** [comment]
I believe this is an Arch packaging issue and so have reported it upstream.

https://gitlab.archlinux.org/archlinux/packaging/packages/zed/-/issues/3

**Comment by alerque** [comment]
Upstream packager for the Arch Linux `zed` package here...

Thanks for the nice upstream bug report with specific suggestions for how to fix them. I've got those fixes building now, it should go out to package repositories soon.

As for the build method, yes we're hand tooling our own build rather than using the `bundle-linux` script because we *don't want to* do about ⅔ of what is in that script. We don't need some of the things it does, we want our own system paths and binary stripping (which includes generating debug symbols packages automatically), and so forth. At the end of the day we're trying to build and install, not "bundle a release".

I would definitely suggest moving the version handling and other things that always need handling out of the scripts and into `build.rs` or a more universal script that could be used by distros. This will also affect the ability to install directly from crates.io. Obviously you haven't published there yet, but working out these little glitches will enable that. It will also enable installation directly from the Git repo and many other potential niceties like easily setting up a Nix Flake.

**Comment by alerque** [comment]
I think you can close this issue now. Arch packages have been updated:

```console
$  pacman -Q zed
zed 0.146.5-2
$ zeditor --version
Zed 0.146.5 – /usr/lib/zed/zed-editor
```

![image](https://github.com/user-attachments/assets/0fbc0cd3-df69-4e71-a6ff-637796c46ce3)

![image](https://github.com/user-attachments/assets/cdcc9584-6fb2-415f-9900-e54bd8cc3857)

As well as the official package, the `zed-preview` and `zed-git` packages in the AUR are getting the same fixes.
