### ISSUE TITLE
' should has autocomplete

### ISSUE THREAD

**Issue by Tahinli** [zed-industries/zed#14878]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi, as you know characters like ", [, {, ( have autocomplete. I think ' also needs to be autocompleted by default.

### If applicable, add mockups / screenshots to help present your vision of the feature

' ' pair have been using by developer with chars in many language and sometimes for strings as well. This should be autocompleted.

**Comment by xtanion** [comment]
I think it's been fixed in the recent release #14014

**Comment by Tahinli** [comment]
> I think it's been fixed in the recent release #14014

it may fix for Python but I tried in Rust it's not working. I think it should work for every language from assembly to javascript. It always has a use case.

**Comment by SomeoneToIgnore** [comment]
For Rust, the problem here is the fact that in certain cases, you do not want another `'` automatically inserted, I would find the `for<''`, `enum Foo<''`, `fn something<A: Debug + ''` and many other cases like 
```Rust
) -> ToggleElement
            + '',
```

```Rust
where
        F: Fn(bool, &mut V, &mut ViewContext<V>) + '',
```

unacceptable.

If anybody wants to work on that, current approach in Zed is to add a declaration similar to

https://github.com/zed-industries/zed/blob/cd9b25d82728d2c8f2537db3ceccc5e211e8146e/crates/languages/src/c/config.toml#L10-L11

into the corresponding Rust-language related config and define what `string`, `comment` and other `not_in` things are in 

https://github.com/zed-industries/zed/blob/cd9b25d82728d2c8f2537db3ceccc5e211e8146e/crates/languages/src/c/overrides.scm#L1-L3

I'm not certain that it's the most straightforward way in case of Rust and _maybe_ it's better to add an `only_in` definition into 

https://github.com/zed-industries/zed/blob/cd9b25d82728d2c8f2537db3ceccc5e211e8146e/crates/language/src/language.rs#L769-L776

instead, and add a logic for that on Zed side but that can be also hard.

On top of that, there's a possibility for current tree-sitter-rust library to have bugs where it might detect scopes differently and not parse a certain not-yet-finished code good enough to be captured into the scopes — most probably it will work in most cases, but would be good to consider.

------------

That was one language, and not sure about the other languages, but in some of them there could be similar reasons to avoid autocompletion of `'`.

**Comment by Tahinli** [comment]
> For Rust, the problem here is the fact that in certain cases, you do not want another `'` automatically inserted, I would find the `for<''`, `enum Foo<''`, `fn something<A: Debug + ''` and many other cases like
> 
> ```rust
> ) -> ToggleElement
>             + '',
> ```
> 
> ```rust
> where
>         F: Fn(bool, &mut V, &mut ViewContext<V>) + '',
> ```
> 
> unacceptable.
> 
> If anybody wants to work on that, current approach in Zed is to add a declaration similar to
> 
> https://github.com/zed-industries/zed/blob/cd9b25d82728d2c8f2537db3ceccc5e211e8146e/crates/languages/src/c/config.toml#L10-L11
> 
> into the corresponding Rust-language related config and define what `string`, `comment` and other `not_in` things are in
> 
> https://github.com/zed-industries/zed/blob/cd9b25d82728d2c8f2537db3ceccc5e211e8146e/crates/languages/src/c/overrides.scm#L1-L3
> 
> I'm not certain that it's the most straightforward way in case of Rust and _maybe_ it's better to add an `only_in` definition into
> 
> https://github.com/zed-industries/zed/blob/cd9b25d82728d2c8f2537db3ceccc5e211e8146e/crates/language/src/language.rs#L769-L776
> 
> instead, and add a logic for that on Zed side but that can be also hard.
> 
> On top of that, there's a possibility for current tree-sitter-rust library to have bugs where it might detect scopes differently and not parse a certain not-yet-finished code good enough to be captured into the scopes — most probably it will work in most cases, but would be good to consider.
> 
> That was one language, and not sure about the other languages, but in some of them there could be similar reasons to avoid autocompletion of `'`.

yeah sorry I completely forgot lifetime and focused on char. Thanks for reminding.
