### ISSUE TITLE
add `"go.testFlags": ["-v"],` like vscode to output log for go test

### ISSUE THREAD

**Issue by aohanhongzhi** [zed-industries/zed#15007]
### Check for existing issues

- [X] Completed

### Describe the feature

how should I add `"go.testFlags": ["-v"],` like vscode to output log on console?

![image](https://github.com/user-attachments/assets/3b68aac0-2916-41d0-a9c8-0d8f86ccec70)

 I found it in souce code . but I don't know how to let it work.

![image](https://github.com/user-attachments/assets/922c64be-8cfe-4016-b6b7-8bef020fa016)

# vscode
add `"go.testFlags": ["-v"],` 
![image](https://github.com/user-attachments/assets/9ab590ae-e0c7-4eb9-8cab-91c6ae3a56dd)

![image](https://github.com/user-attachments/assets/9fee2b68-bd82-4717-a27e-141d63ec6096)

**Comment by notpeter** [comment]
We don't currently expose a setting for toggling verbose test output, but our Spawn Task menu does include an option for verbose logging, confusingly it is missing the label.

I've improved the label in #15375 (which will be in Preview next wednesday and stable the following wednesday). At which point it'll look like this:
<img width="546" alt="Screenshot 2024-07-28 at 11 56 59" src="https://github.com/user-attachments/assets/dee819b0-411f-41c6-8df7-8cabeb64394a">


But in the meantime, if you want to spawn tasks with verbose logging, instead of using the "▶" in the sidebar, you can use Spawn Task... (`option+shift+t` or `alt+shift+t`).  If you hover over the item in the list, the second line shows you the `-v` 

![image](https://github.com/user-attachments/assets/4f0f62d9-2489-401a-b6e8-5e3a98366366)
