### ISSUE TITLE
support drag-and-drop for text

### ISSUE THREAD

**Issue by Chen1Plus** [zed-industries/zed#15155]
### Check for existing issues

- [X] Completed

### Describe the feature

As title.

Zed: 0.145.1
Mac OS: Sonoma 14.5

**Comment by JosephTLyons** [comment]
Hey @Chen1Plus,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4958

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
