### ISSUE TITLE
Zed install messes with default file manager settings

### ISSUE THREAD

**Issue by limbusdev** [zed-industries/zed#15161]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After installing Zed when clicking on "open folder" in some apps like the Epson Scan App Zed opens instead of Nautilus. I had to uninstall Zed to get back the old behavior.

### Environment

Zed: v0.143.7 (Zed)
OS: Linux Wayland manjaro unknown
Memory: 46.8 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by neunato** [comment]
That is I believe up to your [default applications](https://wiki.archlinux.org/title/Default_applications) setup.

Zed simply states it can be used to open directories, you might be able to fix with:
```sh
xdg-mime default org.gnome.Nautilus.desktop inode/directory
# sudo update-desktop-database /usr/share/applications           # or reboot
```

**Comment by limbusdev** [comment]
I'll check this. Thanks.

**Comment by edgarogh** [comment]
Same issue here, which causes IntelliJ and other JetBrains IDEs to open Zed when I want to show a file in the system explorer. Here is my `~/.local/share/applications/mimeinfo.cache` before I fixed it with @/neunato's solution:
```
[MIME Cache]
application/x-ipynb+json=jupyter-notebook.desktop;jupyterlab.desktop;
application/zip=org.prismlauncher.PrismLauncher.desktop;
inode/directory=dev.zed.Zed.desktop;
text/plain=dev.zed.Zed.desktop;
x-scheme-handler/curseforge=org.prismlauncher.PrismLauncher.desktop;
[...]
```

Note that in Linux Mint, the file manager is `nemo.desktop` instead of `org.gnome.Nautilus.desktop`. What's odd is that the "Preferred applications" settings app in Linux Mint isn't able to fix this issue, it still displays the default file manager as the `inode/directory` opener...

**Comment by jansol** [comment]
This should no longer be happening since zed no longer advertises support for opening directories in its desktop file since #16940 . @limbusdev can you verify and close this?

**Comment by JosephTLyons** [comment]
I'm going to close this issue out, due to inactivity. Feel free to open a new issue if you are still hitting it in the latest version of Zed.
