### ISSUE TITLE
Zed release build downoload process being stuck at the last step (zed(bin))

### ISSUE THREAD

**Issue by NmkDjecko** [zed-industries/zed#15360]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The bug is very strange. The building and compiling process simply stops when I try to run a simple cargo build --release on windows at the last step called zed(bin) the 1165 on 1166 step. 
    Building [=====================> ] 1165/1166: zed(bin)

Please I just want to code with this IDE.

### Environment

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.19 GHz
20,0 Go (19,7 Go utilisable)
system 64 bits, processeur x64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Capture d'écran 2024-07-27 233828](https://github.com/user-attachments/assets/2a92a4df-72db-46ea-9229-a2c21984d942)

**Comment by SomeoneToIgnore** [comment]
It could be not stuck, but rather doing last build steps, most probably linking the final binary (or link-related optimizations).

Entire Windows support is brought by external contributors, so I cannot agree that this is a bug, and neither can I agree that this issue is related to Zed project — it works on others' machines (mine included).

We have rather aggressive `release` profile set-up, consider using `release-fast` or waiting even more:
https://github.com/zed-industries/zed/blob/fee49fcf657e2514b02b6e9f81003ea48206c231/Cargo.toml#L521-L532

https://doc.rust-lang.org/cargo/reference/profiles.html has more information if needed.
Same Cargo book should contain more information on how to profile a cargo build, that should help with getting to know where it's stuck (or not).

**Comment by LucasAlfare** [comment]
I've wait long minutes and the process finished, making the application UI inflate properly. For all those who have this, just wait.
