### ISSUE TITLE
`Projects: open remote`: Accept `~/` as the usual `$HOME` shorthand in the command.

### ISSUE THREAD

**Issue by danfuzz** [zed-industries/zed#15501]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The `SSH arguments` of a remote connection setup don't recognize `~` as meaning "my home directory."

1. Invoke `Projects: open remote`.
2. Click on `New Server`.
3. Enter `~/...` under `SSH arguments`, where `...` is the path to an `ssh` wrapper command. (You can probably simulate this by making a symlink to the regular `ssh` command somewhere under your home directory.)
4. Click `Connect`.

Expected: Connects to the remote machine.
Actual: Failure. The setup box indicates `Not connected`, but there is no other visible error.

If I change `~/...` to be (for me) `/Users/danfuzz/...`, then the connection is made successfully. Notably, it continues to fail with either no prefix or with the prefix `./`. But in any case, I would prefer `~/` as an indicator that is both pithy and explicit.

### Environment

Zed: v0.145.1 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

Note: Slightly redacted.

<details><summary>Zed.log</summary><pre>

2024-07-30T18:32:07.442785Z [ERROR] Working directory: <none specified, using home directory> /Users/danfuzz Shell command: `~/src-danfuzz/... <args>`, IOError: Failed to spawn command '~/src-danfuzz/...': No such file or directory (os error 2)

Caused by:
    Failed to spawn command '~/src-danfuzz/...': No such file or directory (os error 2)

</pre></details>

**Comment by notpeter** [comment]
I attempted to reproduce this and was partially successful.
You are correct using `~` is not supported in the path for the command.

But more interestingly, even if I created a wrapper (```ln -s `which ssh` ~/fancyssh```) when I attempted to use the absolute path Zed did not setup the remote correctly.

Steps to reproduce:
1. `ln -s `which ssh` ~/fancyssh`
2. Command Palette: `projects: open remote`
3. Select `New Server`
4. In SSH arguments put: `/Users/peter/fancyssh think21` (edited accordingly).
5. Click Connect.

Actual behavior:
1. Terminal tab opened an interactive session, which waits at a bash prompt.
2. Spinning 🔄 "Waiting for connection"
3. Reconnect button (which will spawn an additional terminal)

Expected behavior: Terminal window pops, installs zed-editor just like when I use `ssh think21` in the SSH arguments.

@danfuzz Are you seeing this same broken behavior? Or does your remote created with the absolute path of your wrapper actually work with remote projects?

**Comment by danfuzz** [comment]
@notpeter In my case, the absolute path to my (non-symlink) wrapper script works to hook up a remote connection.

**Comment by notpeter** [comment]
Support for specifying the explicit command to run was deprecated in https://github.com/zed-industries/zed/pull/15321.

>Note: In an earlier version of remoting, we supported typing in gh cs ssh or gcloud compute ssh directly. This is no longer supported. Instead you should make sure your SSH configuration is up to date with gcloud compute ssh --config or gh cs ssh --config, or use Manual setup mode if you cannot ssh directly to the machine.

See: https://zed.dev/docs/remote-development#ssh-connections
