### ISSUE TITLE
Add command and shortcut to maximize terminal height, increase terminal height to cover the full editor, like in VSCode

### ISSUE THREAD

**Issue by remorses** [zed-industries/zed#15593]
### Check for existing issues

- [X] Completed

### Describe the feature

Add command and shortcut to maximize terminal height, increase terminal height to cover the full editor, like in VSCode

Useful to read long logs

**Comment by chungweileong94** [comment]
Not sure if this is what you want, you can hit `shift + esc` to make the terminal full-screen.

**Comment by PatzEdi** [comment]
> Not sure if this is what you want, you can hit `shift + esc` to make the terminal full-screen.

Hello, was just wondering, when transparency is enabled in Zed, the full screen terminal is not blurred but is rather transparent, so the text comes together with the background (say you have a file open) and the text in the terminal itself. Is there a way to make it so that the terminal, even when full screen, is not fully transparent to improve readability?
