### ISSUE TITLE
Assistant markdown formatting

### ISSUE THREAD

**Issue by jimcroft** [zed-industries/zed#15601]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice if the assistant responses that contain markdown were formatted rather than presented raw (or have it as a configurable option), especially for longer responses than might contain several sections, code examples, or other md elements.

<img width="419" alt="SCR-20240801-kobp" src="https://github.com/user-attachments/assets/a28e08b2-6892-4d40-9911-3235f08a9a81">

versus....

<img width="505" alt="SCR-20240801-knsd" src="https://github.com/user-attachments/assets/a7603482-804b-4c8d-8899-d42359522274">

**Comment by mrnugget** [comment]
I'll defer to @nathansobo and @as-cii on this, but I think for now we want to stay with raw Markdown, because it allows us to use all the text-manipulation we already have on the prompts and responses: you can modify the response before sending it back up again, you can use the inline assist in the assistant panel, etc.

**Comment by nathansobo** [comment]
It would be nice to someday render the assistant output in a different font to better signal its origin, but preserving edibility and selectability via the keyboard is more important to us than how it's formatted right now. Zed is an editor, so the text should be editable.
