### ISSUE TITLE
Project Panel Mouse hover

### ISSUE THREAD

**Issue by pengcu** [zed-industries/zed#15614]
### Check for existing issues

- [X] Completed

### Describe the feature

When the mouse hovers over it, the cursor style will change.
Maybe keep one style is better?

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/user-attachments/assets/d366e2fd-7977-47b2-af73-2ed6816a7cc4

**Comment by notpeter** [comment]
There's a couple things going on here:
1. I think the flickering comes from each entry in the list having a border or padding so there's ~2 pixels between each list item which is a dead zone. (cursor is pointer not hand)
2. To the left of an icon (including any indentation) is also a dead zone (not clickable). This is confusing because the background highlighting suggests that you could click and select the highlighted file/folder.
3. I couldn't figure out how to reproduce the mouse cursor not changing (0:00 - 0:02) while moving through the list, but that's not right either.

I'm running Zed Nightly 0.148.0 on MacOS, curious your version/platform.
Thanks for reporting.

**Comment by pengcu** [comment]
I'm running Zed v0.146.3 on MacOS 13.6.8
`the mouse cursor not changing (0:00 - 0:02)` At that moment, the application was not the active window，so it not changing

**Comment by stippi** [comment]
The problem also manifests when you "two-finger-scroll" the outline. Then the mouse pointer is stationary and flickers its shape while the items scroll underneath with the two pixel padding dead-zone.
