### ISSUE TITLE
`detect_venv` setting does nothing

### ISSUE THREAD

**Issue by injust** [zed-industries/zed#15699]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Configuring the `detect_venv` setting does nothing, and it is impossible to disable the feature.

1. When I set `"detect_venv": { "on": { "activate_script": "fish" }}` to fix https://github.com/zed-industries/zed/issues/11246, Zed still tries to activate the venv using the default script.
2. When I set `"detect_venv": "off"`, nothing changes.

Because of this, every new terminal session spews a fish error.

### Environment

Zed: v0.146.5 (Zed)
OS: macOS 14.6.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by injust** [comment]
🤦 This was me setting `detect_venv` as a top-level option, instead of `terminal.detect_venv`.

**Comment by iteroji** [comment]
I believe that the `default` option should auto-detect the  user's login shell instead of just sourcing `.venv/bin/activate`. 
I understand that the activation script  can be explicitly set to `fish` , `csh` or `nushell`  but this only works if all team members working on the project use the same shell. 

If that is not a common enough scenario to implement it, then can someone suggest an alternative way? Is there a way to call a shell script when a terminal starts?

**Comment by injust** [comment]
> I believe that the `default` option should auto-detect the user's login shell instead of just sourcing `.venv/bin/activate`.

https://github.com/zed-industries/zed/issues/11246 covers this.

> I understand that the activation script can be explicitly set to `fish` , `csh` or `nushell` but this only works if all team members working on the project use the same shell.

How are you sharing your Zed config with other team members? That's not an expected use case -- your Zed config should be local to you only.

**Comment by iteroji** [comment]
> @iteroji How are you sharing your Zed config with other team members? That's not an expected use case -- your Zed config should be local to you only.

I'm sharing the project settings as part of the project repo, not the global settings. Can I partially override global settings, such as the `directories` in `detect_env`? Because in that case it would be easier to leave the `activation_script` out of the project settings, and only override the directories part.

**Comment by injust** [comment]
> I'm sharing the project settings as part of the project repo, not the global settings. Can I partially override global settings, such as the `directories` in `detect_env`? Because in that case it would be easier to leave the `activation_script` out of the project settings, and only override the directories part.

Oh, I see. I didn't think about that use case at all.

You should probably open a separate issue for this.
