### ISSUE TITLE
font fallback not support ligature

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#15939]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My config:

```jsonc
{
  "ui_font_family": "Menlo",
  "buffer_font_family": "Menlo",
  "ui_font_fallbacks": [
    "JetBrainsMono Nerd Font",
    "MonacoLigaturized Nerd Font Mono"
  ],
  "buffer_font_fallbacks": [
    "JetBrainsMono Nerd Font",
    "MonacoLigaturized Nerd Font Mono"
  ],
  "buffer_font_features": {
    "calt": true,
    "zero": true
  },
  "ui_font_features": {
    "calt": true,
    "zero": true
  }
}
```

The nerd font symbol display normal
It seems to support ligature 👀

<img width="595" alt="image" src="https://github.com/user-attachments/assets/7ed6e978-e5c3-46c8-b6d3-98d4371c153d">

### Environment

Zed: v0.148.0 (Zed Nightly 990774247ecb61ddf69f0325d28eb3b203fc3699)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JunkuiZhang** [comment]
The enabled font features won't apply to the fallback fonts. The fallback is only used to check for codepoints not supported by the original font and render them using the specified fallback, that's why it's called "fallback". AFAIK, if you want a font that doesn't support ligatures to support ligatures, you can try [Ligaturizer](https://github.com/ToxicFrog/Ligaturizer). I used Ligaturizer in the past to enable ligature support for Ubuntu Mono.
