### ISSUE TITLE
Outline Panel items have flickering effect when typing

### ISSUE THREAD

**Issue by backsideofdawn** [zed-industries/zed#15956]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When selecting an item in the outline panel, and then typing in the editor, the currently selected item turns the "selected color" whenever a key is pressed, and reverts back to its normal color when it's not. Edit: It only happens when you're adding new characters to the end of a function/method.

https://github.com/user-attachments/assets/a80e4bcb-a959-42ed-8862-ea1826870830

### Environment

Zed: v0.147.2 (Zed)
OS: Linux X11 linuxmint 21.3
Memory: 14.3 GiB
Architecture: x86_64
GPU: AMD Unknown (RADV GFX1103_R1) || radv || Mesa 23.2.1-1ubuntu3.1~22.04.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment]
cc @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/pull/20031 should have improved things on this front.

We still flicker when adding a newline, seems to be due to the way tree-sitter grammars capture function blocks for Python.
But after you start editing the line, it does not flicker anymore:

https://github.com/user-attachments/assets/1d09fdd0-150a-42e4-8753-36c28363a65d

I think this is more or less good now, so I'll close the issue, but let's discuss it more if you think something is very broken still.
