### ISSUE TITLE
When setting all the cmd+\\ keybindings to null the key binding still gets triggered

### ISSUE THREAD

**Issue by ExploHash** [zed-industries/zed#16187]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Set the keymap.json to
```
// Zed keymap
//
// For information on binding keys, see the Zed
// documentation: https://zed.dev/docs/key-bindings
//
// To see the default key bindings run `zed: open default keymap`
// from the command palette.
[
  {
    "context": "Workspace",
    "bindings": {
      "cmd-\\": null
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "cmd-\\": null
    }
  },
  {
    "context": "Editor && mode == full",
    "bindings": {
      "cmd-\\": null
    }
  },
  {
    "context": "Pane",
    "bindings": {
      "cmd-\\": null
    }
  },
  {
    "context": "CommandPalette",
    "bindings": {
      "cmd-\\": null
    }
  },
  {
    "context": "Terminal",
    "bindings": {
      "cmd-\\": null
    }
  },
  {
    "context": "BufferSearchBar",
    "bindings": {
      "cmd-\\": null
    }
  }
]

```

And do CMD+\ and see a pane still splits which is the default keybinding

### Environment

Zed: v0.148.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

No logging happens

**Comment by notpeter** [comment]
I can reproduce.

- with `"cmd-\\": null` it still triggers `pane::SplitRight` (incorrectly)
- with `"cmd-\\": "zed::NoAction"` it still trigger `pane::SplitRight` (incorrectly)
- with any other bind (e.g. `"cmd-\\": "workspace::NewFile"`) it triggers the new action and does not split panes (correct).

As `cmd-\\` is only mapped in one place in the default MacOS keybinding:
https://github.com/zed-industries/zed/blob/910dbe9ce6c8e1441ca0822aacc5394a34143062/assets/keymaps/default-macos.json#L349

This is the only context you should need to remap:
```
  {
    "context": "Editor",
    "bindings": {
      "cmd-\\": null
    }
  },
```

Thanks for reporting.

**Comment by ExploHash** [comment]
@notpeter Thanks for checking :), good to hear that I didn't do anything stupid

**Comment by CharlesChen0823** [comment]
because "ctrl-\\" also register into macos system menus, link [here](https://github.com/zed-industries/zed/blob/910dbe9ce6c8e1441ca0822aacc5394a34143062/crates/zed/src/main.rs#L306)  which you cannot remap this actions.

**Comment by notpeter** [comment]
Thanks @CharlesChen0823 that it.  Because we include the `cmd-\` in the menu, MacOS captures it.  If you would like to unmap `cmd-\` you will need this:
```json
  {
    "context": "Editor",
    "bindings": {
      "cmd-\\": null
    }
  },
```

And you will need to assign an alternate shortcut under System Preferences -> Keyboard -> Keyboard Shortcuts -> App Shortcuts for `Split Right` for Zed. 
<img width="715" alt="Screenshot 2024-08-15 at 13 17 43" src="https://github.com/user-attachments/assets/5bea0c2f-5010-4a48-be81-38e49b49f4c3">

Then your View->Editor Layout menu will change from this to this:
<img width="181" alt="Screenshot 2024-08-15 at 13 16 11" src="https://github.com/user-attachments/assets/a22922a9-6e13-4540-aca9-fc41e6a3802e"><img width="212" alt="image" src="https://github.com/user-attachments/assets/7ae9f0c2-f251-4598-9159-e82fddda7cf5">

And `cmd-\` will truly be a no-op.
@ExploHash Please let me know if this works for you.

**Comment by ExploHash** [comment]
Ahh I see, thanks! It works kind of, the reason why I asked this is because I created a custom shortcut on CMD+\ in settings (to open a terminal). After remapping split right, now nothing happens at all even though in other applications CMD+\ does trigger my custom shortcut.

But it's fine I could just choose another keybinding even though it's interesting that it now doesn't trigger anything haha

**Comment by notpeter** [comment]
Once you've gotten MacOS out of the way instead of setting it to null, you should just be able to rebind it to whatever action you want. For example, this works for me:
```json
  {
    "bindings": {
      "cmd-\\": "terminal_panel::ToggleFocus"
    }
  },
```

**Comment by ExploHash** [comment]
@notpeter Its a shortcut in macos, so I kinda want Zed not to do anything with cmd + \ at alll
