### ISSUE TITLE
Font looks squeezed in

### ISSUE THREAD

**Issue by viz404** [zed-industries/zed#16401]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've loaded JetBrains font on my system and it's doesn't look same in zed compared to my terminal or other editors

### Environment

Operating System: Fedora Linux 40 (Workstation Edition) x86_64
Kernel: 6.10.3-200.fc40.x86_64
Resolution: 1920x1080
DE: GNOME 46.4
Graphics Platform: Wayland
CPU: Intel i5-6300U (4) @ 3.000GHz
GPU: Intel Skylake GT2 [HD Graphics 520]
Memory: 12 GB

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Font rendering on zed: (everything looks squeezed in)
![image](https://github.com/user-attachments/assets/db6da3bf-0b54-498f-a364-de6d56920896)

On vscode for comparison:
![image](https://github.com/user-attachments/assets/b2fd234f-1eec-421e-b48f-d0cd50ef5960)

On Neovim on Gnome Console:
![image](https://github.com/user-attachments/assets/99d9f014-ac08-426e-9adb-c87d4eb9e170)

If you notice in other places there's proper space between the letters but not on zed, and even the letters looks relaxed compared to zed.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

 I'm a little concerned to paste my log file here in public
</pre></details>

**Comment by apricotbucket28** [comment]
I think the spacing should be solved by https://github.com/zed-industries/zed/pull/16238

> the letters looks relaxed compared to zed

This sounds like https://github.com/zed-industries/zed/issues/13564

**Comment by notpeter** [comment]
1. Can you add your zed environment (`ctrl-shift-p` `zed: copy system specs`) in the issue description?
3. Can you also provide the relevant lines from your settings (e.g. `buffer_font_family`) defining which JetBrains Mono variant you are using (e.g. `JetBrainsMono-Regular`) so I can try and reproduce?
2. Would you be willing to build main to see if #16238 fixes your issue?

**Comment by viz404** [comment]
Sorry for responding late, right after this I bought another machine and gave this one to someone else.
Thank you responding guys, although I can't confirm about this issue on the original machine but it renders just fine on my new one.
Again apologies for responding late and thanks for the support.

**Comment by yioannides** [comment]
Not sure if it relates to this specific closed issue, but I'm experiencing the same thing on my Fedora 40 machine:

![1](https://github.com/user-attachments/assets/38e19a43-2ad2-449c-8a99-0ac5cfa078ac)
![2](https://github.com/user-attachments/assets/a2cdae3d-327a-4790-b7b2-71d190c9840e)

I'm using JetBrains NL Mono on both IDEs, but while the font renders the font weight and antialiasing correctly in GNOME Builder, the same font looks squeezed in both editor and terminal.

I'm on a 2560 x 1440 display and running the flatpak version of Zed (v0.155.2) on Fedora 40 / Wayland. Please let me know if I can provide you with more info if that would help you find the cause of this issue.

**Comment by notpeter** [comment]
The Zed version is definitely not just narrower but smaller and a different weight. The 
I think Zed may be defaulting to using the "JetBrains Mono Light" instead of "JetBrains Mono Regular"

Could you try altering your settings to this:
```
  "buffer_font_size": 16,
  "buffer_font_family": "JetBrains Mono Regular",
```
Note: Zed will show red squiggles for the font name, this is harmless.

P.S. This is very much related to this issue, just with a different font.  If you try and use the Zed Mono font it defaults to `Zed Mono Narrow` instead of `Zed Mono Regular` and I think you may be seeing the same thing with `Light` vs `Regular`.  I have a feeling Zed may be choosing the first font alphabetically.

**Comment by yioannides** [comment]
```
  "buffer_font_size": 16,
  "buffer_font_family": "JetBrains Mono Regular",
```

I tried these settings, but the font family value has a yellow squiggly, because it requires just the name of the family; pressing Enter defaults to another monospace font. Changing the size to 16 didn't do much either, the same narrow font as the screenshot, but larger.

I don't think it's related, since the rendering of the actual font in Zed seems completely different, but I have the command below to solve some of the issues stemming from how my HP Omen display renders text in GNOME:

```sh
FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0  |  sudo tee -a /etc/environment
```
