### ISSUE TITLE
Ctrl+shift+up/down does not match vscode when using the vscode keybinds (linux)

### ISSUE THREAD

**Issue by Landon-Kuehner** [zed-industries/zed#16441]
### Check for existing issues

- [X] Completed

### Describe the feature

In vscode ctrl+shift+up/down splits the cursor to the next line above like zed does with middle click and drag, but in zed this does not happen, it splits the cursor to other occurrences of the token in the current buffer

## Comparison
https://github.com/user-attachments/assets/f3870a23-9ede-4d94-afaf-ab53ad1cccb6

### If applicable, add mockups / screenshots to help present your vision of the feature

Ctrl+shift+up/down should split the cursor to the next line above or below the cursor like in vscode while using the vscode keymap.

**Comment by notpeter** [comment]
Hi @Landon-Kuehner,

The default vscode keybinding on Linux actually has duplicate binds for this:
- `ctrl-shift-up` / `ctrl-shift-down`
- `alt-shift-up` / `alt-shift-down`

![image](https://github.com/user-attachments/assets/81f87b99-4edb-4363-a5dd-454078347c3c)

For the moment we've chose to only duplicate the latter so that we can use `ctrl-shift-up`/`ctrl-shift-down` for unique features.

You can add this to your `~/.config/zed/keymap.json` if you would like to reclaim those keys:

```json
  {  //https://github.com/zed-industries/zed/issues/16441
    "context": "Editor",
    "bindings": {
      "ctrl-shift-up": "editor::AddSelectionAbove", // Insert Cursor Above
      "ctrl-shift-down": "editor::AddSelectionBelow" // Insert Cursor Below
    }
  },
```

Thanks for reporting.
