### ISSUE TITLE
SSH remoting Terminal uses ssh2 library

### ISSUE THREAD

**Issue by thuc98** [zed-industries/zed#16523]
### Check for existing issues

- [X] Completed

### Describe the feature

Is it possible to use ssh2 (https://docs.rs/ssh2/latest/ssh2/) instead of running the ssh command?

**Comment by notpeter** [comment]
Hi @thuc98, for the moment this is intentional.  Using the openssh cli (`ssh`) we can support every esoteric configuration supported by openssh and users can easily validate "if it works from the CLI it'll work in zed". If we built our own client with ssh2/libssh2 we would have to implement many of those features ourselves (agent support, hardware tokens, jump servers, etc).

**Comment by thuc98** [comment]
> Hi @thuc98, for the moment this is intentional. Using the openssh cli (`ssh`) we can support every esoteric configuration supported by openssh and users can easily validate "if it works from the CLI it'll work in zed". If we built our own client with ssh2/libssh2 we would have to implement many of those features ourselves (agent support, hardware tokens, jump servers, etc).

I really need this feature, can you write me a sample code for using ssh2 with alacritty_terminal on zed?

**Comment by notpeter** [comment]
> I really need this feature, can you write me a sample code for using ssh2 with alacritty_terminal on zed?

Please provide additional context as to why you "need this feature".

Are you working in an environment where you don't have access to an ssh binary? The Zed assumption that the platform provides a functioning openssh-client available via the `ssh` command seems like a reasonable pre-requisite for supporting ssh-based remoting.
