### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by 0xElessar** [zed-industries/zed#16914]
### Check for existing issues

- [X] Completed

### Describe the feature

I have no idea why you don't provide Windows builds. IMO either don't support Windows at all or provide builds. I followed your guide to compile the software, it builds fine. But it crashes when running (I posted the error message in the below box).

This is really frustrating. You create this software for people, but many people can't simply use it because they can't follow your compile guide, or they have a problem with compilation or it crashes after compilation. If you provide proper windows builds, you could share your hard work with more people. Just my 2 cents. 

### If applicable, add mockups / screenshots to help present your vision of the feature

```
Faulting application name: rustfmt.exe, version: 0.0.0.0, time stamp: 0x66b2885c
Faulting module name: rustc_driver-a71ba2c5a3b674ac.dll, version: 0.0.0.0, time stamp: 0x66b27e5c
Exception code: 0xc00000fd
Fault offset: 0x0000000003ed3b9e
Faulting process id: 0xd40
Faulting application start time: 0x01daf7dda8edb650
Faulting application path: C:\Users\elessar\.rustup\toolchains\1.80-x86_64-pc-windows-msvc\bin\rustfmt.exe
Faulting module path: C:\Users\elessar\.rustup\toolchains\1.80-x86_64-pc-windows-msvc\bin\rustc_driver-a71ba2c5a3b674ac.dll
Report Id: 381d8202-775d-4e34-a90f-292e5fcb1a43
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by JosephTLyons** [comment]
We don't not provide official Windows builds yet because we haven't personally invested time into working on that front and ensuring that everything works as we'd expect. Most of the reason why Zed compiles on Windows is due to our really awesome community of users who have opened PRs to get things moving. But because we haven't really dug into it too much ourselves, we don't feel confident saying "official support is ready," and so we don't ship binaries at the moment. We haven't nailed down any deadlines for Windows support, but we are actively working on a new roadmap to pin this down.

**Comment by JosephTLyons** [comment]
Closing in favor of:

- https://github.com/zed-industries/zed/issues/5394

Where we will post updates, as things unfold.
