### ISSUE TITLE
Release notes (in editor)

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#17527]
### Check for existing issues

- [X] Completed

### Describe the feature

After every update it would be nice to have something like this from vscode.

<img width="1396" alt="Screenshot 2024-09-07 alle 10 26 20" src="https://github.com/user-attachments/assets/445c564f-5ef0-410f-b07f-61e3fca3c9af">

Link: https://code.visualstudio.com/updates/v1_93

**Comment by jansol** [comment]
With the current release cadence it would be nice to have say, the last month's changelogs shipped in the application bundle so they can be shown offline (with a "older changelogs can be found on the website" link at the end). Having only the single latest changelog is not very useful since there are often hotfix releases.

**Comment by JosephTLyons** [comment]
I'm curious about doing this. Would showing all versions related to the minor version suffice? If you send up a request to view release notes for v0.153.6, maybe we just open a tab of release notes for every patch released under v0.153?

**Comment by jansol** [comment]
That would be a great start yes. The entries older than the most recent patch could maybe be collapsed by default, if that is supported in the markdown viewer.

**Comment by JosephTLyons** [comment]
Just so that you (@Angelk90) are aware, we do have the `auto update: view release notes locally`, which shows these release notes of the current version within Zed. This isn't something that is triggered automatically because our Markdown-rendered view isn't quite complete - it doesn't fully support media and there are some issues.

That being said, I went ahead and adjusted the endpoint to provide all release notes for every patch associated with the installed version, which seems more stable and useful than just the current version's release notes.

https://github.com/zed-industries/zed/pull/18108

**Comment by JosephTLyons** [comment]
> @JosephTLyons : Why do you see all versions of `V0.153.1`, `V0.153.2`, `V0.153.3`, `V0.153.4` with version `V0.153.x`?
> 
>  Registrazione.schermo.2024-09-21.alle.11.04.02.mov

This is now in the latest preview and will be in today's stable once the new builds go out in the afternoon.

**Comment by JosephTLyons** [comment]
> @JosephTLyons : It would be nice if when this appears you could click and it opens the tab, instead of opening the browser. <img alt="Screenshot 2024-09-25 alle 19 35 17" width="472" src="https://private-user-images.githubusercontent.com/20476002/370829723-ed7a98e4-c309-490e-b728-4dd23a73f526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODcyNDIsIm5iZiI6MTcyNzI4Njk0MiwicGF0aCI6Ii8yMDQ3NjAwMi8zNzA4Mjk3MjMtZWQ3YTk4ZTQtYzMwOS00OTBlLWI3MjgtNGRkMjNhNzNmNTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE3NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OGE1MzI1N2VhYzAyZWNmOTViNDcyYTE1ZjgzMTA3NDg3ZDAyNWFiYWRlYmIzZTU0NmY2YjI2NjkyZjAxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YSmsbSxb-gH7vPJME5Oj14G60Hli5rii2tQ87GbXX8c">

I want to, but because our markdown render doesn't currently support showing media (images and videos) and we sometimes include those in the release notes, we can't really swap it out yet. Once the markdown renderer can handle displaying media, I think we will switch this over to using the local version of release notes.

**Comment by bjorn** [comment]
It's really nice that the release notes are now shown immediately in the editor, but the new view is missing a scroll bar. There also doesn't appear to be support for selection nor any form of keyboard handling, so the only way to read all the release notes is by using the mouse wheel. :-S

(I'm running Zed on Fedora)

**Comment by bjorn** [comment]
@Angelk90 Whether there's a line below a subtitle or not is a style choice and not necessarily a bug. In any case, by commenting here I think it should already reach the relevant people. It was just an observation, if they'd like an issue it can be trivially created.

**Comment by JosephTLyons** [comment]
There are some things missing from the view and the markdown renderer, which is one of the reasons I waited so long to switch from the release notes being launched in the browser to in editor.

I think @osiewicz is working on a generic scrollbar component and might be able to quickly drop it into views that are missing them, like this one.
