### ISSUE TITLE
TS & JSON autocompletion shortcut key combination doesn't work

### ISSUE THREAD

**Issue by Marcisbee** [zed-industries/zed#17691]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When in TypeScript files or JSON files that use jsonschema, pressing shortcut keys for "Show completions" action, does nothing. When triggering action manually via comand prompt, it works.

Current keymap:
```
"base_keymap": "Atom",
```

![image](https://github.com/user-attachments/assets/dc9109fb-57e1-4908-8f06-c08e31ddc463)

https://github.com/user-attachments/assets/cf3a69de-0456-4312-8c00-32b0dea88bf3

Note I am presing CMD+SPACE (and nothing happens) before doing it manually via comand prompt.

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I believe this is because macOS includes a default keyboard shortcut for `ctrl-space` which toggles keyboard locales.  We likely should not include a default shortcut which attempts (and in the default system config, fails) to use such a shortcut.

Can you try opening Keyboard system preference panel and selecting "Keyboard Shortcuts" and unchecking it there and see if it works for you now?
<img width="671" alt="Screenshot 2024-11-25 at 14 59 46" src="https://github.com/user-attachments/assets/ebf08513-7a83-4fbf-b574-71735765be49">

**Comment by Marcisbee** [comment]
@notpeter seems like it works now if I disable both of those shortcuts from Input Sources.
