### ISSUE TITLE
delete multiple files together on the file tree after `ctrl+click` on them

### ISSUE THREAD

**Issue by sparrowsl** [zed-industries/zed#17746]
### Check for existing issues

- [X] Completed

### Describe the feature

I can't seem to delete multiple files after `ctrl+click`ing on them.
I can mark multiple but once I press the `delete` key, I only get a popup to delete the first marked file instead of all the selected/marked files

### If applicable, add mockups / screenshots to help present your vision of the feature

![Peek 2024-09-12 08-38](https://github.com/user-attachments/assets/c4bdabf8-a551-4c70-b957-bf9db984041c)

**Comment by mrnugget** [comment]
According to the code, this seems to work intentionally like this:

https://github.com/zed-industries/zed/blob/97d91244fc5ab40e200df664076beed33420d6ae/crates/project_panel/src/project_panel.rs#L1737-L1738

It means that in your video, you haven't "marked" your currently selected entry, only the other two files, and when you hit delete, this logic kicks in and we only propose the currently selected file to be deleted.

If I understand it correctly, VS Code does something different: as soon as you cmd-click on another file that's not the currently selected one, they change the selection to that file.

https://github.com/user-attachments/assets/cfba49aa-5af3-476e-9fbc-c735d5d92499

@osiewicz git tells me you added that method in https://github.com/zed-industries/zed/pull/12363 — what's the background behind the logic? I'm reluctant to change anything here since it seems intentional.

**Comment by sparrowsl** [comment]
I just tried it and it works the way you explained, I had to click the current selected file to get Zed to delete multiple.
I will start using this trick till this is decided.

Thanks a bunch. @mrnugget

**Comment by mrnugget** [comment]
Found something else: seems like we _do_ mark an entry on click. But there is also a bug where we then immediately remove that marking once the entry is revealed.

**Comment by osiewicz** [comment]
> @osiewicz git tells me you added that method in https://github.com/zed-industries/zed/pull/12363 — what's the background behind the logic? I'm reluctant to change anything here since it seems intentional.

Tbh there's no grand scheme behind this logic; I've just tried to match what VSC does.
I think we should be changing the selected entry to the one that was clicked.
