### ISSUE TITLE
Buffer font disable ligatures for Linux

### ISSUE THREAD

**Issue by jangorecki** [zed-industries/zed#17784]
### Check for existing issues

- [X] Completed

### Describe the feature

https://zed.dev/docs/configuring-zed#buffer-font-features
It seems that disabling ligatures on linux is not yet supported in zed.
Therefore I am filling out this issue so whoever is interested in such a support can subscribe to this missing feature for Linux users.

**Comment by jansol** [comment]
See also #12176

**Comment by notpeter** [comment]
Closing in favor of:
- https://github.com/zed-industries/zed/issues/15752
- https://github.com/zed-industries/zed/issues/12176

**Comment by jangorecki** [comment]
@notpeter none of the linked issues solves the problem described here.
If you want to close this one and link the other please at least explicitly add problem described here to the scope of the other issue. Otherwise it may happen other issues will get resolved while this problem will not.
The problem described here is that it is currently not possible to disable ligatures on Linux. The fact they are not functioning properly is another thing.

**Comment by jansol** [comment]
> The problem described here is that it is currently not possible to disable ligatures on Linux. The fact they are not functioning properly is another thing.

The `*_font_features` settings are exactly the ones that control ligatures (both enabling and disabling them) so #15752 does solve your problem.

**Comment by jangorecki** [comment]
@jansol are you sure you linked proper number of the issue? it is completely not related to disabling the disfunctional feature. Could you quote the part of it that covers request posted here?

**Comment by jansol** [comment]
[The documentation page you linked in the OP](https://zed.dev/docs/configuring-zed#buffer-font-features) says that the `*_font_features` settings are used for disabling font ligatures.

In order to disable font ligatures, the settings that disable font ligatures need to work.

#15752 says that the `*_font_features` settings (which disable font ligatures) do not work on Linux.

So in order to resolve #15752, the `*_font_features` settings (which disable font ligatures) need to be fixed to work on Linux.

When the `*_font_features` settings (which disable font ligatures) work on Linux, you will be able to use them to disable font ligatures like you requested in this issue.
