### ISSUE TITLE
Can't access the project panel when it is set to the right dock only see New Context

### ISSUE THREAD

**Issue by joshdales** [zed-industries/zed#18022]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In my setting I have put the project panel in the right dock, I've also disabled the assistant
```json
{
  "assistant": {
    "version": "2",
    "enabled": false,
  },
  "project_panel": {
    "dock": "right"
  }
}
```
And then I have have keybindings set to open and close the right dock with `CMD+\`
```json
[
    "bindings": {
      "cmd-\\": "workspace::ToggleRightDock"
    }
]
```
However now when I press my shortcut I just get the new llm context menu instead

### Environment

Zed: v0.152.4 (Zed)
OS: macOS 15.0.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
I was able to reproduce your issue. The contents of the right dock remains cached with their previous contents.  If you switch to the project pane once either by pressing cmd-shift-e (reveal in project panel) or click the little project panel icon in the corner it should subsequently remember that mapping
<img width="207" alt="Screenshot 2024-09-20 at 9 36 03" src="https://github.com/user-attachments/assets/cdfa5ca1-218f-4938-be8a-a9456699df94">

Also here's the correct keymap I'd use for this. You're mapping in the global context instead of workspace and you will want to override the default keymap in the Editor context which is bound to the same key here:
https://github.com/zed-industries/zed/blob/d6c184b494a0c9a9a46d4ffdb5483ba65967ab0b/assets/keymaps/default-macos.json#L355

```
[
  {
    "context": "Workspace",
    "bindings": {
      "cmd-\\": "workspace::ToggleRightDock"
    }
  },
  {
    "context": "Editor",
    "bindings": {
      "cmd-\\": "workspace::ToggleRightDock"
    }
  },
]
```
