### ISSUE TITLE
Generator prompt showing on wrong screen

### ISSUE THREAD

**Issue by calebchris000** [zed-industries/zed#18115]
- [ ] Completed

https://github.com/user-attachments/assets/82941bbc-20c3-433d-bcd6-3fce643353ed

## Steps to reproduce

- Open two different files and split the screen
- Ctrl + Enter to open prompts on the right window.

### Environment

<details><summary>System Specifications</summary>

## System
- **Kernel**: 6.10.7-200.fc40.x86_64 (x86_64, 64-bit)
- **Compiler**: gcc v2.41-37.fc40
- **Desktop**: GNOME v46.4 (GTK v3.24.43)
- **Window Manager**: gnome-shell
- **Display Manager**: GDM v46.2
- **Distribution**: Fedora Linux 40 (Workstation Edition)

## Machine
- **Type**: Laptop
- **System**: LENOVO ThinkPad L480 (20LS0000US)
- **Motherboard**: LENOVO 20LS0000US (SDK0J40697 WIN)
- **UEFI**: LENOVO R0QET69W (1.46), date: 01/03/2023

## Battery
- **Model**: SMP 01AV464
- **Type**: Li-poly
- **Charge**: 40.4 Wh (99.5%)
- **Condition**: 40.6/45.3 Wh (89.7%)
- **Voltage**: 12.3V (min: 11.1V)
- **Cycles**: 380

## CPU
- **Model**: Intel Core i5-8250U
- **Architecture**: Coffee Lake
- **Cores**: 4 (8 threads)
- **Speed**: avg: 3099 MHz, max: 3400 MHz
- **Cache**: L1: 256 KiB, L2: 1024 KiB, L3: 6 MiB

## Graphics
- **Device 1**: Intel UHD Graphics 620
- **Device 2**: Lite-On Integrated Camera
- **Display Server**: X.org v1.20.14 with Xwayland v24.1.2
- **Monitor**: BOE Display 0x06b3 (1366x768, 112 dpi)

## Audio
- **Device**: Intel Sunrise Point-LP HD Audio
- **API**: ALSA v k6.10.7-200.fc40.x86_64
- **Server**: PipeWire v1.0.7

## Network
- **Ethernet**: Intel I219-V
- **Wireless**: Intel Wireless 8265 / 8275

## Bluetooth
- **Device**: Intel Bluetooth wireless interface
- **Version**: Bluetooth 4.2

## Storage
- **Total**: 119.24 GiB
- **Used**: 51.63 GiB (43.3%)
- **Drive**: Lenovo O.E.M. RPFTJ128PDD2EWX (119.24 GiB SSD)

## Partitions
- **/** : 117.66 GiB (43.6% used)
- **/boot**: 973.4 MiB (36.2% used)
- **/boot/efi**: 598.8 MiB (3.2% used)
- **/home**: 117.66 GiB (43.6% used)

## Swap
- **Type**: zram
- **Size**: 8 GiB
- **Used**: 7.92 GiB (99.0%)

## Memory
- **Total**: 16 GiB
- **Available**: 15.51 GiB
- **Used**: 12.5 GiB (80.6%)

## System Info
- **Processes**: 1134
- **Uptime**: 2d 20h 19m
- **Init System**: systemd v255
- **Packages**: 27 (1 dpkg, 26 flatpak)
- **Shell**: Bash v5.2.26
</details>

**Comment by notpeter** [comment]
I can reproduce this in Zed Stable. I believe it is fixed in Zed Preview.
You can no longer move file tabs into the Assistant Panel (dragging a file now drops it as `/file`).  You can alternately drag an Assistant context out of the Assistant Panel into a split of the main Editor pane and accomplish the same thing in your screenshot, but without the bug.

If you can reproduce the issue on Zed Preview or after next week's Zed Stable let me know and I'm happy to reopen.

In the future please provide your system specs (cmd-shift-p, "zed: copy system specs to clipboard") in your issue description. 

Thanks for reporting!
