### ISSUE TITLE
Zed can't open a specific folder

### ISSUE THREAD

**Issue by gggritso** [zed-industries/zed#18224]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Similar to https://github.com/zed-industries/zed/issues/7264 but different! There's one folder on my machine that Zed can't seem to open. Other folders all work fine. Does not hang, but doesn't open any UI, either.

1. Clone https://github.com/getsentry/sentry-docs to a new directory
2. `cd sentry-docs`
3. `zed .`

Zed launches, but does not open an actual window. I can technically ctrl-tab to the missing window, and it's listed in the application icon's context menu, but there's no actual window and no way to do anything with it except exit. Same thing happens if you open that folder through Zed's UI while another folder is open. Other editors can open the folder.

### Environment

Zed: v0.153.6 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="292" alt="Screenshot 2024-09-23 at 9 04 18 AM" src="https://github.com/user-attachments/assets/9290b245-23f3-405d-a1fa-65e04277037e">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-23T09:02:08.879862-04:00 [INFO] open paths ["/Users/my-username/path-to-code/sentry-docs"]
</pre></details>

**Comment by SomeoneToIgnore** [comment]
![image](https://github.com/user-attachments/assets/919f93bc-13de-491d-b380-35d678257a3a)

Interesting, seems to work for me.
And if that's all logs that you've provided, does not seem that it's breaking explicitly either..

I recall there were odd bugs when something odd was stored in the database.
What happens if you navigate into `~/Library/Application Support/Zed/db/` and `mv` a corresponding directory (`0-stable/`) away somewhere?

If things start to work and you do not mind sharing that directory, I'd love to have a look at the contents of it.

**Comment by gggritso** [comment]
@SomeoneToIgnore thanks for the reply! `mv`ing `0-stable` fixed the problem 🙌🏻 

As for the contents, I had to sanitize the file names a little bit, but here's a SQLite file which, if placed back into `0-stable`, reproduces the problem for me. Hopefully that helps!

[db.sqlite.zip](https://github.com/user-attachments/files/17098928/db.sqlite.zip)

**Comment by JosephTLyons** [comment]
This seems a bit weird, since something funky was going on in your workspace db. There's certainly some issue at play here, but since we don't really have any good leads, I think I will close this out. If we run into a bunch of other users hitting this aggressively, we can investigate - I'm hoping this is just some strange one-off weird migration thing.

**Comment by SomeoneToIgnore** [comment]
Found it: 
```
sqlite> select window_width, window_height from workspaces where workspace_id=4;
1.0|1.0
```

So we have a "bug" which allows us to somehow shrink the window into a very-very small one and then, when we deserialize, we keep that size without a way to expand.


The related issue is https://github.com/zed-industries/zed/issues/13812 but I'm not sure how to fix that yet.
