### ISSUE TITLE
Problem when work through Cryptomator fuse-t drive

### ISSUE THREAD

**Issue by swayll** [zed-industries/zed#18388]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

I work with my projects using an encrypted Cryptomator drive via fuse-t (рerhaps it matters, python projects with the pytrightconfig configuration).
Earlier, until about version 0.149-150, everything was fine, files were opened, edited, but with the latest updates, when opening the project folder and trying to open the file, the cryptomator disk (fuse-t) crashes, I have to forcibly lock the disk.
<img width="293" alt="Снимок экрана 2024-09-26 в 13 16 55" src="https://github.com/user-attachments/assets/7418c771-bf04-4b77-95ec-213509b2da52">
After reopening, next to the file that was previously attempted to open, appears the macos service file "._" (with the name of the target file). I installed an earlier version of Zed for verification and the problem was gone.

### Environment

Zed: v0.154.2 (Zed)
OS: macOS 13.6.9
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>
[Zed.log](https://github.com/user-attachments/files/17146765/Zed.log)</pre></details>

**Comment by notpeter** [comment]
Zed is interfacing with that software only using the normal operating systems call for reading and writing files/directories on the filesystem. If it is crashes, it's more likely because it cannot actually handle a high volume of reads in parallel. Often times FUSE filesystems work great of low volume access but once you try to read/write multiple files simultaneously everything falls apart.

The fact that it worked in the past may have been a fluke or it could be an area where Zed now has improved parallelization seeking better performance. If you can track down a particular commit where prior to the change Zed works and after it Zed does not (via a git bisect) we might be able to identify what changed, but in the absence of that, this is a cryptomator bug (a filesystem should never crash) and I recommend you [file an issue](https://github.com/cryptomator/cryptomator/issues) with them.

Good luck!
