### ISSUE TITLE
Typescript file wrongly identified as Javascript if shebang `#!/usr/bin/env -S yarn run ts-node`

### ISSUE THREAD

**Issue by nathanael-ruf** [zed-industries/zed#18430]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Basically the title.
We have many ts scripts with the shebang `#!/usr/bin/env -S yarn run ts-node`.
All of them are detected as JS. I need to change the type manually and restart the language server every time I open one of these.

### Environment

Zed: v0.155.0 (Zed Preview)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
I believe this is happening because the Javascript language has a `first_line_pattern` regex defined:
https://github.com/zed-industries/zed/blob/580c490d9e1f98051f312a34946b47d54e281ca1/crates/languages/src/javascript/config.toml#L1-L6

But the Typescript language does not:
https://github.com/zed-industries/zed/blob/580c490d9e1f98051f312a34946b47d54e281ca1/crates/languages/src/typescript/config.toml#L1-L4

**Comment by nathanael-ruf** [comment]
That workaround works, thank you!
