### ISSUE TITLE
Add Automatic Virtual Environment Detection for Python Projects

### ISSUE THREAD

**Issue by tuklu** [zed-industries/zed#18505]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**Feature Request: Automatic Virtual Environment Detection**

**Problem:**
Currently, when using Zed for Python projects with virtual environments (like `.test` or `.venv`), Pyright doesn't automatically detect the virtual environment. This requires manually adding a `pyrightconfig.json` file for each project, specifying the `venvPath` and `venv`, which can be cumbersome.

**Proposed Solution:**
Add a feature where Zed automatically detects Python virtual environments in common directories (e.g., `.venv`, `env`, `.test`) without needing to manually configure `pyrightconfig.json`. This could work similarly to how VSCode handles Python virtual environments by detecting the active environment within the project folder.

**Benefits:**
- Reduces setup time for Python developers.
- Provides a smoother developer experience, especially for users who frequently switch between projects with different virtual environments.
- Ensures that Pyright works out of the box with common Python setups.

**Examples:**
In VSCode, the editor automatically picks up a virtual environment located in the project root or subdirectories like `.venv` without needing manual intervention.

Thanks for considering this request! 🙌

### Environment

Zed: v0.154.3 (Zed)
OS: macOS 15.0.0
Memory: 8 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @tuklu,

I think what you are requesting here is covered by the following issue.

- https://github.com/zed-industries/zed/issues/7808

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

Also, you might have some extra details here we would like over there, feel free to add a comment to capture some of this in that thread.
