### ISSUE TITLE
Enhanced Documentation Retrieval for Third-Party Libraries (ai assistant)

### ISSUE THREAD

**Issue by erik-balfe** [zed-industries/zed#18508]
### Check for existing issues

- [X] Completed

### Describe the feature

To effectively develop projects that use third-party libraries, accessing accurate documentation is crucial. Current tools, like Sonnet 3.5, can miss information due to outdated knowledge about these libraries.

I propose a documentation retrieval system in Zed IDE that provides real-time access to third-party library documentation. This would work similarly to the system in Cursor, where Zed AI maintains an updated index for commonly used libraries, allowing developers to access relevant documentation quickly.

The system should utilize existing embeddings for code. By creating embeddings for full documentation and for specific queries or dialogue summaries, it could perform similarity searches to find pertinent documentation sections with relevant context. This would streamline development by granting immediate access to needed documentation without manual searching.

Implementing this in hosted Zed AI has advantages over traditional IDEs requiring API keys. The Zed team can maintain indexes for popular libraries, saving time on embedding generation and improving retrieval speed. This eliminates reliance on commands like /fetch or manual copy-pasting of documentation.

Enhancing documentation retrieval will improve the experience for developers working with third-party libraries in Zed IDE.

**Comment by notpeter** [comment]
There is limited support for this already in Zed, but it is behind a feature flag because it only supports Rust (docs.rs).  To enable this feature use:
```
  "slash_commands": {
    "docs": {
      "enabled": true
    }
  },
```

<img width="575" alt="Screenshot 2024-10-13 at 11 34 28" src="https://github.com/user-attachments/assets/61a36a43-e7eb-4d9d-9932-25305628df7c">

We hope to add support for additional docs providers in the future, but in the meantime you can see how this is implemented with docs.rs by looking at [crates/indexed_docs](https://github.com/zed-industries/zed/blob/main/crates/indexed_docs/) in the repo.
