### ISSUE TITLE
Markdown preview: list items should indent

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#18540]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice if the list items were aligned as seen on the others.

Zed:
<img width="735" alt="Screenshot 2024-09-30 alle 16 47 04" src="https://github.com/user-attachments/assets/59447559-cd1e-4b8b-ab1a-b340d910cf44">

Vscode:
<img width="668" alt="Screenshot 2024-09-30 alle 16 47 56" src="https://github.com/user-attachments/assets/dee5dda0-6d5c-4979-a6a9-081d2d791a25">

Github:
<img width="590" alt="Screenshot 2024-09-30 alle 16 49 07" src="https://github.com/user-attachments/assets/be724c34-c7dc-438c-a9be-ff16a19a673e">

**Comment by notpeter** [comment]
To be clear, you're looking for unordered list items (`- ` and `* `) to be indented slightly from the left margin to make it more similar to GitHub and VSCode rendering?

**Comment by notpeter** [comment]
> @notpeter : Just looking at the pictures I think it's quite clear what's happening.

Your description included no mention of **indentation** and only mentioned alignment. Perhaps I should have closed the issue with `"invalid. items are aligned"` because you didn't bother to take the time actually describe your request.

Instead I asked a clarifying question and you chose to AGAIN *fail to define your request* and instead penned a snarky reply.

You're right, it is quite clear what's happening, you're choosing to be a jerk instead of being professional and respectful as is required by our [COC](https://zed.dev/docs/code-of-conduct). Do better.

**Comment by notpeter** [comment]
Happy to review PRs which improve such things, but it's too small to use a dedicated issue to track. Thanks for the feedback.
