### ISSUE TITLE
Markdown preview: code blocks: more horizontal padding

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#18542]
### Check for existing issues

- [X] Completed

### Describe the feature

As you can see from the image, the highlighted text needs a little bit of side margin, maybe a little less margin at the top and bottom, and a more rounded corner.

Zed:
<img width="509" alt="Screenshot 2024-09-30 alle 17 14 20" src="https://github.com/user-attachments/assets/567f29de-5126-492d-933d-7ee597875a66">

Vscode:
<img width="506" alt="Screenshot 2024-09-30 alle 17 14 52" src="https://github.com/user-attachments/assets/6dbcd624-c9ad-414d-a2db-4baee724d449">

**Comment by notpeter** [comment]
Always happy to review PRs to improve stuff like this, but it's is too small for a dedicated issue for tracking. Thanks.

**Comment by notpeter** [comment]
@Angelk90 This is notification spam. Do not tag multiple Zed folks in your comments asking them to take a look. This is not ok -- you have been warned.

> What does it mean: `but it's is too small for a dedicated issue for tracking`.

An issue is the wrong format for tracking individual pixel-level placement enhancements for a single component in Zed. It's just the wrong level of abstraction. It is not how our designers communicate internally and it is a distraction for everyone else using the issue tracker, both Zed team members and the community at large.

I'm closing this (and many similar issues) because if you have 3300 priorities you have zero priorities. 

You had multiple issues that tracked micro-level changes to markdown rendering alone:
- https://github.com/zed-industries/zed/issues/18540
- https://github.com/zed-industries/zed/issues/18601
- https://github.com/zed-industries/zed/issues/18602
- https://github.com/zed-industries/zed/issues/19062

Which is on top of the more than two dozen enhancement requests cataloged here:
- https://github.com/zed-industries/zed/issues/5346

None of those issues I closed are bugs. Nor are they things you're fixing (or tracking things you broke) -- they are mostly screenshots of things you wish were different. Opinions about Zed's design. I'm telling you our issue is a bad fit for that.

This isn't a criticism of you or the issues you've opened.
But please accept my apologies if it feels like it is.
Thanks
