### ISSUE TITLE
Zed finds a .DS_Store that vscode doesn't see

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#18620]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Looking on Zed I saw that it finds a `.DS_Store` that `vscode` doesn't see, when I try to open it with `Zed` it tells me: `Failed to open file stream did not contain valid UTF-8. Please try again.`

<img width="199" alt="Screenshot 2024-10-02 alle 12 39 42" src="https://github.com/user-attachments/assets/e313dcd6-e158-4093-b286-43e5b5bd443b">
<img width="222" alt="Screenshot 2024-10-02 alle 12 39 53" src="https://github.com/user-attachments/assets/810efb59-8042-482a-9d78-f1a8f5b4ba69">

### Environment

```
Zed: v0.155.2 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
Zed is also supposed to ignore this file by default due to
https://github.com/zed-industries/zed/blob/ff5b99db25d8e84c4bc3a156aa89ede8cbe5cd16/assets/settings/default.json#L581-L593

Can you ensure you don't have any overrides that exclude this file or anything spoiled in the config?

**Comment by SomeoneToIgnore** [comment]
> I opened the Zed project (Updated to the latest commit) with the latest version of Zed preview

Same did I and I see nothing:

![image](https://github.com/user-attachments/assets/ea97b784-30e3-4277-aaf9-bf5c9859082d)

That's why [in my previous message](https://github.com/zed-industries/zed/issues/18620#issuecomment-2388359054)
I've asked about the config:
> Can you ensure you don't have any overrides that exclude this file or anything spoiled in the config?

Zed project contains no local overrides for `file_scan_exclusions`, so it should be your settings.
Can you do `zed: open local settings` and check for `file_scan_exclusions` there? For errors too, just in case?
If nothing is odd and the file is there still, I'd commented the entire local settings and added `{}` below.

**Comment by SomeoneToIgnore** [comment]
So, you've removed them all by doing this.
If you set it to `[  "**/.DS_Store"]`, you'll hide the entries.
