### ISSUE TITLE
Search and replace does not use changes to the search text

### ISSUE THREAD

**Issue by ChaiTRex** [zed-industries/zed#18822]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Go to the `Edit` menu, and select `Find In Project`.
2. Search for some text that exists in the project.
3. Switch the search mode to replace.
4. Change the search text to a superstring of the original search text. The superstring should also exist in the project.
5. Enter replacement text.
6. Click to do one replacement.
7. Note that the originally-searched-for text is replaced, not the longer current search string.

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 15.0.1
Memory: 8 GiB
Architecture: aarch64

**Comment by notpeter** [comment]
I understand the confusion, but when using "Find in Project" we currently require explicitly pressing "Enter" on the search field to apply any changes there.  This is because any changes will require reloading all the result multi-buffers, which themselves could have been modified. 

When performing a find within a single buffer it behaves as you expect (automatically updating the highlighted terms matching, ready for you to click "replace") but the nature of the multibuffer used for find-in-project makes that difficult.  If typing altering the search string automatically recalculated the find results (e.g. after a 250ms delay) there could be different buffers for the new results. If you had manually edited one of the old buffers, but hadn't yet saved your changes, then typing a letter in the search box could trigger a Save modal which would be super confusing.

Thanks for reporting.
