### ISSUE TITLE
Add assistant command /selection, for action assistant: quote selection

### ISSUE THREAD

**Issue by AndydeCleyre** [zed-industries/zed#18868]
### Check for existing issues

- [X] Completed

### Describe the feature

I finally found the `assistant: quote selection` action and corresponding shortcut, which is great!

But I'd assumed it wasn't possible, because I expected such an action to be in the same place as the assistant slash-commands `/file` and `/tab`.

So I'm requesting an additional slash-command for the assistant, maybe `/selection` but the name doesn't matter much, that has the same effect as the existing action `assistant: quote selection`.

**Comment by counterleft** [comment]
👋 I have a draft of this feature ongoing.

I made a `SelectionCommand` slash command that basically copies the logic from [quote_selection()](https://github.com/zed-industries/zed/blob/6d5784daa6ca7edb03c903af367525cd48e2bc6f/crates/assistant/src/assistant_panel.rs#L2968-L3125). Instead of opening `assistant_panel` and creating `Crease`'s, I create sections (`SlashCommandOutputSection`) for each text selection. Those sections are added to the the resulting `SlashCommandOutput`.

Here's a video of the outcome: 

https://github.com/user-attachments/assets/e56ed552-e831-438a-886e-572ce1a57351

The 'no selections found' error case is inspired by the `diagnostics_command`.

This approach does duplicate much of `quote_selection()`. I could extract a method that takes the current editor selections and returns a list of tuples of the text required for both methods (label, text, selection ranges), though I don't know which file such a method would want to live.

**Comment by counterleft** [comment]
I just saw https://github.com/zed-industries/zed/pull/19988/files so my WIP may be moot. ¯\_(ツ)_/¯
