### ISSUE TITLE
local configuration should allow to set lsp settings

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#19060]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

At https://zed.dev/docs/configuring-zed, there's this sentence: "Not all settings can be set in local files, just those that impact the behavior of the editor and language tooling."
But, when I try to set a custom clangd in my local settings, it's not working.

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 15.0.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Please provide a copy of the local your settings that are not working for you.
Project-specific local settings for LSP are supported.

**Comment by hferreiro** [comment]
I'm sorry, it appears the issue was a badly constructed local settings. It appears that wrong keys on the settings file are not logged, right?

**Comment by notpeter** [comment]
There is some validation, which throws an error on invalid json or highlights an unexpected type/value (e.g. string where we expect an object) but we aren't strict in all contexts (e.g. `lsp` settings, areas impacted by extensions, etc) because it's not possible (or at least hard) to dynamically define a validation schema.

For example, we're unlikely catch a typo in inside `settings` or `initialization_options` for an LSP (we have no idea what's valid or not). Similarly if you have a key under `file_types` for a Language that doesn't exist for your running copy of Zed (e.g. `Handlebars` without the `Gleam` extension installed) I don't think we should necessarily highlight, because it **is** a valid setting when paired with that extension.

Always looking to improve though, if you have bad settings test case, paste it below and I'll investigate whether it's something we could/should validate.

Otherwise, ok to close?

**Comment by hferreiro** [comment]
In my case, I had the `lsp` setting inside `languages`.
