### ISSUE TITLE
Nix language server issue

### ISSUE THREAD

**Issue by unbreakabl3** [zed-industries/zed#19069]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Getting this error, when trying to open .nix file:

```
Language server error: nixd

The Nix language server (nixd) is not available in your environment (PATH).
                You can install it from https://github.com/nix-community/nixd.
-- stderr--
```

### Environment

Environment

Zed 0.156.1
OS: macOS 15.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Hi!

The [Nix Zed Extension](https://github.com/zed-extensions/nix) does provide the nix language server as you can see in [nix.rs](https://github.com/zed-extensions/nix/blob/main/src/nix.rs). 

In order to use the nix language server you will need to [install nixd](https://github.com/nix-community/nixd/blob/main/nixd/docs/editor-setup.md) like via nix itself.

On MacOS:
```sh
# install Nix
sh <(curl -L https://nixos.org/nix/install)

# quit your shell and reopen then
# install nixd
nix-env -iA nixpkgs.nixd

# check path nixd
which nix
```

Then Quit and restart Zed to pickup your new path information.
(Make sure you don't launch from an old Terminal that doesn't have nix pathing setup).
