### ISSUE TITLE
Terminal renders custom fish prompt wrongly

### ISSUE THREAD

**Issue by bitconym** [zed-industries/zed#19197]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The Zed embedded terminal shows the fish shell prompt like this:
![terminal prompt](https://github.com/user-attachments/assets/b8c72f2f-d3aa-44ee-877e-95283381cb81)

It should render it properly like this (VSCode):
<img width="552" alt="image" src="https://github.com/user-attachments/assets/4f2f927f-d93f-4212-a55a-028021e6e9c4">

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 15.0.1
Memory: 32 GiB
Architecture: aarch64
Shell: [fish](https://fishshell.com/), version 3.7.1
Plugin manager: [fisher](https://github.com/jorgebucaran/fisher), version 4.4.5
Prompt: [tide](https://github.com/IlanCosman/tide), version 6.1.1
Theme: [Dracula](https://draculatheme.com/zed)

**Comment by notpeter** [comment]
Yep. I believe adding this to your settings.json should fix it:
```
{
  "terminal": {
    "line_height": "standard"
  }
}
```
The NerdFont/Powerline characters do not properly support a line height taller than a single character as happens with our default `line_height` of `comfortable` (slightly taller than most terminals, to approximate the golden ratio). I believe this is because some of the glyphs are anchored to bottom (e.g. Apple Logo) and some are centered (`|>` arrow glyph)
