### ISSUE TITLE
CMD + Right is triggering something.  AI Autocomplete?  Not "end of line" in any case

### ISSUE THREAD

**Issue by VoiceNPO** [zed-industries/zed#19355]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

CMD+Right is sometimes triggering something that is not "end of line" (which is the only keybinding listed for it on your keybindings page).  I think it's AI autocomplete, but I'm not quite sure.

If there's a way to figure out what's being executed, let me know.

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/172b1746-626c-4245-9e8b-ee4481f43855

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
https://github.com/zed-industries/zed/blob/2bcf9fc4904fca6ea9aa24eba5a4df5259048e3d/assets/keymaps/default-macos.json#L153-L160

If you don't want this you can unbind it by adding this to you keymap.json:

```json
[
  {
    "context": "Editor && mode == full && inline_completion",
    "bindings": {
      "cmd-right": null
    }
  }
]
```

**Comment by VoiceNPO** [comment]
Thanks, but there are a few of other issues here

- in my video, you can see that there is no suggested completion, so you're blind to what's actually going to happen with the default bindings
- I would **STRONGLY** argue that you should not ever overload something as fundamental as "end of line" and that the default binding should be changed.
- This isn't documented.  According to https://zed.dev/docs/key-bindings, the only keybinding for https://zed.dev/docs/key-bindings is EOL

**Comment by notpeter** [comment]
> This isn't documented. According to https://zed.dev/docs/key-bindings, the only keybinding for ⌘ + Right is EOL

- For the moment, I recommend you reference [default-macos.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-macos.json) as the source of truth for key bindings.  You can also access this in-app via the `zed: open default keymap` from the command palette.

- There has been some work to generate our settings documentation from the source of truth in-repo, with the thought that we could do the same for keymaps, but that has been put on hold: https://github.com/zed-industries/zed/pull/16554

- We are aware that the docs at https://zed.dev/docs/key-bindings are out of date, these docs are currently manually maintained and thus chronically out of date.  Beyond this missing key, you will also notice it also Linux keymaps are entirely absent. Happy to review PRs.

> I would STRONGLY argue that you should not ever overload something as fundamental as "end of line" and that the default binding should be changed.

- I understand your feeling here, but we didn't just pull this out of a hat.  This key (like much of our default keymap) is borrowed directly from VSCode https://github.com/zed-industries/zed/issues/15487
![image](https://github.com/user-attachments/assets/ce3dffd1-7d57-4d8b-9fa2-a6ad1cb53409)

---
This is the thing with keybindings, there is no magical one size fits all solution which makes everyone happy -- and this is why we support custom keymaps.

**Comment by a-non-a-mouse** [comment]
You're apparently right, but also I've never once seen that in VSCode until I just went looking for it.  I couldn't even figure out how to trigger it without going to SO, lol.  There's apparently multiple different types of inline completions.  Anyway, there are a couple of key differences (2nd one is probably a bug):

- VSCode's inline suggestions of that exact fashion are opt-in, they're not default behavior (even with co-pilot and inline suggestions, they're in a different context, but I can't figure out how to inspect it because opening the inspector makes the context dissapear)
- Zed doesn't always show inline completions (even after waiting), yet CMD+right still triggers them.  So it is *impossible* to know what cmd+right is going to do

The net result here is that in years I've never once noticed VSCode do anything to my navigation keys other than sometimes block them if a popup is open.

With Zed, I'm constantly undoing stuff that it inserted/replaced/deleted.

I hope that doesn't sound too harsh :)  You guys have done some great work, this bit just needs some attention IMO.
