### ISSUE TITLE
AI model auto-fallback (iterate through list of AI models in config in case of connection error)

### ISSUE THREAD

**Issue by mchzimm** [zed-industries/zed#19371]
### Check for existing issues

- [X] Completed

### Describe the feature

able for zed editor to iterate through the list of AI models that the editor, to try and use the next one in the list in case of connection error; case scenarios:

out of tokens - using a cloud AI service and running out of tokens, should then try and run the next model in the list (another cloud AI model, or local model)

LAN run local model - if offline / not reachable due to different LAN and not available through public IP, then try to run the next model in the list

implementation:
iterate through listed model in config starting w/ 1st model, if connection error (optionally set timeout) then try next one; this should be done w/ each user req (call to LLM) to always reach first listed model as listed in config

**Comment by notpeter** [comment]
We are unlikely to implement this in the near future. Notably because different providers/models may have different tokenizers, prompts and feature support (tool calling, image support, etc). But it's also unclear to me what a reasonable set of defaults or tunable settings would look like.

My recommendation is if you need this, implement a local router which is connected to each of the models you use.

There are a number of such projects:
- https://github.com/BerriAI/liteLLM-proxy
- https://github.com/lm-sys/RouteLLM
- https://github.com/SomeOddCodeGuy/WilmerAI

Example complexity:

Imagine a simple case, single provider, multiple models. User wants to fallback to a cheaper model if they receive a 429 (e.g gpt-4 -> gpt-4o -> gpt-3.5). Cool. But once this fallback has occurred does it now default to the cheaper model? On every request does it retry the more expensive models? Or just after some timeout?  On a connection failure (which will apply to all models) what does it do?

Fallback between multiple local models is also problematic.  If you have a query which fails on a given model (e.g. out of memory, timeout) or malformed request...should the user see that error? Should it retry? Or should it just fallback another different model (which triggers unloading/reloading and significant delay) and try again?

Similarly, if you have temporary interruption (e.g. 5 second wifi hiccup) would you really want things to automatically switch models?  How does failback work?

There's definitely room for improvement here, but I think we're better off without a half-baked implementation just so it's easier for a few folks to jump between various VC-subsidized "free tier" quotas.

Thanks for reporting. Interesting to think about.
