### ISSUE TITLE
Transparency on Windows.

### ISSUE THREAD

**Issue by thedeveloper-sharath** [zed-industries/zed#19405]
### Check for existing issues

- [X] Completed

### Describe the feature

I did check the existing GPUI issue and all but nowhere we see windows support mentioned for transparency. I am not a rust expert but since windows does provide this effect via mica and mica alt, I would definitely like to see this implemented on windows.  

There is already a crate that will provide this functionality
https://docs.rs/window-vibrancy/latest/window_vibrancy/index.html.

I tried around a bit, but due to me being a complete novice when it comes to rust, i am getting a truck load of compile and runtime errors. Will be great if someone can pick this up. I know not a burning problem, but seeing that both linux and macos already got this, would love this on windows. 

Currently when i apply catpucchin blur theme this is how it looks
![image](https://github.com/user-attachments/assets/be47f911-bd6a-473f-8a2f-a8c8e80d0d62)

**Comment by dovakin0007** [comment]
@thedeveloper-sharath could try building it and see how it works? and please do feel free to edit it

**Comment by thedeveloper-sharath** [comment]
> @thedeveloper-sharath could try building it and see how it works? and please do feel free to edit it

I tried around a bit, but due to me being a complete novice when it comes to rust, i am getting a truck load of compile and runtime errors. Will be great if someone can pick this up. I know not a burning problem, but seeing that both linux and macos already got this, would love this on windows.

**Comment by dovakin0007** [comment]
> > @thedeveloper-sharath could try building it and see how it works? and please do feel free to edit it
> 
> 
> 
> I tried around a bit, but due to me being a complete novice when it comes to rust, i am getting a truck load of compile and runtime errors. Will be great if someone can pick this up. I know not a burning problem, but seeing that both linux and macos already got this, would love this on windows.

Yeah I have added mica effect you can take a look

**Comment by thedeveloper-sharath** [comment]
which branch?

**Comment by dovakin0007** [comment]
> which branch?
> 
> 

There should be one for transparency

**Comment by thedeveloper-sharath** [comment]
> > which branch?
> 
> There should be one for transparency

got it. I didn't see the branch before. let me try

**Comment by thedeveloper-sharath** [comment]
@dovakin0007 I am compiling on wsl to make sure it does not break on linux. I don't have access to mac to check on that

**Comment by dovakin0007** [comment]
> @dovakin0007 I am compiling on wsl to make sure it does not break on linux. I don't have access to mac to check on that

for mac and linux it should be fine I haven't made any changes their and also the build hasn't failed

**Comment by thedeveloper-sharath** [comment]
> > @dovakin0007 I am compiling on wsl to make sure it does not break on linux. I don't have access to mac to check on that
> 
> for mac and linux it should be fine I haven't made any changes their and also the build hasn't failed

confirmed, works

**Comment by dovakin0007** [comment]
this can be closed

**Comment by SomeoneToIgnore** [comment]
Closed in https://github.com/zed-industries/zed/pull/20400

**Comment by rainbowflesh** [comment]
Broken in newer version, neither `blurred` and `transparency` work since commit `94b75f3ad95eadc29b76218696fbd054642ace45`.

**Comment by Tiktack** [comment]
I know that this issue is closed, but from what I can see right now, we can get transparency on windows. But author of this issue mentioned mica and mica alt, not just transparency. Is it already possible to enable mica in a latest stable version? If no, should we create another issue?
@SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
Another issue sounds better to me.

**Comment by dovakin0007** [comment]
> I know that this issue is closed, but from what I can see right now, we can get transparency on windows. But author of this issue mentioned mica and mica alt, not just transparency. Is it already possible to enable mica in a latest stable version? If no, should we create another issue?
> @SomeoneToIgnore 

Mica can be added but it doesn't match with other platforms behaviour so we didn't add it  during that time

**Comment by congchuahiep** [comment]
> I know that this issue is closed, but from what I can see right now, we can get transparency on windows. But author of this issue mentioned mica and mica alt, not just transparency. Is it already possible to enable mica in a latest stable version? If no, should we create another issue? [@SomeoneToIgnore](https://github.com/SomeoneToIgnore)

Mica can indeed be enabled in GPUI, but the problem is that once it's active, font rendering becomes noticeably worse—text looks blurry, fuzzy, and unpleasant, as shown in the screenshot I shared. When Mica is disabled, the fonts return to being sharp and easy to read. This is the real reason why Zed hasn't enabled Mica yet. It's not about "inconsistent behavior across platforms," as @dovakin0007 suggested, but rather the fact that Mica introduces serious font rendering issues that negatively affect the user experience.

<img width="602" height="451" alt="Image" src="https://github.com/user-attachments/assets/330e2ec7-1538-40e4-8799-68119eb37626" />

When disable the Mica effect, the font look much better

<img width="602" height="451" alt="Image" src="https://github.com/user-attachments/assets/bca529b3-5f20-4ddc-acdf-43eec6dccc01" />
