### ISSUE TITLE
Failed to build from source on ubuntu18.04

### ISSUE THREAD

**Issue by Zhou-Pixel** [zed-industries/zed#19504]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Failed to link zed binary

![图片](https://github.com/user-attachments/assets/77c90476-8122-4e32-be27-d7aa4a87f941)

### Environment

uname -a

![图片](https://github.com/user-attachments/assets/5180a87c-b8f5-438e-be1a-1ec69c3bccd1)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Ubuntu 18.04 is EOL and is not a supported distribution.

That said the issue you're running into is because Ubuntu 18.04 ships with a too-old ZSTD.
You should be able to install a newer version of ZSTD manually from [facebook/zstd/releases](https://github.com/facebook/zstd/releases) into /usr/local (you might have to `apt-get remove libzstd-dev` too) and get past this error.
