### ISSUE TITLE
Suggestion: remove_trailing_whitespace_on_save should default to false for Markdown files

### ISSUE THREAD

**Issue by nevadascout** [zed-industries/zed#19528]
### Check for existing issues

- [X] Completed

### Describe the feature

The setting `remove_trailing_whitespace_on_save` defaults to `true` which is fine for most cases except when editing Markdown files.

Markdown files can contain a line with two trailing spaces, which functions the same as a `<br>` in HTML.

It is possible to bypass this by adding this to your settings, but I think this should be disabled for Markdown files like this by default?
```
"languages": {
  "Markdown": {
    "remove_trailing_whitespace_on_save": false
  }
}
``` 

Currently in the default Markdown settings it has `"format_on_save": "off"`, but it still removes trailing whitespace thanks to the aforementioned setting.

**Comment by notpeter** [comment]
This is a design choice.  Currently for all file types (except `Diff`) by default we enable `remove_trailing_whitespace_on_save`.

The Markdown docs explicitly call this out and suggest the same settings as you have above: https://zed.dev/docs/languages/markdown

In the near future (this week for Zed Preview, next week for Zed Stable) `.editorconfig` will also be supported, so Zed will respect an .editorconfig in your repo that contains:
```
[*.md]
trim_trailing_whitespace = false
```

**Comment by nevadascout** [comment]
I doubt many people read the documentation for each language before they start editing files! I disagree with this design choice, but I respect it.

I look forward to editorconfig support, that will be great - thanks for the info 👍

**Comment by ethanmsl** [comment]
With all respect: having the default settings destroy all Markdown formatting is _absolutely mental_.

That would be like having the default Python interpreter remove all indenting in the name of consistency.  
It's  huge pain.  And a large % of the potential audience isn't going to be willing to go into json settings to try to get default functionality working.

As long as I'm here I'll also add I'm not even sure how to get the settings to turn off all the text breaking:

![markdown_formatting](https://github.com/user-attachments/assets/569c8339-45c2-49ee-bc99-19496ff124ab)

e.g.  all I want to do here is move 3 lines over by the same amount of spaces.  But all the `false`, `"off"`, `disabled`, `null` settings in `Markdown:` that I can muster won't stop the IDE from telling me how to write notes.
<img width="504" alt="markdown settings" src="https://github.com/user-attachments/assets/999b42e4-9f4e-4917-8168-de0825f8c2f2">

And I'm someone that has spent quite a bit of time going through your docs.

It's to the point that if I need to edit markdown I just don't do it in Zed.  I'm writing notes there so that I can use vim and write whatever I want -- but I'd apparently have to spend even more time in your docs just to figure out how to set it to not do anything.

**Comment by taciturnaxolotl** [comment]
I would agree here; It makes it next to impossible to insert line breaks in Markdown, as you need 2 extra spaces at the end of a line. Please make this `false` by default.

**Comment by notpeter** [comment]
@ethanmsl If would like to report a problem with multi-line editing in markdown code blocks, pasting a gif in a comment on a closed issue is likely an ineffective path to getting this fixed. I'd suggest a creating a clean issue with step-by-step instructions which trigger the issue and what you expected should happen & suggestions to improve the behavior.

---

> With all respect: having the default settings destroy all Markdown formatting is absolutely mental.

With all respect: having the presence/absence of invisible trailing whitespace **sometimes** alter the behavior of code is bonkers.

--- 

I absolutely understand the position of everyone who disagree with this decision by Zed. Really, I do. The Markdown spec says you can use trailing whitespace and so you want to be able to use trailing whitespace.  

My response is that Zed absolutely supports editing in such a mode (trailing whitespace is significant) but just requires you to explicitly communicate via `.editorconfig`:

```toml
[*.md]
trim_trailing_whitespace = false
```

That's it.

It also has the pro-social side-effect that collaborators, using any editor (vscode, vim, emacs, jetbrains, etc), will behave appropriately too.

**Comment by eric-seppanen** [comment]
Note also that rustdoc comments are Markdown too, which means that stripping trailing spaces from the end of a rust `///` comment can also change the documentation output.

This is more subtle, as it wouldn't make sense to say "Don't remove trailing whitespace on .rs files"-- ideally the decision to remove whitespace would need to be based on the language syntax.

vscode handles this correctly, fwiw.

**Comment by notpeter** [comment]
@eric-seppanen Are you saying with `trim_trailing_whitespace` enabled for Rust, but disabled for Markdown in VSCode won't delete trailing whitespace in Rust comments? That's wild!

**Comment by eric-seppanen** [comment]
The vscode behavior I am seeing is part of the `editor.formatOnSave` setting. If I enable `files.trimTrailingWhitespace` then vscode does remove trailing whitespace everywhere.

Sorry, I guess I was comparing two dissimilar things.

**Comment by Hammerklavier-cn** [comment]
Zed editor needs to obey Markdown spec, not the other way around. This is why I define zed removing trailing white space as a BUG (#23677). `remove_trailing_whitespace_on_save` should be set to off by default.

> With all respect: having the presence/absence of invisible trailing whitespace sometimes alter the behavior of code is bonkers.

With all respect: Allowing it or not, it is up to us. Considering it unacceptable that trailing white spaces alter the behavior of code does not change the fact that zed fails to adapt to Markdown syntax.

You could have developed a more complicated mechanism to parse syntax and determine whether trailing spaces can be safely deleted. Maybe the task can be handed to prettier, but I don't think removing any trailing white spaces regardless of syntax is a good choice.

**Comment by insane-dreamer** [comment]
Just want to point out that this doesn't only affect Markdown files. It also affects triple quoted strings in python -- all of ours were being modified on save, driving us nuts; we couldn't figure out why until we finally found this setting. (We also couldn't figure out what it was changing until we leaded the file in Sublime Text because Zed doesn't have a way to show hidden characters.)

**Comment by colinbate** [comment]
@insane-dreamer For what it's worth, you can add `"show_whitespaces": "all"` to display the trailing spaces. That said, trailing whitespace is significant in Markdown and should be left alone.

**Comment by alex-konkov** [comment]
Let me configure IDE to NOT change my files if this is a design choice for users. Make yourself happy by having it by default, but leave users with an ability to disable it.

**Comment by octobocto** [comment]
This also messes up and changes my inline SQL in golang. Go has a great built-in formatter. Don't override it.. This is a very strange default imo, no other editor I've used does this.

**Comment by Derjyn** [comment]
Glad to come in and find we can implement a solution to this easily, however it seems the steps to do so have changed from what was previously noted, or I just found a different path. Just in case anyone else stumbles in here scratching their head, here is how I tweaked this specific whitespace knob:

Hit the hotkey for `zed: open settings file` and check/integrate the Markdown settings (_other settings omitted_):

```json
{
    "languages": {
        "Markdown": {
            "remove_trailing_whitespace_on_save": false,
        }
    }
}
```

I'm also using Prettier in my setup, and not sure if that will add some complexity to the combination of potentially troublesome settings; Another setting I personally set in the `"Markdown"` section is:

```
"format_on_save": "off",
```

Hopefully that is helpful!

<details><summary>On a more personal note...</summary>
<p>While developers obviously reserve the right to have opinionated design choices, part of being maintainers of a popular project is being prepared to be questioned about those choices and present alternative solutions if possible. This shows maturity, experience, and a care for the users that make the project popular in the first place. History has shown the alternative - being stubborn and acting with emotional malice toward anyone who dare question a choice, not offering an explanatory "why" (<em>whether it be technical constraints or simply preference</em>) - can leave a bad mark on the project and/or the maintainers interfacing with the users.</p>

<p>All that being said, users and maintainers alike would do good to remember that tone doesn't always translate well over the internet. Even being a moody sunnuva gun with no time to be patient, my habit is to assume good intent and friendly tone from whoever I'm communicating with. I mention this bit, because issues related to design choices come up often in projects, and is easily one of the top sources of friction between team members, maintainers, and users. It shouldn't be - opinionated design choices exist, and should be embraced. People should be ready to offer information on those decisions, which should be easy enough if internal documentation has already addressed those decisions.</p>

<p>In the end, I'm glad this is resolved. I love Zed and the team behind it, and I hope in the future issue scenarios like this get resolved even more efficiently, in a friendly/professional manner. That, my fellow nerds, is how the heartbeat of open-source pulses 💪</p>
</details>
