### ISSUE TITLE
Enable Prettier only if have prettier config

### ISSUE THREAD

**Issue by Cool9977** [zed-industries/zed#19534]
### Check for existing issues

- [X] Completed

### Describe the feature

By default I use Eslint for formatting and Linting for my JS/TS projects. But sometime for small project like cloudflare worker, I want to use Prettier. 

So if prettier only enable when have config then this problem can be solved. Or is there any other way ? Yes I know I can override zed config on project basis. But If prettier can be enable when have config that will be awesome

### If applicable, add mockups / screenshots to help present your vision of the feature

Currrent config

```json
    "JavaScript": {
      "language_servers": ["emmet_language_server", "tailwindcss-language-server", "..."],
      "prettier": { "allowed": false },
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true,
          "source.organizeImports": false
        }
      }
    },
    "JSX": {
      "language_servers": ["emmet_language_server", "tailwindcss-language-server", "..."],
      "prettier": { "allowed": false },
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true,
          "source.organizeImports": false
        }
      }
    },
    "TypeScript": {
      "language_servers": ["emmet_language_server", "tailwindcss-language-server", "..."],
      "prettier": { "allowed": false },
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true,
          "source.organizeImports": false
        }
      }
    },
```

**Comment by notpeter** [comment]
As you know, Zed uses prettier by default for formatting. Part of the Prettier ethos is having good defaults such that it can be used in most installations with requiring configuration.  For example, we use Prettier at Zed, but the Zed repo does not contain a .prettierrc.

As I understand your request, it implies that every repo would need to include a prettierrc (even if empty) or explicitly have a `.zed/setttings.json` directive to opt-in to using prettier.  Our current setup is an intentional design choice, such that Prettier is used by default for most languages and if you don't want this, you have to opt-out via user or project settings.

I think for the moment my suggestion is that you include Zed settings in your project when you need to deviate from the Zed defaults.  This also has the benefit that collaborators on those repos using Zed will get the correct settings even if they have no user settings defined.

Thanks for reporting, I definitely had to think through this a bit.
If I've misunderstood things, please add a clarifying comment below.
