### ISSUE TITLE
Remote development: Daemon does not respond to signals and cannot be shut down

### ISSUE THREAD

**Issue by almereyda** [zed-industries/zed#19784]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When logging in to a remote via SSH, the connection is not terminated upon closing the Zed client. This  behaviour is intentional:

- https://zed.dev/docs/remote-development#maintaining-the-ssh-connection

While it is possible to SIGTERM (15) the Zed development servers in proxy mode manually (`zed` processes), neither this nor SIGKILL (9) will be responded to by the SSH control master daemon (`zed -F` process?). This in turn means the daemon cannot be shut down.

### Environment

Zed: v0.158.2 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 125.7 GiB
Architecture: x86_64
GPU: AMD Radeon RX 570 Series (RADV POLARIS10) || radv || Mesa 24.0.5-1ubuntu1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

- The Zed Daemon reacts to life cycle signals.
- It is possible to remotely shutdown a Zed daemon, e.g. automatically upon logout of the last client or manually with a special command.

### If applicable, attach your Zed.log file to this issue.

Does not apply.

### References

- #5347
- #15910
- #18931

**Comment by mrnugget** [comment]
> When logging in to a remote via SSH, the connection is not terminated upon closing the Zed client. This behaviour is intentional:

That's not quite correct: when you close the Zed client (or even the window in which you have the SSH project open), it should shutdown the remote server and kill the connection.

We do keep the server running when you your connection dies so that when we try to reconnect, we can reuse the server. But if there is no reconnect within 10min, the server will shut itself down. If the client is closed and then reconnects to the host, if a running server is found, it's also shut down.

**Comment by mrnugget** [comment]
Closing this for now, since I'm pretty sure the daemon now shuts down correctly and it always has responded to `kill -9`, which is what we used for testing. Happy to reopen if there's an actual problem still.
