### ISSUE TITLE
Commit a9f48bd should be reverted, the musl shouldn't be a default libc

### ISSUE THREAD

**Issue by stalkerg** [zed-industries/zed#19803]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This commit a9f48bd  break compilation script for glibc distors (most?! except Alpine) and where Rust managed by pkg manager (because you have `rustup` call). 

### Environment

Gentoo Linux but it doesn't matter here, it's should affect many other

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment]
> musl shouldn't be a default libc

Why?

**Comment by stalkerg** [comment]
> Why?

1. In Linux glibc is a default libc, except Alpine Linux which try to reduce binary sizes. 
2. Musl has a lot of limitation and performance penalties. Glibc much more mature libc. 
3. musl support is good, but as default libc it's too much. Will be good to have options.

**Comment by SomeoneToIgnore** [comment]
1. Yes, glibc is the default on some systems (water is wet), but that did not answer why "musl shouldn't be a default libc".
2. Seems to work for us just fine, please provide some reproducible measurements of the "limitation" and "performance penalties"
3. So, "musl shouldn't be a default libc" because it "Will be good to have options."? Great, but does not excuse the categorical tone of the issue.

**Comment by SomeoneToIgnore** [comment]
To note on top of that, 

>  break compilation script for glibc distors (most?! except Alpine) and where Rust managed by pkg manager (because you have rustup call).

This mixes libc "issues" with `rustup` issue which is not very good to do, as those are very separate issues.


To comment the rustup one, I'll quote my reply to you in the PR you've commented: 

> We strongly rely on the rustc version from https://github.com/zed-industries/zed/blob/main/rust-toolchain.toml and do not guarantee that other set-ups work.
> This file needs rustup to function automatically, hence we strongly rely on it too.
> 
> Other people with alternatives should know what they are doing and are expected to handle fall-outs of their cleverness themselves.

**Comment by stalkerg** [comment]
> Yes, glibc is the default on some systems (water is wet), but that did not answer why "musl shouldn't be a default libc".

sorry, but not for "some" but most. 

> Seems to work for us just fine, please provide some reproducible measurements of the "limitation" and "performance penalties"

You can read difference here https://wiki.musl-libc.org/functional-differences-from-glibc for example host resolve can be broken on system which relay on glibc. 
For runtime performance you can read here https://edu.chainguard.dev/chainguard/chainguard-images/working-with-images/images-compiled-programs/glibc-vs-musl/#runtime-performance

> Great, but does not excuse the categorical tone of the issue.

sorry for my tone, I just was too surprise a such decision without any discussions which can break a lot of things and provide performance penalty. 

> To comment on the rustup one, I'll quote my reply to you in the PR you've commented:

1. before it's worked fine
2. rustup is not a part of tool-chain it's external tool to manage a such tool-chains.

**Comment by stalkerg** [comment]
Can you reopen this ticket at least until we have here discussion? 
Also good article https://pythonspeed.com/articles/alpine-docker-python/

**Comment by SomeoneToIgnore** [comment]
What stops you from discussing it further in the closed issue?

**Comment by stalkerg** [comment]
> What stops you from discussing it further in the closed issue?

difficult to find more opinions? If ticket is open other users can confirm it and add context, or provided arguments where I am wrong. 
Close ticket usually means, you don't want to talk about this issue, especial with "not planned" status.

**Comment by SomeoneToIgnore** [comment]
My problem with this issue is how poorly it is formulated, as the question is a half of the answer.
I would keep this one closed, as:

* it mixes badly build issues with libc (something global and potentially "hard" to solve + it needs proofs that things are degraded there) and rustup (something related to one script, quite simple to fix + super easy to retest)
* the tone of the issue and revert claims are based on "I want to build things my way" and "musl seems bad, here's the article for Python and Docker builds"

As we seem to have arrived to https://github.com/zed-industries/zed/pull/19571#issuecomment-2439998139 the whole approach has to be different: 

* unless (for Zed application only!) there's an issue with musl libc that **is reproducible and has some numbers to compare**, we do not revert any of the musl changes at all. 
Instead, we have to allow to build things with other libc somehow, on a side.

* `rustup` approach is not supposed to be reverted at all, something on a side for other users might be ok to have.


So, it seems that instead of issues and discussions with many useless words, there has to be 2 PRs with a small, standalone, non-default, changes for people who prefer building things their way.

And, frankly, while it's all for Gentoo, I would prefer to keep this in ebuidls too, unless the PRs are simple and small.

**Comment by stalkerg** [comment]
I agree, my apologies. 
Do we have any benchmarks inside Zed?

**Comment by SomeoneToIgnore** [comment]
We seem to have only one microbenchmark, related to text data structure: https://github.com/zed-industries/zed/blob/5506669b0654add16dca8447332f4804a4cea0d8/crates/rope/benches/rope_benchmark.rs#L60

I have no clue how libc usage is supposed to be benched at all, to be honest.

**Comment by stalkerg** [comment]
ouch, I tried to build Zed with musl and rustup on ArchLinux and got error:
```
The following warnings were emitted during compilation:

warning: ring@0.17.8: Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-gcc` installed?
warning: ring@0.17.8: Compiler family detection failed due to error: ToolNotFound: Failed to find tool. Is `musl-gcc` installed?

error: failed to run custom build command for `ring v0.17.8`
```

It seems like musl developers now should have musl-gcc in the system, which does not automatically exist for glibc distros. 

Should I create a new ticket?

**Comment by stalkerg** [comment]
Yes, you add 
    musl-tools
    musl-dev
only to Debian deps; all other distros are now broken in `script/linux` (I didn't use it but still)
