### ISSUE TITLE
Running Zed as root returns "Found PID 58727 bound to PID file "/run/zed.pid""

### ISSUE THREAD

**Issue by LolzTheDev** [zed-industries/zed#20116]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I removed the Zed binary from `~/.local/bin` and running `sudo zed` still returns `Found PID 58727 bound to PID file "/run/zed.pid"`

Is this normal?

### Environment

(Using KDE settings to find this)

Operating System: Linux Mint 12
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-47-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700U with Radeon Graphics
Memory: 15.0 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Acer
Product Name: Aspire A315-44P
System Version: V1.01

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

Found PID 58727 bound to PID file "/run/zed.pid"
</pre></details>

**Comment by LolzTheDev** [comment]
forgot to add that killing it just restarts it as root

**Comment by jansol** [comment]
**Do NOT run Zed as root.** [1]

(In fact, do not run any GUI applications with sudo, period. Aside from the usual X11-as-root security problems, GUI applications e.g. have a habit of touching things like Qt and GTK config files which then has very fascinating ripple effects on the rest of the system when they suddenly aren't accessible to your user because they were edited by root once.)

For editing system files etc that requires elevated permissions, see #13585 and #13259 

[1]: Unless of course you know *really* well what files it will access, what subprocesses it will launch and what files *they* will access - because ALL of that is going to happen as the root user, with root privileges, and all created files (including temp, pid and configuration files, and zed itself whenever it auto-updates) will be owned by the root user in that case.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/issues/19648#issuecomment-2445051914
