### ISSUE TITLE
Formating big json (>1M) cause 100% cpu usage

### ISSUE THREAD

**Issue by zhongyi51** [zed-industries/zed#20236]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I:
1. copy-paste a compat json file (>1m) to zed; [example](https://json-generator.com/)
2. click ctrl+shift+L to format the json **more than one time**;

Then:
1. each click open a new process of json LSP
2. each LSP process fully occupies a cpu core

Finally:
1. all cpu cores are occupied and the total usage is 100%

Possible solutions:
1. optimize the performance of json LSP
2. kill the LSP after timeout

### Environment

Zed: v0.159.10 (Zed)
OS: macOS 12.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-11-05T21:12:54.302401+08:00 [WARN] timed out waiting for formatting
2024-11-05T21:13:10.583931+08:00 [WARN] timed out waiting for formatting
2024-11-05T21:13:16.545007+08:00 [WARN] timed out waiting for formatting
</pre></details>

**Comment by notpeter** [comment]
I assume instead of `ctrl-shift-l` you meant `cmd-shift-i`
I am not able to reproduce 100% CPU on linked 13MB json file.
[big.json](https://github.com/user-attachments/files/17907644/big.json)
It fails to format and times out.
Formatting multiple times does not invoke different behavior (for me).

I'm going to close in favor of:
- https://github.com/zed-industries/zed/issues/18209
