### ISSUE TITLE
`phpactor: Undefined variable "$this"` on a fresh Laravel project

### ISSUE THREAD

**Issue by Rusydy** [zed-industries/zed#20433]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="1440" alt="Screenshot 2024-11-09 at 01 23 54" src="https://github.com/user-attachments/assets/055e5446-79e4-4bf7-9edb-484b69e5db0b">

I just create a new Laravel project using Laravel 11, then I go to `console.php`. I found that the `$this` is labelled as undefined.

- why is that?
- I would like to solve it, but I am not sure where to start in this case. May I ask for guidance?

### Environment

Darwin Users-MacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:13 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8112 arm64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by RemcoSmitsDev** [comment]
Hey @Rusydy, this is not something we could fix inside Zed. This is a shortcoming of the **phpactor** language server, it does not understand that Laravel bound the closure under the hood. So it's correct that it shows that `$this` is not defined, because you are not inside a class scope where `$this` is always bound to that class instance.


Even if you make it clear that the closure is bound to a class, **phpactor** does not get it. 
See the following example:

```php
<?php

final class SomeClass {
    public function returnSomeThing() {
        echo "Some string";
    }
}

$someClass = new SomeClass();

$closure = function() {
    return $this->getPrivateVar(); // `$this` is still not defined acording to phpactor.
};

$boundClosure = Closure::bind($closure, $someClass);

echo $boundClosure(); // will echo "Some string"
```

**Comment by Rusydy** [comment]
@RemcoSmitsDev what can I do to help?
is it need an improvement in Zed or `phpactor` side?

**Comment by RemcoSmitsDev** [comment]
No it has nothing to do with Zed, see this [issue](https://github.com/phpactor/phpactor/issues/2344) on the **phpactor** repo. It's the same issue that you have, it's only with Pest the testing framework.
