### ISSUE TITLE
Jump to found line from search

### ISSUE THREAD

**Issue by DevNulPavel** [zed-industries/zed#20653]
### Check for existing issues

- [X] Completed

### Describe the feature

Hello

It would be comfortable and faster to have ability jump on specific line from search.

At this moment i just can open file using top panel with path, after i must jump to line manually or search again.

### Environment

Zed: v0.161.1 (Zed)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="828" alt="Screenshot 2024-11-14 at 08 59 54" src="https://github.com/user-attachments/assets/131bd393-0e09-450a-ba95-1616b27f587a">

**Comment by SomeoneToIgnore** [comment]
Can you elaborate on the 

> i just can open file using top panel with path, after i must jump to line manually or search again.

part, that navigates me to the first search match, which would be line 25 in your example.
Can you record the video if it's not the same for you? Ideally, get some repro steps.

Otherwise, there is 
https://github.com/zed-industries/zed/blob/72939bc0912588462a6b954a55c34e056cfe8e28/assets/keymaps/default-macos.json#L539

whicxh should jump straight to your current caret in the excerpt.

**Comment by DevNulPavel** [comment]
I mean - just open file from search using new tab with cursor on line with found word

**Comment by DevNulPavel** [comment]
Oh, thanks - now understand how it works. Works fine, but was not obvious for me before video)

My suggestion was about using line number as link for opening file with cursor on this line)

> Ok, so
> 
> > At this moment i just can open file using top panel with path, after i must jump to line manually or search again.
> 
> was related to the fact that your caret is not on the place where the search match is, and that's the issue. Good, then it's all about pressing `alt-enter`:
> 
>  Screen.Recording.2024-11-14.at.11.33.39.mov
