### ISSUE TITLE
macOS app icon looks too small

### ISSUE THREAD

**Issue by hbons** [zed-industries/zed#20737]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The app icon on macOS looks visually smaller compared to other apps because of its dark tile background. This is specially the case when using the dark system theme.

When I measured the height of the app icon I was surprised it's exactly the same size, but it doesn't look like it:

<img width="397" alt="Screenshot 2024-11-15 at 18 48 58" src="https://github.com/user-attachments/assets/f835d35d-8747-4175-9fa0-fb921aa123b0">

A blue or white tile for the app icon could work better?

### Environment

Zed: v0.161.2 (Zed)
OS: macOS 15.0.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by vancura** [comment]
If you're using Figma, you can use my icon template :) https://vancura.design/d/macos-big-sur-icon-template

**Comment by notpeter** [comment]
Unless there's something specific beyond "change your icon color" I'm going to go ahead and close as unactionable.  I think the icon size/corner curves aren't wrong it's just perception issue because our icon is black.  If you want a blue icon, feel free to check out [Zed Preview](https://github.com/zed-industries/zed/issues/17937) ;)
<img width="484" alt="Screenshot 2024-11-15 at 13 25 32" src="https://github.com/user-attachments/assets/95df531e-070d-481a-8b39-ca15a5dfd209">


Thanks fore reporting.

**Comment by hbons** [comment]
Not sure why this is unactionable? It's a good thing to have an app icon that works on all backgrounds and looks integrated into the system. Just because it's a perception issue doesn't mean it's not an issue...
