### ISSUE TITLE
File missing or duplicated when copying multiple items in project panel

### ISSUE THREAD

**Issue by 0xtimsb** [zed-industries/zed#20858]
### Describe the bug / provide steps to reproduce it

Consider worktree:

<img src="https://github.com/user-attachments/assets/fa9d3abd-d498-4b8f-810f-68abb699d7ae" alt="image" width="200">

---
Case 1: Partial copy.

Select `dir1` and `c.txt` (in that order, reverse order works!), and copy it and paste in `dir2`.

Before / After / Expected
<img src="https://github.com/user-attachments/assets/ed51013c-76ba-43a7-b950-cf3a4b9d7b4f" alt="image" width="200"><img src="https://github.com/user-attachments/assets/a42eb8b8-ed0b-4fec-b853-d8b786752bcc" alt="image" width="200"><img src="https://github.com/user-attachments/assets/3dd62201-040d-402c-becc-ca2dbd72ada4" alt="image" width="200">

Actual (After): `c.txt` is not copied in `dir2`.

---
Case 2: Duplicate copy.

Select `a.txt`, `dir1` and `c.txt` (in that order), and copy it and paste in `dir2`.

Before / After / Expected
<img src="https://github.com/user-attachments/assets/aabdfd4b-b3db-47d7-9fb7-a0a55385232f" alt="image" width="200"><img src="https://github.com/user-attachments/assets/18026858-721f-46f8-a8a7-90caf9ee8da0" alt="image" width="200"><img src="https://github.com/user-attachments/assets/ff0aff3a-56d2-4c64-9ed3-1a8b645cdfc8" alt="image" width="200">

Actual (After): `a.txt` is duplicated in `dir2`.

### Environment

Zed: v0.162.2 (Zed Preview)
OS: Linux X11 fedora 40
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-S) || Intel open-source Mesa driver || Mesa 24.1.7

**Comment by notpeter** [comment]
I was not able to reproduce example 1.  Could you provide more explicit instructions?

I was able to reproduce example 2 (contents duplicated when a child and parent are both individually selected and copy/pasted).

### Setup:
```
mkdir -p ~/source/issue20858/
cd ~/source/issue20858 
mkdir dir{1,2}
touch dir1/{a,b}.txt {c,d}.txt
zed .
```

### Example 1
1. cmd click dir1
2. cmd click c.txt
3. right click c.txt -> Copy
4. right click dir2 -> Paste
-> Could not reprouce (my dir2 contains both dir1 and c.txt)

### Example 2
Reset:
```
rm -rf * && mkdir dir{1,2} && touch dir1/{a,b}.txt {c,d}.txt
```
1. expand dir1
2. cmd click a.txt
3. cmd click dir1
4. cmd click c.txt
5. right click dir2 -> Paste

-> I can reproduce. dir2 contains a.txt (and dir1/a.txt, dir1/b.txt, c.txt)

**Comment by 0xtimsb** [comment]
I'm not right clicking to copy, but pressing `ctrl + c` on keyboard. Can you try this?

---

I found new issue while testing following your steps for Example 1. 

1. click dir1
2. cmd click c.txt
3. right click c.txt -> Focus is lost from dir1 so, now copy will be only considered for c.txt

Ideally focus should not be lost. This maybe linux specific issue. I will file this later.

https://github.com/user-attachments/assets/6617e261-1b95-4de3-b420-a27d5de64575

**Comment by notpeter** [comment]
Ah, there's a couple things going on here.

First, Zed is using text color for two git status and to show which items are marked in the sidebar.  If you disable git colors with:

```json
  "project_panel": {
    "git_status": false,
  }
```

You will now be able to see which items are marked (darker or lighter text color).
When you cmd-click (mac) or ctrl-click (linux) it will mark/unmark the directory.
When you left click on a file it will mark it, but when you left click on a directory it will not.

So I believe there are a total of three things in this issue:

1. When project_panel.git_status is true (the default) there is a `.git` repo present, you cannot tell which files you are selecting because if they have an existing git status highglight (e.g. green for new) the mark/unmarked looked the same.
2. It is confusing that you can mark the first file by clicking on it, but if you click on a directory (a) it does not mark the directory and (b) it does not unmark the previously selected file.
3. If you mark a directory and child file contained within that directory and copy/paste into a second directory the child file will be copied twice, nested and alongside the copied directory.

**Comment by 0xtimsb** [comment]
Yes, I wasn't aware of 1 issue. I think we can create another issue for it maybe?

I'm already working on fix for second and third issue in https://github.com/zed-industries/zed/pull/20859 PR.

**Comment by notpeter** [comment]
Yeah, I don't know if there's an issue, but it's absolutely something we are internally aware of.  I just wanted to explicitly enumerate it as a root cause of some of the confusion.  Happy to exclude that from the scope of this issue.
