### ISSUE TITLE
Cannot type '@' or comment out lines/blocks of code with cmd+/ with danish ISO keyboard on macOS

### ISSUE THREAD

**Issue by Salby** [zed-industries/zed#21049]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Since a recent update, I am no longer able to type '@' in the editor, I can type it into the terminal as expected.
The keyboard shortcut for commenting out lines (cmd+/) also doesn't work.

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 15.1.1
Memory: 24 GiB
Architecture: aarch64

**Comment by crob-tv2** [comment]
I have the same issue and I believe it appeared after this update: https://zed.dev/blog/keyboard-localization

Prior to this update I didn't actually notice any keyboard shortcuts not working on my Danish keyboard, but now at least `⌥/` and @ (typed by pressing `⌥*`) aren't working.

**Comment by ConradIrwin** [comment]
Sorry about this! Typing @ will be fixed by https://github.com/zed-industries/zed/pull/21669.

In v0.162.x I shipped a change to automatically localize keyboard shortcuts. This is the solution macOS uses (for people who haven't gone out of their way to disable the default shortcuts for this :D). https://zed.dev/blog/keyboard-localization

On a Danish keyboard commenting is now available by default as cmd-´

If you want to restore the prior behavior

```
{
    "use_layout_keys": true // for Zed v0.162 ..= v0.165
    "context": "Workspace",
    "bindings": {
      "cmd-/": "editor::ToggleComments"
    }
}
```

In v0.166 `"use_layout_keys"` will become the default.
