### ISSUE TITLE
Excalidraw integration

### ISSUE THREAD

**Issue by hrmnjt** [zed-industries/zed#21197]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm not sure if this is a "Feature Request", as this is borderline plugin situation.

[Excalidraw](https://excalidraw.com/) is my go-to tool to quickly sketch concepts and in order to not loose sketches, I use this VSCode plugin (https://marketplace.visualstudio.com/items?itemName=pomdtr.excalidraw-editor) which opens up an Excalidraw window in the editor pane and I can version control the JSON output if I wanted to. If this feature was present in Zed, I would not switch away from VSCode completely.

If this possible, either core feature or a plugin, I'm open to contribute. I would need some direction however.

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 15.1.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/1ac5d94f-0504-4e43-aa2f-bd93b47bcac3">

**Comment by notpeter** [comment]
I believe for this is implemented the extension API would have to support webviews and so am closing in favor of:
- https://github.com/zed-industries/zed/issues/21208

**Comment by sounddrill31** [comment]
The VSCode version feels like a full PWA/local thing in the sense that it starts up without internet.

Please correct me if I'm wrong but won't the webview route only start when the internet is connected and active?

**Comment by dandaniel5** [comment]
Where the Excalidraw on zed plugin ? 🤔

**Comment by SirawichDev** [comment]
still waiting for it

**Comment by arindampradhan** [comment]
@SirawichDev just made this and opened a pull request: https://github.com/zed-industries/extensions/pull/5570 I'm not sure if Zed will work with webview-based extensions. It seems like they're avoiding it because of what happened with Atom. For now, I'm just starting up a small webview engine every time I open a .excalidraw file to support editing exclidraw file... 

Here is the extension code: https://github.com/arindampradhan/excalidraw-zed-extension
will release it's binary in some time

**Comment by JaimeJunr** [comment]
deveria sair algo assim
