### ISSUE TITLE
indent_guides seems to be ignoring tab_size

### ISSUE THREAD

**Issue by cemoktra** [zed-industries/zed#21212]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have the following setting (partially shown):
```
"languages": {
  "Proto": {
    "tab_size": 2,
    "indent_guides": {
      "enabled": true
    }
  }
}
```      

As you see in the attached screenshot, the indent guides only show for full 4 spaces

### Environment

Zed: v0.162.5 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (TGL GT1) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/4fdf939d-c41d-46b2-b12c-832ebba28e03)

**Comment by notpeter** [comment]
I also cannot reproduce.  Do you perhaps an `.editorconfig` or project settings?

**Comment by cemoktra** [comment]
> I also cannot reproduce. Do you perhaps an `.editorconfig` or project settings?

shit, yeah we have ... sorry. closing

**Comment by viktaur** [comment]
I had a similar issue. In a .svelte file, indent guides appeared to be size 2, while the actual tab size (number of positions jumped when pressing tab once) was actually 4.

<img width="247" alt="Screenshot 2024-12-02 at 15 44 50" src="https://github.com/user-attachments/assets/fa86a9c6-44d3-4301-8df5-7bdde86519f0">
<img width="248" alt="Screenshot 2024-12-02 at 15 45 02" src="https://github.com/user-attachments/assets/a2689311-1516-49f5-b36c-5b141f3b9148">

Settings:
```json
{
  "tab_size": 4,
  "languages": {
    "Svelte": {
      "tab_size": 2
    },
    "JavaScript": {
      "tab_size": 2
    },
    "TypeScript": {
      "tab_size": 2
    },
    "JSON": {
      "tab_size": 2
    },
  }
}
```

For now, this configuration seems to work for all languages i normally use (set the `tab_size` to 2, instead of 4 as default):

```json
{
  "tab_size": 2,
  "languages": {
    "Svelte": {
      "tab_size": 2
    },
    "JavaScript": {
      "tab_size": 2
    },
    "TypeScript": {
      "tab_size": 2
    },
    "JSON": {
      "tab_size": 2
    },
    "Rust": {
      "tab_size": 4
    }
  }
}
```

**Comment by joelis10** [comment]
just wanted to thank @notpeter for mentioning `.editorconfig` - had no idea this existed in my project root and was the only reason my tab size wouldn't change from 4 to 2
