### ISSUE TITLE
Search buffer symbols won't show "methods" of prototype-based "classes" in Javascript or Typescript test files

### ISSUE THREAD

**Issue by exalted** [zed-industries/zed#21243]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

For example this

```js
class Person {
    constructor(name, age) {
        this.name = name;
        this.age = age;
    }

    greet() {
        return `Hello, my name is ${this.name} and I am ${this.age} years old.`;
    }
}
```

shows 
![CleanShot 2024-11-27 at 16 58 52@2x](https://github.com/user-attachments/assets/0eb2cd50-c4fe-4491-a773-dbf84dbef5b5)

in the buffer symbols while this:

```js
// Constructor function
function Person(name, age) {
    this.name = name;
    this.age = age;
}

// Adding methods to the prototype
Person.prototype.greet = function() {
    return `Hello, my name is ${this.name} and I am ${this.age} years old.`;
};
```

only shows 
![CleanShot 2024-11-27 at 16 59 43@2x](https://github.com/user-attachments/assets/4f3a216c-a7ef-4838-a421-2c69ec20001d)

I may agree if it wouldn't be possible to show `greet` as a "method" for `Person` in the prototype-based approach, however I'd argue that Zed should at least enlist those "anonymous" functions in the buffer symbols.

### Environment

Zed: v0.163.2 (Zed Preview)
OS: macOS 15.1.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
This is almost surely an upstream language server issue and not something that can be fixed by Zed.

If you'd like to explore further, I recommend you take a look at the `debug: language server logs` view, the select your language server in question and choose RPC messages.  Then you can see exactly what Zed is getting as a response to the `workspace/symbol` query we are sending to the LSP.  If you'd like your language server to add support to including populating `workspace/symbol` results from your example you'd need to file an issue upstream.

1. Which language server are you using?
2. Do you see the behavior you are looking for in other Editors using the same LS (neovim, VSCode, etc).
3. If Zed is behaving differently and it works elsewhere, I'd be happy to reopen and dig in (sometimes there are language server initialization_options which change LS behavior -- and it might make sense for Zed to use those by default).

**Comment by exalted** [comment]
@notpeter fair ask!

Re 1: Here's my relevant Zed configuration:

```
  ...

  "languages": {
    "TypeScript": {
      "language_servers": ["typescript-language-server"]
    },
    "TSX": {
      "language_servers": ["typescript-language-server"]
    },
    "JavaScript": {
      "language_servers": ["typescript-language-server"]
    }
  },

  ...

  "lsp": {
    "typescript-language-server": {
      "initialization_options": {
        // https://github.com/typescript-language-server/typescript-language-server/blob/master/docs/configuration.md#initializationoptions
        // & https://zed.dev/docs/languages/typescript#large-projects:
        "maxTsServerMemory": 24576 /* 24 GiB */
      }
    },

    ...
  }

  ...
```

Re 2: Check out screenshots between Zed and VSCode:

![CleanShot 2024-12-14 at 10 18 42@2x](https://github.com/user-attachments/assets/052e9934-f069-43e0-9210-3389ac51eb0c)
![CleanShot 2024-12-14 at 10 18 33@2x](https://github.com/user-attachments/assets/256148c9-3a9b-4e84-b027-50550315cc0c)

What do you think, @notpeter?
