### ISSUE TITLE
Overriding `panel.background` dose not affect file tree

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#21266]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Use the below settings

```json
{
  "experimental.theme_overrides": {
    "panel.background": "#ff0000"
  }
}
```

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/36f4c094-5b56-46d4-9e74-f1735e546349">

Before 0.164.0, the background of the file tree will also be updated.

### Environment

Zed: v0.164.0 (Zed Preview)
OS: macOS 15.1.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by nilskch** [comment]
Changing: https://github.com/zed-industries/zed/blob/196fd65601af0b22cba3f6f0fbbda821b0403427/crates/project_panel/src/project_panel.rs#L262-L263

to:
```rust
   ItemColors {
        default: colors.panel_background,

```
should fix the issue

cc @danilo-leal

**Comment by nilskch** [comment]
There are overrides for `"panel.background"`, `"panel.focused_border"`, `"panel.indent_guide_hover"`, `"panel.indent_guide_active"`, and `"panel.indent_guide"`. I can look into respecting all of those overrides and create a PR for that.

**Comment by nilskch** [comment]
I did some digging and 
```json
{
  "experimental.theme_overrides": {
    "panel.indent_guide_hover": "#ffff00",
    "panel.indent_guide": "#ff0000",
    "panel.indent_guide_active": "#ffffff"
  }
}
```
work perfectly.
```json
{
  "experimental.theme_overrides": {
    "panel.background": "#ff0000"
  }
}
```
works if we do the change that I suggested in https://github.com/zed-industries/zed/issues/21266#issuecomment-2516470226:

<img width="252" alt="Screenshot 2024-12-04 at 22 10 01" src="https://github.com/user-attachments/assets/b1677b5f-bd83-4526-a58b-18a0d43540cf">



There is still an issue with:
```json
{
  "experimental.theme_overrides": {
    "panel.focused_border": "#ff0000"
  }
}
```
The color from `"panel.focused_border"` is actually never used and therefore there is nothing to override. All themes set `"panel.focused_border": null`, so all themes pick up the default colors.

Light-mode:
https://github.com/zed-industries/zed/blob/a30ea2fc682bdaec572f3e130631e297670612a6/crates/theme/src/default_colors.rs#L61

Dark-mode:
https://github.com/zed-industries/zed/blob/a30ea2fc682bdaec572f3e130631e297670612a6/crates/theme/src/default_colors.rs#L167

And those colors look different (and not good imo):
| Gruvbox Light Hard         | Gruvbox Dark Hard         |
|----------------|----------------|
| <img width="258" alt="light" src="https://github.com/user-attachments/assets/cd987a63-409d-496d-a0fe-dbda9e04476e"> | <img width="256" alt="dark" src="https://github.com/user-attachments/assets/500a13bd-f300-4288-acf6-8cb013122f3e">| 

(for the screenshots I changed the code to use `"panel.focused_border"` for the border colors)

The place where `"panel.focused_border"` should be used (if I understand this correctly) is here:
https://github.com/zed-industries/zed/blob/a30ea2fc682bdaec572f3e130631e297670612a6/crates/project_panel/src/project_panel.rs#L3102-L3105

Instead of using the color from `"panel.focused_border"` we use the selected color which internally maps to the color `text.accent` (which is different in every theme), so you could override the border color like this:
```json
{
  "experimental.theme_overrides": {
    "text.accent": "#ff0000"
  }
}
```
This would obviously also override every other place where `"text.accent"` is being used.

There are a lot of different ways we could solve this, but this is a completely different discussion. The fact that the border color from the theme is not being used is a separate problem and orthogonal to this issue, but I still wanted to share my findings in case someone wants to tackle this.

**Comment by danilo-leal** [comment]
Awesome work on this quick research, @nilskch, appreciate it! It helped me sort out this PR → https://github.com/zed-industries/zed/pull/21593. We'll hopefully merge yours soon, too.
