### ISSUE TITLE
Support for x.com Grok AI

### ISSUE THREAD

**Issue by MrBuddyCasino** [zed-industries/zed#21635]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice if Zed coding assistant would support Grok AI.

### Environment

irrelevant

**Comment by notpeter** [comment]
This has been supported since X.ai launch, but I've added [Assistant Configuration: X.Ai Grok](https://zed.dev/docs/assistant/configuration#a.xi-grok) to the docs.
```
  "language_models": {
    "openai": {
      "api_url": "https://api.x.ai/v1",
      "available_models": [
        {
          "name": "grok-beta",
          "display_name": "X.ai Grok (Beta)",
          "max_tokens": 131072
        }
      ],
      "version": "1"
    },
  }
```

**Comment by jackTabsCode** [comment]
@notpeter you may have forgotten to add it to the "Providers" list 
<img width="609" alt="image" src="https://github.com/user-attachments/assets/9f82b478-d728-4e0b-9053-05cce0b6dcf7">

**Comment by notpeter** [comment]
This corresponds to the `providers` we have explicit support for in the code.  The configuration page has grown out control and I intend to revamp these docs into multiple pages, with individual pages for each Provider (in the common parlance) no matter the underlying Zed `provider`. For example: X.Ai (openai), Ollama (ollama and openai), LM Studio (openai), Amazon Bedrock (anthropic, openai, etc). 

Part of the issue is that we currently only support a single `openai` provider being configured at once.  I've been playing with ways to support simultaneous OpenAI API compatible providers via settings.

Anyways, thanks for the heads up. I'll see what I can do.

**Comment by gianpaj** [comment]
How do we set the API key for a non-OpenAI provider?

This doesn't work :
```json
  "language_models": {
    "openai": {
      "api_url": "https://api.x.ai/v1",
      "api_key": "xai-xxx",
      "available_models": [
        {
          "name": "grok-3-mini-beta",
          "display_name": "X.ai Grok 3 mini (Beta)",
          "max_tokens": 131072
        }
      ],
      "version": "1"
    }
  },
```
<img width="860" alt="Image" src="https://github.com/user-attachments/assets/34969b43-05a0-42b8-a295-8030bdf0b4b2" />

**Comment by notpeter** [comment]
You need to specify it in your environment via `OPENAI_API_KEY` or by pasting it into the Assistant Configuration panel.

**Comment by abourget** [comment]
This prevents me from using OpenAI natively when I configure a Grok 3 API..
Now that the Grok 3 API is out, and it's one of the frontier models, I'd expect native configuration support for this provider. Please please? :)

**Comment by notpeter** [comment]
https://github.com/zed-industries/zed/issues/30010
