### ISSUE TITLE
Persistent own voice feedback in Zed Collaboration Mode

### ISSUE THREAD

**Issue by shadevkumar** [zed-industries/zed#21649]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I hear my own voice in the zed collaboration mode which is annoying 

### Steps to reproduce
- Call any of your contact for zed collaboration.
- Make sure your microphone is on and try speaking something.
- you will hear your own voice.

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 14.6.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment]
I am not able to reproduce this.  We use Zed collaboration for many times a day internally without issue.

The only time I have ever run into this is when someone on the other end is unmuted, using speakers and has their volume turned way up or has their microphone configured in such a way that it is picking up their speaker output and feeding it back.

My suggestion is that you ask your collaboration partner to reconfigure their audio.  Sometimes it's as simple as putting on headphones or switching to use a different mic (e.g. webcam mic instead of macbook internal mic, etc) -- this is easily toggle-able by option-clicking on the volume control in the menu bar.
