### ISSUE TITLE
Rust tooltip on type suggestions

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#22020]
### Check for existing issues

- [X] Completed

### Describe the feature

https://github.com/user-attachments/assets/c1d4580b-3ff9-4e22-ae5a-fd677d01ef7e

### Environment

```
Zed: v0.166.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment]
I cannot reproduce, these hover states show up for me just fine in Zed.

<img width="546" alt="Screenshot 2024-12-15 at 23 41 29" src="https://github.com/user-attachments/assets/00258fdf-b9c5-4d5b-81cf-a2f8848da7a8" />

Additionally, please do not create issues which are just a video.  Just because something is self-evident to you from a video, does not make that sufficient information when communicating here.
