### ISSUE TITLE
VIM delete till start of next sentence d( does not work

### ISSUE THREAD

**Issue by jmagaram** [zed-industries/zed#22151]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Put this text in a `.md` file...

`This is the first sentence. This is another sentence. This is the third sentence.`

Put the cursor on the T in the second sentence. Press `)` and notice the cursor moves to the beginning of the third sentence. Correct.

Put the cursor on the T in the second sentence. Press `d)` and notice everything is deleted.

I'm pretty sure that tying `d)` should delete that second sentence. That is what happens in vim.

### Environment

Zed: v0.165.4 (Zed)
OS: macOS 15.1.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by thomasheartman** [comment]
Realized I added a duplicate issue in #22249, so I closed that as a duplicate. But in case it's useful, here's the repro steps that I included there:

### Describe the bug / provide steps to reproduce it

I was playing around with Zed's vim mode today and came across the `vim::SentenceBackward` and `vim::SentenceForward` operators. Coming from Emacs, I wanted to see if I could use them to achieve the same as `M-a`, `M-e`, and `M-k`, which do:
- move to the start of the current sentence
- move to the end of the current sentence
- kill till the end the current sentence

The first two work fine with the default bindings (well, technically, you get to the start of the next sentence, but that's often what you want), but the last one: `d)` and `d(` behaves very strangely. It appears to ... act on visual lines? Or something?

I used this text (taken from a different discussion in this repo):
> Recently came across this editor and I have been impressed by the speed of it. I generally use neovim as my main editor 99% and if I am able to incorporate my frequently used keybindings then I can attempt to daily drive Zed. The keybindings I would like to incorporate are:

It might be worth noting that it's all on one line, and my editor is set to wrap when necessary.

It looks like this:
![image](https://github.com/user-attachments/assets/c831eb59-645c-4edc-8162-005e92f84e78)

For the sake of ease in this demonstration, I'll be putting the text in with line breaks in the examples. The `|` character signifies my current position.

Let's take this as the starting position:

```
Recently came across this editor and I have been impressed by the speed of it. I generally use neovim as 
my main editor 99% and if I am |able to incorporate my frequently used keybindings then I can attempt to
daily drive Zed. The keybindings I would like to incorporate are:
```

If I do `v)d`, my result is:

```
Recently came across this editor and I have been impressed by the speed of it. I generally use neovim as 
my main editor 99% and if I am |he keybindings I would like to incorporate are:
```

But if I do `d)`, I get an empty buffer?

```
|
```

Likewise, if I go backwards, `v(d` yields:
```
Recently came across this editor and I have been impressed by the speed of it. |able to incorporate my frequently used keybindings then I can attempt to daily drive Zed. The keybindings I would like to incorporate are:
```

but `d(` yields:
```
daily drive Zed. The keybindings I would like to incorporate are:
```

There's probably more corner cases here, but this is seems strange. It might be because of some settings I've got, but I don't know. Happy to help out! But it's also not something I use very often, so it's not a big deal. (but side note: text objects for SentenceEnd (maybe PreviousSentenceEnd) could be nice, although I've got other text objects I'd much rather see before then)

**Comment by mrnugget** [comment]
Fix is here: https://github.com/zed-industries/zed/pull/22289
