### ISSUE TITLE
Formatting Json seems to finally work, but it doesn't work for GeoJson

### ISSUE THREAD

**Issue by MVHINC** [zed-industries/zed#22361]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Use the following string
{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[341.971435546875,75.44479062156888],[341.80664062499994,75.43236091090435],[341.7352294921875,75.34784096336145],[341.60888671875,75.37283104050242],[341.4056396484375,75.39500943841519],[341.0101318359375,75.36450565060706],[340.96618652343744,75.30470457303787],[341.015625,75.17595443080889],[340.916748046875,75.00067558134106],[341.16943359375,74.9707914022581],[341.58691406249994,74.94227620388224],[341.883544921875,74.99214317362151],[342.279052734375,74.97648810806794],[342.2021484375,74.9108484418626],[342.3834228515625,74.90083526944221],[342.7349853515625,75.01062406678055],[342.8228759765625,75.14218646962429],[342.630615234375,75.17876503868581],[342.36694335937494,75.16048677152294],[342.26806640625,75.11963273575662],[342.09228515625,75.17033165185124],[342.18017578124994,75.20684248011797],[342.21313476562494,75.25864871532573],[342.27355957031244,75.32280912777709],[341.971435546875,75.44479062156888]]]}},{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[342.04833984375,77.91106812275609],[341.8505859375,77.77921572574621],[341.630859375,77.62006466839729],[341.927490234375,77.57641428752758],[342.3779296875,77.60238679318502],[342.5152587890625,77.69989363485175],[342.66357421875,77.78386601167459],[342.4383544921875,77.8741990405409],[342.04833984375,77.91106812275609]]]}},

And try to format it.
There will be no changes.
As a point of comparison, vscode does format it correctly.
The file above is an unformated geojson without spaces and new lines.

Error is as follows

2024-12-23T10:17:21.532323+09:00 [ERROR] default prettier instance failed to format buffer

Caused by:
    error during message '{"jsonrpc":"2.0","id":6,"method":"prettier/format","params":{"text":"..snip..","options":{"plugins":[],"parser":null,"filepath":"/Users/username/Downloads/17302684-v703-geojson.json","prettierOptions":{"useTabs":false,"tabWidth":2,"printWidth":80}}}}' handling: SyntaxError: Unexpected token (2:1)
      1 | {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[341.971435546875,75.44479062156888],[341.80664062499994,75.43236091090435],[341.7352294921875,75.34784096336145],[341.60888671875,75.37283104050242],[341.4056396484375,75.39500943841519],[341.0101318359375,75.36450565060706],[340.96618652343744,75.30470457303787],[341.015625,75.17595443080889],[340.916748046875,75.00067558134106],[341.16943359375,74.9707914022581],[341.58691406249994,74.94227620388224],[341.883544921875,74.99214317362151],[342.279052734375,74.97648810806794],[342.2021484375,74.9108484418626],[342.3834228515625,74.90083526944221],[342.7349853515625,75.01062406678055],[342.8228759765625,75.14218646962429],[342.630615234375,75.17876503868581],[342.36694335937494,75.16048677152294],[342.26806640625,75.11963273575662],[342.09228515625,75.17033165185124],[342.18017578124994,75.20684248011797],[342.21313476562494,75.25864871532573],[342.27355957031244,75.32280912777709],[341.971435546875,75.44479062156888]]]}},{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[342.04833984375,77.91106812275609],[341.8505859375,77.77921572574621],[341.630859375,77.62006466839729],[341.927490234375,77.57641428752758],[342.3779296875,77.60238679318502],[342.5152587890625,77.69989363485175],[342.66357421875,77.78386601167459],[342.4383544921875,77.8741990405409],[342.04833984375,77.91106812275609]]]}},
    > 2 |
        | ^

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

Unformated Zed to the left after clicking button to format vs doing the same in vscode to the right
<img width="1908" alt="image" src="https://github.com/user-attachments/assets/68c06e9d-ff89-4e02-840a-6f7479ba838d" />

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment]
Zed can format things with either prettier (current case) or a corresponding language server.
Zed does not know what a "language", "syntax", etc. are and how to deal with those.

Here

> "options":{"plugins":[],"parser":null,"filepath":"/Users/username/Downloads/17302684-v703-geojson.json",

Prettier is told to use no extra plugins and guess the parser out of the file path, which will be `json`.
Prettier is very opinionated about the formatting and does not try to format incorrect JSON in many (all?) cases.

Here, the JSON is obviously invalid due to the trailing comma but even if we remove that, here's what Prettier will error with later, using [Prettier online](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACYAdEMCeAHOLJLAMTgEMYBXAJ0JABos8aICaYBLOAZyOAC+TEAHM4EALZwYNHPyy4CRLAAUIAGxwjoWYZAg0AJpyiVeRANpWAzABYAjADoAnAHZ7t6wFYvtgGwAHK5eDMGOthGuzgAMfgBM9l6BAQEAugwWdk4BsX62sXG2zsXOtqFe4dZx1n7RzvZ10Z5e6ZkOjq7ecXGlzglBIWF2rgH5zn7WNR4tGVmOtSkBfu4D5Y7WrnEB1g35XtGFca1zexPjtqMbgxXWzvt1nqOJ9s7H7dEN9jvbXs5XazVbPskvtaq5Ym9oi4-H57EsvNVPK4IgCmuCgZ1ohsgm8nB8knFro57ME7hFrNEcilXrN8i57MsLk1AsE1tF2csfAEvg4IbSnAzSpNfv9kS5wVEPAdCdzcY4vEt6vl4kVimUxaVuq54liUt1bHKUt4In04ayNabPCSagkvPY3nFHHEotEEZ0kYNbOK8ikGjllqUHU6Dh5LuavfVKRcInD4n4g9ZtrZugE7QTPS52T84n5SsmEkH3c5U95EvEiR8CsrljkfEGAinSdr02sPP08rmVT0gxNYolEaKKiSgn59onAgr7bTHTVc55vH9kaVW7ULst3Aiegbp07ArllYTWy8Js7vMEYUcd3UU2ny63wZMGXbU-ZCkG4R9giNX6r1RU4rEoyFDk9gkm4QYJDswyjiqy5hDKPoblUXidBBnQ+HcD4-n+6wpnUr6uIR4I0m0ThuB43i+CyRIRLYLrxGWiypMxAhCJg2D4PQxAgGQlC0PQwgsGwcAcNwfDIIIwhiJI0iyPIHFKMgqgaFoOiMFg+hGCYZjiUgVhtI6TTbLcYaDK49INIEr7OkkdSGsCqaLmZHRRLamwof4Bb8vMFKOaK5k6rE-iBLcmwkXMfRLgcdj+fK2oOMmAw2WkO4bK54yrIR8zRUsUTfPsl4GfK-YKiMMR3llubFn8EwXHawQ9hMHn9Oa5kjOOtSgYyvxBo8xpFC1zlBA4xRNK6YxBkZkzFh6oTmfUlnclqtmvCxAgYFAjAgGwXDQDwEkgOQNCsAA7ioR0IPtKDkOoJ3kDg+0MCAABGNDkGAADW0gAMrkFIAAyJhwMgABmN08HAT2ve9X0wN9eDvSYIjIDIVCQyAEMSJwKM0GjT08Ej6hwAAilQEDwKD4PowAVjwAAe32EyTZMU0gYPqBDT0AI4s3AKisHgV2HTwAC0UBwHAhiS1tMjkJw6hIwAwpIEjkMgh3qOoW0E1AIhEwAgjAMicM9VDwCoImA+LlMc+jAAWMASOoADqducPAPAI2AcDfZd7ucAAbu7ODq2APCPSAAdowAklAUuwN9YA0JweAwPrcffbgRM25zIBCRDztvXg6ssLwIkB8DT0mBDHD8+QIiqzn6MIzQNfq7T0BbSwJgwM7nCGDAdvIDkT10DznB0HXDdq2zVNPTA5DPX3A9D0gcRPVQEMACqL1d7O53AEjPZLUuGP95C61Q9dwCQBiq0bSPq+QZsQCArFAA):

![image](https://github.com/user-attachments/assets/6da011b5-75bd-420d-813a-d287761972fb)

> SyntaxError: 'SequenceExpression' is not allowed in JSON. (1:2)

In this particular case, I see that there are two objects on the root level which is not a valid JSON indeed, it has to be a single `{}` in the root.

-------------------------------

Using  `"formatter": "language_server",` as described in `https://zed.dev/docs/configuring-languages#configuring-formatters` for JSON language fixes the issue and starts to format even malformed JSONs, so maybe that's what you can do?
`.zed/settings.json` can be created inside project directories and should work for formatter preferences too.

I do not think there's much else we can do on top of that? 
Neither Zed nor Prettier have any GetJSON support right now, and formatting things twice with a formatter that is not configured sounds odd.

**Comment by MVHINC** [comment]
Hi, yes.
This is GeoJson, that is how it works
https://en.wikipedia.org/wiki/GeoJSON

Very unfortunate you won't fix this.

**Comment by notpeter** [comment]
Your example is not GeoJSON. GeoJSON is valid JSON.

What you have provided is two GeoJSON feature objects, each with a comma appended to them.

It looks like what you may have pasted is actually the inner contents of a `FeatureCollection` `features` array without the wrapper.

<details><summary>Hand formatted JSON-like code from above</summary>

```json
{
    "type": "Feature",
    "properties":{},
    "geometry":{
        "type":"Polygon",
        "coordinates": [
            [   
                [341.971435546875,75.44479062156888],[341.80664062499994,75.43236091090435],[341.7352294921875,75.34784096336145],[341.60888671875,75.37283104050242],[341.4056396484375,75.39500943841519],[341.0101318359375,75.36450565060706],[340.96618652343744,75.30470457303787],[341.015625,75.17595443080889],[340.916748046875,75.00067558134106],[341.16943359375,74.9707914022581],[341.58691406249994,74.94227620388224],[341.883544921875,74.99214317362151],[342.279052734375,74.97648810806794],[342.2021484375,74.9108484418626],[342.3834228515625,74.90083526944221],[342.7349853515625,75.01062406678055],[342.8228759765625,75.14218646962429],[342.630615234375,75.17876503868581],[342.36694335937494,75.16048677152294],[342.26806640625,75.11963273575662],[342.09228515625,75.17033165185124],[342.18017578124994,75.20684248011797],[342.21313476562494,75.25864871532573],[342.27355957031244,75.32280912777709],[341.971435546875,75.44479062156888]
            ]
        ]
    }
},
{
    "type": "Feature",
    "properties": {},
    "geometry": {
        "type":"Polygon",
        "coordinates": [
            [
                [342.04833984375,77.91106812275609],[341.8505859375,77.77921572574621],[341.630859375,77.62006466839729],[341.927490234375,77.57641428752758],[342.3779296875,77.60238679318502],[342.5152587890625,77.69989363485175],[342.66357421875,77.78386601167459],[342.4383544921875,77.8741990405409],[342.04833984375,77.91106812275609]
            ]
        ]
    }
},
```

</details>

<details><summary>Reformatted as a `FeatureCollection`</summary>

```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties":{},
            "geometry":{
                "type":"Polygon",
                "coordinates": [
                    [
                        [341.971435546875,75.44479062156888],[341.80664062499994,75.43236091090435],[341.7352294921875,75.34784096336145],[341.60888671875,75.37283104050242],[341.4056396484375,75.39500943841519],[341.0101318359375,75.36450565060706],[340.96618652343744,75.30470457303787],[341.015625,75.17595443080889],[340.916748046875,75.00067558134106],[341.16943359375,74.9707914022581],[341.58691406249994,74.94227620388224],[341.883544921875,74.99214317362151],[342.279052734375,74.97648810806794],[342.2021484375,74.9108484418626],[342.3834228515625,74.90083526944221],[342.7349853515625,75.01062406678055],[342.8228759765625,75.14218646962429],[342.630615234375,75.17876503868581],[342.36694335937494,75.16048677152294],[342.26806640625,75.11963273575662],[342.09228515625,75.17033165185124],[342.18017578124994,75.20684248011797],[342.21313476562494,75.25864871532573],[342.27355957031244,75.32280912777709],[341.971435546875,75.44479062156888]
                    ]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type":"Polygon",
                "coordinates": [
                    [
                        [342.04833984375,77.91106812275609],[341.8505859375,77.77921572574621],[341.630859375,77.62006466839729],[341.927490234375,77.57641428752758],[342.3779296875,77.60238679318502],[342.5152587890625,77.69989363485175],[342.66357421875,77.78386601167459],[342.4383544921875,77.8741990405409],[342.04833984375,77.91106812275609]
                    ]
                ]
            }
        }
    ]
}
```

</details>

You can look at [RFC 7946 The GeoJSON Format](https://datatracker.ietf.org/doc/html/rfc7946) for more.
