### ISSUE TITLE
Shell (zsh) formatter breaks the script

### ISSUE THREAD

**Issue by korikhin** [zed-industries/zed#22519]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Suppose I want to check if some command exists with the script below:

```sh
#!/usr/bin/env zsh

if (( $+commands[cat] )); then
    echo "ok"
fi
```

After formatting You will see:

```sh
#!/usr/bin/env zsh

if (($ + commands[cat])); then
    echo "ok"
fi

```

which rises an error:

`./test.zsh:3: bad math expression: operand expected at '/bin/cat'`

So You are forced to use quotation:

```sh
#!/usr/bin/env zsh

if (("$+commands[cat]")); then
    echo "ok"
fi

```

After formatting it still lacks padding spaces.

Desired behaviour: `(( "$+commands[cat]" ))` or `(( $+commands[cat] ))`

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment]
Zed does not format anything itself, delegating that to Prettier or corresponding language server.

On top of that, default Zed config does not specify any associated language server with the scripts:

https://github.com/zed-industries/zed/blob/ddc469ca3ef5ed30757278c527cfc3368ba7dbe1/crates/languages/src/lib.rs#L143

So, this issue is not very clear: which language is used for this example and which formatter is used?
And not very actionable: Zed cannot fix it in itself, it's the formatters' issue or a configuration issue (which seems to be different from the default).

**Comment by georgeharker** [comment]
I wrote https://github.com/georgeharker/tree-sitter-zsh I wonder if that might help?
