### ISSUE TITLE
Unable to set `rust-analyzer` target directory

### ISSUE THREAD

**Issue by bgins** [zed-industries/zed#4264]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The setting `rust-analyzer.rust.analyzerTargetDir` does not trigger `rust-analyzer` to write to a custom directory.

In my `lsp` settings, I have:

```json
    "rust-analyzer": {
      "rust": {
        "analyzerTargetDir": "target/analyzer"
      }
    }
```

With these settings, I expect `rust-analyzer` to create and use a `target/analyzer` directory in my project, but it does not. Instead, it seems to use `target/debug`.

This setting is relevant when `rust-analyzer` is overwriting the build cache and ruining incremental compilation. This can happen under a variety of circumstances, and setting a custom directory is a nice escape hatch.

### Environment

Zed: v0.118.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxbrunsfeld** [comment]
Zed has an additional key called `initialization_options` that you need to use. Sorry, this should probably be made clearer in some docs.

```jsonc
{
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "rust": {
          "analyzerTargetDir": true
        }
      }
    }
  }
}
```

**Comment by bgins** [comment]
Thanks! Setting it this way does work.

Also, setting a specific target works as well:

```json
{
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "rust": {
          "analyzerTargetDir": "target/analyzer"
        }
      }
    }
  }
}
```

Now that you all are open source, would you be interested in a docs PR? Happy to contribute.

**Comment by SomeoneToIgnore** [comment]
> would you be interested in a docs PR

Always, please do, happy to review and thank you.

**Comment by bgins** [comment]
@SomeoneToIgnore where would be the right place to submit a PR? 

My thought was to add "Target directory" section to the Rust language page (https://docs.zed.dev/languages/rust). That page exists in the now-deprecated docs repo, but I'm not seeing it in the main repo. Was looking here: https://github.com/zed-industries/zed/tree/main/docs/src.

**Comment by SomeoneToIgnore** [comment]
Unfortunately, our documentation effort is somewhat constrained and focused more on the general approach to docs, rather than the contents migration.

It's correct that https://github.com/zed-industries/zed/tree/main/docs/src are the docs now, and at the current state of its contents, any reasonable approach on top works.

I would add a `languages/rust.md` straight there, copy the https://github.com/zed-industries/docs/blob/main/languages/rust.md contents there and add continue with the addition planned.
That would be the first PR to add new docs to Zed repo and it's great.

I think we should also 
* copy the rest of the language settings description from the old repo
* add pages for Zig, Haskell, Gleam, Deno and PureScript
* ask further PR creators to add the language docs

First two are pretty much doable already, any extra help is welcome. 
I will get some sleep and rest, and deal with both tomorrow otherwise.

**Comment by bgins** [comment]
Thanks! PR for the first two is up: #6957.

Did a bit of digging to track down the language server and tree sitter links for the new languages. Hopefully I got those right.
