### ISSUE TITLE
Add "Copy", "Cut", and "Paste" to the right-click context menu when text is selected

### ISSUE THREAD

**Issue by bradgessler** [zed-industries/zed#4280]
### Check for existing issues

- [X] Completed

### Describe the feature

When I right click on selected text, I'd like to see a "Copy", "Cut", and "Paste" as menu options because many times its easier for me to perform these operations with my mouse cursor.

### If applicable, add mockups / screenshots to help present your vision of the feature

Not much to envisioning this—just copy how all other apps do it.

<img width="772" alt="Screenshot 2024-01-09 at 11 50 14 AM" src="https://github.com/zed-industries/community/assets/4628/0d8519cc-ce7c-44d8-8572-b5f3022eb689">

**Comment by JosephTLyons** [comment]
This is now available in [v0.136.0-pre](https://zed.dev/releases/preview/0.136.0).

**Comment by andrey-reznik** [comment]
Hi, I noticed that this issue was previously addressed and marked as resolved, but unfortunately, I am still experiencing the problem. When I select text and click with two fingers on the trackpad, the selection is cleared and the context menu opens only for the line where the cursor was positioned.

Here are my details:

- Device: MacBook Air with M1
- Zed: v0.141.0 (Zed Preview)
- OS: macOS 14.5.0
- Memory: 16 GiB
- Architecture: aarch64

Could you please provide some guidance on what I might be missing or suggest any troubleshooting steps? I have already tried reinstalling the editor and ensuring that I am using the latest version. Any help would be greatly appreciated!

Thank you!
