### ISSUE TITLE
Support vim's :0 and :%

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#4303]
### Check for existing issues

- [X] Completed

### Describe the feature

:0 should move the cursor to the beginning of the buffer
:% move the cursor to the end of the buffer.

**Comment by hferreiro** [comment]
I've just updated to latest stable and this is still not working for me.

**Comment by ConradIrwin** [comment]
I looked into this a bit, and it seems like there's been a race condition for a while but which has got worse recently. The reason `:%` it doesn't work is that it happens too quickly and so it jumps you to the end of the command palette instead of the editor (this also means that things like `:5` to go to line 5 don't work any more either).

I think the right fix to this is more of a restricting of how vim mode works, currently we track the active editor ourselves, but I think we could/should use the workspace's active_item instead.

**Comment by hferreiro** [comment]
This seems to be fixed in version 0.123.2.
