### ISSUE TITLE
Fuzzy finder is both too fuzzy and not fuzzy enough

### ISSUE THREAD

**Issue by brandonweiss** [zed-industries/zed#4315]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I often feel the fuzzy finder is giving me really poor results, although usually I don’t get a chance to capture it. But I think this one I noticed today highlights the problem pretty well:

<img width="574" alt="Screenshot 2023-12-01 at 8 45 10 AM" src="https://github.com/zed-industries/community/assets/4727/a5c5d3e2-58cf-4d3d-b5d4-505035ce3caa">

Also adding this one for good measure:

<img width="556" alt="Screenshot 2023-12-01 at 8 49 25 AM" src="https://github.com/zed-industries/community/assets/4727/60767147-6466-4f58-a944-391db6bdf4b0">

I know there’s another issue regarding spaces not working in the fuzzy finder, but I felt like it was relevant in so far as showing that the fuzzy finder generally feels sort of broken, which is disappointing because it feels like pretty core functionality in an editor to me.

### Environment

Zed: v0.113.0 (stable)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
Hi @brandonweiss,

Happily the `space` being poorly handled in search was fixed a while back.
 
Separately, although your issue is older, I think I'm going to close this in favor of this single tracking issue:

- https://github.com/zed-industries/zed/issues/12698

If this is incorrect, feel free to reopen with some more detail.
Your screenshot alone documents how bad it used to be.
Thanks again for reporting.
