### ISSUE TITLE
Tailwind LSP support in Ruby files for Phlex Components

### ISSUE THREAD

**Issue by bradgessler** [zed-industries/zed#4368]
### Check for existing issues

- [X] Completed

### Describe the feature

Similar to https://github.com/zed-industries/zed/issues/6340 and https://github.com/zed-industries/zed/issues/6306, Tailwind LSP auto-complete would be useful in Ruby (.rb) code for authoring Phlex components.

### If applicable, add mockups / screenshots to help present your vision of the feature

I have this working in Sublime Text at https://gist.github.com/bradgessler/1907d07593918fb5d2f27911bccc75f4

Here's what it looks like in .rb files when decorating the `class:` attribute with a Tailwind class:

<img width="806" alt="Screenshot 2023-11-07 at 8 22 01 AM" src="https://github.com/zed-industries/community/assets/4628/369a3fb1-e1f0-4200-af06-b0d90aa8d759">

**Comment by joeldrapper** [comment]
In VSCode, Tailwind can be configured to work in Ruby files like this. Is there any way to access the same configuration in Zed?

```json
{
  "tailwindCSS.includeLanguages": {
    "ruby": "html"
  },
  "tailwindCSS.experimental.classRegex": [
	"\\bclass:\\s*[\"']([^\"']*)[\"']",
  ]
}
```

**Comment by drale2k** [comment]
This would be great. I am not using phlex but this addition would also make it work for standard ERB rails helper tags, like 
`<%= f.label :keywords, class: "block text-sm ...` i assume? Currently it only works with plain HTML in ERB files

**Comment by kucho** [comment]
I think we will be able to have it working soon after https://github.com/zed-industries/zed/issues/5830 and https://github.com/zed-industries/zed/pull/11360 🚀

**Comment by joeldrapper** [comment]
That’s awesome!

**Comment by mrnugget** [comment]
I'm pretty sure with these settings and the latest version of the Ruby extension (which includes this: https://github.com/zed-industries/zed/pull/12742) this is fixed:

```json
{
  "languages": {
    "Ruby": {
      "language_servers": ["tailwindcss-language-server", "..."]
    }
  },
  "lsp": {
    "tailwindcss-language-server": {
      "settings": {
        "includeLanguages": {
          "erb": "html",
          "ruby": "html"
        },
        "experimental": {
          "classRegex": ["\\bclass:\\s*['\"]([^'\"]*)['\"]"]
        }
      }
    }
  }
}
```

And @joeldrapper tweeted that it works: https://twitter.com/joeldrapper/status/1798812799898136856

Happy to reopen if it doesn't work though.

**Comment by MSchmidt** [comment]
At some point this stopped working for me. I'm still using the config from this thread. Any new settings someone has figured out for Zed + Rails + Phlex + Tailwind?

**Comment by drale2k** [comment]
> At some point this stopped working for me. I'm still using the config from this thread. Any new settings someone has figured out for Zed + Rails + Phlex + Tailwind?

This keeps breaking for the regularly. I opened an issue https://github.com/zed-industries/zed/issues/27118

**Comment by KonnorRogers** [comment]
So I installed Zed for the first time today to try to help. (Very nice editor btw, coming from Neovim, the snappiness felt great)

I wasn't able to get it working in Phlex unfortunately. I did have it working in ERB however.

Minimal repro:

```bash
mkdir -p tailwind-phlex
cd tailwind-phlex
npm init -y
npm install tailwind
echo "@import \"tailwindcss\";" > index.css
touch test.{html,erb,rb}
```

<details>

<summary>ZED settings</summary>

```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette (cmd-shift-p / ctrl-shift-p)
{
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "Ayu Mirage"
  },
  "languages": {
    "Ruby": {
      "language_servers": ["ruby-lsp", "tailwindcss-language-server", "!solargraph", "!rubocop"]
    }
  },
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          // This disables diagnostics
          "diagnostics": true
        }
      }
    },
    "tailwindcss-language-server": {
      "settings": {
        "includeLanguages": {
          "ruby": "html",
          "eruby": "erb"
        },
        "experimental": {
          "classRegex": ["class:\\s*['\"]([^'\"]*)['\"]"]
        },
        "suggestions": true,
        "emmetCompletions": false
      }
    }
  }
}

```

</details>

So theres a few problems:


Tailwind v0.14.5 seems to have broken logic for finding the root file of a project, especially in files without a root level `tailwind.config.js`

https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1139

https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1228#issuecomment-2692557703

https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1033#issuecomment-2768794078

I created a top-level `index.css` in the root of the repo, and ERB / HTML completion started working, and I could see in the debug logs it was able to establish the root.

Where I think its getting lost is it doesn't know that Ruby can still have an HTML context, and its almost like the `experimental.classRegex` is just not firing, because I see tailwind registering the `"document/didChange"`

I *feel* like the most "comprehensive" solution would be to make an `injections.scm` in the [tree-sitter-embedded-template](https://github.com/tree-sitter/tree-sitter-embedded-template/tree/master/queries)

Barring that, someone could probably make an extension that adds an `injections.scm` to properly infer the HTML embedded context, but im not familiar enough with Zed to know how that would work. A [Ruby LSP addon](https://shopify.github.io/ruby-lsp/add-ons.html) may be another place to look, but I don't know if it can communicate the embedded language to Tailwind.

**Comment by bradgessler** [comment]
I’ll add that Tailwind v4 projects don’t have a `tailwind.config.js` file since it no longer uses JS for configuration.

**Comment by KonnorRogers** [comment]
> I’ll add that Tailwind v4 projects don’t have a `tailwind.config.js` file since it no longer uses JS for configuration.

Sorry yea I wasn't 100% clear there. Been staring at GitHub issues for a while, but Tailwind v4 did get rid of the config file, but the LSP still uses it for downgrading the LSP for v3 compatibility.

**Comment by Vagab** [comment]
I wonder if the class regex can also handle this case somehow?:
```ruby
div(class: %w[someclass someother-class])
```
I've been able to make it work with non percentage arrays:
```ruby
# regex: "\\bclass:\\s*\\[(.*?)\\]"
div(class: ["someclass", "someother-class"])
```
but `"\\bclass:\\s*%w\\[(.*?)\\]"` fails for percentage arrays. Maybe someone managed to make it work?
