### ISSUE TITLE
The node process using a lot of memory while working on a vue project

### ISSUE THREAD

**Issue by freedomlang** [zed-industries/zed#4405]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a vue project by zed
2. Check Activity monitor and find the node process started by zed

### Environment

Zed: v0.109.1 (stable)
OS: macOS 13.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1302" alt="image" src="https://github.com/zed-industries/community/assets/11409069/9f46443a-6e19-4e7c-8d2b-87d07d273c40">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by rubnogueira** [comment]
@JosephTLyons I'm having the same issue (not a vue project).
<img width="819" alt="image" src="https://github.com/zed-industries/zed/assets/40404708/3e0f21fc-384b-4773-862f-82b66ad95da1">

I'm assuming that this "Code Helper (Plugin)" is doing the same as the "node" zed process. Because when I go to "Open Files and Ports," I can see all my .ts project files there.
