### ISSUE TITLE
Zed process off the charts after running code from terminal

### ISSUE THREAD

**Issue by Pantagrueliste** [zed-industries/zed#4515]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever I run the app I'm currently developing on Zed from the terminal, Zed process goes out of control. All the files related to my project are opened, including large json files, which I suspect could be the cause of Zed's erratic behaviour. Could be related to zed-industries/zed#4525 or zed-industries/zed#5233.

<img width="273" alt="Screenshot 2023-08-27 at 14 38 32" src="https://github.com/zed-industries/community/assets/9995536/01516b5c-edbb-4bc1-bce3-b8b9c9f1e464">

### Environment

Zed: v0.100.1 (stable)
OS: macOS 13.5.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
Given that there has been significant changes in the intervening 13 months since this issue was filed I'm going to go ahead and close this issue.  Apologies @Pantagrueliste that we didn't give your issue the proper consideration it deserved.  If experience pegged CPU usage in the future, please feel free to open a clean issue and we're happy to help.

Thanks for reporting!
