### ISSUE TITLE
add command to switch between source and header files

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#4546]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like a quick way of switching between matching `.h` and `.cc`/`.cpp` files. While not part of the LSP spec, `clangd` provides support for that: https://clangd.llvm.org/extensions.html#switch-between-sourceheader.

**Comment by notpeter** [comment]
Hi @hferreiro.  Even though this issue was opened first, I'm going to close this in favor of another because it has more upvotes and links to neovim/vscode implementations:
- https://github.com/zed-industries/zed/issues/12801

Please be sure to 👍 upvote that issue and subscribe over there to track progress.

Thanks for reporting!
