### ISSUE TITLE
Strange string breaks markdown highlighting

### ISSUE THREAD

**Issue by MoritzKn** [zed-industries/zed#4565]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The following string seems to break the highlighting after it:

```
`__name__)(__name__`
```

This is a real world string from this post:
https://www.robustperception.io/which-are-my-biggest-metrics/

### Environment

Zed: v0.96.4 (stable)
OS: macOS 13.4.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2023-07-31 at 16 11 50](https://github.com/zed-industries/community/assets/10676525/d587b930-eb36-434d-af4e-4b5b494020aa)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Tobbe** [comment]
I just noticed md highlighting issues too:

![markdown highlighting screenshot](https://github.com/user-attachments/assets/d425e653-6f35-4360-81f1-2505f1cc6893)


```
Allow passing `NavigateOptions` (which for now is just `replace`) from a
`<Link>` and `<NavLink>` to `navigate()` by setting an `options` prop on the
link component.
```

This sounds/looks very similar to https://github.com/zed-industries/zed/issues/8108 but since that one was closed I'm commenting here on this issue instead
