### ISSUE TITLE
Can't open Zed under another user account

### ISSUE THREAD

**Issue by dangh** [zed-industries/zed#4607]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have two accounts on my Mac, and I use them simultaneously for different purposes.
If I open Zed in the first account, switch to the second account and open Zed, it quit immediately.
Running Zed CLI, it just stuck there and doesn't print anything.

Just noticed it today, it was working fine before.

### Environment

Zed: v0.95.2 (stable)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

All I got from Zed.log file

```
2023-07-21T10:54:47 [INFO] Got instance handshake
```

**Comment by samsonjs** [comment]
This is more than a bit unfortunate. As someone who uses separate personal and work accounts on my machine this is a deal-breaker. Really sad end to my very short journey into trying Zed.

**Comment by dangh** [comment]
@ForLoveOfCats Sublime Text also use socket and they has a uniq hash in the socket name. Could we do the same for Zed?
https://github.com/sublimehq/sublime_text/issues/3376

**Comment by samsonjs** [comment]
That sounds like a relatively simple task so I tried diving in to see what's involved in making this work, and it looks like it might be using a TCP socket with a hard-coded port number rather than a Unix socket for this purpose:

![CleanShot 2024-07-10 at 08 36 12@2x](https://github.com/zed-industries/zed/assets/32487/ab455dd3-0fe5-4752-848e-6cb842c02b77)

![CleanShot 2024-07-10 at 08 29 18@2x](https://github.com/zed-industries/zed/assets/32487/bdd2f67d-0023-4fd0-9b07-51c733852b9e)

On macOS and Linux, users have unique numeric IDs and those could be added to the port number to make it unique, which seems like it could work fine. I'm not sure how things work on Windows (does Zed even run on Windows?). I'm willing to help out with this one because I like what I see so far but I've never written a line of Rust in my life so I'd probably need some guidance.

There is definitely some Unix socket stuff in here too but it doesn't look directly related to the message I see when running `/Applications/Zed.app/Contents/MacOS/zed`, which is: "zed is already running". And I can't find that actual socket file on my system so don't _think_ that's what's preventing me from launching another instance.

![CleanShot 2024-07-10 at 08 37 20@2x](https://github.com/zed-industries/zed/assets/32487/8a3e677c-f008-4fb2-a3d7-cd9f91d48b8a)

I do have something listening on 127.0.0.1:43739 though so that must be zed:

```
/Users/sjs % netstat -an | grep -i 43739
tcp4       0      0  127.0.0.1.43739        *.*                    LISTEN     
```

**Comment by samsonjs** [comment]
Don't have time to try this out at the moment but could it really be this easy?!

![CleanShot 2024-07-10 at 09 05 52@2x](https://github.com/zed-industries/zed/assets/32487/f1285757-9437-4d34-b0fb-86cddfc947ea)

**Comment by dangh** [comment]
@samsonjs will there be a case that first user using Preview build prevents second user using Dev build?

**Comment by samsonjs** [comment]
@dangh Yes good call, it's not this simple! 🤦‍♂️

**Comment by samsonjs** [comment]
A small tweak like staggering the ports could make this general approach work. I'm stuck trying to test this because I don't know how to package it into an app bundle, and running multiple instances of the binary directly from my shell works fine even under the same user so it seems like there's a difference between running a plain binary and an app . I'll try submitting a draft PR to see if I can get some help and guidance from the core team. I'm committed to giving Zed a fair shot 😄 

![CleanShot 2024-07-10 at 21 31 41@2x](https://github.com/zed-industries/zed/assets/32487/79dca358-f23f-4dc6-b2d6-063594cca6fa)

**Comment by dangh** [comment]
@samsonjs I would change to `43x37` instead of `437x7`. I personally never have more than 10 users on my machine but if anyone want it at least they can :p

**Comment by samsonjs** [comment]
That should be fine and it makes sense, no reason not to allow more users. On macOS user IDs start at 500 and on Linux they start at 1000 so there's lot of room in there.

**Comment by deveshXm** [comment]
Any updates on this ? Would really love to have this feature as I'm not able to use Zed on different accounts
