### ISSUE TITLE
Autocomplete doesn't work anymore 

### ISSUE THREAD

**Issue by domaschh** [zed-industries/zed#4613]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I try to apply a suggested autocomplete word with tab or enter it just either inserts a new line or tabs. Clicking the suggestion works tho.

### Environment

Zed: v0.95.2 (stable)
OS: macOS 13.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[logs.txt](https://github.com/zed-industries/community/files/12104146/logs.txt)

**Comment by rsheidow** [comment]
Feel free to close out - issue resolved._______________Best Regards,      Ryan SheidowOn Sep 24, 2024, at 08:55, github-actions[bot] ***@***.***> wrote:﻿
Hi there! 👋
We're working to clean up our issue tracker by closing older issues that might not be relevant anymore. Are you able to reproduce this issue in the latest version of Zed? If so, please let us know by commenting on this issue and we will keep it open; otherwise, we'll close it in a week. Feel free to open a new issue if you're seeing this message after the issue has been closed.
Thanks for your help!
