### ISSUE TITLE
Auto-detect language in new files

### ISSUE THREAD

**Issue by probablykasper** [zed-industries/zed#4682]
### Check for existing issues

- [X] Completed

### Describe the feature

Auto-detecting what language is being typed in a new file. VSCode has this feature:

https://github.com/zed-industries/community/assets/11315492/84ec127c-61f3-4f6d-85a6-3a574d2d61d8

**Comment by evrensen467** [comment]
Seems like VSCode uses the [guesslang](https://github.com/yoeo/guesslang) ML model to achieve this, maybe zed can do something similar.

**Comment by JosephTLyons** [comment]
Hey @probablykasper,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4868

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
