### ISSUE TITLE
Can’t type `“` open/left double quote mark 

### ISSUE THREAD

**Issue by skullface** [zed-industries/zed#4722]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The MacOS-standard shortcut for typing “smart”/typographer’s/curly double quotes is <kbd>Option</kbd> + <kbd>[</kbd> for the left/open mark (`“` U+201C) and <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>[</kbd> for the right/closed mark (`”` U+201D). When I perform the shortcut for `“` (left/open), nothing appears, but `”` (right/closed) works just fine.

I have no custom keymapping defined.

### Environment

Zed: v0.87.6 (stable)
OS: macOS 13.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
Hi all! 👋 

It appears that the original issue has been fixed in Zed and so I'm going to close this issue.
<img width="444" alt="Screenshot 2024-09-24 at 16 26 51" src="https://github.com/user-attachments/assets/540f1590-9e40-46f5-914f-c08d9692414f">

We do partially support unmapping keys (duplicate the context/binding from the default keymap and set the action to `null`) although there are some outstanding issues:
- https://github.com/zed-industries/zed/issues/7544

The separate concerns that @woylie raised [above](https://github.com/zed-industries/zed/issues/4722#issuecomment-1908631570) are still valid, but I wanted to let you know that we are working on revamping our key binding system to properly support non-US keyboard including proper handling of dead keys, matching localization specific macOS shortcuts, etc.  Here is a discussion with some details about our thinking:
- https://github.com/zed-industries/zed/discussions/17031

Thanks for reporting and enjoy using “smart” ‘quotes’ in Zed!
