### ISSUE TITLE
Items in `.gitignore`should still be searchable via file finder

### ISSUE THREAD

**Issue by mifopen** [zed-industries/zed#4745]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Create file with name `.env.local` in the open directory
2. Open file search pallete
3. Search for `env` or `local`

### Environment

Zed: v0.85.4 (stable)
OS: macOS 13.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by abejfehr** [comment]
Piggybacking to share this related behaviour: in VS Code, doing "Find in folder" and searching for a query works if a folder is ignored, but in Zed that doesn't seem to be the case.

Even if build/dist folders are grayed out in the editor, sometimes I want to make sure that something built correctly by searching for a string directly in a hidden folder.

Similar thing if I'm learning how a node_module works, sometimes I want to perform a scoped search in the node_modules folder even though it's ignored

**Comment by fvsch** [comment]
I have this issue as well. I understand that excluding all files matched in `.gitignore` is helpful to exclude directories with installed dependencies (`node_modules`, `vendor`, etc.), and temporary outputs like build artifacts and caches.

Still, there are gitignored files which are legitimately useful to be able to open quickly.

Some possible heuristics that could balance those two needs (at the cost of some complexity):

- Include the file in results if the query is sufficiently precise. For instance, include the file only if the query matches enough of the file name and the start of the file name, so typing `env` will not return `.env.local` but typing `.env` or `.env.` might?
- Include the file in results but deprioritize it (i.e. put gitignored results at the end, so that you have to have a sufficiently precise query to filter out other not-ignored matches).
- Only exclude gitignored _files_ which which are children or descendants of a gitignored _directory_. That would typically exclude dependencies and cache, but include config files.

**Comment by alex-astronomer** [comment]
I have started work on this issue.  The solution that I came up with is adding an "Ignore Included" toggle to the FileFinder Picker.

<img width="744" alt="image" src="https://github.com/zed-industries/zed/assets/89415310/bcc0c68c-e986-4c9c-9a8d-f71a74cbd79a">

**Comment by SomeoneToIgnore** [comment]
This is a relatively hard issue to tackle, if put in a generic form as "[any] items in `.gitignore` should still be searchable via file finder".
The hardest part would be to keep the file finder searching very fast with all gitignored files knowledge (https://github.com/zed-industries/zed/issues/7504).

First of all, `note_modules/`, `target/`,  `foo_bar_output`, `.env` or other files are all alike to Zed and it does not have any heuristics on their side.

Consider https://github.com/microsoft/vscode-eslint project as a web example, after installing the dependencies with `npm i`:
```
❯ find . -type f ! -path node_modules |wc -l
     870

❯ find . -type f |wc -l
    7882

❯ du -ha node_modules
........snip
 90M	node_modules

❯ du -ha .
........snip
104M	.
```

`node_modules` is a [gitignored](https://github.com/microsoft/vscode-eslint/blob/8173467bfdb046468336e5b6878fdf484d69cfba/.gitignore#L2) directory there, has by an order of magnitude more files than the real project and occupies ~90% of the project, size-wise.

Also note that this repo is a relatively small project that does not include Angular or React + somethingX + .. in its `package.json`.

## State in Zed

Zed used to track all gitignored files at some point, but it was soon discovered that it becomes unresponsive relatively quickly due to the requirement to react on all related FS events and also [re]scan directories:
https://github.com/zed-industries/zed/blob/e77d313839b382760a5d24c550e2ab795a1fac27/crates/worktree/src/worktree.rs#L3460

Now, Zed does scan only the non-ignored directories:
https://github.com/zed-industries/zed/blob/e77d313839b382760a5d24c550e2ab795a1fac27/crates/worktree/src/worktree.rs#L2455 and `expand_entry -> refresh_entries_for_paths -> forcibly_load_paths` chain of actions in the worktree — so, all currently expanded gitignored directories will be added into the same collection of worktree entries:
https://github.com/zed-industries/zed/blob/e77d313839b382760a5d24c550e2ab795a1fac27/crates/worktree/src/worktree.rs#L135-L136

and will be used when searching or displaying in the project panel, project search, file finder and various entry-related iterations.

This way, Zed only "indices" and uses gitignored files if they are in the worktree/"project" root (as it gets opened by default) and all other directories that were open (e.g. due to autonavigating in the project tree to the entry corresponding to the editor opened).
This index is a core thing when it comes to addressing the files, so things might get slow if more entries will be added inside.
Seems that there are some scaling issues with the current model already: https://github.com/zed-industries/zed/issues/8242 and adding more (10x at least) things on top is easy, if possible at all.

Zed does not use "gitignored files" concept too frequently: it shows a different icon in the project panel (ergo the whole "load gitignored directories via `expand_entry` call" story) and allows to do a project search on files + the gitignored ones.
The project search part is done via a separate, background thread walking the gitignored tree roots and matching the files + there's a limit on the number of entries: https://github.com/zed-industries/zed/blob/e77d313839b382760a5d24c550e2ab795a1fac27/crates/project/src/project.rs#L6299-L6300

## Design considerations

At first, we need to understand what to display and how. So far, it feels that there are certain people that expect Zed showing an arbitrary `node_modules/foo/bar.ts` file in file finder if queried, and some other set of people who will be happy with just their `.env.*` files from the project root opening in the file finder.

The latter are simple to fix with https://github.com/zed-industries/zed/pull/9760 or similar, but keeping the same design, how could former part be done?
I currently think it's not really possible? As we cannot bloat the main cache with so many extra entries, but have to be able to answer fuzzy path queries over a 10x repository of files.

While traversing such file trees in realtime for fuzzy match queries does not sound possible, caching seems hard too due to invalidation? 
Current, worktree entry SumTree cache, tracks every related FS event for that which would not work here, so either some other strategy has to be picked, or a better way of approaching the problem considered — it seems rather wasteful to cache 10x of the repo size just to enable file finder queries.

Neither of the current editors known to me seem to provide any similar functionality, but VSCode has a "whitelist" of directories to track — we could solve the issue with yet another config thing but that would not be very discoverable and might still slow things down overall on large enough `node_modules` if we reuse the same worktree entry SumTree cache.
On the bright side, with reasonable defaults (we can add all `.env*`-like files there explicitly) it will work for many people.

One idea that seems worth exploring is to add more interactivity into file finder and propose to input gitignored roots first to start looking them up: match regularly before receiving `node_modules` or whatever other gitignored root that was not scanned, then start to propose `node_modules/*` directories that match further file finder queries, e.g.
for `node_modules/pr`, the picker will show first N directories with names starting with `pr`.
Since the input operation is relatively tedious, some list completion would be needed + a background indexing task might index a subset and switch to regular, fuzzy matching mode.
While might be a blast if implemented properly, sounds rather complicated (and would require more design than anything else above) and the "whitelist" + new file finder input toggle sound more feasible to do.

**Comment by solventak** [comment]
Ohhh interesting.... Thank you so much for replying so quickly to this issue.  I will take a look through the (incredibly extensive) comment that you left and I'll let you know if I have additional questions.

**Comment by CurbaiCode** [comment]
#6927 seems like it could be related to this.

**Comment by Hemant-Mann** [comment]
I think the solution by @aarroisi should work.

I also need to search some files which are ignored in .gitignore like configurations or some internal dependency, giving a configuration option to the user would give them more control over what they want to search, the default behaviour is okay but we must have an option to override it if needed!

**Comment by ottodevs** [comment]
Another idea could be just reusing the already proved and mature `.gitignore` syntax so users are able to do things like:

```jsonc
  "file_scan_exclusions": [
    "!.env*"
  // (...your other exclusions) 
]
```

whenever the editor reads the `.gitignore` fail it would be just applying the file_scans_exclusions over it to come up with the final exclusions list with a great flexibility and avoiding introducing new settings.

**Comment by thnt** [comment]
I think we just need to allow to search file by relative path, ex: `./.env.local` to open ignored file

**Comment by Tobbe** [comment]
I think [@abejfehr's comment](https://github.com/zed-industries/zed/issues/4745#issuecomment-1908860611) is worth more attention.

If I explicitly list a .gitignored directory in my "include" filter I think it makes sense to override the exclusion of that directory and actually include files inside it when searching, even though it's part of my .gitignore

**Comment by maxsbelt** [comment]
E.g. in vscode my workaround is to use .ignore file to unignore the things that I want to see in quick search:

.gitignore
```
*.local
```

.ignore
```
# enables ability to jump to .env.local file through VSCode quick search
!.env.local
```

**Comment by AgapovOne** [comment]
I read thread diagonally and still don't get how one could search for ignored files, it's not user-friendly. Do some button in UI with a hotkey to enable/disable ignored search. Other options would lead to ton of developers searching through github issues, not doing the actual work

**Comment by StaTicDKK17** [comment]
For anyone who is interested in this. I spend the time reading through PRs and wrote an article about how it actually works. It was merged into zed last week. If you want to read a basic description my article is here: https://medium.com/@thobias.larsen/zed-editor-can-finally-search-for-git-ignored-files-61df8516456f this link should be available to everyone :)

**Comment by coopbri** [comment]
> For anyone who is interested in this. I spend the time reading through PRs and wrote an article about how it actually works. It was merged into zed last week. If you want to read a basic description my article is here: [medium.com/@thobias.larsen/zed-editor-can-finally-search-for-git-ignored-files-61df8516456f](https://medium.com/@thobias.larsen/zed-editor-can-finally-search-for-git-ignored-files-61df8516456f) this link should be available to everyone :)

Thanks so much! This issue was closed without any leads, lol. Appreciate you!

**Comment by sylbru** [comment]
Landing in v164!

**Comment by mmikhan** [comment]
I just found that there's an option baked in. `⌘⇧p` to `project panel: toggle hide git ignore` shall toggle between git ignored files inside the file tree
