### ISSUE TITLE
Sort autocomplete suggestions by prefix/exact match

### ISSUE THREAD

**Issue by msfeldstein** [zed-industries/zed#4817]
### Check for existing issues

- [X] Completed

### Describe the feature

Right now if i have a type Tensor in my code and i press ctrl+space to add its import, the first dozen items are irrelevent and the actual exact match is way down in the list.  Exact Tensor matches should be at the top, followed by things prefixed with Tensor, then fuzzy matches after that.  `Ctrl-space enter`should be a reliable way to just add missing imports

![image](https://user-images.githubusercontent.com/161135/230510518-3450a3d8-6a22-4b0e-a4e0-3377f5d1deaf.png)

**Comment by JosephTLyons** [comment]
It seems out matching algorithm has improved a bit since this issue was created, so I'm going to close this out. If you run into more cases where Zed is picking the wrong thing first, please open a new issue.

<img width="732" alt="SCR-20240728-coaq" src="https://github.com/user-attachments/assets/a32ef25c-0547-4f5a-a8f9-94ba4c7df1d0">

**Comment by nicholaswmin** [comment]
should have an option to disable fuzzy finder
