### ISSUE TITLE
Recognize solid-js

### ISSUE THREAD

**Issue by tonyrewin** [zed-industries/zed#4825]
### Check for existing issues

- [X] Completed

### Describe the feature

`tsx` files are recognized properly as react source code, but it is not used only for react, it can be used for solid-js which is widely used framework as well.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="335" alt="Снимок экрана 2023-04-06 в 13 32 07" src="https://user-images.githubusercontent.com/454794/230353106-1a951c41-3754-42e2-aace-3a5255a3193a.png">

**Comment by iamcdonald** [comment]
Hi,

Just wondering if there's been any movement on this?
Happy to take a look if not.

Iain

**Comment by JosephTLyons** [comment]
We now have a `Solidity` extension in the extension store:

<img width="1479" alt="SCR-20240728-cpls" src="https://github.com/user-attachments/assets/702104ac-b307-4c06-858d-09d1ca26f95d">

<img width="1022" alt="SCR-20240728-cphu" src="https://github.com/user-attachments/assets/eb18dc32-7feb-4ad6-a272-a1655d87bc64">

**Comment by spenat28** [comment]
> We now have a `Solidity` extension in the extension store:
> 

Solid-JS - is framework which uses `TSX` markup, and is still not completely recognized, since in SolidJS we can write syntax such as `on:click` - while Zed is not recognizing that as valid code.

`Solidity` is a statically-typed curly-braces programming language designed for developing smart contracts that run on [Ethereum](https://ethereum.org/). ...

Which has nothing to do with Javascript - and SolidJs frontend framework ...

This issue should not be closed. Can you please reopen this?
