### ISSUE TITLE
Typing blocked for a fraction of a second after pressing the arrow keys

### ISSUE THREAD

**Issue by spaceexperiment** [zed-industries/zed#4826]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I often would want to delete or type a charachter after pressing the left/right arrows. but it seems to be blocked for a fraction of a second before I am able to type.

### Environment

Zed: v0.80.5 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Zed has undergone a lot of changes since this issue was filed, lots of performance enhancements, an entire rewrite of our UI engine, etc. Doing a delete after moving the cursor via the arrow keys feels pretty snappy to me, so Im going to close this issue out. If you are still experiencing some issue on your end, feel free to open up a new issue!
