### ISSUE TITLE
Sorting files in Project Panel

### ISSUE THREAD

**Issue by kropochev** [zed-industries/zed#4851]
### Check for existing issues

- [x] Completed

### Describe the feature

Add the ability to sort files like in VS Code.

### If applicable, add mockups / screenshots to help present your vision of the feature

VS Code
<img width="356" alt="VS Code" src="https://user-images.githubusercontent.com/8565494/229268829-66900300-7fcc-43a4-aa51-e7659bb32f9a.png">
Zed
<img width="363" alt="Zed" src="https://user-images.githubusercontent.com/8565494/229268852-05d94587-82ae-4c27-989d-78fcc3f4fd0f.png">

**Comment by Ilham-Habibullin** [comment]
Hello, i've created a discussion about adding feature for manual rearranging of files/folders order in project panel. 

As far as i understand what you talking about in this issue is something like a custom rules for sorting e.g. alphabetical or numerical or folders-first-files-last or by-creation-time and etc., while what i mean is manual rearranging like in this GIF

![ezgif-4-37ca8f3fe0](https://github.com/zed-industries/zed/assets/18722721/041a8150-c994-4170-ae87-1032da5cb851)

One of the IDEs that does that is Xcode. 

I wonder if what i proposing in my discussion can be considered as part of this issue. What do you think @kropochev @hungify @JosephTLyons ?

**Comment by imarfanc** [comment]
how can someone change the sorting order?
(i want it to match however i have it my finder/file explorer)
