### ISSUE TITLE
Terminal tabs cannot be split

### ISSUE THREAD

**Issue by dcow** [zed-industries/zed#4854]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you are on a terminal tab (`+` -> `New Terminal`) and you select the split button in the upper right then select one of the options, nothing happens.

I was trying to do this to move the terminal window to be on the right. I just found the dedicated option to move the dock around and anchor it to the right, and I can get a terminal window to be on the right that way, but then the dock is always on the right (which is fine for me for now but not if I had reason for the dock to stay on the bottom and just wanted a terminal split on the right). In any event, the bug exists either way: selecting a split does nothing.

### Environment

Zed: v0.79.1 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey <user>,

I'm going to close this issue out in favor of:

- https://github.com/zed-industries/zed/issues/4351

This isn't normal protocol, usually, we close out newer dupes in favor of older ones, but the dupe above slipped past us and gained more upvotes than this original. Please upvotethe linked issue with a thumbs up (👍) so that we can keep all the votes in one place?
