### ISSUE TITLE
Empty project window does not get closed when opening a project

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#4889]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If there is no window, I have to open one in order to get access to the "Open Recent" modal. After picking a project from that modal, it gets opened in a new window, but the now unnecessary empty project window does not get closed.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 12.6.3
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment]
Hi @jansol, Even though your issue is older, I'm going to close this in favor of an another issue which has screenshots:

- https://github.com/zed-industries/zed/issues/10101

Please 👍 vote for that issue and subscribe over there to track progress.
Thanks for reporting, I've been bugged by this behavior as well.
