### ISSUE TITLE
Persist undo history across restarts

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#4942]
### Check for existing issues

- [X] Completed

### Describe the feature

Title says it all.
I'm experiencing this issue at least once a day https://github.com/zed-industries/zed/issues/5951 which I guess is the main reason for wanting this feature. But even outside of that I can imagine this being useful.

**Comment by JosephTLyons** [comment]
Hey @N8th8n8el, I normally close out new issues for older duplicates, but I think in this case, I will close this one out in favor of:

- https://github.com/zed-industries/zed/issues/15097

Since it has some details on what we've landed so far, recently, in the world of workspace serialization. For anyone following this issue, please upvote (👍) the aforementioned issue!
