### ISSUE TITLE
Multiple external commands for format_on_save

### ISSUE THREAD

**Issue by Liam-Breen** [zed-industries/zed#5072]
### Check for existing issues

- [X] Completed

### Describe the feature

Add the ability to have multiple external commands for `format_on_save`.

### If applicable, add mockups / screenshots to help present your vision of the feature

```
{
    "buffer_font_size": 15,
    "language_overrides": {
        "Python": {
            "format_on_save": {
                "external": [
                    {
                        "command": "isort",
                        "arguments": [
                            "-"
                        ]
                    },
                    {
                        "command": "black",
                        "arguments": [
                            "-"
                        ]
                    }
                ]
            }
        }
    }
}
```

**Comment by daniel-nguyen24** [comment]
> If anyone is looking at this and wants to solve this exact problem (isort and black) my zed config looks like:
> 
> ```
> "Python": {
>             "formatter": {
>                 "external": {
>                     "command": "poetry",
>                     "arguments": [
>                         "run",
>                         "isort",
>                         "--stdout",
>                         "{buffer_path}",
>                         "|",
>                         "poetry",
>                         "run",
>                         "black",
>                         "-"
>                     ]
>                 }
>             }
>         }
> ```
> 
> EDIT: this actually didn't work at all, got some weird "Broken 5 paths" string appended to a file every time I saved it.

Not sure whether you've got this fixed or not but this is what I have in my `settings.json`
```json
{
  "languages": {
    "Python": {
      "formatter": {
        "external": {
          "command": "poetry",
          "arguments": ["run", "sh", "-c", "isort - | black -"]
        }
      },
      "format_on_save": "on"
    }
  }
}
```

Temporary workaround until there's support for multiple formatters

**Comment by JosephTLyons** [comment]
Closed via:

- https://github.com/zed-industries/zed/pull/14846

**Comment by srfsh** [comment]
> Closed via:
> 
>     * [Allow user to use multiple formatters #14846](https://github.com/zed-industries/zed/pull/14846)

Hi,

My use case isn't really related to Python, but it is related to *sequential* ordering of the formatters. You see, I am piping the default language server's output to `unexpand`[^1], which packs the spaces into tabs as, in my case, there's no option to tell this to the formatter. The formatter in question here belongs to Dart, which takes an authoritarian stance toward customization for a reason I don't comprehend. I am not here to judge them, however.

This is what I used to have before I discovered the feature for multiple formatters. Here, as can be clearly seen, the sequential order is `dart format` first, then `unexpand`. And this is exactly what happens when it is used.

```
{
	"languages": {
		"Dart": {
			"formatter": {
				"external": {
					"command": "sh",
					"arguments": [
						"-e",
						"-o",
						"pipefail",
						"-c",
						"dart format | unexpand --first-only -t 2"
					]
				}
			}
		}
	}
}
```

I tried to test the new feature, and according to the documentation, I should be able to replicate the behavior I used to have with the following new configuration.

```
{
	"languages": {
		"Dart": {
			"formatter": [
				{
					"language_server": {}
				},
				{
					"external": {
						"command": "unexpand",
						"arguments": ["--first-only", "-t", "2"]
					}
				}
			]
		}
	}
}
```

However, the order of execution appears to be mixed up when this is used. I tried to order them differently as well, but the behavior was identical: incorrect execution order. Sometimes the Dart formatter is applied later, sometimes before. Am I missing something or misusing this? Is this not the way it is intended to function?

I tried to look at the diff for the pull request but I didn't come across a test case that tests the way I expect it to work (forgive my oversight if that's not the case).

Please do tell me if this isn't the right place to mention about this. I would very like to create a separate issue or start a discussion if desired.

Happy hacking.

[^1]: `unexpand(1)` is a Unix utility that converts spaces into tabs. Its inverse is `expand(1)`.

**Comment by failable** [comment]
@srfsh Maybe related https://github.com/zed-industries/zed/issues/15544#issuecomment-2295975378

**Comment by srfsh** [comment]
> @srfsh Maybe related [#15544 (comment)](https://github.com/zed-industries/zed/issues/15544#issuecomment-2295975378)

Ah, yes. It definitely is related. I will mention it there, too. Many thanks.
