### ISSUE TITLE
Reduce the height of toolbar or allow moving/disabling

### ISSUE THREAD

**Issue by diocletiann** [zed-industries/zed#5241]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

N/A

### Describe the solution you'd like

Between the title bar, tab bar, and breadcrumbs bar, Zed seems to use ~100 vertical pixels before the code starts. I think users coming from Vim/Emacs would appreciate getting that space back, especially on laptop screens.

**Comment by JosephTLyons** [comment]
You can disable the tool bar (and some other options) via:

```json
"toolbar": {
    "breadcrumbs": false,
    "quick_actions": false,
    "selections_menu": false
  },
```

You can also disable the tab bar:

```json
  "tab_bar": {
    "show": false
  },
```

Since this is requested the ability to reduce height or disable, and we allow disabling, I'm going to close this issue out. If there is want for a setting to reduce the height of these elements, please open up a new issue.

**Comment by Malorn44** [comment]
Personally, I don't find this solution satisfactory. I still find the toolbar useful (so don't want to disable it), but also find it takes up more space than necessary.

Maybe something to adjust the font size of just the toolbar independent of the rest of the UI would be a good approach?

**Comment by xdotli** [comment]
any follow up on this issue?
