### ISSUE TITLE
Add a plugin interface to extend the editor

### ISSUE THREAD

**Issue by gracicot** [zed-industries/zed#5269]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I would like to write a plugin to add CMake support. Currently, as far as I can see, there is no support for writing, browse or install plugins.

Plugins are an essential way to grow the ecosystem of developers and allow anyone to make the editor act as they need in way the Zed developers cannot afford to develop or haven't thought of.

### Describe the solution you'd like

I can imagine my plugin be able to do this:

 - Add commands to build the project, configure the build system and clear the build directory
 - Have the ability to instruct the language server where is the `compile_commands.json`
 - Use triggers to complete actions like updating the build system config when a build system related file is changed
 - Show compilation output and configuration output to the user
 - Provide a way to display some UI elements like selecting the build profile
 - Configure debuggers when Zed supports debugging
 - Running a given CMake executable (either from path or a config)

### If applicable, add mockups / screenshots to help present your vision of the feature

A good plugin system should be 100% multiplatform and also allow multiple languages. It should also be secure and sandboxed. Rust has an extremely good support for WebAssebly coupled with WASI. A plugin written in wasm would be fast, allow for plugins to be written in Rust and also be multiplatform so only one target is required for a plugin to be used everywhere. Wasm with wasmtime or wasmer has a controllable sandbox and it should be possible to expose an API for Rust, C, and Typescript to allow writing plugin in whatever the plugin developer likes to write.

**Comment by haikyuu** [comment]
> I think it might be possible to implement a JavaScript-based plugin system using Deno.

This is a great attempt at that for neovim https://github.com/vim-denops/denops.vim
I find this a great fit for Zed

**Comment by ThatXliner** [comment]
Personally, I think a WASM system like https://github.com/lapce/lapce is a good idea

**Comment by sachaw** [comment]
Worth considering:
https://extism.org/

**Comment by berkus** [comment]
Will Zed be the first to support multiple plugin languages? Exciting!

**Comment by sirenkovladd** [comment]
> Will Zed be the first to support multiple plugin languages? Exciting!

Actually no, because above mentioned `lapse` and also `vscode` support wasm
therefore, zed will not be the first to support multiple plugin languages

**Comment by simonzkl** [comment]
When designing the plugin system it would be nice to support some sort of early initialization phase that plugins can hook into to set process environmental variables that other plugins (e.g. language servers) might depend on. This would be useful for https://github.com/zed-industries/zed/issues/4977 (direnv support).

See https://github.com/zed-industries/zed/issues/4977#issuecomment-1908639351 for more context.

**Comment by noozo** [comment]
My two cents: Multiple language plugins might become a nightmare to maintain in the long run. Just make the system in Rust (which is a nice enough language) and be done with it :)

**Comment by so1ve** [comment]
Just use wasm :)

**Comment by TheBlckbird** [comment]
> My (maybe unpopular) two cents: Multiple language plugins might become a nightmare to maintain in the long run. Just make the system in Rust (which is a nice enough language) and be done with it :)

WASM.

**Comment by konsumer** [comment]
Yep, I agree with others. WASM-based plugin system would be sick. You can target WASM in just about any language (including rust) and the plugins don't need to be recompiled per-machine/os, or need a complex interpreter, and are fairly efficient. WASM also has profiling and security-features that make it very good for any plugin-system.  It doesn't even need to be full WASI host or anything super-complicated, just like a central event-responder that has access to current buffer/selection and can trigger other zed-commands. Figma [used this](https://www.figma.com/blog/webassembly-cut-figmas-load-time-by-3x/) to allow users to make plugins in any language (most use rust and C++) and use them on the desktop/web app, with no recompile. You can compile rust, c, micropython, nelua, assemblyscript (typescript) and many more languages to wasm once, and they just drop-in, with no modification.

There is already [this](https://github.com/zed-industries/extensions) for theme/languages/grammars, but I think personally the plugins I would use most often would be "when you hit this key, call this command that does something with source in current buffer, on current line." A combination of these would be very cool (wasm for actual behavior, config for theme/grammar.)

Not having plugins is the only thing that makes me not use Zed full-time (I really like emmet for JSX, for example.)

**Comment by clarkezone** [comment]
+1

**Comment by brandondrew** [comment]
Since extensions already exist in Zed, is there any documentation for how we can create our own?

I use Zed by choice (most of the time) and HAML for legacy reasons, but it's driving me crazy that I can't do basic things like toggle multiline comments in HAML.  I started down the rabbit hole of creating my own HAML plugin, but I couldn't find any documentation.

I'm not looking forward to going back to VS Code for all my HAML files. 🙁

**Comment by colinta** [comment]
Many people mentioning VS Code, so I'll be the one to say _please do not model yourself off of VSCode's plugins_. It's bizarre to me that writing a plugin should be this level of tedious. Sublime Text got it right: open a file that is in the right folder, save it – and the editor (re)loads your plugin and you're done, back to work.

**Comment by maxdeviant** [comment]
> Since extensions already exist in Zed, is there any documentation for how we can create our own?
> 
> I use Zed by choice (most of the time) and HAML for legacy reasons, but it's driving me crazy that I can't do basic things like toggle multiline comments in HAML. I started down the rabbit hole of creating my own HAML plugin, but I couldn't find any documentation.
> 
> I'm not looking forward to going back to VS Code for all my HAML files. 🙁

@brandondrew We're still a little light on docs for extensions, but we do have a quick [guide](https://github.com/zed-industries/extensions/blob/1dc809ece0575df952833461686f62bba0170c3e/AUTHORING_EXTENSIONS.md) for getting started with making an extension.

Aside from that, we have a lot of examples of extensions in the [`extensions`](https://github.com/zed-industries/zed/tree/0ab5a524b024c375b4f259b47cd9d80e5a6f3919/extensions) directory in the Zed repo. These are all extensions that we extracted out of the Zed binary.

**Comment by maddanio** [comment]
Will there also be custom commands and build system integration? And integration with the editor aka inline type display, git status/blane etc?

**Comment by brandondrew** [comment]
> Will there also be custom commands and build system integration? And integration with the editor aka inline type display, git status/blane etc?

git blame was added in the last few days.

**Comment by maddanio** [comment]
My question was about the extension api, so far i could only see lsp integration, no build Systemintegration, commands, editor interaction, text manipulation etc

**Comment by mocenigo** [comment]
> My (maybe unpopular) two cents: Multiple language plugins might become a nightmare to maintain in the long run. Just make the system in Rust (which is a nice enough language) and be done with it :)

Not necessarily. If the plugins have a well defined interface to the application, then the interface files for various languages are going to be stable. But I am also sure that we need a more "official" way, such as a scripting language.

I am a Lisp person, with a sweet spot for Scheme, but I understand that this can scare people. SublimeText uses python and it is a very powerful language for prototyping software quickly. So RustPython seems a good option, if the WASM compiled software can also be run embedded in an application with Wasmtime: on fact, one can always use the interpreter, maybe even access a REPL, and once ready, compile. If Extism can help here, making packaging easier, then it would be welcome.

Another advantage is that python plugins/extensions for SublimeText could become somewhat portable. In fact, I reckon that to eschew from using node.js or Deno may be wise, otherwise there would be no incentive to use anything but Atom/VSCode extensions, with the performance and threading problems they carry with them. Also, this would make Zed heavier than VSCode, which would contradict one of the motivations of the Zed projects in the first place...

**Comment by maxbrunsfeld** [comment]
Zed now has a plugin interface. So far, we've focused on languages, themes, and language server adapters. But the path is paved for building other kinds of plugin APIs.

I'm going to close this out, and I encourage folks to open further issues for specific plugin capabilities that are important.

**Comment by maxbrunsfeld** [comment]
Our docs for creating extensions are currently here: https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md.

**Comment by pnodet** [comment]
@maxbrunsfeld For anyone wondering the link above was removed since the comment. You can find it here:

[https://github.com/zed-industries/extensions/blob/0359b...85915/AUTHORING_EXTENSIONS.md](https://github.com/zed-industries/extensions/blob/0359b8e8e1e203ccdc884f901b58c2263dd85915/AUTHORING_EXTENSIONS.md)

There is also a more up-to-date version on the website: https://zed.dev/docs/extensions/developing-extensions
