### ISSUE TITLE
Show Function Signature/Variable Type in Completion Menu

### ISSUE THREAD

**Issue by dnjp** [zed-industries/zed#5287]
**Describe the solution you'd like**
In many LSP-enabled text editors, the function signature or variable type is shown in the completion menu. Consider how this is done in VS Code:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/37786372/179284346-f8f96f0b-fb8a-4e92-ae32-afac1c91d653.png">

This makes it clear what a particular completion option is/does.

**Comment by leviptz** [comment]
For me the problem is quite similar

_I'm in a NextJS project_

In Zed, when the auto completion screen opens, there is just the name of the component shown. In my case there is no way to know, what kind of "Link" component it is and where it comes from. When there is a detail screen, there are not many information shown.

I tried to find out if its just a settings issue but i could not find anything.

Zed:
<img width="649" alt="Screenshot 2024-02-22 at 20 20 30" src="https://github.com/zed-industries/zed/assets/102365305/684ae206-c622-4f32-8f91-0b9cebb6923e">
<img width="1143" alt="Screenshot 2024-02-22 at 20 57 02" src="https://github.com/zed-industries/zed/assets/102365305/66d0b357-a581-40f0-877f-22a3bd037c0d">

It would be nice to have a detail screen like the following:

other editor (neovim):
<img width="1265" alt="Screenshot 2024-02-22 at 20 20 52" src="https://github.com/zed-industries/zed/assets/102365305/a9deec68-044b-4b10-b1aa-66346800d30f">

**Comment by babyccino** [comment]
For future reference: I looked into this a bit and this is more of a bug with typescript-language-server than it is with Zed. For whatever reason the completions given by the TS LSP are really bad and different from the information it gives to the hover request. For example, it returns types and interfaces as `type: class`, constants as `type: variable` and the only detail it returns is the import file. You can even see above that it lists Link as a variable even though in the hover pane it is a const
