### ISSUE TITLE
Clojure/Clojurescript support

### ISSUE THREAD

**Issue by vedang** [zed-industries/zed#5292]
I'd love to have Clojure / Clojurescript language support for Zed. [clojure-lsp](https://clojure-lsp.io/) is a well-supported language server for the Clojure/script ecosystem.

Other resources:
1. a lot of the Clojure tooling is powered by the [Cider](https://cider.mx/) stack
2. [clj-kondo](https://github.com/clj-kondo/clj-kondo) is the goto static linter of the Clojure world (it powers clojure-lsp as well)

**Comment by luontola** [comment]
Cursive's parinfer support has its quirks, but it's still miles better than the VSCode plugins I've tried (I couldn't get any to work properly). [Parinfer](https://shaunlebron.github.io/parinfer/) support is the single critical feature I want from a Clojure/Lisp editor. Even REPL is less important to me.

Other top requirements: Find all usages of an identifier/keyword, regardless of how it's written (e.g. destructuring map keys). Rename refactoring for identifiers/keywords. Evaluate selected code in REPL.

Some nice-to-haves: Other refactorings like extracting and inlining variables/functions, but with good parinfer and "select larger syntax node" it's easy enough to do without advanced refactoring support, since the language is so regular.

**Comment by kees-** [comment]
Wow !! At last!

In addition to cljc, what support does zed offer for autodetecting languages from shebangs?

Babashka (clojure SCI scripting) supports files without extensions that have clojure-related shebangs e.g. `#!/usr/bin/env bb`. Having `bb` would continue to round out clojure support.

**Comment by cap10morgan** [comment]
Not sure if this is the right place to report this, but I was testing the preview release (0.123.1) and it appeared that sometimes (but not always) when I edited a `.cljc` file that I had manually told Zed was a Clojure file, on save it would revert my changes. Is that a format-on-save bug?

**Comment by cap10morgan** [comment]
> Wow !! At last!
> 
> In addition to cljc, what support does zed offer for autodetecting languages from shebangs?
> 
> Babashka (clojure SCI scripting) supports files without extensions that have clojure-related shebangs e.g. `#!/usr/bin/env bb`. Having `bb` would continue to round out clojure support.

Yes to all of the above. And that also reminds me that `.bb` and `.edn` should be added to the Clojure file extension list. Thanks!!!

**Comment by JosephTLyons** [comment]
Support for this has landed in today's [v0.123.1-pre](https://zed.dev/releases/preview/0.123.1) release.

Since initial Clojure support has landed, let's close this issue out and open new issues for whatever comes up.
