### ISSUE TITLE
Options for bulk closing tabs

### ISSUE THREAD

**Issue by 4141done** [zed-industries/zed#5317]
**Is your feature request related to a problem? Please describe.**
I generally open files with command + p then wind up with a lot of files open I want to get rid of.  Currently I need to close all those files manually (with my workflow, this is often tens of tabs)

**Describe the solution you'd like**
I primarily use sublime text so I make a lot of use of the "close other tabs" or "close tabs to right" context menus.  I've also found "close all unmodified" to be really useful.  I don't have an opinion on particularly how this works and there may be a better zed specific solution.

**Describe alternatives you've considered**
My current workaround is to mash `command + w` which works ok.

**Screenshots**
This is what sublime text does which works well for me.
![Screen Shot 2022-07-06 at 2 08 01 PM](https://user-images.githubusercontent.com/785331/177643461-696674e8-b13d-4e39-9e33-99b15aef8264.png)

**Comment by Moshyfawn** [comment]
Most of the requested functionality has already been added to Zed, with the exception of directional closing of clean tabs and tabs with deleted files, which is impossible in the current version of Zed because the tab with the deleted file is removed.

I'm going to close this broader issue as most of the requirements have been met and the issue was created a year ago. I encourage users who want to see the directional option to close clean tabs to create a separate issue.
 
<img width="1398" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/22d648fb-b258-4363-8947-3ce11d7b5b00">
