### ISSUE TITLE
Do NOT change formatting in case of existing inconsistently formatted files

### ISSUE THREAD

**Issue by exalted** [zed-industries/zed#5323]
**Premise:** I think this request goes hand-to-hand with issues https://github.com/zed-industries/feedback/issues/70, https://github.com/zed-industries/feedback/issues/91, https://github.com/zed-industries/feedback/issues/96, and alike, in terms of "configuring Zed so that whether it applies some type of code formatting for all/some projects/files"…

**The actual request:** Unless Zed was "instructed" explicitly (e.g. via currently available `~/.zed/settings.json` file, or project-level settings files —if they'll become _a thing_ in the future) to apply some type of code formatting (e.g., adding a newline at the of a file, setting line tab-indentation —tabs VS spaces & 2 VS 4 VS 8 spaces, etc.), instead of applying a default formatting thorough an entire file (and yes, this has to be a file-level operation rather than a project-level operation), it should instead do:

1. Detect whether a given file has already consistent formatting (e.g., tabs VS spaces, number of spaces to indent, etc.)

2. If existing formatting appears to be consistent, then Zed should assume that is the formatting to use for further formatting.

3. If existing formatting appears to be inconsistent (e.g., some lines have tabs, others spaces; some lines have 2 spaces to indent, others 4, etc.) then Zed SHOULD NOT attempt to reformat the file with regards to X, and instead should show an info/warning message to the user, letting them know that there are inconsistencies, therefore Zed won't apply formatting X.

4. The message could also include buttons to "ignore" or "apply the formatting" if the user chooses so.

P.S.: VSCode does this type of "best guessing what formatting to use" (I know for a fact that at least for tab styling, it does) however if the file is poorly and inconsistently formatted, to begin with, you end up with whitespace changes you didn't intend to make, and you constantly keep fighting with VSCode's own auto-detect system, by [specifying the language](https://github.com/zed-industries/feedback/issues/207), space settings, etc., manually. 😢 

Here's a wireframe of how I could see this implemented:

![New Wireframe 1](https://user-images.githubusercontent.com/314398/176872488-358d9bf9-7891-4a59-ab37-ce74457f78f9.png)

**Comment by notpeter** [comment]
This issue is older, but I'm going to close this in favor of:
- https://github.com/zed-industries/zed/issues/4681

I understand that is only part of what you were asking for, but there is an inherent tension in between defining default settings which are opinionated (delete trailing whitespace, add final newline, auto_format file types that have a good formatter, etc) and building an editor which is operates in a "first do no harm" mode. 

Given that in the 28 months ago Zed added support for disabling `format_on_save` and now supports project local settings, I hope it should be possible configure Zed so that in meets your needs.

Thanks for reporting.
