### ISSUE TITLE
`cmd+click` symbol definition to find all references

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5351]
Being able to `cmd+click` on the usage of some symbol and jump to its definition [has been implemented](https://github.com/zed-industries/zed/pull/1237), but I would also like to be able to `cmd+click` on a definition to launch the Find All References action.

**Comment by OgulcanCelik** [comment]
I tried Zed today for the first time and this is something that become muscle memory for me using VSCode, would be super helpful to have it on Zed for the intuitive migration process.

**Comment by xixixao** [comment]
Love the speed of Zed, but this is a must-have feature. Including showing the references in a popover instead of in a new tab.

Similarly I need project search in a sidebar (haven't figured out if that's already possible).

These are features I use every few seconds in VS Code. Will give Zed another try when these are implemented.
