### ISSUE TITLE
Project-specific settings for including / excluding directories and files

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5443]
Depending the project, there is quite a bit of noise in some of my file searches.  I would like to be able to exclude some directories (virtual environment directories, npm module directories, etc.) from being searched through when using `command+p` to find a file, to remove as much noise as possible.  I'm guessing this implies some sort of project settings?  I think it could just be as simple as a hidden json file, that gets committed with your project, that excludes items via patterns:

A small example might be:

```json
{
    "excluded_patterns": [
        "<some-path-prefix-starting-from-project-root>/some_specific_file.py"
        "<some-path-prefix-starting-from-project-root>/some_specific_director/*",
        "*.scss"
    ],
}
```

Some open-ended questions about this:

1. When a directory is added to an exclusion list in a project setting file, what all is affected?
    - Does it affect what shows up in the file browser on the left?
    - Does it affect searches?
    - Does it affect searching for files?
    - etc.
 
    Or are all of those separate project settings?

**Comment by David-Portillo** [comment]
is https://zed.dev/docs/getting-started documentation updated? I tried finding combination of "file_scan_exclusions" and I wasn't able to

**Comment by SomeoneToIgnore** [comment]
I think there's none, so please submit a PR with tue adjustments 🙂

**Comment by nikuz** [comment]
Thank you for adding this feature. It truly helps.

But I discovered an issue which is kind of a deal breaker in cases when you have projects with different directory structure and naming convention. 

Defining the `file_scan_exclusions` in Folder-specific settings doesn't have any effect. So, I can't specify project specific directories to be excluded, otherwise they appear to be hidden in any other project I open in Zed editor.

**Comment by SomeoneToIgnore** [comment]
Great catch (albeit seems hard to implement?).
If you could add an issue with some basic example, it would be really great — otherwise we risk having it forgotten in this closed issue.

**Comment by SomeoneToIgnore** [comment]
Indeed we can, but the main part of my message is to get an example of such project-specific files/directories that are ok to have in one project and not ok in another.

As mentioned, it's somewhat tricky to implement potentially, and thinking of it more without your part of the context makes me wonder: why would anybody exclude `.DS_Store`-like garbage (or project-specific build files, etc.) from one project and keep in another? 
Some real-life example would help me to understand it better — maybe there are other ways, or, at least, this way I'm able to test it without setting some synthetic set-up.

**Comment by nikuz** [comment]
@SomeoneToIgnore sure, the reason I discovered this issue is that I tried to search something in my codebase and I was getting unwanted results from my `docs` directory. I have some mock files in there with real data my app receives from the API. So I wanted to exclude that folder from search only (I actually would prefer to have that folder still visible in the file explorer but it's a topic for another discussion).

So the way to do the exclusion I discovered is described in this issue - define a `file_scan_exclusions` setting option. It works, now I don't get the results from `docs` directory. But when I open another project (which also is having a `docs` directory in it) I would prefer to have that directory visible perhaps. 

So, possibly I misuse this setting and there is another way to exclude files and directories from search? If yes, then it's totally fine to have the `file_scan_exclusions` universal for all the projects and have there only garbage and build output files.

**Comment by SomeoneToIgnore** [comment]
You're certainly misusing it! So glad that we've discussed it further before doing anything 🙂 

There's a "Toggle filters" button in the project search:
![image](https://github.com/zed-industries/zed/assets/2690773/211f391c-f9f0-43ba-a327-3e295adbf9c6)
that contains the `Exclude:` field which should do what you've described.

In addition to that, project panel allows to narrow the search with a particular directory:
![image](https://github.com/zed-industries/zed/assets/2690773/8bb53249-4aec-4a2c-8a09-ec92c64039d3)

While those things may also have bugs, I do not think that a static `file_scan_exclusions` is a good choice for your use case.

**Comment by nikuz** [comment]
Search inside is also good. But I would still prefer to exclude some directories from scanning and search as Jetbrains IDEs do. You simply right click on a folder and mark it as excluded for this project.
<img width="585" alt="Screenshot 2024-02-26 at 3 36 49 PM" src="https://github.com/zed-industries/zed/assets/1743481/e8356782-aee2-4885-96ea-b46743389d08">

**Comment by SomeoneToIgnore** [comment]
Yes, persistence for them is lacking for now, alas, we should improve it.

**Comment by markbrown4** [comment]
Sorry if this has been answered already, how can I surface .gitignore'd files in "Search project files..."?

**Comment by SomeoneToIgnore** [comment]
There's a button under the search filters (note the filter button toggled on the screenshot, opening the inputs below it) to include them into the search results: 

![image](https://github.com/zed-industries/zed/assets/2690773/0c99453d-85d9-4c12-ba9f-a58baaa1fa3a)

**Comment by markbrown4** [comment]
Thanks, I'm referring to "Search project files..." to find a file by filename rather than contents.

**Comment by SomeoneToIgnore** [comment]
Oh, I see now: there's no such thing yet and here's an issue for it: https://github.com/zed-industries/zed/issues/4745

**Comment by dlight** [comment]
> As mentioned, it's somewhat tricky to implement potentially, and thinking of it more without your part of the context makes me wonder: why would anybody exclude `.DS_Store`-like garbage (or project-specific build files, etc.) from one project and keep in another?

Every language and stack may have their own directories to skip and it isn't really possible to list them all in your own config. By including this in the repository, every contributor using Zed benefits, without having to edit themselves an ever growing, half-complete local list (Likewise one could add a VSCode config - which supports project-specific settings - etc)

But the problem here is that [this other issue](https://github.com/zed-industries/zed/issues/6035) from 2003 was closed because it was deemed a duplicate of this one. But if this one is just about including and excluding files *without* it being project-specific, then the other issue should be reopened.

**Comment by karteekiitg** [comment]
> > Some real-life example would help me to understand it better — maybe there are other ways, or, at least, this way I'm able to test it without setting some synthetic set-up.
> 
> [@SomeoneToIgnore](https://github.com/SomeoneToIgnore) One good use case would be to commit the config to git, to step up a consistent ide env for new collaborators, when using gitpod or otherwise. Are there any alternatives to do this well?

Never mind. I found a [feature request](https://github.com/zed-industries/zed/issues/11473) tracking this use case.

**Comment by aaronmarkey** [comment]
Is this available yet? Zed is quite literally unusable for JS and TS development due to this issue.

**Comment by markbrown4** [comment]
> Is this available yet? Zed is quite literally unusable for JS and TS development due to this issue.

Not sure _which_ feature you're requesting.  But I've just discovered that there is config for allowing gitignored files to be included in "Search project files..." now. e.g.
```
"file_scan_inclusions": ["src/__generated__/*"],
```
