### ISSUE TITLE
Allow for tab/tabs to be pulled out to a new window

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#6078]
### Check for existing issues

- [X] Completed

### Describe the feature

When working in multiple tabs, it would be useful to be able to pull the tab outside of the working window to detach from current work window to a separate new window.

**Comment by dumski** [comment]
Hi, I tried to use this feature with no luck - maybe I'm doing something wrong. Can someone explain how to achieve this? I have a project opened in one window. I'm creating a second window and try to drag a tab from the first one to the second one but my dragged tab just vanishes when crossing a border of first window... Am I doing sth wrong or we have a regression here?

Cheers

**Comment by dlight** [comment]
> Hey [@krstp](https://github.com/krstp), would you mind upvoting this issue?
> 
>     * [Allow tabs to be moved between Zed instances #5229](https://github.com/zed-industries/zed/issues/5229)
> 
> 
> Thanks

I think this another feature. I want to move a terminal or a file to another window, but still be associated with the current Zed instance

@JosephTLyons this was closed as *completed*, but I can't drag a window or a terminal tab outside like I can do with a Firefox tab or Konsole tab (among other apps). Does this feature works differently than just moving the tab outside the window?

(I am on Linux, Zed 0.184.8)

I am asking also because I can't find the PR where this was implemented either.
