### ISSUE TITLE
vim: support true Vim-like search-mode

### ISSUE THREAD

**Issue by tmaxmax** [zed-industries/zed#6157]
### Check for existing issues

- [X] Completed

### Describe the feature

The search command `/` doesn't work as in Vim – it opens Zed's find/replace functionality instead. I don't have necessarily an issue with this (using the same UI would be nice), but I would like to preserve initial behavior: use `n` and `N` to cycle through the search result; and keep the editor in Normal mode – right now it seems to switch to Edit mode (worse, without any clear indication, such as a cursor change).

**Comment by rrcobb** [comment]
Found this old issue and it seems related to something I'm seeing now.

In vim, after searching, I can hit 'Enter' and be back in normal mode, with `n` and `N` for cycling through matches. In Zed, almost every time I search, I end up with `keywordnnn` in the searchbox, because the keystrokes have to be `/keyword<ESC>n` instead of `/keyword<Enter>n`

Now that I write this, I see that there is a setting for how Enter behaves in the BufferSearchBar context, and switching from 
```
      "enter": "buffer_search::SelectNextMatch",
```
to 
```
      "enter": "buffer_search::Dismiss",
```

makes my issue go away.

Leaving the comment in case it helps someone else, I don't think any fix is needed!

**Comment by ConradIrwin** [comment]
@rrcobb Glad you found a fix for this!

That said, I believe that if you have vim_mode enabled, the default keymap should work with the same keystrokes as vim.

By default in vim mode, enter in the buffer search bar is overridden to `vim::SearchSubmit`, which emulates vim's "jump to the next match but stay in normal mode on enter".

Are you seeing something different?
