### ISSUE TITLE
Double-tap Keybinds

### ISSUE THREAD

**Issue by Sensanaty** [zed-industries/zed#6460]
### Check for existing issues

- [X] Completed

### Describe the feature

In the Jetbrains editors, one of the default keybinds is a double-tap of the Shift key to open their global searchbar. The main use of this is for fuzzy finding files, though it also acts similarly to the command palette common to VSC, Sublime & indeed in Zed. This is so far ingrained in my muscle memory that I find it nearly impossible to use other editors until I set this up for file searches, however I've found that I'm not able to do this in `keymap.json` (or maybe I'm just doing it wrong :D)

My `keymap.json`:

```json
[
  {
    "context": "Workspace",
    "bindings": {
      "shift shift": "file_finder::Toggle"
    }
  }
]
```

I've also tried `shift+shift`, `shift-shift`, to no avail. Is this something that is supported in Zed yet? 

In Sublime the option looks like this:

```json
{ 
  "keys": ["shift", "shift"],
  "command": "show_overlay", 
  "args": { 
    "overlay": "goto",
    "text": "@"
  } 
}
```

And in VSCode it looks like this:

```json
{
  "key": "shift shift",
  "command": "workbench.action.quickOpen"
}
```

**Comment by JosephTLyons** [comment]
Thanks for the report @Sensanaty - yep, at the moment, we don't have a way to register something like this, but we should def support it going forward, as I know it will be needed to really make JetBrains users comforable.

**Comment by Acetyld** [comment]
Nice to see this is being worked on!

**Comment by joloppo** [comment]
Double-tap ALT -> hold -> up/down for multicursor is something similar, also quite useful.

**Comment by b-hayes** [comment]
Reopen this issue. I just installed zed and I am using the Jetbrains keymap offered by the IDE.
Double tap of shift is still mapped wrong and this isntantly make me close zed and go back to my regular ide because I cant even open a file quickly.
If you offer jetbrains mapping get it right.

**Comment by notpeter** [comment]
@b-hayes I hear you.

- [ ] Double-tap shift should not be mapped by default. It currently is mapped to `command_palette::Toggle` which only searches the jetbrains equivalent of actions. But if you opened it looking for filenames, file contents, settings, symbols, types, menus like you can in JetBrains we've put you in the wrong place.  We shouldn't bind this by-default until we have something that resembles Search Everywhere in Jetbrains.
- [ ] `zed: open keymap` provides no template JSON, just an empty file. This is bad experience.
- [ ] Opening default keybinds opens [default-linux.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-linux.json) or [default-macos.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/default-macos.json) but does include the JetBrains overlay provided by [assets/keymaps/linux/jetbrains.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/linux/jetbrains.json) or [assets/keymaps/macos/jetbrains.json](https://github.com/zed-industries/zed/blob/main/assets/keymaps/macos/jetbrains.json).

I've recently been spending much of my time improving our keymaps (including creating the initial version of our JetBrains for Linux keymap) but there's definitely more room to improve.

This particular issue was closed because we now **can** support modifier only shortcuts like "shift shift" (previously there was a bug that prevented this mapping from working) not because we considered `shift shift` feature complete.

Thanks for commenting @b-hayes, I very much appreciate the honest feedback.

**Comment by notpeter** [comment]
See also:

- https://github.com/zed-industries/zed/pull/14252
- https://github.com/zed-industries/zed/issues/14249
- https://github.com/zed-industries/zed/issues/14248
- https://github.com/zed-industries/zed/issues/14251

**Comment by arthaud-proust** [comment]
For people searching a solution, it's working to add this shortcut on zed 0.203.5, as @Sensanaty suggested :
```json
[
  {
    "context": "Workspace",
    "bindings": {
      "shift shift": "file_finder::Toggle"
    }
  }
]
```

(Go to "Zed" > "Settings" > "Open Key Bindings" > Click on "{}" to open the json file)

**Comment by b-hayes** [comment]
So 2 years later thought Id try Zed again and this issue STILL exists wow! Surely its not that hard to match the intellij keyboard shortcuts like you intended!
