### ISSUE TITLE
Makefile support

### ISSUE THREAD

**Issue by coolcoder613eb** [zed-industries/zed#6463]
### Check for existing issues

- [X] Completed

### Language

Makefile

### Tree Sitter parser link

https://github.com/alemuller/tree-sitter-make

**Comment by JosephTLyons** [comment]
Hey @coolcoder613eb ,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5366

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
