### ISSUE TITLE
Zed.dmg still shows the old EULA

### ISSUE THREAD

**Issue by ismail** [zed-industries/zed#6686]
<img width="653" alt="Screenshot 2024-01-25 at 08 03 41" src="https://github.com/zed-industries/zed/assets/4255/9ba1634e-eb8a-447f-a558-583bc26249e6">

Since the client is now GPL-3.0, it should show that if wanted.

**Comment by b-** [comment]
I'd feel much more comfortable not seeing a big scary proprietary EULA open after downloading an open source program…

**Comment by maxbrunsfeld** [comment]
The open-source license does not supplant the EULA. Whereas the open-source license governs how you can modify and distribute the *source code*, a EULA is an agreement between Zed and its *end users*. Most of the EULA has nothing to do with the source code.
 
The section in your screenshot (that forbids decompiling / reverse engineering) doesn't forbid you from viewing the publicly available, GLP-licensed source code. That clause is just there (and I think is still valid) because there may be some secrets embedded in the application bundles that we distribute.

Sorry that the EULA is scary looking; I get that it's unappealing to be presented with this kind of legal agreement. From my understanding, the EULA is a safety precaution that we need to take as a company to protect against various legal edge cases. If there are particular clauses in there that seem incorrect or unfair to you, feel free to open further issues.

For now, I'm going to close this out, because the open source license doesn't render the EULA out-of-date.
