### ISSUE TITLE
Flatpak package for Linux

### ISSUE THREAD

**Issue by Eonfge** [zed-industries/zed#6687]
Following the issue to support Linux (https://github.com/zed-industries/zed/issues/5395), I would ask you to investigate Flatpak.

## What is Flatpak

Flatpak is a modern method of packaging Linux applications. It has a lot in common with IOS, Android and Windows UWP. It's a sandboxed, auto-updating, atomic format that supports all Linux distributions and that integrates with modern concepts like xdg-portals, wayland and pipewire.

The benefits to users are obvious: They have a robust package that integrated with modern desktop Linux, while also offering advanced sandboxing features. Even the installation is easier, since Flatpaks integrate with GNOME Software and KDE Discover, and updates are done in-place, while only downloading the files that have actually changed.

For developers though, the benefits are also great. First off, you get to provide a single package to all different versions of Linux. No longer worry about .rpm and .deb, or a single tar. Additionally, since auto-updating is easily implemented with services like Flathub, you don't have to worry about clients running older versions. Finally... no dependency hell. You can use a single base image, and then add all dependencies yourself.

## What is  Flathub
Flathub is the de-facto central repository for Flatpaks, that means that every application on it will be directly available to Linux Mint, Fedora or Arch Linux. It provides many of the more advanced features, like atomic updates, at no expense to users or developers.

It also has a series of nice examples. like [Lapce](https://flathub.org/apps/dev.lapce.lapce) or [Verloren](https://flathub.org/apps/net.veloren.veloren) who's manifests ([Lapce](https://github.com/flathub/dev.lapce.lapce), [Verloren](https://github.com/flathub/net.veloren.veloren/tree/master)) show you how easy it is to distribute a Rust-based application on Linux nowadays. Flathub is optional, and you can even host your own back-end if you really want, but it's a nice one-stop shop for new applications.

## Competitors
But why not use a competitor like App Image or Snap? As a Flathub maintainer I'm obviously biased, but there are some common criticisms. 

For App Image, the complete lack of automated updates or sandboxing make it a poor choice for the 21st century. It also relies on deprecated technology like `fuse2` which is no longer available on all systems. It also doesn't integrate well with modern desktops.

For Snap, the problems are more organizational: It's Ubuntu-only and although it could work on other distributions, the adoption outside of Ubuntu is next to nothing. Finally, it's not open source. If Canonical decided to take 30% of your revenue in the future, you have nowhere to go.

## Getting started
The best way to start, is to check out the repository of a similar project and to compile it all locally. Lapce would be a good example, and now that you're an Open Source project, there is no shame in looking how they do things.

- [Flatpak documentation](https://docs.flatpak.org/en/latest/)
- [Flathub documentation](https://docs.flathub.org/docs/category/for-app-authors)

**Comment by DarkArc** [comment]
> It also has a series of nice examples.

Beyond this point, it's worth noting flatpak is very much not a toy and is an officially supported distribution format for big names such as [Discord](https://flathub.org/apps/com.discordapp.Discord), [Telegram](https://flathub.org/apps/org.telegram.desktop), [OBS Studio](https://flathub.org/apps/com.obsproject.Studio), [LibreOffice](https://flathub.org/apps/org.libreoffice.LibreOffice), [Firefox](https://flathub.org/apps/org.mozilla.firefox), and [Thunderbird](https://flathub.org/apps/org.mozilla.Thunderbird).

**Comment by someone13574** [comment]
I’d be interested in adding some preliminary flatpak build support, but the only problem is that it doesn’t directly support cargo, so we would probably need to add meson as a build system. It also makes it a bit messy because flathub doesn’t support internet connections during builds, so the flatpak manifest would need a list of sources to fetch before hand. Neither are huge problems, but it does make it a bit less clean.

**Comment by razzeee** [comment]
@someone13574 I guess you are aware, that you can use https://github.com/flatpak/flatpak-builder-tools/tree/master/cargo to generate the source list

**Comment by RustoMCSpit** [comment]
now that the alpha is out, can this be put on flathub?

**Comment by someone13574** [comment]
> now that the alpha is out, can this be put on flathub?

No, there is currently no support for doing flatpak builds and furthermore lots of things which need to interact with the host system wouldn’t work. There are also plenty more reasons stated in the PR above. At the moment I’ve stopped working on it but I have gotten a change upstreamed in alacritty which should fix some of the problems if I try again in the future.

**Comment by ConradIrwin** [comment]
Fixed by #12006

**Comment by PgBiel** [comment]
Regarding the discussion we previously had on sandboxing in the Flatpak PR's thread, I was recently having some thoughts based on what we spoke and wanted to share.

Basically, if I understood correctly, what we're doing right now is
1. The Zed CLI launches Zed outside of the sandbox so it has access to the host paths as they are;
2. When doing so, it defines environment variables (such as `LD_LIBRARY_PATH` or similar) to ensure it uses the libraries made available by the chosen Flatpak runtime in the sandbox.

In theory, this would be avoided to ensure users can still use Flatseal to configure Zed's environment (and also for Flathub approval), as well as to ensure full cross-compatibility of the Flatpak package, but we weren't finding a way to easily expose the host's binaries for use within Zed.

In that context, I commented that I actually can, quite easily, expose my host's binaries to Zed, but that's because, in my distro (NixOS), they are all in the `nix/` directory, which I can expose to the sandbox through Flatseal directly and point the `$PATH` to the appropriate location. However, it seemed to be impossible to expose `bin/` from typical Linux distros, since the sandbox overrides `bin/`.

I'm just seeing now, however, that it _is_ actually possible to do that, through the `host-os` permission: https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

It allows mounting `bin/`, `lib/` and so on under `/run/host`.
This means that one possibility is to invert our procedure here:

1. The Zed CLI launches Zed inside the sandbox;
2. While doing so, it adds to `/run/host/bin` to the `PATH`, and perhaps `/run/host/lib` (etc) to `LD_LIBRARY_PATH` as well, to ensure extensions and the terminal can access those binaries.

This could be a perhaps more appropriate workaround while a more full-fledged solution isn't available, and probably wouldn't affect user experience negatively in any significant way (or, at least, potentially less than the current solution).

Thoughts on this? cc @someone13574

**Comment by brunoais** [comment]
@PgBiel In the case of allowing the execution of the host's shell for testing purposes or anything of that sort, use `host-spawn`.
See: https://github.com/flathub/com.vscodium.codium/blob/master/com.vscodium.codium.yaml#L109-L137

That's what you need to make it available.

If I misunderstand and the purpose is something else, please explain it better.

**Comment by PgBiel** [comment]
@brunoais Yeah, ideally you'd just give users the option to run things with `flatpak-spawn`, as was attempted here: https://github.com/zed-industries/zed/pull/11949

But it ended up not being a viable approach at the time due to the amount of changes.

I still think this change (customizable command invocations) will end up being needed anyway for direnv support and stuff (not just for Flatpak), but this isn't the case yet. So we settled on a much simpler solution for now (spawn Zed on the host).

My proposed alternative solution of just changing Zed's PATH would be just as simple (only the Zed CLI would have to be changed), but wouldn't require fully bypassing the sandbox, thus paving a way for Zed to be pushed to Flathub. Hope that clarifies my idea.

**Comment by imbev** [comment]
I suggest the following:

- Running Zed within the sandbox
- A Flatpak-specific first start doc showing the steps for installing a Flatpak SDK (with examples for Python, JS, Rust, etc)
- Access to `flatpak spawn --host`

This would make the Zed Flatpak a decent development experience without depending on host package managers (dnf, apt, Homebrew), while allowing users to access such tools with minimal difficulty.
