### ISSUE TITLE
Decrease the space between the line numbers and code

### ISSUE THREAD

**Issue by fatih** [zed-industries/zed#6749]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi, I've added a picture. The space between the line numbers and the code is a lot. Is there a way I can make it smaller or remove it? I checked the settings, but I couldn't find anything yet. I love to use every single amount of space, and coming from Vim/NeoVim this is one of the UI changes that feels weird for me.

![ScreenShot-2024-01-26-10 08 25@2x](https://github.com/zed-industries/zed/assets/438920/877a011e-d85d-45f9-a9d4-b71b558dae40)

Thank you!

**Comment by mrnugget** [comment]
@fatih! Nice to see you here! To clarify: do you want to remove the fold-gutter completely or just remove its paddings/margings?

Because that's what's taking up most of the space: 
![screenshot-2024-01-26-09 43 44@2x](https://github.com/zed-industries/zed/assets/1185253/b431a83d-da1a-4cfd-886e-f44451e65653)

(Based on assumption that in your screenshot we're looking at parts of a `import ()` statement in Go with the imported packages being indented.)

**Comment by fatih** [comment]
Hi @mrnugget 👋🏼 

Yeah I see now what you mean. TIL about the fold-gutter. I never use folds (even in Vim), so I wonder if I can disable them completely. So basically I want to remove this padding completely:

![ScreenShot-2024-01-26-13 48 37@2x](https://github.com/zed-industries/zed/assets/438920/d098a4c0-604f-49ad-a2ee-09c519e44999)

I searched in https://docs.zed.dev/configuration/configuring-zed for the keyword "fold" but couldn't find any references yet.

**Comment by fatih** [comment]
This is now fixed and properly implemented with https://github.com/zed-industries/zed/pull/7665. Closing this.
