### ISSUE TITLE
Version Control System on Zed Editor

### ISSUE THREAD

**Issue by vanloc1808** [zed-industries/zed#6785]
### Check for existing issues

- [X] Completed

### Describe the feature

Hi team,
As I observed, now we can only see which files the changes appear in, not what the change is (like the below figure)
![image](https://github.com/zed-industries/zed/assets/76842571/0953cd8c-8239-4a26-9ea9-a8cbe3c38421)
Could you please tell me, if there are any available features that allow developers to view what have we changed on the files visually? Examples are in the below image (the feature in Visual Studio Code).
![image](https://github.com/zed-industries/zed/assets/76842571/d0ce994f-6996-443f-be9c-aaac688055fd)
Thank you

**Comment by basitcodeenv** [comment]
+1

**Comment by JosephTLyons** [comment]
Hey @vanloc1808, we don't have a diff view yet, but its on our [roadmap](https://zed.dev/roadmap). Here's the issue we are tracking for it:

- [<issue_url>](https://github.com/zed-industries/zed/issues/4523)

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

Also the

**Comment by bohdanbirdie** [comment]
@JosephTLyons hi! It's great to know that this feature is on the roadmap
Yet, was the roadmap page removed or moved somewhere? Current link is 404

**Comment by JosephTLyons** [comment]
> [@JosephTLyons](https://github.com/JosephTLyons) hi! It's great to know that this feature is on the roadmap Yet, was the roadmap page removed or moved somewhere? Current link is 404

Yes, we removed it for now, as our roadmap was revamped for 2025. We should probably put something up somewhere...

**Comment by shagunsharma12** [comment]
Eagerly waiting for this feature so that I can switch to Zed permanently.
