### ISSUE TITLE
Vim Mode - Fold/Unfold using `za`

### ISSUE THREAD

**Issue by titouandk** [zed-industries/zed#6822]
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode has a nice Vim command `za` to fold / unfold code under cursor.

(This is not a native Vim behavior - Vim is natively more restrictive as you must have an existing fold for this to work.)

https://github.com/zed-industries/zed/assets/5413308/ed95f73c-7f77-4589-a79d-56bab93e716d

This works for all languages, as in markdown:

https://github.com/zed-industries/zed/assets/5413308/1e56ab80-f43b-4703-9e8d-3cf0a59170cc

**Comment by rauann** [comment]
you can do it with keymaps:
```
  {
    "context": "Editor && VimControl && !VimWaiting && !menu",
    "bindings": {
      // put key-bindings here if you want them to work in normal & visual mode
      "g f": "editor::Fold",
      "g u": "editor::UnfoldLines"
    }
  },
```

**Comment by titouandk** [comment]
I might be wrong, but it seems to me that this solution has 2 problems:

- `gu` and `gf` are already existing vim command
- You have 2 different commands for fold/unfold, instead of only one that acts as a toggle

**Comment by soham-suki** [comment]
Bump! Would love this feature.

**Comment by MrDwarf7** [comment]
Also bump - Feels quite strange not being able to easily fold and unfold things.
Are we able to hook the editor's folding controls (To enable the LSP to do a majority of the lifting work and defer to the indenting set there?)

**Comment by ConradIrwin** [comment]
I've added support in #18421. It doesn't support the markdown example, but that's because Zed doesn't have suggested folds for markdown (yet...). I think that should be a separate issue though.

A related downside is that if you create a custom fold with `zf` and then open it with `za` you cannot close it again with `za` (you have to recreate it with zf). We need to update Zed to track manually created folds too.

We also now have (most) of the manual fold shortcuts from vim: za, zA, zc, zC, zo, zO, zR, zM.

We still dont' have an enable/disable (zn/zN) to allow turning off and restoring state; nor do we have a concept of fold level (but see also #5142 for a non-vim request for that).

Beyond that who knows - maybe fold motions `zj/zk/[z/]z`?
