### ISSUE TITLE
Offer arm64/x64 binaries individually

### ISSUE THREAD

**Issue by probablykasper** [zed-industries/zed#6837]
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to install the x86_64 version only, instead of the universal binary. This should take the app from 350MB to 187MB or less

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1010" alt="image" src="https://github.com/zed-industries/zed/assets/11315492/4d3d1cbb-4caa-4171-9a2e-dd8f78794413">

**Comment by osiewicz** [comment]
+1 to that, though one difficulty lies in the fact that we do not provide the CPU architecture in the asset download query (see [this query line](https://github.com/zed-industries/zed/blob/main/crates/auto_update/src/auto_update.rs#L252)).
That is relevant for older Zed installations - how can a universal binary (UB) version upgrade to non-universal binary (NUB) version? We'd have to handle that transition gracefully, which means having a transition period of sorts:
1. We could roll out the URL change first (so that the zed.dev backend knew the architecture of the client requesting the update) and only roll out the bundling change once a vast majority of our users uses the version that provides the architecture in the update request. That I think would take few weeks.
2. We could start shipping the NUBs straight away, keeping the old asset in place for update requests that do not provide a CPU architecture. That allows us to switch to NUB with overhead in release process for a few weeks.

**Comment by osiewicz** [comment]
The query params are now in main/nightly, so we just have to let that sit a bit so that most users are on a build that provides architecture in a query. I'll revisit this issue in a few weeks probably.

**Comment by osiewicz** [comment]
That's it folks, latest stable is using single architecture binaries (and today's Preview is 20Mb smaller than that, likely due to us shifting some languages into extensions).
We do plan to phase out universal binaries at some point (likely within a month or two), but for now they're still built in CI just in case we get an old client that tries to update.

Feel free to reopen this ticket if you run into any issues.
