### ISSUE TITLE
[COMPLAINT] You disrespect the (potential) user-base

### ISSUE THREAD

**Issue by abebeos** [zed-industries/zed#6871]
>> @ maxdeviant , please do not close issues that fast.

>> This is more about the liberal qualities of the zed-project

>>unmanipulated open voting and (open-ended) discussion process

> We won’t
> We’re aware

Whos is "we"?

This issue affects product/project lead.

You disrespect the (potential) user-base

_Originally posted by @abebeos in https://github.com/zed-industries/zed/issues/6849#issuecomment-1913175737_

Unblock the voting, or alternatively, remove the blocked issues from the list.

You really need to fix this.

**Comment by telectr** [comment]
They are not currently focusing on cross-platform support, and as they are a small team, do not have the resources to do so. By closing the issue quickly, they are not being disrespectful.

**Comment by abebeos** [comment]
Common, at least try to understand what this is about:

> This is more about the liberal qualities of the zed-project

* invitation to vote on issues
* Some listed issues are blocked (one cannot vote)

=> disrespect

**Comment by maxdeviant** [comment]
> Whos is "we"?
> 
> This issue affects product/project lead.

As a member of Zed staff, I am able to speak on behalf of the project and convey our plans around certain areas of development.

> Unblock the voting, or alternatively, remove the blocked issues from the list.

We originally locked the platform support issues because they were targets for lots of noise in the comments that didn't do anything in terms of advancing the discussion or bringing us any closer to supporting a particular platform. It is unfortunate that locking the issue thread also prevents voting on it, but this is a limitation of GitHub.

I suspect unlocking the issues would allow them to fall back into the same state that caused them to be locked in the first place.

As previously mentioned, we are in the process of figuring out what is necessary to bring Zed to Linux, with other platforms to follow.

I don't think any of the actions I have taken thus far have been disrespectful; closing an issue is certainly not a sign of disrespect. You, of course, are entitled to your own interpretation.

That being said, I am going to close this issue as I don't think there is anything more to be gained by leaving it open.

**Comment by abebeos** [comment]
> > Whos is "we"?
> > This issue affects product/project lead.
> 
> As a member of Zed staff, I am able to speak on behalf of the project and convey our plans around certain areas of development.

But you're not the product/project lead.

> > Unblock the voting, or alternatively, remove the blocked issues from the list.
> 
> We originally locked the platform support
[...] explanations

It is trivial to understand what you did wrong.

As it is trivial to solve the dilemma.

Sadly, if you refuse to listen.

Where/how can i reach the leadership to file a complaint?

**Comment by abebeos** [comment]
- Followup https://github.com/zed-industries/zed/discussions/6873

**Comment by maxdeviant** [comment]
> Where/how can i reach the leadership to file a complaint?

You can email hi@zed.dev if you wish to file a complaint.

**Comment by abebeos** [comment]
Note to readers:

I moved the discussion over to:

* Followup [[COMPLAINT] You disrespect the (potential) user-base #6873](https://github.com/zed-industries/zed/discussions/6873)

Result:

> you are more than welcome to coordinate a conversation about building a windows port with the team through proper channels.

notice "proper channels".

then

> Any further issues or discussions will be locked or closed.

I rest my case.

**Comment by antaz** [comment]
@abebeos Why does any of this matter to you if you don't mind me asking?
The project is completely open source and open to contribution now, if you have any contributions to the platform support i'm pretty sure they would be gladly accepted by the team. Merely voting for Windows over Linux or vice versa is not going to accelerate the process in any way.

**Comment by abebeos** [comment]
You're late, game over here.

**Comment by antaz** [comment]
Well, I'm sorry you had to learn things and come to the conclusion the hard way then.

**Comment by mikayla-maki** [comment]
Alright everyone, it's time to calm things down. @antaz this is a professional space, no need to bring that energy here, we can deal with people.

@abebeos given your behavior over the three separate issues, consider [this](https://github.com/zed-industries/zed/discussions/6873#discussioncomment-8265921) an official warning as per our [code of conduct](https://zed.dev/docs/code-of-conduct). Knock it off, or we'll ban you.
