### ISSUE TITLE
xml

### ISSUE THREAD

**Issue by Tsolmonx** [zed-industries/zed#6963]
### Check for existing issues

- [X] Completed

### Language

xml

### Tree Sitter parser link

https 

### Language server link

https://github.com/eclipse/lemminx

### Misc notes

Need xml lsp, syntax highlight etc

**Comment by JosephTLyons** [comment]
Hey @Tsolmonx,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4869

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
