### ISSUE TITLE
Vim motion `e`/`E` is blocked by hint text 

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/zed#7046]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/40336192/e0a21918-8596-4175-9eda-15ea923edd8f

If you disable the inlay hints:

https://github.com/zed-industries/zed/assets/40336192/f3446ebb-6555-446c-b0cf-265f3bea4e06

### Environment

Zed: v0.120.4 (Zed Preview)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
Thanks for reporting this!

This is due to some of the helpers that vim motions currently use hitting the wrong layer of abstraction (the DisplayMap instead of the Buffer) when moving around. Fixing this will also help with a number of other edge cases around folding and soft-wraps too. I think we can fix this by moving the implementation of `chars_at` and `reverse_chars_at` on DisplayMap and providing a compatible API that reads from the Buffer directly.

If you (or anyone'd) like to pair on a fix, feel free to book time: https://calendly.com/conradirwin/pairing.

**Comment by Vagab** [comment]
@ConradIrwin I think this is currently [fixed](https://github.com/zed-industries/zed/pull/10103) in main, is it not?

**Comment by ConradIrwin** [comment]
Sadly not. I'm not sure why though, as I thought that would have fixed it.

Will happily pair if you want to!

**Comment by Vagab** [comment]
> Will happily pair if you want to!

let's do this!
