### ISSUE TITLE
Add reuse window flag in Zed CLI

### ISSUE THREAD

**Issue by samueldurantes** [zed-industries/zed#7047]
### Check for existing issues

- [X] Completed

### Describe the feature

Add a flag in Zed's CLI that allows opening to another directory in the same window already opened.

### If applicable, add mockups / screenshots to help present your vision of the feature

VSCode example:

<img width="1782" alt="image" src="https://github.com/zed-industries/zed/assets/44513615/f6dd0345-c537-49c7-a51e-ab035eaf635c">

**Comment by d1y** [comment]
Yes yes, I need this too

**Comment by JosephTLyons** [comment]
Hey @samueldurantes,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4861

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Comment by 2zqa** [comment]
I don't think this is a duplicate. This issue occurs when you have an existing Zed window open to the project(/directory/folder) A, but you want to switch to project B. The ticket you are referencing is about opening a file, while keeping the current project open.

They also [mention](https://github.com/zed-industries/zed/pull/9202#issuecomment-2238523322) this in the comments of the MR solving the issue mentioned above
