### ISSUE TITLE
Why are there nodejs files in zed

### ISSUE THREAD

**Issue by ethan-phu** [zed-industries/zed#7054]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I used clean my mac to check the space occupied by zed. I found that there is a node folder in the zed folder in the support file, which takes up about 200 megabytes. I want to know what is the main function of this? Can it be removed later?
![image](https://github.com/zed-industries/zed/assets/12579229/4c9bb721-f7e1-46d8-bd22-4a0b1ba9674c)
![image](https://github.com/zed-industries/zed/assets/12579229/896e5cdc-6668-47d4-b0d4-ef1bbb4c6bbd)

### Environment

![image](https://github.com/zed-industries/zed/assets/12579229/fa988893-24e3-4e7f-8195-d91899fdb389)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Zed installs various tools based on nodejs, e.g. formatters (prettier) and language servers (copilot, typescript, javascript, json, ...).
Zed only downloads things that are being used (e.g. a file is being opened that required a TS langserver) or enabled by default (e.g. formatter has `auto` setting that includes formatting with prettier), and the node itself (also on the first access, not unconditionally).

You can remove those directories, but Zed will either break (if it's running at that moment) and/or redownload them next time the related feature is used.

We do not have plans to abandon this approach since there's so much code written to support various frontend tools already, that rewriting those in Rust will take an eternity, so not sure what is actionable here, hence closing.

**Comment by karenetheridge** [comment]
This doesn't look good. https://old.reddit.com/r/programming/comments/1dxmroj/zed_editor_automatically_downloads_binaries_and/
