### ISSUE TITLE
Nim Support

### ISSUE THREAD

**Issue by AritraBanik08** [zed-industries/zed#7065]
### Check for existing issues

- [X] Completed

### Language

Nim

### Tree Sitter parser link

https://github.com/alaviss/tree-sitter-nim

### Language server link

https://github.com/nim-lang/langserver

### Misc notes

Providing support for [Nim](nim-lang.org) would be great as I do most of my backend in Nim.

**Comment by JosephTLyons** [comment]
Hey @AritraBanik08,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5095

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
