### ISSUE TITLE
Support for ESLint's new configuration format (FlatConfig)

### ISSUE THREAD

**Issue by Nyaacinth** [zed-industries/zed#7271]
### Check for existing issues

- [X] Completed

### Describe the feature

Related discussion: https://github.com/zed-industries/zed/discussions/7204

FlatConfig: https://eslint.org/docs/latest/use/configure/configuration-files-new

ESLint announced this new configuration format about half or 1 years ago, and now it's feature completed and able to use, there has been a lot of plugins supporting it. It contains several improvements like the ability to use ESM instead of CJS for config itself and the ability to use different configs for different files through file and ignore patterns.

After several tries to solve this, I found *this* is related to the problem:
https://github.com/zed-industries/zed/blob/8bafc61ef57f8f1807ced6f8b69891c4ee701a7d/crates/zed/src/languages/typescript.rs#L217-L232

Maybe we need to build a settings entry that will add `"experimental": { "useFlatConfig": true }` to workspace settings (above) passed to `vscode-eslint/.../eslintServer.js`

But, since this will be my very first time to write and debug rust program if I try to solve this by myself, I filed this issue instead to look around for some potential help.

❤️

**Comment by koddsson** [comment]
We landed support in #8109 _but_ the vscode-eslint extension needs to be updated to a version 2.3.0 or later for it to take effect. [Unfortunately it seems like there won't be any more versions released on the GitHub releases page](https://github.com/microsoft/vscode-eslint/pull/1770#issuecomment-1963707143) so we'd need to revise the code a bit in a effort to access some ESLint language server.

I cloned the `vscode-eslint` repo, compiled the code and changed the reference in zed to that JS file and got the flat config working.

![image](https://github.com/zed-industries/zed/assets/318208/34dba082-1fde-4d71-ab79-80669a45b000)

So it kind of depends on what we'd like to do to get newer versions of `vscode-eslint`. We could clone and build the project in zed, or prebuild it and ship it with zed. Also possible for someone (I could do it) to set up a different npm package that just exposes the build `vscode-eslint` language server and we could install that.

I'm happy to work making a PR to zed with these changes but I'm unsure what approach we'd like to take.

cc/ @SomeoneToIgnore since we talked about ESLint LSP stuff in #8109.

**Comment by Nyaacinth** [comment]
> We landed support in #8109 _but_ the vscode-eslint extension needs to be updated to a version 2.3.0 or later for it to take effect. [Unfortunately it seems like there won't be any more versions released on the GitHub releases page](https://github.com/microsoft/vscode-eslint/pull/1770#issuecomment-1963707143) so we'd need to revise the code a bit in a effort to access some ESLint language server.
> 
> I cloned the `vscode-eslint` repo, compiled the code and changed the reference in zed to that JS file and got the flat config working.
> 
> ![image](https://private-user-images.githubusercontent.com/318208/309055262-34dba082-1fde-4d71-ab79-80669a45b000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzg1NzEsIm5iZiI6MTcwOTI3ODI3MSwicGF0aCI6Ii8zMTgyMDgvMzA5MDU1MjYyLTM0ZGJhMDgyLTFmZGUtNGQ3MS1hYjc5LTgwNjY5YTQ1YjAwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwNzMxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzIwNGE2NTU2Y2RlNDliNWVkMTVlMDMzMDUzMjk4MmQ0Yzk2Y2RiNGI0ZjA3ZTlkNDNmZTg0YzFjM2JkNzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SvnOCOKW3ErATojmwMKL5MLyWGT2mYJ7UnCHLF6Sfks)
> 
> So it kind of depends on what we'd like to do to get newer versions of `vscode-eslint`. We could clone and build the project in zed, or prebuild it and ship it with zed. Also possible for someone (I could do it) to set up a different npm package that just exposes the build `vscode-eslint` language server and we could install that.
> 
> I'm happy to work making a PR to zed with these changes but I'm unsure what approach we'd like to take.
> 
> cc/ @SomeoneToIgnore since we talked about ESLint LSP stuff in #8109.

Thanks a lot for your efforts! It’s really sad to see that it cannot take effect because of the releases lacking.

But maybe we can do something around OpenVSX, which allows us to download vscode-eslint releases without violating licenses.

*Something like the fake code below:
```js
fetch("https://open-vsx.org/api/dbaeumer/vscode-eslint")
    .then((res) => res.json())
    .then((data) => somehowDownload(data.downloads.universal))
```
And use the `extension` folder in it as language server.

This way I think could be more graceful than forking repo or building unofficial builds.

**Comment by SomeoneToIgnore** [comment]
Fantastic follow-up @koddsson , thank you for sharing.
I believe we should stay on a safer side and avoid releasing anything ourselves or forking, if possible — it's extra maintenance cost and somebody's time spent on that in the end.

Nice open-vsx idea @Nyaacinth  too: using *.vsx might be the simplest to do among all proposed, maintenance-wise: it's the similar concept as GitHub releases we're downloading right now, from a different HTTP source (need more Rust code) and with a different package structure (needs a few path strings changed for eslint adapter).
```
~/Downloads ❯ unzip -l dbaeumer.vscode-eslint-2.4.4.vsix
Archive:  dbaeumer.vscode-eslint-2.4.4.vsix
  Length      Date    Time    Name
---------  ---------- -----   ----
     2692  01-23-2024 03:24   extension.vsixmanifest
      513  01-23-2024 03:24   [Content_Types].xml
       79  01-23-2024 03:24   extension/.CodeQL.yml
    17914  01-23-2024 03:24   extension/CHANGELOG.md
   389316  01-23-2024 03:24   extension/client/out/extension.js
    31940  01-23-2024 03:24   extension/eslint_icon.png
    42497  01-23-2024 03:24   extension/images/2_1_10/eslint-dialog.png
     1044  01-23-2024 03:24   extension/images/2_1_10/eslint-status.png
     1119  01-23-2024 03:24   extension/License.txt
      196  01-23-2024 03:24   extension/package-json-schema.json
    17656  01-23-2024 03:24   extension/package.json
    25211  01-23-2024 03:24   extension/README.md
     2779  01-23-2024 03:24   extension/SECURITY.md
   233204  01-23-2024 03:24   extension/server/out/eslintServer.js
---------                     -------
   766160                     14 files
```

So if we could adjust https://github.com/zed-industries/zed/blob/48aba8eb4c147d8644a1fe3c13c39adaffc32773/crates/util/src/github.rs#L28 to deal with OpenVSX API, then download, unpack and provide as an asset a given version, it would work similar to what we have now with release tags.

I've checked out https://open-vsx.org/api/dbaeumer/vscode-eslint and got interested on where do they take their versions from — and looks like https://github.com/microsoft/vscode-eslint/tags contains most of that and even the prerelease tags.
For prereleases, OpenVSX's `latest` version seems to match the semantics somehow: it uses something after the last release, judging by the date, but no corresponding tag seems to be in vscode-eslint repo?

It's a bit sad that we have to introduce another source for this package, but using vscode-esling GitHub directly is worse, since release tags provide archives with sources, not the compiled version.
Fetching entire repo, building it (with installing its dev dependencies, potentially) and using build results as an archive seems doable, but much harder to maintain and debug.

I wonder what are the OpenVSX API usage terms? We might need to do extra announcements (http headers? other places?) at least.

**Comment by Nyaacinth** [comment]
> Fantastic follow-up @koddsson , thank you for sharing. I believe we should stay on a safer side and avoid releasing anything ourselves or forking, if possible — it's extra maintenance cost and somebody's time spent on that in the end.
> 
> Nice open-vsx idea @Nyaacinth too: using *.vsx might be the simplest to do among all proposed, maintenance-wise: it's the similar concept as GitHub releases we're downloading right now, from a different HTTP source (need more Rust code) and with a different package structure (needs a few path strings changed for eslint adapter).
> 
> ```
> ~/Downloads ❯ unzip -l dbaeumer.vscode-eslint-2.4.4.vsix
> Archive:  dbaeumer.vscode-eslint-2.4.4.vsix
>   Length      Date    Time    Name
> ---------  ---------- -----   ----
>      2692  01-23-2024 03:24   extension.vsixmanifest
>       513  01-23-2024 03:24   [Content_Types].xml
>        79  01-23-2024 03:24   extension/.CodeQL.yml
>     17914  01-23-2024 03:24   extension/CHANGELOG.md
>    389316  01-23-2024 03:24   extension/client/out/extension.js
>     31940  01-23-2024 03:24   extension/eslint_icon.png
>     42497  01-23-2024 03:24   extension/images/2_1_10/eslint-dialog.png
>      1044  01-23-2024 03:24   extension/images/2_1_10/eslint-status.png
>      1119  01-23-2024 03:24   extension/License.txt
>       196  01-23-2024 03:24   extension/package-json-schema.json
>     17656  01-23-2024 03:24   extension/package.json
>     25211  01-23-2024 03:24   extension/README.md
>      2779  01-23-2024 03:24   extension/SECURITY.md
>    233204  01-23-2024 03:24   extension/server/out/eslintServer.js
> ---------                     -------
>    766160                     14 files
> ```
> 
> So if we could add another function around
> 
> https://github.com/zed-industries/zed/blob/48aba8eb4c147d8644a1fe3c13c39adaffc32773/crates/util/src/github.rs#L28
> 
> to deal with OpenVSX API, then download, unpack and provide as an asset a given version, it would work similar to what we have now with release tags.
> I've checked out https://open-vsx.org/api/dbaeumer/vscode-eslint and got interested on where do they take their versions from — and looks like https://github.com/microsoft/vscode-eslint/tags contains most of that and even the prerelease tags. For prereleases, OpenVSX's `latest` version seems to match the semantics somehow: it uses something after the last release, judging by the date, but no corresponding tag seems to be in vscode-eslint repo?
> 
> It's a bit sad that we have to introduce another source for this package, but using vscode-esling GitHub directly is worse, since release tags provide archives with sources, not the compiled version. Fetching entire repo, building it (with installing its dev dependencies, potentially) and using build results as an archive seems doable, but much harder to maintain and debug.
> 
> I wonder what are the OpenVSX API usage terms? We might need to do extra announcements (http headers? other places?) at least.

We can see Terms of Use on https://open-vsx.org/terms-of-use , the about page on https://open-vsx.org/about and the the FAQ in https://www.eclipse.org/legal/open-vsx-registry-faq , the page of ESLint extension is on https://open-vsx.org/extension/dbaeumer/vscode-eslint

OpenVSX seems had been created as somehow the opposite of VSCode Marketplace by Eclipse Foundation, as it is open sourced and allows not only VSCode itself but also most of compatible clients to use.

For the announcements, I haven’t see any immediate requirement to do things other than providing proper UA, but it might be wrong since I’m not a lawyer at all. 😐

**Comment by SomeoneToIgnore** [comment]
Also seems more work needed in terms of supporting flat config files: https://github.com/zed-industries/zed/pull/8109#issuecomment-1980403545

but that can wait for the actual eslint package fetch rework.

**Comment by koddsson** [comment]
I spent more time than I'm willing to admit on trying to download the OpenVSX package and unzipping it. I have everything down that I need to do but am hitting some of the edges of my Rust knowledge 😅 

The only snag I'm running into really is juggling the unzipping of the file downloaded via streams(?) and futures(?) and putting the correct data into the right interfaces 😄 

I think I wanted to use the [`async_compression::futures::bufread::ZlibDecoder`](https://docs.rs/async-compression/0.4.6/async_compression/futures/bufread/struct.ZlibDecoder.html) to deflate the ZIP stream like how we do for GZIP when the asset come from GitHub Releases. I just didn't find a equivalent way of then consuming the whole reader into a file. I assume that `async_tar` does that somehow under the hood but I'm not sure how I'd do that for this.

If there are any ideas I could rig up another PR with the fixes for https://github.com/zed-industries/zed/pull/8109#issuecomment-1980403545 as well.

**Comment by koddsson** [comment]
> If so, the question is: do we handle 2.3x correctly or did they change the API?

I can give that a try later tonight but I _think_ that they don't distribute the built extension any more in those releases but just the source code.

> If you'd like to pair with me on this, feel free to book some time here: https://calendly.com/thorsten-ball-zed/60min Happy to!


I'd love to, let me find some good time :)

**Comment by koddsson** [comment]
> > I can give that a try later tonight but I _think_ that they don't distribute the built extension any more in those releases but just the source code.
> 
> Ah, that might be it. In that case: if it's not that hard to build, we could fork the repo and cut our own releases.

For sure, I suggested that in https://github.com/zed-industries/zed/issues/7271#issuecomment-1971854615 but wasn't sure what approach the zed org wants to do since y'all are gonna have to continue maintaining it. But yeah, probably not complicated to rig up something with GitHub Actions to make it work automagically.

**Comment by koddsson** [comment]
> Fetching entire repo, building it (with installing its dev dependencies, potentially) and using build results as an archive seems doable, but much harder to maintain and debug.

As me and @mrnugget discovered today, zed was already doing this but just from the GitHub release assets! The fix was then simply to use the GitHub repo archive API to download the repository and build that 😄

**Comment by savoygrizzly** [comment]
Eslint is broken again with flat configs, used to work fine for me and it stopped.

I just love Zed but this kind of bugs just makes me angry and on the fence of switching back to viscose.

**Comment by mrnugget** [comment]
@savoygrizzly sorry to hear! Would love to help but I can't without any more information.

eslint works for me, in Zed stable, in a project with JavaScript.

![screenshot-2024-04-29-18 37 16@2x](https://github.com/zed-industries/zed/assets/1185253/ca719915-7604-4cd3-a41a-e5b84e2adeb5)

**Comment by savoygrizzly** [comment]
Well, thanks @mrnugget  for the quick reply. I was so bummed I tweaked around for a good time.
Somehow Zed sometimes showed Downloading eslint in the bottom left and that's it. Stayed stuck there.
Somehow creating a local setting like so got it to work.
```json
"language_overrides": {
    "JavaScript": {
      "code_actions_on_format": {
        "source.fixAll.eslint": true
      }
    }
  }
```


I just tried removing it after updating to the release made a few hours ago (0.132.4) and it now works without. 
I'll have to try the new config format to see if it breaks it somehow, just before I couldnt get it to work, maybe it is fixed now.

**Comment by SomeoneToIgnore** [comment]
Hey @koddsson , just wanted to appreciate your activity on the topic more, as Microsoft had removed all binaries from their releases, including the one we've relied on: https://github.com/zed-industries/zed/issues/21220

Thanks to the fork made by you with @mrnugget and the repository with the eslint example, I've managed to re-release the version with the binaries and have something fixed for now: https://github.com/zed-industries/vscode-eslint/releases/tag/2.4.4

Also, that VSIX idea is now looking more and more compelling.

Anyway, hope you all having a good week.
