### ISSUE TITLE
assertion failed: !self.nodes.is_empty()

### ISSUE THREAD

**Issue by l1Dan** [zed-industries/zed#7350]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Run this example panic.
https://github.com/zed-industries/zed/blob/main/crates/gpui/examples/image.rs

### Environment

Zed: v0.120.6 (Zed)
OS: macOS 14.3.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

thread 'main' panicked at /Users/lidan/.cargo/git/checkouts/zed-23861290b5d2093f/ac74a72/crates/gpui/src/key_dispatch.rs:444:9:
assertion failed: !self.nodes.is_empty()
stack backtrace:

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Which example is that?
If you can share the project, it would be very useful.

**Comment by l1Dan** [comment]
https://github.com/zed-industries/zed/blob/main/crates/gpui/examples/image.rs

**Comment by SomeoneToIgnore** [comment]
<img width="1053" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/39746664-dad1-497b-a5e6-31c06468984e">


Seems to work for me, so it looks like some mismatch in the way the project is configured and we need to find what exactly, which might be hard.

1. What does a full backtrace look like in ~/Library/Logs/Zed/Zed.log ?
2. The path `.cargo/git/checkouts/zed-23861290b5d2093f/ac74a72` looks rather odd, was it `git clone`'d or retrieved somehow otherwise? Does it build?
3. Do other projects with a similar "checkout" method work normally? What changes if Zed is checked out as `git clone --recursive git@github.com:zed-industries/zed.git` into some "regular" directory like `/Users/lidan/test` ?

**Comment by l1Dan** [comment]
[hello.zip](https://github.com/zed-industries/zed/files/14159732/hello.zip)

https://github.com/zed-industries/zed/assets/7961100/1b61643b-265e-4fb4-8280-1c1735c8ec85
