### ISSUE TITLE
Material color theme

### ISSUE THREAD

**Issue by kobzar** [zed-industries/zed#7370]
### Check for existing issues

- [X] Completed

### Describe the feature

Please add Material color theme

**Comment by kevinrambaud** [comment]
Hi @kobzar, while waiting for this theme to eventually be available, if you haven't seen this yet, there is a work-in-progress theme importer you can use to import a VS Code theme to Zed. You can find a blog post about it at https://zed.dev/blog/user-themes-now-in-preview.

**Comment by JosephTLyons** [comment]
I'm not sure we will be pulling any more default themes into Zed at the moment, since we have support for user-defined themes and we will be moving to theme plugins once the plugin system is in place. I'd like to keep the issue open, with a `potential_plugin` label, so that plugin devs can find this.

**Comment by kobzar** [comment]
Thanks. This is a strange position. 
The first step for any editor its look on color themes support. 
No one will work on worse color theme. 
For example you can change theme in vim/nvim by add a few strings.
