### ISSUE TITLE
Feature Request: Folder copy

### ISSUE THREAD

**Issue by oo00spy00oo** [zed-industries/zed#7490]
### Check for existing issues

- [ ] Completed

### Describe the feature

As a developer, I want to copy/duplicate one or many folder(s) in my workspace.

**Comment by JosephTLyons** [comment]
Hey @oo00spy00oo,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4983

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
