### ISSUE TITLE
Support an equivalent Terminal-Based Interface (TUI) 

### ISSUE THREAD

**Issue by berkeleynerd** [zed-industries/zed#7493]
### Check for existing issues

- [X] Completed

### Describe the feature

# Feature Request: Terminal-Based Interface

## Summary

I propose the addition of a terminal-based interface enabling users to launch and use the editor directly from the terminal. This feature would allow for seamless integration into a terminal-centric workflow, providing the convenience of a GUI editor and TUI editor for those preferring mixed-mode workflows.

## Motivation

Many developers prefer using terminal-based tools due to their speed, low resource usage, and flexibility. Adding a terminal-based interface would cater to this audience, broadening the editor's appeal and usability. It would also enhance the tool's versatility, making it a more powerful option for remote development scenarios, where GUI access might be limited or non-existent.

## Desired Features

- **Terminal Launch Capability**: Allow zed to be started directly from the terminal with a specific command (e.g., `zed --terminal`).
- **Full Feature Accessibility**: Ideally, all features available in the GUI version are accessible in the terminal version.
- **Keyboard Navigation and Shortcuts**: Implement intuitive keyboard navigation and shortcuts, enabling efficient operation without the need for a mouse. First-class mouse support in the terminal is also desirable. 
- **Customizable Appearance**: Provide options to customize the appearance of the terminal interface including truecolor themes if the terminal supports them.

## Potential Challenges

- **UI/UX Adaptation**: Adapting the GUI elements and interactions to a terminal interface in a user-friendly manner may require significant design and development effort.
- **Performance Optimization**: Ensuring the terminal version runs smoothly and remains responsive and competitive with existing terminal editors, even on lower-specification systems or in resource-constrained environments.
- **Cross-Platform Support**: Maintaining consistent functionality and appearance across different operating systems and terminal emulators.

## Conclusion

By offering a terminal-based interface, Zed could significantly enhance its utility and appeal to a broader range of developers. This feature would not only align with the preferences of terminal-savvy users but also reinforce Zed's position as a versatile and adaptable development tool.

I look forward to hearing your thoughts on this proposal and am happy to contribute to discussions or preliminary testing phases. Thank you for considering this feature request!

**Comment by CommanderStorm** [comment]
I am a bit sceptical on this proposals utility given the insane cost (as I see it this would basically need a new editor, or am I off-base?).

> Many developers prefer using terminal-based tools

So basically, you want something like neovim/emacs/..., correct?
What would be the difference to the existing tooling?

**Comment by thiagomajesk** [comment]
I want to echo this comment: https://github.com/zed-industries/zed/issues/5347#issuecomment-1908653617... I love the idea of a "headless mode" where you can simply attach a GUI or TUI. It seems to me that this is one of the biggest selling points of [N]Vim up to this day as you can run it everywhere (locally on a server).

**Comment by thiagomajesk** [comment]
Hi @CommanderStorm! The comment I linked is from that issue... I think that if we are talking about supporting different types of UIs, the first step would be implementing a headless mode as the comment suggests. This could potentially make Zed as ubiquitous as Vim since it's not tied to a specific GUI.

**Comment by arunoruto** [comment]
> So basically, you want something like neovim/emacs/..., correct? What would be the difference to the existing tooling?

A year ago, I started using NixOS with all of its features and decided to give neovim a try. I went from a Lua config to using [nixvim](https://github.com/nix-community/nixvim) for my configurations.I am not sure why, but the performance was kinda sluggish, and configuring neovim LSP, lining, and so on is bothersome... Then I came upon [helix](https://helix-editor.com/): while not having a plugin system like (neo)vim, it was blazingly fast (rust did its thing I guess?) and LSPs were first class citizens! It was so easy to configure languages through its config; it was a dream! The only downside to helix, is the different keybinding mentality. While I do like the concept of highlighting something and then applying an action (you can see what will be changed), it always takes a few more keystrokes to execute.

So why the long story now: zed could be a middle ground between neovim and helix. It could provide navigation like nano for new users and use the vim keybindings for more experienced ones. It has a plugin system, which could be configured through a config file instead of using the UI (I think the nix folks will find a way here!). I kind of look at zed like I am looking at wayland; it is new and does things in a modern way; it is not bound by choices made decades ago compared to xorg (vscode, (neo)vim, emacs, ...).

Having zed in a terminal would also enable remote development on servers directly instead of launching a headless instance and keeping a connection alive like that. Lunching a TUI zed in tmux/zellij would keep the program running and we can pick up the work where we left, even working from a different machine (but on the same server).

**Comment by notpeter** [comment]
While a fun thought, we are extremely unlikely to implement in this in the the near-term (1-2years), if ever and so I'm going to close this as not-planned.

Thanks for reporting!
