### ISSUE TITLE
Selected item in file selector jumps around when language server is starting up

### ISSUE THREAD

**Issue by bennetbo** [zed-industries/zed#7519]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I just noticed that sometimes bringing up the file explorer and selecting different items seems to "reset" the selection for me. Hard to describe, you can see it in the video. In the last couple of seconds im repeatedly trying to select the second item (by pressing arrow down multiple times), but after a split second the selection "jumps" back to the first item.

https://github.com/zed-industries/zed/assets/53836821/fe666b64-279f-4724-8ea4-11ea8af8c617

I can reliably reproduce this if the rust language server is starting up while im searching for files.

### Environment

Zed: v0.122.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[zed.log](https://github.com/zed-industries/zed/files/14201387/zed.log)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
Most probably the same as https://github.com/zed-industries/zed/issues/5006

**Comment by alygin** [comment]
> Most probably the same as #5006

I think #5006 is very similar, yet a bit different problem, and it needs a different solution.

This one is caused by an avalanche of unnecessary searchings due to file finder subscription to all of the project updates, including those not changing the project structure.

#5006 is also caused by frequent searchings, but they are all necessary (because files are really appear and disappear in the project). We can't fix #5006 by just tailoring subscriptions.
