### ISSUE TITLE
Cannot unbind commands used in native menus on macOS

### ISSUE THREAD

**Issue by meguriau** [zed-industries/zed#7544]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Can not unbind a command by setting it to `null`.

1. Paste the following setting in keymap.json
```json
[
  {
    "context": "Editor && mode == full",
    "bindings": {
      "ctrl-g": null
    }
  }
]
```

2. Press `ctrl-g`.

### Environment

Zed: v0.122.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="672" alt="image" src="https://github.com/zed-industries/zed/assets/60995977/0c6b1f89-f3b8-4d75-8762-992331527a26">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
Thanks for reporting this!

It looks like this is broken specifically in the case that the action is in the menu; because macOS triggers the key-binding for us.

This should be fixable, and if you'd like to pair on a fix, please book time here: https://calendly.com/conradirwin/pairing

**Comment by liebkne** [comment]
Can I help if I am not experienced in Rust?

**Comment by ConradIrwin** [comment]
Absolutely! I think the problem stems from how our keybindings interact with the macOS key handler; so mostly this is going to be reading documentation and trying to figure out what to do. Happy to pair on it if you want: https://calendly.com/conradirwin/pairing

**Comment by Yevgnen** [comment]
Not sure if it's related. I trying to rebind `cmd-a` in the search bar 

```
{
    "context": "BufferSearchBar",
    "bindings": {
      "cmd-a": "search::SelectAllMatches"
    }
}
```

But with the above config, `cmd-a` still "selects all the text in the input text field" instead of "selecting all the matches".

**Comment by ConradIrwin** [comment]
Yup, it looks like this is also in the "Selection" menu.

**Comment by Yevgnen** [comment]
Is this related? https://github.com/zed-industries/zed/issues/9313

**Comment by notpeter** [comment]
When Zed generates our MacOS native menu items with keyboard shortcuts in default keymap it include those shortcuts so they show up in-menu.  When these key events are triggered they are handled by MacOS and invoke the commands as if the menu item had been selected and Zed never receives the key input.

As a result any keys which are unlucky enough to have dedicated menu items cannot be user-rebound because MacOS handles those keyboard shortcuts directly.  

The current workaround is to go into System Preferences->Keyboard->Keyboard Shortcuts->App Shortcuts->Zed.app and define an alternate dummy key to replace the action as described in this comment:
- https://github.com/zed-industries/zed/issues/16187#issuecomment-2291779015

I think the solution is likely that when the user updates they keymap Zed should update/regenerate it's MacOS menu items accordingly.
