### ISSUE TITLE
editor: sort import on save

### ISSUE THREAD

**Issue by avetisk** [zed-industries/zed#7624]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently sorting import is done manually through action menu.

It would be great to be able to have an option to sort them on save.

**Comment by JosephTLyons** [comment]
Hey @avetisk,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5232

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Comment by avetisk** [comment]
@JosephTLyons done!

Sorry, I only checked for the specific feature in the existing issues. Next time I'll take more time and check thoroughly  👍
