### ISSUE TITLE
Diagnostics remain in an outdated state

### ISSUE THREAD

**Issue by bennetbo** [zed-industries/zed#7685]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As of yesterday my diagnostics panel seems to be stuck on some old state when opening zed inside zed.
I have tried restarting the language server, restarting zed, rebooting my MacBook, but nothing helped.

Stale errors:
![image](https://github.com/zed-industries/zed/assets/53836821/1525affd-ed76-40cb-b794-8a7247c0611d)

These errors are not there when running `cargo check`, and I don't get any new indicators when I introduce new errors in code.
The language server seems to be working normally, because I can see inlay hints and get auto completion.
This seems to only appear on the zed project, other projects still work fine for me.

Not sure if this is related, but my logs are full of 
- `[INFO] completion out of expected range`
- `[WARN] Generic lsp request to rust-analyzer failed: content modified`
- `[ERROR] inlay hint update task for range Anchor { timestamp: Lamport {0: 1}, offset: 10319, bias: Left, buffer_id: Some(BufferId(367)) }..Anchor { timestamp: Lamport {0: 1}, offset: 11202, bias: Right, buffer_id: Some(BufferId(367)) } failed: inlay hint fetch task: inlay hints LSP request: content modified`

### Environment

Zed: v0.122.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[zed.log](https://github.com/zed-industries/zed/files/14236400/zed.log)

**Comment by SomeoneToIgnore** [comment]
Those come from rust-analyzer's analysis, it returns a bunch of false-positives for Zed already:
https://github.com/rust-lang/rust-analyzer/issues/16514
https://github.com/rust-lang/rust-analyzer/issues/16513
this seems to be yet another symptom.

Proving an absence of something is quite hard, so I cannot say that it's not Zed's fault, but I'm almost sure it's the case and the issue has to be created in rust-analyzer's repo instead.

**Comment by bennetbo** [comment]
Thanks for your answer.
When you get these stale errors, are you able to get any other diagnostics?

Because my main problem is that I don't seem to be getting any other diagnostics anymore, regardless of what I change in the code.

**Comment by SomeoneToIgnore** [comment]
For my two cases, the diagnostics are indeed still able to update, but r-a can fail (or even panic) bad enough and not recover.
Given that you have logs full of `content modified` errors, I suspect r-a gets into restart loop of a kind: those errors usually happen when r-a loads the workspace and has new data, so it rejects pending requests and forces them to be re-queried.
Those errors are relatively normal on the initial project loading (hints' request may fail once or twice during that, for instance), but sure are not normal during regular work, esp. in big quantities.

rust-analyzer may output certain errors via stderr, so checking LSP server logs may reveal something, but otherwise I only can suggest cleaning the target directory and restarting the workspace: it seems to help for this particular error (and may hint there's some build configuration mismatch issue that spoils it)

**Comment by bennetbo** [comment]
Thanks for your detailed explanation, I deleted rust analyzer from `/Users/bebo/Library/Application Support/Zed/languages`and my diagnostics are working again (stale errors are still there).
Looks like rust-analyzer was the problem here, closing.
