### ISSUE TITLE
Vim mode: support special keys `ctrl-w` and `ctrl-u` for batch deletion in Insert mode

### ISSUE THREAD

**Issue by noritada** [zed-industries/zed#7691]
### Check for existing issues

- [X] Completed

### Describe the feature

In Insert mode of Vim mode, special keys `ctrl-w` and `ctrl-u` for batch deletion are currently unavailable.
Since they are very useful, it would be nice if it is implemented.

See `:help i_CTRL-W` in Vim:

```
                                                i_CTRL-W
CTRL-W          Delete the word before the cursor (see i_backspacing about
                joining lines).  See the section "word motions",
                word-motions, for the definition of a word.
                                                i_CTRL-U
CTRL-U          Delete all entered characters before the cursor in the current
                line.  If there are no newly entered characters and
                'backspace' is not empty, delete all characters before the
                cursor in the current line.
                If C-indenting is enabled the indent will be adjusted if the
                line becomes blank.
                See i_backspacing about joining lines.

```

**Comment by noritada** [comment]
Now that I have a rough understanding of what is needed for implementation, I am trying to see if I can implement it and submit a PR.

**Comment by Yohannfra** [comment]
You can already have C-w using key bindings (I didn't try for C-U since I don't use it but it's certainly possible with the same kind mapping) :

Add these in your **keymap.json**

```json5
  {
    "context": "Editor && vim_mode == insert",
    "bindings": {
      // Erase previous word with C-w
      "ctrl-w": "editor::DeleteToPreviousWordStart"
    }
  }

```

**Comment by ConradIrwin** [comment]
I would love a PR to add these to the default vim keymap!

**Comment by rk-terence** [comment]
One thing I did notice is that `ctrl u` does not automatically add indenting to a line. In Neovim, `ctrl u` will keep the indenting right, whereas zed will put the cursor to position 0. To achieve the same effect, I use the following keymaps:
```json
[
  {
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "S": [
        "workspace::SendKeystrokes",
        "d d shift-o"
      ],
      "c c": [
        "workspace::SendKeystrokes",
        "d d shift-o"
      ]
    }
  },
  {
    "context": "Editor && vim_mode == insert",
    "bindings": {
      "ctrl-u": [
        "workspace::SendKeystrokes",
        "escape S"
      ]
    }
  }
]
```

**Comment by ConradIrwin** [comment]
@rk-terence I think we could reasonably change the behavior of `editor::DeleteUntilBeginningOfLine` to do what you want (or add a vim-specific version). The first time you hit it it deletes but preserves leading indentation, and the second time, it deletes the remaining space characters.

Happy to work with you on this if you want: https://calendly.com/conradirwin/pairing

**Comment by rk-terence** [comment]
> @rk-terence I think we could reasonably change the behavior of `editor::DeleteUntilBeginningOfLine` to do what you want (or add a vim-specific version). The first time you hit it it deletes but preserves leading indentation, and the second time, it deletes the remaining space characters.
> 
> Happy to work with you on this if you want: https://calendly.com/conradirwin/pairing

It will be very convenient to have this feature enabled! In my experience, the need of emptying a line but at the same time keeping the indenting correct is frequent, so I think it beneficial to add your proposed functionality.

Your proposed functionality still differs from that in Neovim, but in my opinion, the semantics of `ctrl`-`u` in Neovim is a little different from "delete util beginning of line". By hitting `ctrl`-`u` in insert mode, we first delete the newly entered characters in a line (if there are any), and if there are no newly entered characters or we hit `ctrl`-`u` the second time, it will only preserve the indenting; when we hit `ctrl`-`u` the third time, the whole line will become empty. Therefore, I don't think the behavior of `editor::DeleteUntilBeginningOfLine` should totally match the behavior of `ctrl`-`u` in Neovim, since after all, that contradicts the meaning of "delete until beginning of line".

**Comment by ConradIrwin** [comment]
Nice, thanks for calling out that extra detail – vim never ceases to surprise me :D
