### ISSUE TITLE
zed . will open two instance

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#7906]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```sh
export http_proxy=http://127.0.0.1:1090; export https_proxy=http://127.0.0.1:1090
cd ~/Desktop
zed .
```

two instance will open:

<img width="240" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/34a6f3e7-fa43-489b-92fc-0d8147ec334a">

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by kzhui125** [comment]
@tml do you have proxy env enabled?
```
export http_proxy=http://127.0.0.1:1090; export https_proxy=http://127.0.0.1:1090
```

**Comment by tml** [comment]
Yes, I have tried both of the values you showed and neither results in opening multiple copies of zed for me on 0.123.1

**Comment by kzhui125** [comment]
thanks, will try if still reproduce when brew updated…

**Comment by tml** [comment]
Ah - you should have mentioned earlier that you installed with Homebrew!

Turns out that the Homebrew [cask for zed](https://github.com/Homebrew/homebrew-cask/blob/56f27ba2ec957bd01ece91f99671e22d4eff815b/Casks/z/zed.rb) links "#{appdir}/Zed.app/Contents/MacOS/cli" to "zed". When I run `cli .` rather than `zed .`, I can reproduce the two windows behaviour.

**Comment by SomeoneToIgnore** [comment]
Do note that Zed team is not responsible for the homebrew package directly — we did not create it or maintain this part, hence would it be more reasonable to address the issue there?

**Comment by kzhui125** [comment]
what’s the difference of cli and zed?
Where are there two binary?
Does cli behave incorrectly?

Thanks,

**Comment by tml** [comment]
@SomeoneToIgnore you may have a more clear understanding of this than I do, because I have not looked at the code for `cli` yet, but I don't think `cli` should be opening two windows here. That is to say, I can reproduce this issue using the `cli` tool directly out of the Zed appdir.

I think it's arguable whether the brew cask should be linking `cli` to `zed`, and would agree that question is more properly debated within the homebrew project; but without looking at the code for `cli` itself it's not facially clear that opening two windows is the correct behaviour here.

**Comment by tml** [comment]
This might be related to #7998

**Comment by mrnugget** [comment]
> but without looking at the code for `cli` itself it's not facially clear that opening two windows is the correct behaviour here.

I think it's a matter of defaults. VS Code's `code` for example reuses the last active window. But it has command-line flags to change that behavior (`--new-window`)

**Comment by tml** [comment]
No, I cannot reproduce this with the `cli` binary anymore.

**Comment by mrnugget** [comment]
Closing then! Thanks!
