### ISSUE TITLE
Capture groups in regex search like \1

### ISSUE THREAD

**Issue by abliger** [zed-industries/zed#7999]
### Check for existing issues

- [X] Completed

### Describe the feature

![image](https://github.com/zed-industries/zed/assets/53035692/d7e88320-58d9-48da-bd57-93cc62e71a93)

**Comment by jansol** [comment]
The usual name for this in a regex context is "capture groups", might want to update the title to contain that

**Comment by zacharysyoung** [comment]
@abliger, I don't see you stating what you expect to happen.

I gather you want the entire "kfk" string to be highlighted because `\1` means `k` in that context.

Please update the issue and explicitly state what you expect to happen. Thanks!

**Comment by grrowl** [comment]
If using capture groups in a regex search/replace

![image](https://github.com/user-attachments/assets/1886761f-0a59-4ffc-b0ab-378ba88f7824)

we'd expect placeholders to be replaced with the capture group value

![image](https://github.com/user-attachments/assets/0630b72f-5c61-46ec-9f5c-77a5eebccbc0)

**Comment by jansol** [comment]
Reopening since in OP the capture groups were used in the search field, not the replace field. This does not seem to work:

Capturing a group is fine
![image](https://github.com/user-attachments/assets/904c3347-9a2f-4058-910a-6db0c1dac493)

But using it in the same search regex does not trigger a match:
![image](https://github.com/user-attachments/assets/aba5f5c4-84ca-4da3-930b-dd68e70c8d92)

While it should match the captured letter as if it was written out in the original search expression:
![image](https://github.com/user-attachments/assets/47186bf8-bc62-481c-8d62-c77c144b6959)

**Comment by jansol** [comment]
Apparently I was a bit off in my initial investigation as well, while capture groups are needed for this, the name of the feature being asked for turns out to be [backreferences](https://www.regular-expressions.info/backref.html).

Here, a better illustration. This should match both instances of "Duck" and the space between them, but not the 2nd space nor "Goose":
![image](https://github.com/user-attachments/assets/a4b18c17-61cd-4abb-9bb0-0d86c39c7951)
regex101.com with the PCRE2 engine handles this:
![image](https://github.com/user-attachments/assets/557d7b78-ad92-465b-83f7-b6305eaa08b1)

I assume Zed uses the [`regex` crate](https://docs.rs/regex/latest/regex/) to implement regex search, which does explicitly not support backreferences:
>  it lacks several features that are not known how to implement efficiently. This includes, but is not limited to, look-around and backreferences.

@notpeter Feel free to re-close as out of scope if there is no plan to support this in Zed.

**Comment by notpeter** [comment]
Thank you @jansol.  Yes, we currently use the [regex](https://docs.rs/regex/latest/regex/) crate which explicitly does not support back references.
<img width="691" alt="Screenshot 2024-10-29 at 14 53 35" src="https://github.com/user-attachments/assets/27cf52d1-de94-42a7-afe3-2a426f162384">

We would need to switch to [fancy_regex](https://docs.rs/fancy-regex/latest/fancy_regex/) crate to support this.

**Comment by jansol** [comment]
> Although this is older, because there are more watchers, I'm going to close in favor of: #7999

That's this issue...

**Comment by notpeter** [comment]
> That's this issue...

Sigh.

- https://github.com/zed-industries/zed/issues/13486
