### ISSUE TITLE
Shortcut for accepting completions partially (word by word)

### ISSUE THREAD

**Issue by cdc-lst** [zed-industries/zed#8020]
### Check for existing issues

- [X] Completed

### Describe the feature

In addition to the "Accept completion" shortcut, it would be helpful to have a shortcut to accept partial completions, i.e. accept completions word by word.
For example, in VS Code and IntelliJ IDEA, this is done using Cmd+Right Arrow (on Mac).

**Comment by JosephTLyons** [comment]
This is a super cool suggestion! Didn't know this was possible in other editors.

**Comment by sirenkovladd** [comment]
@JosephTLyons, do tags [assistant](https://github.com/zed-industries/zed/labels/assistant), [autocompletions](https://github.com/zed-industries/zed/labels/autocompletions) satisfy this issue, so that people can also find it?

I will also add text to search by keywords

Accept Next Word Of Inline Suggestion
editor.action.inlineSuggest.acceptNextWord
https://code.visualstudio.com/updates/v1_74#_command-to-partially-accept-inline-completions

**Comment by JosephTLyons** [comment]
> @JosephTLyons, do tags [assistant](https://github.com/zed-industries/zed/labels/assistant), [autocompletions](https://github.com/zed-industries/zed/labels/autocompletions) satisfy this issue, so that people can also find it?
> 
> I will also add text to search by keywords
> 
> Accept Next Word Of Inline Suggestion editor.action.inlineSuggest.acceptNextWord https://code.visualstudio.com/updates/v1_74#_command-to-partially-accept-inline-completions

As per your suggestion, I added `autocompletions`, which makes sense. We use the `assistant` tag specifically for Zed's assistant panel, which is different from Copilot.

**Comment by jdk-21** [comment]
I looked into this issue and it seems pretty straightforward to implement because most of the functionality already exists. But I'm struggeling with the keybindings a bit. I replaced the cmd-right shortcut with a new function. That way ctrl-e and end won't trigger the partial completion. But on Linux this shortcut, doesn't seem to exist.
I will open a pr. Then it's easier to discuss changes and ideas.
