### ISSUE TITLE
R support

### ISSUE THREAD

**Issue by aravezskinteeth** [zed-industries/zed#8027]
### Check for existing issues

- [X] Completed

### Language

R

### Tree Sitter parser link

https://github.com/r-lib/tree-sitter-r

### Language server link

https://github.com/REditorSupport/languageserver

**Comment by JosephTLyons** [comment]
Hey @aravezskinteeth ,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4972

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Comment by aravezskinteeth** [comment]
Done!
