### ISSUE TITLE
Haxe support

### ISSUE THREAD

**Issue by lpmathiasendk** [zed-industries/zed#8033]
### Check for existing issues

- [X] Completed

### Language

HAXE

### Tree Sitter parser link

https://github.com/vantreeseba/tree-sitter-haxe

### Language server link

https://github.com/vshaxe/haxe-language-server

### Misc notes

I'd like to have Haxe added to Zed.

**Comment by JosephTLyons** [comment]
Hey @lpmathiasendk,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5271

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
