### ISSUE TITLE
Hide status/symbol outline bar in Terminal

### ISSUE THREAD

**Issue by IroncladDev** [zed-industries/zed#8125]
### Check for existing issues

- [X] Completed

### Describe the feature

When I open a new terminal, the status bar is still present at the top, taking up a bunch of space.

It would be nice if it could be removed in Terminal panes or if there was a setting to hide it for terminal panes.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot 2024-02-21 at 8 07 05 AM](https://github.com/zed-industries/zed/assets/50180265/d2a328c5-c858-4ff4-ba13-d95ead7a6e13)

**Comment by wmstack** [comment]
This feels like it should disappear when you turn off the breadcrumbs but it doesn't.

**Comment by IroncladDev** [comment]
I tried disabling breadcrumbs and the empty space still appears in terminal panes.

**Comment by JosephTLyons** [comment]
It was probably just missed in:

- https://github.com/zed-industries/zed/pull/7338

**Comment by alygin** [comment]
@IroncladDev,
What Zed version do you use?
What happens when you open the search panel in the terminal window with `cmd+f`?

**Comment by IroncladDev** [comment]
I believe I'm on the latest stable version (0.123.6).

![Screenshot 2024-02-27 at 10 05 53 AM](https://github.com/zed-industries/zed/assets/50180265/da74ad4c-f0de-4c68-a47e-74a59f9a9ebb)

When I use cmd+f, it opens the search but inserts it underneath that space.
![Screenshot 2024-02-27 at 10 06 18 AM](https://github.com/zed-industries/zed/assets/50180265/1a72fc1e-f8b9-4131-a0d2-67bfa0f032f2)

**Comment by alygin** [comment]
The `toolbar/breadcrumbs` setting, added in the mentioned PR, doesn't affect "breadcrumbs" in the terminal windows placed in the editor pane, that's true.

@IroncladDev, I think you see an empty toolbar because your `PROMPT_COMMAND` variable/function returns the empty value. You can try switch to bash in a terminal with an empty toolbar, and run something like this:

```bash
PROMPT_COMMAND="echo -ne \"\033]0;Here's my title\007\""
``` 
and you'll see the title in the breadcrumbs panel.

I guess, we have two options here:

1. Make the existing `toolbar/breadcrumbs` setting also affect the terminal title. Good: since only terminals that are placed in the editor area are affected, the editor's setting may fit better here. Bad: for the terminal it's actually not "breadcrumbs", it's the title or prompt; if something terminal-specific will be added to the toolbar later, the settings will become a mess. 

2. Add another setting `terminal/toolbar/title` that would specifically work with the terminal's title. Good: a proper separation of the editor and the terminal settings. Bad: it may be misleading because the terminals in the bottom pane will not be affected by this setting (though it could be mentioned in the docs but it still looks a bit inconsistent).

I prefer the second option ([here's the impelemntation](https://github.com/zed-industries/zed/pull/8559/files)), but I don't mind throwing it away for a better alternative.

@SomeoneToIgnore, @JosephTLyons, what do you think is the right way? Maybe there're other options?

**Comment by SomeoneToIgnore** [comment]
I ended up merging that PR, thank you for the proposals list — I liked it also among the alternatives, and seems that other people agreed too.
