### ISSUE TITLE
Editor becomes unresponsive when using Edit > Find  in large file

### ISSUE THREAD

**Issue by pratikmmohite** [zed-industries/zed#8172]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1) Open the file
[pincode.csv](https://github.com/zed-industries/zed/files/14369701/pincode.csv)
2) Go to Edit > Find (Command + F)
3) Search "Pune"

### Environment

  Model Name:	MacBook Pro
  MacOs :      14.3.1 (23D60)
  Model Identifier:	Mac14,10
  Chip:	Apple M2 Pro
  Total Number of Cores:	12 (8 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	10151.81.1
  OS Loader Version:	10151.81.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1728" alt="image" src="https://github.com/zed-industries/zed/assets/32018912/411be33d-df1a-4b56-b2ef-304a68cd11e0">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/zed/files/14369759/Zed.log)

**Comment by PratikMMohite** [comment]
@jacobdalamb  I am currently using Webstorm and it does not have this issue. 

If search takes times it understandable but application getting frozen.

**Comment by MaXal** [comment]
It looks like the issue is related to `EditorElement::paint_scrollbar` that takes 70% of the main thread during the search.
<img width="1890" alt="image" src="https://github.com/zed-industries/zed/assets/266747/e847453c-9d20-4ade-9ea3-22607ffd946f">
Snapshot: [Run_Zed_2024-03-19-144719.collapsed.zip](https://github.com/zed-industries/zed/files/14652638/Run_Zed_2024-03-19-144719.collapsed.zip)

**Comment by osiewicz** [comment]
Is this still an issue for you?

**Comment by pratikmmohite** [comment]
@osiewicz  No issue is fixed i think. 

Closing this issue
