### ISSUE TITLE
"Speed of thought" comes from Practical Vim by Drew Neil; attribution might be appropriate

### ISSUE THREAD

**Issue by benknoble** [zed-industries/zed#8206]
While not the same tagline ("Code" vs. "Edit text"), to me this is clear descendant of the tagline of [Practical Vim](https://pragprog.com/titles/dnvim2/practical-vim-second-edition/). Even Google knows where it comes from: https://www.google.com/search?q=edit+text+at+the+speed+of+thought.

I would strongly suggest attributing or acknowledging the influence of Drew Neil's book and the Vim editor on Zed and/or its marketing material where appropriate.

**Comment by ConradIrwin** [comment]
Thanks for the suggestion! I wasn't aware of this book, but it seems like I should've been :D. 

The "X at the speed of thought" tagline is in relatively common usage outside of this book (though it may well have been the beginning of the curve, searches result in many people using it in many software-related contexts). It's striking that we both picked similar taglines in the same "genre" of software, it's probably due to being immersed in the same culture rather than a direct line.

I'm going to close this for now, but please keep the book recommendations coming.
