### ISSUE TITLE
Linux build in gh actions

### ISSUE THREAD

**Issue by dougg0k** [zed-industries/zed#8339]
### Check for existing issues

- [X] Completed

### Describe the feature

Why linux building is not automated in gh actions? Isn't that just another release to be included?

https://github.com/zed-industries/zed/blob/main/docs/src/developing_zed__building_zed_linux.md

**Comment by SomeoneToIgnore** [comment]
Consider using https://github.com/zed-industries/zed/discussions for such generic questions in the future.

Because there's nothing production-ready, ~19 hours ago we've got [a PR](https://github.com/zed-industries/zed/pull/8253) that fixed text input to something tolerable, not speaking of anything more high-level.

When the time comes and contributors who participate in Linux part of the project decide it's appropriate, they will sure add something — building Zed in Zed is vital for its development.
