### ISSUE TITLE
Extra space in auto-completion popup

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/zed#8523]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/40336192/091f749f-28de-4dd7-a9dc-7c988c2cb8f5)

Goland:
<img width="652" alt="image" src="https://github.com/zed-industries/zed/assets/40336192/3fbb6539-6da4-419a-b0b7-8c65d09394b8">

### Environment

Zed: v0.124.6 (Zed Preview)
OS: macOS 14.3.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
I think that this might be answered in:

- https://github.com/zed-industries/zed/issues/8389

I'm guessing our we currently just make the autocompletion box as big as the documentation box, but I'm not sure. @ForLoveOfCats might have more info on it.

**Comment by TENX-S** [comment]
> I'm guessing our we currently just make the autocompletion box as big as the documentation box, but I'm not sure.

Sounds about right. But I can't see the reason to make these two boxes the same height.

**Comment by bbb651** [comment]
This is very easily reproducible with javascript DOM types as they have lengthy MDN documentation snippets that span multiple lines. The issue is triggered when entries having differing height, and seems to cause the total height of the scrollable to be the height of the tallest completion times the number of completions, with most space being between completions, and some of the space from the completions before the tallest completion end up at the end.

Is having a completion height be more than one line intended? Because it feels very unintuitive to me, and pretty much redundant with the documentation popover right besides it.

The worst example I found is things that bring up `HTMLMediaElement` as it's longer than the height of the completion popover causing it to show either one or zero completions at a time:
![image](https://github.com/user-attachments/assets/9d0fcbe6-5355-4a61-89a2-bf99e4ff9a6b)
