### ISSUE TITLE
Scrollbar overlaps toolbar with 1 pixel

### ISSUE THREAD

**Issue by eproxus** [zed-industries/zed#8529]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When theming, using certain colors makes it obvious that the scrollbar is placed 1 pixel too high in the UI (in my opinion). It overlaps the toolbar bottom border.

<img width="493" alt="Screenshot 2024-02-28 at 12 32 03" src="https://github.com/zed-industries/zed/assets/112878/00efe4bf-b352-4aa7-a66c-7adae22f5857">

<img width="558" alt="Screenshot 2024-02-28 at 12 33 22" src="https://github.com/zed-industries/zed/assets/112878/8cd96597-1b74-4049-8a07-095e3db41171">

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

The scrollbar should be rendered one pixel lower.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Thanks for the report @eproxus!

**Comment by Anthony-Eid** [comment]
I'm looking in the editor crate to see if I could fix this issue, and I have a couple of questions that I'm hoping someone could answer. 

Mainly, what exactly is the `ScrollAnchor`? And what directions are the x and y coordinates in? The reason I'm asking about the x and y coordinates is because some gui frameworks represent (0, 0) as the top left or the middle of a view.

**Comment by JosephTLyons** [comment]
@maxdeviant might know off hand.

**Comment by eproxus** [comment]
Tried with Zed 0.126.3 (7ee7ef5f33f884d480c2884f5fc07691f02770c4). Seems fixed now.
