### ISSUE TITLE
Regressions For Mac OS Deb Clients

### ISSUE THREAD

**Issue by caldempsey** [zed-industries/zed#8944]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm having these two issues: https://github.com/zed-industries/zed/issues/4408%20 https://github.com/zed-industries/zed/issues/6719. I installed via downloading Deb. In Github you say to install via Brew. These aren't the same.

Hunch is you're updating the deb package on Brew via your build tool but not auto-updating the link on the website as part of your pipeline, if at all.

Maybe remove the macOS deb package download. `brew` is pretty ubiquitous to the Mac platform, I think that might be the best solution here.

### Environment

Latest Deb package

Zed: v0.124.8 (Zed)
OS: macOS 12.3.1
Memory: 32 GiB
Architecture: aarch64

**Comment by caldempsey** [comment]
@mrnugget Installing the application via Homebrew installs a different version than is available on your debian package. The debian packages on the website, at the time of writing, was not kept up to date.

**Comment by notpeter** [comment]
Do you mean `dmg` (MacOS disk image) instead of `deb` (Debian/Ubuntu Linux package)?

> Installing the application via Homebrew installs a different version than is available on your debian package. The debian packages on the website, at the time of writing, was not kept up to date.

Currently, the source of truth is the dmgs release artifacts on our GitHub releases page. When a release is tagged, the artifacts are built automatically and when they complete, automation deploys the new links to the website and makes it available to the auto-updater.

Homebrew may be delayed slightly on this (because they have their own update process) but they are downloading the same builds from us.

It's possible things were out of sync in the past. Please let us know if you experience it again. Thanks.
