### ISSUE TITLE
experimental.theme_overrides doesn't allow for players[0].selection changes

### ISSUE THREAD

**Issue by fserb** [zed-industries/zed#9001]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Follow up from #7333 and #8599.

On settings.json: 
```
  "experimental.theme_overrides": {
    "players": [
      {
        "selection": "#ff0000"
      }
    ]
  }
```

has no effect, which means it's impossible to change the selection color outside of a theme.

Could we add support for that?

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.2.1
Memory: 64 GiB
Architecture: aarch64

**Comment by maxdeviant** [comment]
This is fixed in Zed 0.126.0, which is currently in Preview:

<img width="288" alt="Screenshot 2024-03-07 at 1 29 02 PM" src="https://github.com/zed-industries/zed/assets/1486634/77821ca1-0eba-4d10-acce-d71ced0c8517">

<img width="460" alt="Screenshot 2024-03-07 at 1 27 05 PM" src="https://github.com/zed-industries/zed/assets/1486634/2249a95c-67a3-43db-a2ba-b755f7d368d0">

It will go out to Stable next week.
