### ISSUE TITLE
Zed does not launch (immediate crash)

### ISSUE THREAD

**Issue by cbadawi** [zed-industries/zed#9036]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After installing "successfully". zed crashes when trying to open the app. Don't have much more to go on as a Zed dir was not created in ~/Library/Logs. but I copied the logs from the console app and pasted them in the attached txt file
[zed-logs.txt](https://github.com/zed-industries/zed/files/14530384/zed-logs.txt)

The logs might be missing as I filtered on the keyword "zed". let me know if all the logs or anything else would help.

specs:
MacBook Air
Apple M1
8 GB
macOS 14.0

### Environment

not able to run the command to get system specs

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

No zed dir is created in ~/Library/Logs

**Comment by JosephTLyons** [comment]
We now have a second user reporting an issue that sounds very similar to this one:

Dear Zed Team,

> I hope this email finds you well. I am writing to express my excitement about using the Zed application, as I was eager to explore its features upon learning about it. However, I regret to inform you that I have encountered difficulties in launching the application.
> 
> Despite reinstalling the application three times, including with the preview release, I have been unable to successfully launch it. I have also scoured the internet for possible solutions, but unfortunately, I have not found any resolutions to this issue.
> 
> I am reaching out to seek assistance in resolving this matter. Could you please provide guidance on how to troubleshoot and fix the problem? Any insights or suggestions you can offer would be greatly appreciated.
> 
> Thank you for your attention to this matter. I look forward to your prompt response and to finally experiencing the features of Zed.
> 
> Warm regards,


https://github.com/zed-industries/zed/assets/19867440/65fccced-4557-42f5-94ee-5ce3a7918c25

**Comment by as-cii** [comment]
Hey @cbadawi! This is pretty strange and I am a bit unclear on what could be causing this. Is there any chance you have some security setting that's stricter than what macOS enables by default?

What happens if you use Finder.app to go in the location where you installed Zed (e.g. `/Applications`) and then right click on `Zed.app` and click `Open` from there? That should bypass some extra security checks that macOS.

<img width="413" alt="image" src="https://github.com/zed-industries/zed/assets/482957/f6bb81df-f136-41fe-b77b-83ac9b74d98b">

**Comment by cbadawi** [comment]
Hey @as-cii . Not aware of any security settings.
Right click open results in the same behaviour.
Eager to get this resolved so let me know if i can help in any way.

**Comment by ConradIrwin** [comment]
I came across something that seems similar when testing #9431:

The steps I took were:
* Have installed Zed in the past, and remove it by deleting `/Applications/Zed` from Finder
* Download Zed.dmg and run Zed without dragging it into applications
* Drag Zed to the Applications folder, and run it again.
* Get an immediate crash:
[zed-2024-03-15-212728.ips.zip](https://github.com/zed-industries/zed/files/14622262/zed-2024-03-15-212728.ips.zip)

It looks like somehow macOS was still trying to run the old version of Zed (v0.121) despite me having installed a newer one. This may not be exactly what's happening in this scenario though because I saw the macOS crash report dialogue, and you seem to get no feedback at all.

@cbadawi If you have some time to help us track this down could you please open the `Console` ("cmd-space Console") and look under "Crash Reports" in the left to see if you have any Zed crashes?

If there's nothing there the next thing to try would be to start recording in the main view of Console, and double click on Zed, and see if any messages are logged about zed.

**Comment by SuperThinking** [comment]
Wanted to try this editor so badly, but it crashes on startup for me. 
Tried both version 0.129.2 & 0.129.1. 
Tried installing the dmg from [here](https://zed.dev/download) & via brew as well 🙃

**Comment by ConradIrwin** [comment]
@SuperThinking  If you have some time to help us track this down could you please open the Console ("cmd-space Console") and look under "Crash Reports" in the left to see if you have any Zed crashes?

If there's nothing there the next thing to try would be to start recording in the main view of Console, and double click on Zed, and see if any messages are logged about zed.

If you'd like to pair on this, You can book time here: https://calendly.com/conradirwin/pairing

**Comment by SuperThinking** [comment]
Not seeing anything related to Zed in Crash Reports.
Tried installing via dmg again and it failed. The editor opened up when I installed it via brew (yeah!), but started crashing again when I tried opening it again (huh..)

Can pair on this ig, have booked time for tomorrow.

**Comment by praveenn77** [comment]
I had the same issue when tried running "0.131.6 - Apple Silicon Version", the I tried running "0.131.6 - Universal binary" , in universal binary it showed the error message dialogue, "Unable to create .cache/zed folder, permission denied",

So changed cache folder permission by running,
```zsh
sudo chown -R $(whoami):staff ~/.cache
```

Now the both Apple Silicon and Universal binary works.

**Comment by ConradIrwin** [comment]
It's very surprising that the Apple Silicon build behaved differently to the Universal Binary; but I'm glad the error message led you to a solution.

Do you know why your cache directory may have had the wrong owner?

**Comment by Glorfindel31** [comment]
> I had the same issue when tried running "0.131.6 - Apple Silicon Version", then I tried running "0.131.6 - Universal binary" , in universal binary it showed the error message dialogue, "Unable to create .cache/zed folder, permission denied",
> 
> So changed the cache folder permission by running,
> 
> ```shell
> sudo chown -R $(whoami):staff ~/.cache
> ```
> 
> Now the both Apple Silicon and Universal binary works.

this Solved my crash

**Comment by cbadawi** [comment]
Can confirm my cache dir was owned by root. everything works now thanks! feel free to close the issue
