### ISSUE TITLE
No visual indicaton for syntax errors that stop [external] auto-formatter

### ISSUE THREAD

**Issue by andreasklinger** [zed-industries/zed#9061]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have added rubocop for autoformatting.

When i save with a syntax error the external formatter (rubocop in this case) just throws an error into LSP logs
But there is no visual indication for me - just leaving me in a "why doesnt it do anything" state

slow-loading gif incoming:
![](https://p195.p4.n0.cdn.zight.com/items/d5u22We6/1b6ecfe4-2e6d-4071-b2a7-ff66278e2767.gif?v=11e6a56cc9fb51b0865b85630b48c24a)
/gif

This might be related to this issue but i am not sure #8072

<details><summary>Config</summary>
<p><code>

// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  "theme": "One Light",
  "base_keymap": "VSCode",
  "buffer_font_size": 15,
  "tab_size": 2,
  "languages": {
    "Ruby": {
      "tab_size": 2
    }
  },
  "lsp": {
    "solargraph": {
      "initialization_options": {
        "diagnostics": true,
        "formatting": true
      }
    }
  },
  "language_overrides": {
    "Ruby": {
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "bundle",
          "arguments": [
            "exec",
            "rubocop",
            "--fail-level",
            "error",
            "--autocorrect",
            "--stdin",
            "corrected.rb",
            "--stderr"
          ]
        }
      }
    }
  }
}

</code></p>
</details> 

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 13.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by mrnugget** [comment]
Since your GIF wasn't added to the issue: did you see any diagnostic messages from solargraph?

Because if I produce invalid syntax, then `solargraph` informs me about it, using `rubocop` that's in my `Gemfile`:

![screenshot-2024-03-12-13 59 22@2x](https://github.com/zed-industries/zed/assets/1185253/a5178050-08dd-4082-b39d-f0617753dad2)

That points to an interesting question, IMHO: is it the job of the formatter to point out syntax errors or is it the job of the language server?

Orthogonal to that I think formatters could fail for various reasons, so surfacing those errors makes sense.

**Comment by JosephTLyons** [comment]
This is now available in [Zed Preview 0.127.0](https://zed.dev/releases/preview/0.127.0).
