### ISSUE TITLE
Emoji picker isn't summoned when shortcode is used directly after another emoji

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#9096]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In chat

1. Type `:dog` - confirm dog emoji picker
2. Type `:cat` - notice the emoji picker isn't summoned

If you add a space after the dog emoji, then type `:cat`, the picker is summoned. It should be noted that the bug doesn't exist when trying to use shortcode directly before another emoji.

### Environment

Zed: v0.127.0 (Zed Nightly)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/19867440/d30b2014-fc59-4eca-8665-20c71ee8df45

**Comment by JosephTLyons** [comment]
@bennetbo, would this be something you'd be interested in taking a look at?

**Comment by bennetbo** [comment]
Hey Joseph,
this happens because we do not want to replace shortcodes if they are part of another word.
E.g. typing `something:wave` should not replace the shortcode as stated here https://github.com/zed-industries/zed/pull/8455#issuecomment-1966881843 and here https://github.com/zed-industries/zed/pull/8455#issuecomment-1974062427.

But that is probably not the best design choice in your example.
My idea would be to add a check if the containing word is an emoji and replace the shortcode if that is the case. I'll put up a PR later today.

**Comment by JosephTLyons** [comment]
This certainly isn't a huge issue; if the bug isn't an easy fix, feel free to bail on it.

**Comment by bennetbo** [comment]
This should be fixed by #9107.
