### ISSUE TITLE
Give zed window class

### ISSUE THREAD

**Issue by ThatOneCalculator** [zed-industries/zed#9132]
### Check for existing issues

- [X] Completed

### Describe the feature

On Linux + Wayland, getting the active window information (in this case, with `hyprctl activewindow`) shows that there's no `class` or `initialClass`. Giving it a class of `zed` would make it far easier to manage.

```
Window 60e065a26ff0 -> empty project:
	mapped: 1
	hidden: 0
	at: 1846,618
	size: 1572,800
	workspace: 1 (1)
	floating: 0
	monitor: 0
	class: 
	title: empty project
	initialClass: 
	initialTitle: empty project
	pid: 31816
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 0
```
Related/parent: #7015

**Comment by ThatOneCalculator** [comment]
Related: #7015

**Comment by bbb651** [comment]
This can be done with [`xdg_toplevel::set_app_id`](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id) on wayland and [`WM_CLASS`](https://docs.rs/x11rb/0.13.0/x11rb/properties/struct.WmClass.html) on x11rb, currently GPUI apps don't set an app identifier at all (nor an app version) since on macos you get it from the app bundle, so a good place to start is getting it from the application somewhere [here](https://github.com/zed-industries/zed/blob/597465b0f54718d3acfc91311ba9526679b69572/crates/gpui/src/app.rs#L114), after that it's pretty easy to expose it

**Comment by antifallobst** [comment]
Is there already someone working on this? If not, I can look into it.

**Comment by ThatOneCalculator** [comment]
:tada: thank you!
