### ISSUE TITLE
linux: Open a Project and CTRL + O not functional

### ISSUE THREAD

**Issue by jasper-at-windswept** [zed-industries/zed#9209]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After building on NixOS Wayland and running everything works with no issues (currently) except that I cannot use CTRL + O or the button to Open a Project. Nothing happens when I do so and there are no error or console logs.

### Environment

Zed: v1.0.0 (Zed Dev)
OS: NixOS (24.05)
Memory: 31.2 GiB
Architecture: x86_64

**Comment by jasper-at-windswept** [comment]
Issue was localized to a invalid computer configuration on my end.

**Comment by Rodrigodd** [comment]
For anyone else who finds this issue, on Linux, Zed relies on XDG Desktop Portal for opening file dialogs.

- https://flatpak.github.io/xdg-desktop-portal/docs/
- https://wiki.archlinux.org/title/XDG_Desktop_Portal

You need to make sure `xdg-desktop-portal` is running. Otherwise you will see the following error when starting Zed (although it shows no error when actually clicking the button):

```
[2024-06-09T18:11:28-03:00 ERROR util] crates/gpui/src/platform/linux/platform.rs:110: Portal request failed: org.freedesktop.zbus.Error: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```

**Comment by jasper-at-windswept** [comment]
> For anyone else who finds this issue, on Linux, Zed relies on XDG Desktop Portal for opening file dialogs.

For me I was on Wayland and needed to install the GTK portal to get the file dialogs to work.
