### ISSUE TITLE
Cursor-like Code Edit

### ISSUE THREAD

**Issue by matmult** [zed-industries/zed#9320]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed is really cool and I have been wanting to make the switch to a stabler and faster code editor for a while. However, the only thing that's keeping me from it is the lack of assistant code editing. 

It would be great if Zed can implement Cursor's approach here: -> select code block -> enter instruction -> have the assistant go through line by line and make edits -> display the final diff.

**Comment by JosephTLyons** [comment]
Is there any part of the process we are missing here @matmult? Loved to learn more about how we can improve this, and if nothing comes to mind, we can probably close this out.

**Comment by chrisalbon** [comment]
I agree with @matmult. I actually don't want the AI to write directly in the codebase. I want the AI to make a diff which I can reject, accept, etc.

For example if I have a 30 line class and then I ask the AI to clean it up, I really REALLY want to see what changes the AI made, rather than just have the AI overwrite my own code

**Comment by haringsrob** [comment]
Yea I too prefer cursor's way of displaying the diff then accept/decline or give additional instructions.

**Comment by canadiannomad** [comment]
Along the same lines I love the cursor 'Fix this' button on errors... 
I think it just selects the surrounding block/file, the error, sends that to the llm, then does the same as the normal inline assist

**Comment by JosephTLyons** [comment]
I think with our most recent improvements to the inline assistant, this issue is basically covered. I'm going to optimistically close this out, but feel free to let me know if I've missed something and need to reopen.

<img width="1124" alt="SCR-20240719-qokv" src="https://github.com/user-attachments/assets/1fccf351-3b0f-43c0-95e9-8dfe33b4bb3d">

**Comment by i-am-the-slime** [comment]
It's always so painful when tickets get closed without any explanation or link to something that explains how to actually do it.
