### ISSUE TITLE
Windows: Worktree ignoring events due to invalid canonical path

### ISSUE THREAD

**Issue by kim-fg** [zed-industries/zed#9535]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Build and run windows app (via cargo run)
2. Open a project
3. Edit and save a file

You should now something similar to the error below in your terminal.
```
ignoring event "C:\\<project_path>\main.cpp" outside of root path "\\\\?\\C:\\<project_path>"
```

### Environment

Zed: v1.0.0 (Zed Dev)
OS: Windows 10.0.22631
Memory: 15.8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

logging seems broken on windows, there is no log.

**Comment by torshepherd** [comment]
Seems like this is actually correct behavior on Windows:

https://stackoverflow.com/questions/50322817/how-do-i-remove-the-prefix-from-a-canonical-windows-path

So there are two ways to solve this

1. Canonicalize the paths sent by the `tx` also so that they match the leading `?`
2. Canonicalize (within `process_events`) the path differently so that it doesn't have the `?`

I suspect the solution will be to do something closer to 2, since this problem could pop up _everywhere_ in the codebase only on Windows.
