### ISSUE TITLE
Duplicate line does not work

### ISSUE THREAD

**Issue by stalexsm** [zed-industries/zed#9622]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Duplicate line does not work using the keyboard shortcut cmd + shift + D.

### Environment

Zed: v0.128.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 8 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment]
The command to duplicate lines in Zed is `editor::DuplicateLine` and it's bound to `alt-shift-up` and `alt-shift-down` to move up and down respectively by default. You can remap it in your own `keymap.json` config.

**Comment by JosephTLyons** [comment]
Version 0.127.3 introduced a breaking change to our default key map in order to bring us close to VS Code defaults, since our default models VS Code's key map. I'm betting this is you hitting that breaking change.

https://zed.dev/releases/stable/0.127.3

I'm going to close this issue out, since you can rebind this in your custom key map, but feel free to reach out here if you have any issues doing so.

```json
{
  "context": "Editor",
  "bindings": {
    "cmd-shift-d": "editor::DuplicateLine"
  }
}
```
