### ISSUE TITLE
Use zed as your primary terminal

### ISSUE THREAD

**Issue by kke** [zed-industries/zed#9762]
### Check for existing issues

- [X] Completed

### Describe the feature

As a long long time terminal and vim user I would like a mode where you could use zed as your primary terminal. This is probably more like a wish or a fantasy than a "feature request".

Using "zed foo.txt" in the "zed terminal" would open the full-window editor in the same manner as vim opens in a terminal window. When you `:q` / `:wq` from the editor, you would be returned to the shell-session.

Currently the workflow is kind of inverse. Zed is an editor first and you can open the shell pane for some quick terminal work. I'd like a "terminal first" mode of zed where I can work in the shell like I do in iTerm2/console/whatever, quickly edit some files in zed, return back to the shell session, do some more shell work, edit more files, and so on.

In this mode, perhaps ctrl-z would allow you to visit the underlying shell like it does when you suspend vim and come back with fg.

This same behavior could further down the line apply to other programs through an API. It would make zed a terminal that can also open temporary richer than vt100/xterm windows on top. 

Perhaps it could even open the editor when inside an ssh session to a remote host that has a zed-stub installed that would send some terminal control code + contents of a file and would then remain waiting for modified contents or a quit signal from zed running on the local machine.

**Comment by Moshyfawn** [comment]
Your proposal sounds a bit like #7493 and #5347 🤔

**Comment by jansol** [comment]
I think this is a bit too vague and broadly scoped to really be actionable at the moment, and indeed parts do overlap with other existing issues.

Narrowing it down to the first part would be a neat feature though:
* Open Zed
* Open a terminal and *zoom in* on it to make it "full screen" (the workspace could maybe remember this in the future)
* Do terminal stuff, then `zed quickedit.txt`
  * This would open `quickedit.txt` in the same Zed window, and *zoom in* on the editor tab to replace the full screen terminal
  * When you exit the zoomed tab with `:q` or `:wq` (if using vim mode) or `shift+esc`, Zed zooms in on the terminal again
* I think the CLI helper already has a blocking mode that could be used here?

**Comment by mikayla-maki** [comment]
This isn't in line with our vision for where Zed ends up.

That said, that does sound like a pretty cool application, I hope someone tries it!

**Comment by devguydavid** [comment]
I know this topic was closed a couple of years ago, but the tooling landscape has shifted significantly, and I think it’s worth revisiting. I’m happy to open a new issue if that’s preferred.

Agentic coding workflows centered around the terminal are seeing a massive resurgence. Tools like Terax show how compelling it is to have an integrated terminal and editor where the terminal is a first‑class citizen. However, Terax’s shortcomings are exactly where Zed shines: mature editor ergonomics, a solid extension system, robust LSP support, and tightly integrated agent communication via ACP.

To lean into this shift, I’d love to see Zed generalize its pane model. Instead of assuming an editor pane must always be present, the main workspace could adopt a unified pane abstraction. Tabs would simply host panes that can be split horizontally or vertically, and each pane could contain an editor, a terminal, or an agent chat—whichever the user chooses. If a developer wants to open Zed as a standalone terminal to run an agentic CLI workflow, the initial workspace should allow that, rather than forcing an editor pane into the layout.

Zed already has strong primitives here with its flexible docks and integrated terminal. Elevating the terminal and agent threads to first‑class peers in the main workspace would keep Zed incredibly competitive against newer, terminal‑forward tools.

I realize this is “easier said than done” and likely involves complex engineering, but given how common these CLI‑agent workflows have become, it feels like a direction worth another look.

Thank you for your consideration!
