### ISSUE TITLE
project search is not reliable since Zed introduced a max file limit

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#9856]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Since https://github.com/zed-industries/zed/pull/9404, project search is limited to 5000 files. I believe this is a huge mistake, since one cannot rely on Zed anymore when doing searches. This is particularly problematic in some cases since the UI doesn't mention that the search is being artificially limited and it might just return no results for some pieces of rarely repeated text.

### Environment

Zed: v0.127.5 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

**Comment by izuzak** [comment]
I think there might have been a mistake in description and release notes of [the PR this issue is related to](https://github.com/zed-industries/zed/pull/9404).

The description in https://github.com/zed-industries/zed/pull/9404 says: 

> Number files that are being searched is now limited to 5000

and the release notes say:

> ... by limiting the number of files that are searched (to 5000)  ...

Looking at the PR's implementation, I don't think that's true. It's not the case that the number of files being searched is at most 5000, but that the number of files with at least one result can be at most 5000. So, even if you have a million files in your project, search will work fine for queries that have results in 5000 or fewer files. Search will break only if more than 5000 files contain at least one result.

@mrnugget @as-cii Can I trouble you to take a quick peek and confirm what exactly was limited to 5000? If I'm right, it might make sense to update the release notes (if that's even possible) since limiting search to 5000 files sounds waaaay scarier than limiting the number of files with results to 5000. I work in a repository with over 100k files, and Zed's search still works fine for me due to this difference.

Many thanks for taking a look 🙇

**Comment by SomeoneToIgnore** [comment]
As a side person, not voting for either of the "sides", generally curious to read a bit more about workflows that involve working with >5k un-expandable, un-foldable search result buffers.

What are you doing (and how efficient is Zed with that?), and how altering or removing limit helps?

**Comment by izuzak** [comment]
> What are you doing (and how efficient is Zed with that?), and how altering or removing limit helps?

@SomeoneToIgnore Oh, I'm not working with more than 5000 result buffers -- that's why I haven't hit this problem yet and Zed's search works perfectly for me. I was just trying to clarify the limit that was introduced since I think the incorrect release notes created some confusion. 

I'll let @hferreiro answer for himself in case he actually does work with search results across more than 5000 files. :v:

**Comment by hferreiro** [comment]
If comment https://github.com/zed-industries/zed/issues/9856#issuecomment-2026920840 is correct, then I'll close this issue.
I thought I tested this, but I might have gotten the wrong impression because of https://github.com/zed-industries/zed/issues/9858.

So, in summary, the problem is not wanting to work with more than 5000 file results, but having a global limit of 5000 files in which search is performed, which apparently might not be true after all.

**Comment by mrnugget** [comment]
> @mrnugget @as-cii Can I trouble you to take a quick peek and confirm what exactly was limited to 5000? If I'm right, it might make sense to update the release notes (if that's even possible) since limiting search to 5000 files sounds waaaay scarier than limiting the number of files with results to 5000.

This is correct, yes. We first search all the files:

https://github.com/zed-industries/zed/blob/3a36b10e3a4eb9aa6608d86c18af284a6caf58b3/crates/project/src/project.rs#L6291-L6305

That returns files that contain >1 matches.

Only _then_ do we limit to 5k:

https://github.com/zed-industries/zed/blob/3a36b10e3a4eb9aa6608d86c18af284a6caf58b3/crates/project/src/project.rs#L6308-L6325


What this fixes is the case where people use this button here

![screenshot-2024-04-02-09 16 47@2x](https://github.com/zed-industries/zed/assets/1185253/e67b4174-f2fc-4e92-853d-9dccece56e08)

to also search in `.gitignore`d directories such as `node_modules` and then seeing Zed blow up because it tries to populate a single buffer with 100k matches.
