### ISSUE TITLE
Image Viewer: Zed should jump to an existing tab instead of creating a duplicate

### ISSUE THREAD

**Issue by slymax** [zed-industries/zed#9896]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When clicking on an image file in the explorer, Zed should jump to the image tab, if the image is already open, instead of creating a new copy of the tab. This can be quickly reproduced by clicking several times on an image file in the project panel.

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

**Comment by weartist** [comment]
@mikayla-maki Hello mikayla, I'm looking at the reason for this bug, and I found that it's because for imageViewer, it doesn't record the entry_id of its own file, I would like to ask if you have any suggestions for this?, should I record a current `File` or other variables for imageViewer that can easily get `entry_id`, or is it better to pass the `entry_id` when the workspace calls the `open_path`

https://github.com/zed-industries/zed/blob/480e3c9dafe16b1955e947fa9ffac15342effb7b/crates/image_viewer/src/image_viewer.rs#L55C1-L57C6

**Comment by bennetbo** [comment]
Would be great to have this for #9125, as of right now double clicking on an image in the project explorer opens two image viewer tabs instead of opening a single "permanent" tab.

**Comment by bennetbo** [comment]
This is still an issue.
