### ISSUE TITLE
[vim] set base_keymap none any key invalid

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#9898]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I don't know if I misunderstood, but my idea was to just enable the vim keymap and not use any vscode keymap, but it doesn't seem to work, causing any of my keystrokes to not work

### Environment

Zed: v0.129.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @0x2CA, it seems like the original intention behind adding a `None` option to the `base_keymap` setting is so that the user has to configure every single binding that the normal keymap provides.  All of the contents of the base keymap (`command palette > "zed: open default keymap`) would need to be manually configured.

That being said, I'm not sure what the intention was with how that setting should interact with vim mode.

cc @ConradIrwin, @mikayla-maki (tagging members who were associated with the PR)

**Comment by ConradIrwin** [comment]
The idea of the None key map was for people who wanted to start from scratch. The vim key map relies on the VSCode one for common keys like left/right/enter, etc. 

It is not a goal for vim mode to work with key map None
