### ISSUE TITLE
Delete line keybinding stopped working?

### ISSUE THREAD

**Issue by brandonweiss** [zed-industries/zed#9926]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It used to be you could `CTRL + SHIFT + K` to delete a line. I notice in the command pane it is `CMD + SHIFT + K`. I assume both `CTRL` and `CMD` used to work, but now only `CMD` works.

### Environment

Zed: v0.128.3 (Zed)
OS: macOS 14.2.0
Memory: 16 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment]
Hey @brandonweiss, this was an intentional breaking change. Our default keymap is based off of VS Code's keymap - so these changes were about Zed more closely matching things. That being said, it looks like these changes were missed in the breaking changes of the release notes of the version they landed in.  Sorry abou that.

- https://github.com/zed-industries/zed/pull/8584

**Comment by brandonweiss** [comment]
But… isn’t `CTRL + SHIFT + K` the shortcut in VS Code to delete a line? 😅

**Comment by brandonweiss** [comment]
Oh, it appears it’s CTRL on Windows and CMD on Mac, but on Mac it also supports CTRL 🙃

**Comment by JosephTLyons** [comment]
<img width="943" alt="SCR-20240328-pcbh" src="https://github.com/zed-industries/zed/assets/19867440/b55c4ec2-98f2-4427-955f-87e935a8ee3d">

**Comment by brandonweiss** [comment]
Yeah, I guess it’s a weird quirk of VS Code being multi-platform and macOS having both CTRL and CMD keys.
